### ISSUE TITLE
cryptography is pinned to an outdated version, has security vulnerabilities

### ISSUE THREAD

**Issue by csdev** [snowflakedb/snowflake-connector-python#100]
Cryptography 2.3 contains fixes for security vulnerabilities. (See https://cryptography.io/en/latest/changelog/#v2-3 ) This version pin is potentially dangerous:
https://github.com/snowflakedb/snowflake-connector-python/blob/v1.6.5/setup.py#L48

**Comment by smtakeda** [comment]
will work on after coming back from off.

**Comment by ianlcassidy** [comment]
would very much like to see this fixed.

**Comment by smtakeda** [comment]
This fix will be released this week in 1.6.6
