### ISSUE TITLE
Pyarrow Unknown error

### ISSUE THREAD

**Issue by BALADEV-1234** [snowflakedb/snowflake-connector-python#1004]
Hi Team, 
Thank you for the amazing library. I was trying to create a flask service in python using the snowflake connector. But when I am trying to test I am getting a issue as  below. Please Help. I am using python 3.9.   
list(extension_columns.keys()))
  File "pyarrow\table.pxi", line 1117, in pyarrow.lib.table_to_blocks
  File "pyarrow\error.pxi", line 116, in pyarrow.lib.check_status
pyarrow.lib.ArrowException: Unknown error: Wrapping C�TE D'IVOIRE failed

**Comment by sfc-gh-jbahk** [comment]
Hi @BALADEV-1234, can you raise a ticket with our support team? It's nearly impossible to go off of the information you provided. Logs, the specs of your environment, etc are all important information needed to diagnose such an issue.

**Comment by BALADEV-1234** [comment]
Hi,  @sfc-gh-jbahk  thanks. I am using python version 3.7.3 and jupyter IDE. Here is the screen sort of the issue I am getting
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/72731231/147212405-35a71a99-2143-4e2f-8404-1852425c87ab.png)

**Comment by BALADEV-1234** [comment]
Hi, @sfc-gh-jbahk thanks. I am using python version 3.7.3 and jupyter IDE. Here is the screen sort of the issue I am gettin
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/72731231/147212573-c3e3a9ca-5133-408d-8902-63c128802de5.png)
g

**Comment by sfc-gh-mkeller** [comment]
@BALADEV-1234 would you able to provide a reproducer script, please?

**Comment by janusqa** [comment]
I believe I am getting this same error.

**Comment by sfc-gh-aling** [comment]
echoing what I have replied in the issue: https://github.com/snowflakedb/snowflake-connector-python/issues/574

> hey folks, thanks for your patience, we got some updates for you.
>
> We have located the issue -- it's within the Snowflake demo data some of which is encoded in `latin-1` instead of `utf-8`. 
Our Python connector is trying to decode the `latin-1` encoded bytes with `utf-8` leading to the decode error. This is not a connector issue but something went wrong with the sample data.
>
> We're working with the sample data team to re-generate the database with the correct encoding. It will take some time to manipulate those tables while avoid any breakings to existing users, and populate the change to all deployments. I will keep you guys updated.
>
> ----- 
>
>Here's some more context of the complete story and for future developers who might encounter similar issue:
>
>Previously snowflake allow people to copy data into database using file without validating the encode being `utf-8` or not, which means data of non `utf-8` encoded could exist in the database if they were inserted long time ago.
>
>However, this is not allowed any more which is announced in https://community.snowflake.com/s/article/VALIDATE-UTF8-File-Format-Option-Obsoleted.
>
>As mentioned in the [COPY INTO TABLE reference doc](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html): `Snowflake stores all data internally in the UTF-8 character set. The data is converted into UTF-8 before it is loaded into Snowflake.`.
>
>So here's what I would recommend to do based on different scenarios if you have some old data in the database which is encoded in non-utf8, you could choose to either approach:
>  - follow @fhoffa-snow's suggestion (thanks!) to hex_encode the data and decode by yourself
>  - or set `snowflake.connector.cursor.CAN_USE_ARROW_RESULT_FORMAT` to `False`, which underlying uses JSON format for internal results. This approach works because on the service side, JSON format has special logic to handle and escape bytes. 
>  - for long term, it's recommended to re-encode the database in `utf-8`, consider dumping the data, and re-importing them if possible.
>
>new inserted data shall be good as all data will be converted to `utf-8` encoded by snowflake.


I wish this helps answer your questions. let me know if there's more I could help.

**Comment by sfc-gh-aling** [comment]
good news folks, the sample data has been re-encoded with `utf-8`, could you take a try?

**Comment by sfc-gh-aling** [comment]
I'm closing the issue now, feel free to reach out or reopen the issue if you have any other questions regarding to this topic.

**Comment by lukehsiao** [comment]
It seems that if we create a table from old sample data like so
```
create or replace transient table
  db.schema.example
  as ( 
    SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCDS_SF100TCL"."CUSTOMER" SAMPLE (1000000 ROWS)
  );
```
And happen to get one of the rows with non-utf-8 characters, trying to load this new `db.schema.example` table also shows the error. Based on what you've posted @sfc-gh-aling, this is a little surprising, as I would've thought that the the creation of the new table would have caused all the sampled rows to be UTF-8 encoded. Am I misunderstanding something?
