### ISSUE TITLE
SNOW-534389: pypi source distribution for v2.7.3 is different than github source

### ISSUE THREAD

**Issue by hajapy** [snowflakedb/snowflake-connector-python#1035]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   n/a

2. What operating system and processor architecture are you using?

   n/a

3. What are the component versions in the environment (`pip freeze`)?

   n/a

4. What did you do?

   While investigating a build failure for the conda-package here: https://github.com/conda-forge/snowflake-connector-python-feedstock/pull/98, I noticed the patch was failing to apply. Curious why, I downloaded the source code for snowlake-connector-python v2.7.3 from pypi and compared the same from github. 
    pypi: https://pypi.io/packages/source/s/snowflake-connector-python/snowflake-connector-python-2.7.3.tar.gz
    github: https://github.com/snowflakedb/snowflake-connector-python/archive/refs/tags/v2.7.3.tar.gz

    I noticed the pypi version is different, specifically the setup.cfg file it contains uses tabs instead of spaces. This is what caused the patch failing to apply in the linked conda-forge PR.  I did not look for other differences, but it is possible there are more.

5. What did you expect to see?

   I expect the source distribution to be clean and match github's source. I would guess this occurred because the upload to pypi was run from a machine that had some local changes.

6. Can you set logging to DEBUG and collect the logs?
    n/a

**Comment by sfc-gh-mkeller** [comment]
> I expect the source distribution to be clean and match github's source. I would guess this occurred because the upload to pypi was run from a machine that had some local changes.

Interestingly, when the sdist locally this still happens without any changes done by me. I wonder if this is because of `setuptools`.

**Comment by sfc-gh-mkeller** [comment]
This seems to be done here https://github.com/pypa/setuptools/blob/1a1397a4ef0327ba09ddd4a3d0916af48d3be7ec/setuptools/command/setopt.py#L73
[ConfigParser](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser) seems to write tabs instead of spaces and it also doesn't preserve the input's formatting.
Maybe we should ask `setuptools` to make this configurable?

**Comment by hajapy** [comment]
Ah interesting. Well a couple other solutions come to mind:

1. revert using setup.cfg for the install_requires, setup.py doesn't get rewritten
2. use tabs within install_requires
3. request a fix to setuptools/ConfigParser so this can be configurable

I'm not sure how prevalent defining the requirements in setup.cfg is, I haven't encountered this in maintaining packages for cobra-forge yet, so my inclination is towards 1 but I'm not sure the rationale behind that change. 

In the meantime, switching from pulling the source from pypi to github has resolved the issue and so we can continue to build/release the conda-forge package.
