### ISSUE TITLE
SNOW-535137: Document how to do privatelink connectivity

### ISSUE THREAD

**Issue by dnarain-astro** [snowflakedb/snowflake-connector-python#1037]
## What is the current behavior?
The documentation does not make any mention about connecting in a Privatelink setup.   Since the host parameter is deprecated; connect() proceeds to construct the hostname using other parameters.  The end result is the public hostname, which does not work in a privatelink environment.   

## What is the desired behavior?
Add documentation to explain that if you're in a privatelink environment, you need to use the privatelink version of your account name (<account>.<region>.privatelink) to establish connectivity. 

## How would this improve `snowflake-connector-python`?
Users who try to use their scripts in a privatelink environment may not realize that they have to connect with a different account name based on the underlying network connection and instead use the host parameter, which is deprecated. 

## References, Other Background
All this is based on experimentation in AWS, I have not not tried this in Azure or GCP, but I expect it to fail in the same way on those clouds as well.

**Comment by sahilpatel1027** [comment]
I've also hit this issue recently and am struggling to find the correct parameters for a privatelink account.
@dnarain-astro would you mind elaborating what we need to change? I've been told I need to add region as a parameter and tack on '.privatelink' after it.

**Comment by sfc-gh-wfateem** [comment]
@dnarain-astro @sahilpatel1027 
Which documentation are you referring to here? Given that you're opening up this issue in the Snowflake Connector Python GitHub repo, I assume you're referring to the connector's documentation. In the link [here](https://docs.snowflake.com/en/user-guide/python-connector-example.html#connecting-to-snowflake) we say that for the account parameter you should use the account identifier and provide the reader with a link [here](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html). [In the first section of that page ](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#where-are-account-identifiers-used) we explain what the account identifier is:
`<account_identifier>.snowflakecomputing.com`

So if you have the privatelink URL: `YOUR_ACCOUNT.privatelink.snowflakecomputing.com` then you should use `YOUR_ACCOUNT.privatelink` for the account parameter.

If you're referring to some other documentation, please let us know and we'll have a look.

**Comment by sfc-gh-wfateem** [comment]
@sahilpatel1027 that's correct.

**Comment by dnarain-astro** [comment]
@sfc-gh-wfateem <https://github.com/sfc-gh-wfateem> - yes, you are correct.
I meant "add a note in the connector documentation that when you use
privatelink, you should use the privatelink-account-name (which is just
accountname.privatelink)"

**Comment by sfc-gh-wfateem** [comment]
Hi @dnarain-astro, 

Thank you for your comment. From our perspective, that's redundant information. As I pointed out earlier, the documentation explains that you should use the `<account_identifier>` and that's defined as anything that precedes `.snowflakecomputing.com`. So if you're using private link then `account_name.privatelink` satisfies the definition of what an account identifier is according to the documentation that's already there, and that's what you should be using for the account parameter.

In any case, I will take your feedback and share it with the documentation team. I'll be closing this issue now.

**Comment by frankcash** [comment]
I do think it should be documented that `region` needs to be not included as a parameter as I've just spent a few hours debugging this issue


https://github.com/snowflakedb/snowflake-connector-python/blob/fda642f07bca955a05121b3eabf3164b0bf5bdb5/src/snowflake/connector/connection.py#L931-L937
