### ISSUE TITLE
Drop Python 2 support in the near future

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/snowflake-connector-python#106]
Will keep eyes on the Python community and decide when we'll do.

Any comment is welcome here.

**Comment by sburns** [comment]
You would be in [good company](https://python3statement.org/). Especially if it means you can develop features/fix bugs more quickly by just focusing (& testing/verifying/etc) on py3.

**Comment by snowstakeda** [comment]
Planning to drop python2 support in the first release in 2020. Note the schedule is subject to change.

**Comment by keller00** [comment]
Next release is officially dropping 2.7 and 3.4 support.
