### ISSUE TITLE
SNOW-544967: URL should be printed in terminal during browser authentication

### ISSUE THREAD

**Issue by thomasaarholt** [snowflakedb/snowflake-connector-python#1064]
## What is the current behavior?
During browser authentication with my identifty provider, there is sometimes no browser window. I have no option but to rerun the dbt run, which can take time.

## What is the desired behavior?
Show the URL so the user can click it during the run.

**Comment by sfc-gh-achandrasekaran** [comment]
To clean up and re-prioritize bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please re-create them. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response
