### ISSUE TITLE
SNOW-559254: blob store credentials not redacted when getting parquet batches from the Azure blob

### ISSUE THREAD

**Issue by bjoern-meier-by** [snowflakedb/snowflake-connector-python#1075]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Python 3.10.2 (main, Jan 29 2022, 03:24:05) [GCC 8.3.0]

2. What operating system and processor architecture are you using?

   Linux-5.10.76-linuxkit-x86_64-with-glibc2.28

3. What are the component versions in the environment (`pip freeze`)?

```
asn1crypto==1.5.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
cryptography==36.0.1
idna==3.3
numpy==1.22.3
oscrypto==1.2.1
pandas==1.3.5
pyarrow==6.0.1
pycparser==2.21
pycryptodomex==3.14.1
PyJWT==2.3.0
pyOpenSSL==21.0.0
python-dateutil==2.8.2
pytz==2021.3
requests==2.27.1
six==1.16.0
snowflake-connector-python==2.7.4
urllib3==1.26.8
```

4. What did you do?

We use Azure  as storage backend, and this is probably mostly relevant for this backend even so the same might haben for a storage backends.

Running a fetch_pandas_batches for data where the batch number is > 1 so that the batch results are fetched from the Azure blob and not directly in the requests executing the SELECT statement.

```
import logging
import os

import snowflake.connector


logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
logger.addHandler(ch)


if __name__ == "__main__":

    conn = snowflake.connector.connect(
        user=os.getenv("SNOWFLAKE_USER"),
        password=os.getenv("SNOWFLAKE_PASSWORD"),
        account=os.getenv("SNOWFLAKE_ACCOUNT"),
    )
    cur = conn.cursor()
    cur.execute("CREATE TEMPORARY TABLE mytemptable (id NUMBER, text VARCHAR(128));")
    for _ in range(10):
        data = [(x, str(x)) for x in range(10000)]
        cur.executemany(
            f"""INSERT INTO mytemptable
        VALUES
       (%s, %s)
    """,
            data,
        )
    cur.execute("SELECT * from mytemptable")
    for batch in cur.fetch_pandas_batches():
        print(batch)

    conn.close()

```

results in log output are shown for request to the blob store with the credentials for it:
```

https://<removed_manually>.blob.core.windows.net:443 "GET /results/01a2eb39-0b02-c562-0000-e3cd66382f9a_0%2Fmain%2Fdata_0_0_3?sv=2020-08-04&spr=https&se=2022-03-14T17%3A05%3A54Z&sr=b&sp=r&sig=<removed_manually>&rsce=gzip HTTP/1.1" 200 164077
https://<removed_manually>.blob.core.windows.net:443 "GET /results/01a2eb39-0b02-c562-0000-e3cd66382f9a_0%2Fmain%2Fdata_0_0_2?sv=2020-08-04&spr=https&se=2022-03-14T17%3A05%3A54Z&sr=b&sp=r&sig=<removed_manually>&rsce=gzip HTTP/1.1" 200 163584
https://<removed_manually>.blob.core.windows.net:443 "GET /results/01a2eb39-0b02-c562-0000-e3cd66382f9a_0%2Fmain%2Fdata_0_0_1?sv=2020-08-04&spr=https&se=2022-03-14T17%3A05%3A54Z&sr=b&sp=r&sig=<removed_manually>&rsce=gzip HTTP/1.1" 200 91970
```
I removed the parts where information from our account. Normally you would see the account name at the beginning and the most concerning is that the "sig" is also logged.

5. What did you expect to see?

   As in other parts of the package, where the e.g.  headers contain credentials they are removed, I would expect this to be the same for the sig of the requests here.
  The problem is that enabling DEBUG log output would also start to leak credentials to the log system.

**Comment by sfc-gh-mkeller** [comment]
The issue for us is that DEBUG level logs sometimes need to have some sensitive information to help find root causes of issues.
It's important to know that the signature you found in the logs is not enough to access any files, there are encryption keys that are required in addition to the URL.

Here's how to turn these specific logs off for your logs:
```python
logging.getLogger("snowflake.connector.vendored").setLevel(logging.WARNING)  # Default logging level 
```

**Comment by bjoern-meier-by** [comment]
Thanks @sfc-gh-mkeller for the answer, this is good to know.
