### ISSUE TITLE
SNOW-575165: Error when writing pandas dataframe after 2.7.0

### ISSUE THREAD

**Issue by Messlow** [snowflakedb/snowflake-connector-python#1092]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

`Python 3.8.12`

2. What operating system and processor architecture are you using?

`Linux-5.4.0-105-generic-x86_64-with-glibc2.17`

3. What are the component versions in the environment (`pip freeze`)?

pandas==1.4.2
pyarrow==6.0.1
snowflake-connector-python==2.7.6

4. What did you do?

When writing a pandas dataframe, I have the following issue:

```
GET with url b'https://sfc-ca-ont-ds1-customer-stage.s3.amazonaws.com/https://sfc-ca-ont-ds1-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-ca-ont-ds1-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /https://sfc-ca-ont-ds1-customer-stage.s3.amazonaws.com/?accelerate (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))
```

5. What did you expect to see?

The exact same function worked fine with 2.6.2, using the flag `use_new_put_get=False` in the connection.
I tried with 2.7.0, and I have the same SSLError. From the documentation, I have not seen any information on how to update the connection arguments to solve this issue.

Region is `ca-central-1`, and account ends with `.privatelink`.

6. Can you set logging to DEBUG and collect the logs?
There's not much going on in the logs, and since there may be some sensitive information there I'd rather not post them. But you can ask me some specifics if needed!

**Comment by Messlow** [comment]
Any news for this? Any PUT or GET will also get me the same error with version >= 2.7

**Comment by sfc-gh-achandrasekaran** [comment]
@Messlow is this still happening with the new versions of the connector?

**Comment by sfc-gh-achandrasekaran** [comment]
To clean up and re-prioritize bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please re-create them. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response
