### ISSUE TITLE
Package structure is broken

### ISSUE THREAD

**Issue by shemigon** [snowflakedb/snowflake-connector-python#11]
The packages is installed to `snowflake/connector` directory. However, the `snowflake` directory does not contain the `__init__.py` file.

**Comment by smtakeda** [comment]
That's how namespace package works.
https://www.python.org/dev/peps/pep-0420/

> Namespace packages cannot contain an `__init__.py` . As a consequence, `pkgutil.extend_path` and `pkg_resources.declare_namespace` become obsolete for purposes of namespace package creation. There will be no marker file or directory for specifying a namespace package.

As far as know, `snowflake_connector_python-1.3.14-py2.7-nspkg.pth` in site-packages tricks the path.

One issue we know is AWS Lambda needs `__init__.py` as it doesn't use the standard site-package directory structure:
https://github.com/snowflakedb/examples/blob/master/lambda_function/package-lambda-function.sh#L17
