### ISSUE TITLE
SNOW-583861: Execute snowflake script with transaction control by snowflake-connector

### ISSUE THREAD

**Issue by Mallegrissimo** [snowflakedb/snowflake-connector-python#1112]
## What is the current behavior?
Currently, sql_text which eventually is passed to execute_stream() in connection.py will be clean and split into statements, and get executed by cur.execute(). However, with new feature - [Snowflake scripting](https://docs.snowflake.com/en/developer-guide/snowflake-scripting/blocks.html), multiple statements should be treated as a whole, especially, a transaction control is in a anonymous block, like below split and execute one after is not appropriate.

```
ALTER SESSION SET AUTOCOMMIT = FALSE; --default is TRUE
DECLARE
    v_val INT DEFAULT 1;
BEGIN
    --insert_stmt_1: insert 2 rows
    INSERT INTO dummy_table(val) VALUES(1),(2);

    --raise DIVIDE-ZERO EXPETION
    v_val := v_val / 0;

    --insert_stmt_2:insert 2 rows after exception
    INSERT INTO dummy_table(val) VALUES(3),(4);

    COMMIT;

    RETURN 'success';

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RETURN 'failed';
END;
```

## What is the desired behavior?
Above anonymous block should be submitted to snowflake as a whole(instead of split statements) and expect to get the message in return statement. I know this block can be turned into a stored procedure, however, stored procedure is out of consideration if all queries are expected to be file based.

**Comment by michaelconan** [comment]
This issue additionally appears to not allow the deployment of Snowflake Scripting (SQL) stored procedure DDL (i.e., CREATE PROCEDURE  LANGUAGE SQL) as the procedure is broken into statements for execution, which is not appropriate. This is a significant limitation especially as this library is the basis of many available automation and CI/CS tools like schemachange and SnowSQL

**Comment by michaelconan** [comment]
Update: this is user error, please refer to the [docs here](https://docs.snowflake.com/en/developer-guide/snowflake-scripting/running-examples.html).

SQL scripts and procedures must be enclosed in string constants ($$) like in the classic console.

**Comment by sfc-gh-aling** [comment]
thanks @michaelconan for the doc references, it seems like we already got the solution.
I'm closing the issue now, feel free to re-open or create new one if you're still encountering issues.
