### ISSUE TITLE
SNOW-585404: Compatibility cryptography 37.0.2

### ISSUE THREAD

**Issue by kyushy** [snowflakedb/snowflake-connector-python#1118]
We're running into an issue with snowflake-connector not being compatible with the new cryptography version.
`Requirement.parse('cryptography<37.0.0,>=3.1.0'), {'snowflake-connector-python'})`

Is there any plan to update those requirement to the new version? (37.0.2)

**Comment by elanou** [comment]
Interested as well. Looks like related PR is #1124

**Comment by panduz86** [comment]
Hello, this issue is impacting us also.
I see that the PR https://github.com/snowflakedb/snowflake-connector-python/pull/1124 is still ongoing, any news about?

**Comment by chaug** [comment]
Interested in this change within an azure context. Any news on PR #1124 ?

**Comment by sodul** [comment]
Unfortunately cryptography 38 is out so PR #1124 would not be sufficient. I guess I'll file a new PR to allow at least up to 38 and I hope the maintainers will be able to accept it.

**Comment by jskrzypek** [comment]
dependabot also made a fix fir thus: #1246

**Comment by sfc-gh-achandrasekaran** [comment]
To clean up and re-prioritize bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please re-create them. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response
