### ISSUE TITLE
SNOW-586325: Please add instructions on how to run tests

### ISSUE THREAD

**Issue by kbroughton** [snowflakedb/snowflake-connector-python#1120]
## What is the current behavior?

Pull requests template requires users to add tests for new code. However, there is no explanation of how to run tests.
In my case, I found ci/tests_darwin.sh but there are a ton of variables that need to be defined and no sample.env.sh to explain what variables are required/optional.  For example, you have config files in 
```
$ ls .github/workflows/parameters/public
parameters_aws.py.gpg   parameters_azure.py.gpg parameters_gcp.py.gpg
```
which are decrypted, but since we can't decrypt them, we have to reverse engineer what the file is like to set the variables to run the tests.
```
gpg --quiet --batch --yes --decrypt --passphrase="${PARAMETERS_SECRET}" ${PARAMS_FILE} > test/parameters.py
```

## What is the desired behavior?

There should be clear instructions on how to run the tests. Ideally, support an all-local test run for someone who just wants to make a one-time-fix PR.

## How would this improve `snowflake-connector-python`?
PRs requires tests, but nobody can run tests to check that their new tests work.

**Comment by sfc-gh-mkeller** [comment]
I think what you're looking for is here https://github.com/snowflakedb/snowflake-connector-python/tree/main/test#running-tests
We should have clear instructions on how to create your own `parameters.py` file and how to run the tests too there

**Comment by sfc-gh-aling** [comment]
To clean up and re-prioritize bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please re-create them. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
