### ISSUE TITLE
SNOW-595306: Can't install snowflake-connector-python-2.7.7 on Windows 10 (Python 3.9.8)

### ISSUE THREAD

**Issue by pybokeh** [snowflakedb/snowflake-connector-python#1154]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?
    
    Python 3.9.8

2. What operating system and processor architecture are you using?

   Windows 10

3. What are the component versions in the environment (`pip freeze`)?

   No packages - freshly created new virtual environment

4. What did you do?

    pip install "snowflake-connector-python[pandas]"

5. What did you expect to see?

   python snowflake connector installed with no errors

Error message while trying to pip install the snowflake-python connector:

```
 building 'snowflake.connector.arrow_iterator' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for snowflake-connector-python
Failed to build snowflake-connector-python
ERROR: Could not build wheels for snowflake-connector-python, which is required to install pyproject.toml-based projects
```

Apparently there is no pre-compiled Windows binaries for snowflake-python connector 2.7.7 for Python version 3.9.8.  Is that correct?

**Comment by airdropsqb** [comment]
Hi, [Solved] - Step by Step
https://youtu.be/Y4QxGemfNrs

**Comment by pybokeh** [comment]
I have upgraded to version 2.7.8 as it has pre-compiled binary (.whl) available.
