### ISSUE TITLE
SNOW-617426: Ability to overwrite tables when using write_pandas()

### ISSUE THREAD

**Issue by iamontheinet** [snowflakedb/snowflake-connector-python#1175]
## What is the current behavior?

Using the [write_pandas()](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.html#snowflake.snowpark.Session.write_pandas) API there is no way to overwrite contents of a Snowflake table with that of a Pandas DataFrame without first executing a truncate SQL statement.

## What is the desired behavior?

Using the [write_pandas()](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.html#snowflake.snowpark.Session.write_pandas) API there should be a way to optionally overwrite contents of a Snowflake table with that of a Pandas DataFrame.

## How would this improve `snowflake-connector-python`?

Better user experience for Python developers and especially those devs that are not familiar with truncate SQL statement or know how to write SQL.

## References, Other Background

Similar to overwriting contents of a Snowflake table when [writing contents of Snowpark DataFrames](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.html#snowflake.snowpark.DataFrame.write) using df.write.mode('overwrite')

**Comment by mhconradt** [comment]
Under the hood, `write_pandas` runs a `COPY` statement which is append-only. I recommend using `TRUNCATE TABLE tbl IF EXISTS` if you want to overwrite the rows in the table, or `DROP TABLE IF EXISTS` if you want to replace the table itself.

**Comment by iamontheinet** [comment]
Yes, I am looking into `DROP TABLE IF EXIST` which will account for any schema change(s) in the Pandas DataFrame. Thanks!

**Comment by simonwardjones** [comment]
@mhconradt would it be worth me making the PR I suggested or better to implement a work around in our application code?

**Comment by iamontheinet** [comment]
I am working on a solution as described in my comment above and will be creating a PR pretty soon.
