### ISSUE TITLE
Missing tag for release v2.7.9

### ISSUE THREAD

**Issue by ad-m-ss** [snowflakedb/snowflake-connector-python#1184]
1. What version of Python are you using?

N/A

2. What operating system and processor architecture are you using?

N/A

3. What are the component versions in the environment (`pip freeze`)?

```
pip freeze | grep 'snowflake'
snowflake-connector-python==2.7.9
```

4. What did you do?

On https://pypi.org/project/snowflake-connector-python/#history latest version is 2.7.9

On https://github.com/snowflakedb/snowflake-connector-python/releases or https://github.com/snowflakedb/snowflake-connector-python/tags there is no release 2.7.9.

5. What did you expect to see?

A expected all official versions of the package match to git tags.

6. Can you set logging to DEBUG and collect the logs?

N/A

Is the driver's release posted on Pypi official? Or maybe the Snowflake account on Pypi has been hijacked and a malicious release has been published, which could explain that the information on GitHub is incompatible with Pypi to such a significant extent?

**Comment by sfc-gh-mkeller** [comment]
The release is official. We forgot to add the release here, but `v2.7.9` is this commit: https://github.com/snowflakedb/snowflake-connector-python/commit/efeaeb15bdae7b7378b8a007bb9fe22e7f540669
We'll fix this today, thanks for reporting it!
