### ISSUE TITLE
SNOW-628192: RequestsDependencyWarning

### ISSUE THREAD

**Issue by bra-fsn** [snowflakedb/snowflake-connector-python#1188]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

`Python 3.10.1 (main, Dec  8 2021, 03:30:49) [GCC 10.2.1 20210110]`

2. What operating system and processor architecture are you using?

`Linux-5.13.0-52-generic-x86_64-with-glibc2.31`

3. What are the component versions in the environment (`pip freeze`)?

```
asn1crypto==1.5.1
certifi==2022.6.15
cffi==1.15.1
chardet==5.0.0
charset-normalizer==2.0.12
cryptography==36.0.2
idna==3.3
numpy==1.23.1
oscrypto==1.3.0
pandas==1.4.3
pyarrow==6.0.1
pycparser==2.21
pycryptodomex==3.15.0
PyJWT==2.4.0
pyOpenSSL==22.0.0
python-dateutil==2.8.2
pytz==2022.1
requests==2.28.1
six==1.16.0
snowflake-connector-python==2.7.9
urllib3==1.26.10
```

4. What did you do?

```
pip install snowflake-connector-python[pandas] chardet
python -c "import snowflake.connector"
/usr/local/lib/python3.10/site-packages/snowflake/connector/vendored/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported 
```

5. What did you expect to see?

No warning.

And please don't fix this by requiring a year old dependency, like the `requests` library, because other libraries depend on newer versions. :(

**Comment by sfc-gh-mkeller** [comment]
recreate jira

**Comment by sfc-gh-mkeller** [comment]
You're right, we should bump our vendored `urllib3` and `requests` instead of requiring old dependencies!
