### ISSUE TITLE
SNOW-659654: Support for arrow 9

### ISSUE THREAD

**Issue by cpcloud** [snowflakedb/snowflake-connector-python#1248]
## What is the current behavior?

Arrow 9 doesn't work with snowflake-connector-python

## What is the desired behavior?

Arrow 9 works with snowflake-connector-python

## How would this improve `snowflake-connector-python`?

By allowing the latest arrow release to work with snowflake-connector-python

## References, Other Background

@saulpw and I are working on a Snowflake backend for https://github.com/ibis-project/ibis and we'd like to be able to use the latest version of arrow so that we can fetch results using `fetch_arrow_all`.

**Comment by phobson** [comment]
In addition to the RAPIDS team, allowing `snowflake-connector-python` to work with pyarrow 9 would be very useful to dask users who rely on the [coiled-rutime](https://github.com/coiled/coiled-runtime/) to easily setup the computation environment of their distributed workers.

**Comment by xhochy** [comment]
We're successfully building the conda package with arrow 9, thus a bump in the package metadata should be sufficient.

**Comment by thomasaarholt** [comment]
Instead of Arrow 9, I would argue that Arrow 10 should now be targeted. That would also allow support for Python 3.11.

**Comment by thomasaarholt** [comment]
#1349  is working on this :)

**Comment by 3dbrows** [comment]
#1336 updates to Arrow 10 but without the Python upgrade.

**Comment by sfc-gh-yixie** [comment]
The latest version already supports pyarrow 10.
