### ISSUE TITLE
SNOW-660127: support for pyarrow 9

### ISSUE THREAD

**Issue by tstearns26** [snowflakedb/snowflake-connector-python#1250]
## What is the current behavior?
The current behavior doesn't allow for newer versions of pyarrow required for some GPU computing libraries

## What is the desired behavior?
Support for pyarrow 9

## How would this improve `snowflake-connector-python`?
allow for easier build for newest RAPIDS integration

**Comment by cpcloud** [comment]
I opened #1248 one day before this issue was opened. Perhaps we should close this one?

**Comment by sfc-gh-achandrasekaran** [comment]
Yep closing this in favor of 1248
