### ISSUE TITLE
SNOW-664703: Importing connector is slow

### ISSUE THREAD

**Issue by AleksaC** [snowflakedb/snowflake-connector-python#1253]
Hi, I noticed that importing snowflake connector takes a long time:
```console
$ hyperfine 'python -c "import snowflake.connector"'
Benchmark 1: python -c "import snowflake.connector"
  Time (mean ± σ):     466.0 ms ±  56.2 ms    [User: 434.9 ms, System: 29.1 ms]
  Range (min … max):   427.6 ms … 616.1 ms    10 runs
```

This can be investigated using python builtin import time profiling and [tuna](https://github.com/nschloe/tuna):
```shell
python -X importtime -c "import snowflake.connector" 2> importtime.log
tuna importtime.log
``` 
![Screenshot from 2022-09-17 02-57-31](https://user-images.githubusercontent.com/25728391/190834303-c00e13c9-4a4b-46e8-9518-239538528a42.png)

**Comment by sfc-gh-yixie** [comment]
Thanks @AleksaC for creating the PR.
@sfc-gh-mkeller Should we adopt this suggestion?
