### ISSUE TITLE
PUT documentation says source_compression=AUTO, source says auto_detect

### ISSUE THREAD

**Issue by sethwoodworth** [snowflakedb/snowflake-connector-python#126]
The [snowflake documentation on the PUT command](https://docs.snowflake.net/manuals/sql-reference/sql/put.html) claims to accept an argument of `SOURCE_COMPRESSION = AUTO`.  This is not the case.  The value the python connector expects is `auto_detect`.  Using `source_compression = auto_detect` in a PUT command, works.  Using `source_compression = AUTO` returns an error.  Somewhere in the cursor object, the request is getting sent to snowflake (`cursor._connection.cmd_query`), where it sets the `ret` return value.
As both the python client, and the java client have always expected `AUTO_DETECT`, something must have changed on snowflake's backend.
https://github.com/snowflakedb/snowflake-connector-python/blame/master/file_transfer_agent.py#L801

**Comment by smtakeda** [comment]
Looks like a documentation error. I'll report this to the documentation to fix it.
