### ISSUE TITLE
SNOW-669760: Union types returned by cursor.fetchone (and similar) require extensive casting on user side

### ISSUE THREAD

**Issue by sfc-gh-nsemmler** [snowflakedb/snowflake-connector-python#1263]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Python 3.6.8

2. What operating system and processor architecture are you using?

   Linux-5.16.13-generic-aarch64-with-centos-7.9.2009-AltArch

3. What are the component versions in the environment (`pip freeze`)?
  
   This has no impact on the issue.

4. What did you do?

   `cursor.execute(sql_query).fetchone()`

5. What did you expect to see?

  Regarding methods fetchone, fetchmany, fetchall, __iter__ and _result_iterator:
  I expect to get a `list` type from the methods on a SnowflakeCursor and a `dict` from the same methods on the DictCursor. Instead, I get a `dict | list` union type either way.

6. Can you set logging to DEBUG and collect the logs?

   Not relevant

**Problem**

Because the SnowflakeCursor/DictCursor returns a Union type as result for method like fetchone, users of the connector have to cast the result to make it work with mypy: e.g., `cast(list, cursor.fetchone())[0]`.

This is unnecessary, DictCursor should return dicts and SnowflakeCursor (or a ListCursor) should return lists.

**Comment by sfc-gh-sfan** [comment]
This is basically a type annotation issue? I believe the returned type is already determined by the cursor type. @sfc-gh-mkeller : Does this sound right?

**Comment by sfc-gh-mkeller** [comment]
I have reviewed the proposed PR and I gave a how to fix this issue in the long term there. Please refer to https://github.com/snowflakedb/snowflake-connector-python/pull/1264#discussion_r982745867

**Comment by sfc-gh-nsemmler** [comment]
@sfc-gh-sfan Yes, this is a type annotation issue.

**Comment by sfc-gh-aling** [comment]
To clean up and re-prioritize bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please re-create them. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
