### ISSUE TITLE
SNOW-669945: BUG: snowflake-connector-python versions  >= 2.7.8 have incompatible dependencies

### ISSUE THREAD

**Issue by velicanu** [snowflakedb/snowflake-connector-python#1265]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

Python 3.9.13

2. What operating system and processor architecture are you using?

macOS-11.6.7-x86_64-i386-64bit

3. What are the component versions in the environment (`pip freeze`)?

```
build==0.8.0
click==8.1.3
packaging==21.3
pep517==0.13.0
pip-tools==6.8.0
pyparsing==3.0.9
tomli==2.0.1
```

4. What did you do?

```bash
$ pip install pip-tools
$ echo "snowflake-connector-python==2.7.8" > requirements.in
$ pip-compile requirements.in
Could not find a version that matches cryptography<37.0.0,<39,>=3.1.0,>=38.0.0 (from pyOpenSSL==22.1.0->snowflake-connector-python==2.7.8->-r requirements.in (line 1))
...
There are incompatible versions in the resolved dependencies:
  cryptography<37.0.0,>=3.1.0 (from snowflake-connector-python==2.7.8->-r requirements.in (line 1))
  cryptography<39,>=38.0.0 (from pyOpenSSL==22.1.0->snowflake-connector-python==2.7.8->-r requirements.in (line 1)) 
```

5. What did you expect to see?

Doing the exact steps above with `snowflake-connector-python==2.7.7` and below works. Something in the dependencies broke with 2.7.8 and above. Also doesn't work in the most recent release `2.8.0` .

**Comment by sfc-gh-sfan** [comment]
It seems like incompatible dependencies on `cryptography` between `snowflake-connector-python` and `pyOpenSSL`. We should probably bump the version of `cryptography` on `snowflake-connector-python`. 

@sfc-gh-mkeller: If that makes sense I could put up a PR to update the dependency.

**Comment by sfc-gh-mkeller** [comment]
> It seems like incompatible dependencies on `cryptography` between `snowflake-connector-python` and `pyOpenSSL`. We should probably bump the version of `cryptography` on `snowflake-connector-python`.
> 
> @sfc-gh-mkeller: If that makes sense I could put up a PR to update the dependency.

Let's try doing that!
