### ISSUE TITLE
SNOW-679107: fetch_pandas_all not all columns with NUMBER(38, 2) converted to float64, some converted to object

### ISSUE THREAD

**Issue by claudiazi** [snowflakedb/snowflake-connector-python#1282]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   `Python 3.8.9 `

2. What operating system and processor architecture are you using?

   `macOS-11.6.4-x86_64-i386-64bit`

3. What are the component versions in the environment (`pip freeze`)?

`aiofiles==0.8.0
aiohttp==3.8.1
aiosignal==1.2.0
aiosqlite==0.17.0
alembic==1.8.1
anyio==3.6.1
asgi-lifespan==1.0.1
asn1crypto==1.5.1
async-timeout==4.0.2
asyncpg==0.26.0
attrs==22.1.0
bcrypt==4.0.0
beautifulsoup4==4.11.1
boto3==1.24.24
botocore==1.27.24
cachetools==5.2.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
click==8.1.3
cloudpickle==2.0.0
commonmark==0.9.1
coolname==1.1.0
croniter==1.3.4
cryptography==36.0.2
dask==2022.5.0
Deprecated==1.2.13
distributed==2022.5.0
docker==5.0.3
et-xmlfile==1.1.0
fastapi==0.79.0
filelock==3.8.0
frozenlist==1.3.1
fsspec==2022.7.1
google==3.0.0
google-api-core==2.8.2
google-api-python-client==2.52.0
google-auth==2.9.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.56.3
graphviz==0.20
greenlet==1.1.2
griffe==0.21.0
h11==0.12.0
HeapDict==1.0.1
httpcore==0.15.0
httplib2==0.20.4
httpx==0.23.0
idna==3.3
importlib-metadata==4.12.0
importlib-resources==5.7.1
Jinja2==3.1.2
jmespath==1.0.1
jsonpatch==1.32
jsonpointer==2.3
kubernetes==24.2.0
locket==1.0.0
lxml==4.9.1
Mako==1.2.1
MarkupSafe==2.1.1
marshmallow==3.15.0
marshmallow-oneofschema==3.0.1
msgpack==1.0.3
multidict==6.0.2
mypy-extensions==0.4.3
numpy==1.22.3
oauthlib==3.2.0
openpyxl==3.0.10
oscrypto==1.3.0
packaging==21.3
pandas==1.5.0
paramiko==2.11.0
partd==1.2.0
pathspec==0.9.0
pendulum==2.1.2
prefect==1.3.0
protobuf==4.21.2
psutil==5.9.0
pyarrow==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodomex==3.14.1
pydantic==1.9.0
PyGithub==1.55
Pygments==2.12.0
PyJWT==2.4.0
pyminizip==0.2.6
PyNaCl==1.5.0
pyOpenSSL==21.0.0
pyparsing==3.0.9
PySocks==1.7.1
python-box==6.0.2
python-dateutil==2.8.2
python-slugify==6.1.2
pytz==2022.1
pytzdata==2020.1
PyYAML==6.0
readchar==3.1.0
redshift-connector==2.0.907
requests==2.27.1
requests-oauthlib==1.3.1
rfc3986==1.5.0
rich==12.6.0
rsa==4.8
s3transfer==0.6.0
scramp==1.4.1
six==1.16.0
slack-sdk==3.18.1
sniffio==1.2.0
snowflake-connector-python==2.8.0
snowflake-sqlalchemy==1.3.4
socks==0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
SQLAlchemy==1.4.36
sqlalchemy-redshift==0.8.9
starlette==0.19.1
tabulate==0.8.9
tblib==1.7.0
text-unidecode==1.3
toml==0.10.2
toolz==0.11.2
tornado==6.1
typer==0.6.1
typing_extensions==4.4.0
uritemplate==4.1.1
urllib3==1.26.9
uvicorn==0.18.2
websocket-client==1.3.2
wrapt==1.14.1
yarl==1.8.1
zict==2.2.0
zipp==3.8.0
`

4. What did you do?

I just normally used the fetch_pandas_all() function

`
     conn = snowflake_conn.connect(
        **get_snowflake_conn_dict(),
        warehouse=warehouse_name,
        database=database_name,
        schema=schema_name,
    )
    cur = conn.cursor()
    cur.execute(query)
    df = cur.fetch_pandas_all()`

6. What did you expect to see?
    I expect that all columns of number(38,2) can be converted to float64. However, only one column had the correct conversion, but three other columns didn't convert. Although, in snowflake they were defined as number(38,2) already.

7. Can you set logging to DEBUG and collect the logs?
Not applicable here

**Comment by sfc-gh-mkeller** [comment]
This is expected, a `NUMBER(38,0)` won't necessarily fit into a [float64](https://arrow.apache.org/docs/python/generated/pyarrow.float64.html#pyarrow.float64).
Please see the more in depth explanation here: https://stackoverflow.com/a/56515598
In general `float64` is precise for ~15 significant figures. 38 significant figures calls for [decimal128](https://arrow.apache.org/docs/python/generated/pyarrow.decimal128.html#pyarrow.decimal128)

Here's my workaround, if your data fits into 64 bits then you could communicate this to Snowflake as:
```sql
from textwrap import dedent

import snowflake.connector

with snowflake.connector.connect(
    ...
) as conn:
    with conn.cursor() as cur:
        print(
            cur.execute(
                dedent(
                    '''\
                    select $1::NUMBER(10, 2) num from values (1),(2),(3),(4)
                    where 1=1
                    and $1 % 2 = 0;
                    ''',
               )
            ).fetch_pandas_all()
        )
```

**Comment by claudiazi** [comment]
many thanks for the very clear explanations!
