### ISSUE TITLE
Distribute via conda-forge & mention in docs

### ISSUE THREAD

**Issue by hajapy** [snowflakedb/snowflake-connector-python#130]
My team works with conda to manage our python environments and we are looking into using snowflake. We've opened up a PR to distribute this connector via conda-forge: https://github.com/conda-forge/staged-recipes/pull/7008

It would be nice if you could mention this way of installing the package in your docs (after the package becomes available), in addition to pypi/pip. Thanks!

**Comment by smtakeda** [comment]
@hajapy sorry but I could not catch up a conda recipe for snowflake connector. I'll find time to walk though and update docs. Thanks

**Comment by hajapy** [comment]
This is now distributed in conda-forge, but no one from this project is a maintainer on this release. Would someone want to be added to be a maintainer so you can help keep that distribution up to date? We’ve had some issues with requirements being kept aligned since these have changed quite often.
