### ISSUE TITLE
SNOW-686461: Can I add pandas and numpy to this list and have layer less that 50M in zipped format?

### ISSUE THREAD

**Issue by ArashMehraban** [snowflakedb/snowflake-connector-python#1306]
Is it possible to add pandas and numpy to this list: https://github.com/snowflakedb/snowflake-connector-python/blob/main/tested_requirements/requirements_38.reqs and the zip folder stays under 50M?

**Comment by ArashMehraban** [comment]
It is simply a python 3.8 lambda layer made for an AWS lambda so that it recognizes pandas. This enables one to write a line such as ‘import pandas’ in the python code that gets run in that AWS lambda. The layer is created from a requirement file that has pandas and numpy in there using pip install. This requirement file is a text file similar to the requirement file you have provided for snowflake. Please note that i create a layer from the requirement file you have provided for Snowflake so that i can write ‘import snowflake’ in aws lambda. The issue i am having is that if i have all of your requirements plus pandas and numpy in one requirement file, the layer size (after pip install) will be larger than 50M zipped.

**Comment by sfc-gh-aalam** [comment]
Hey @ArashMehraban, I'm closing this issue because I don't think we can remove dependencies just for one customer request. We might may reconsider if this is a recurring issue for more customers. 

Have you tried forking and experimenting with the requirement file that meets your need?
