### ISSUE TITLE
SNOW-695095: ModuleNotFoundError: No module named 'snowflake.connector'; 'snowflake' is not a package

### ISSUE THREAD

**Issue by susana-llobera** [snowflakedb/snowflake-connector-python#1331]
Dear Snowflake team, 

We are trying to connect with Python to Snowflake DDBB and we are recieving this error eventhough we adapt the requirements and python version : 

ModuleNotFoundError: No module named 'snowflake.connector'; 'snowflake' is not a package

**Python Version :** 
3.8.6

**Pip installation tried (Requirements)** 
pip install snowflake-connector-python[pandas]==2.8.1
pip install snowflake-connector-python==2.8.1

We have created a virtual environment with "virtualenvwrapper-win" and installed the requirements on that venv. In Pycharm we are also running with the same venv and checked that the packages are correctly installed. 

![image](https://user-images.githubusercontent.com/116001209/202197256-5e70e8c6-629a-4da3-b208-e4167d63eab7.png)

Could you please give us a hand to see were the issue may be?

Thanks,

**Comment by jamesdunham** [comment]
Do you by chance have a script named `snowflake.py` in your working directory?

**Comment by susana-llobera** [comment]
@jamesdunham thanks for the hint... 
Two days trying to figure it out and it's the clumsiest thing that's ever happened to me
Sorry for bothering you :)

**Comment by SM-Spryfox** [comment]
> Do you by chance have a script named `snowflake.py` in your working directory?

I unfortunately fell into the same trap. Thank you so much.

**Comment by ice-ctrl** [comment]
Same issue, but no snowflake.py file.

**Comment by ulrikpl** [comment]
Same issue, also no snowflake.py file

**Comment by SNaveenMathew** [comment]
Previously I did `pip install snowflake` as well as `pip install snowflake-connector`. Then `python -c "import snowflake.connector"` gave me the same error.

Fix (works without error): `pip uninstall snowflake`, then run `python -c "import snowflake.connector"`.

**Comment by bogdanfuerea** [comment]
In my case it works just fine with python 3.10, but with 3.11 you need to get rid `snowflake` and just keep `snowflake_connector_python`, so very much similar to the previous messages.

**Comment by arbitrio** [comment]
Hey team, still running into the same issue. Even if I uninstall, still gives me "No module named 'snowflake.connector'; 'snowflake' is not a package when I do import snowflake.connector.

Any ideas on what I can try?

**Comment by bogdanfuerea** [comment]
@arbitrio, if you're using a mac, you can make sure everything is alright by setting up an enclosed env. See [THIS PAGE](https://opensource.com/article/19/6/python-virtual-environments-mac). Also snowflake and snowflake-connector-python are two different libraries.

**Comment by ulrikpl** [comment]
Like bogdanfuerea experienced for Python 3.11 I needed to delete snowflake even though I was on 3.10. This worked for me on python==3.10.6. 

```pip install -r https://raw.githubusercontent.com/snowflakedb/snowflake-connector-python/v3.0.0/tested_requirements/requirements_38.reqs --force-reinstall```

```pip uninstall snowflake```

**Comment by arashroshani** [comment]
In my case the issue was the jupyter notebook kernel.

**Comment by mrBlackHat777** [comment]
verify if you have `snowflake` listed in your `requirements.txt` file, and retain only `snowflake-connector-python`.

**Comment by noahlove** [comment]
Solution for me was around jupyter caching it appears. 

If you accidentally install snowflake, then uninstall and reinstall snowflake-connector-python, you still need to force restart the kernel, otherwise it will still default to that message being displayed

**Comment by matdac12** [comment]
I just managed to solve this, we have to be careful on the packages we install since snowflake and snoflake.connector are two different things.  What worked for me was installing directly from the snowflake github repo.

pip install -r https://raw.githubusercontent.com/snowflakedb/snowflake-connector-python/v3.0.0/tested_requirements/requirements_38.reqs --force-reinstall


from snowflake.connector import connect

# Establish the connection
con = connect(
    user='***',
    password='***',
    account='url',
    warehouse='warehouse,
    database='database',
    schema='schema',
    role="role"
)

# Write the SQL query
query = "SELECT * FROM table name"

# Execute the query 
df = pd.read_sql(query, con)

**Comment by EdConor** [comment]
Take a look at [Skyvia](https://skyvia.com/connectors/snowflake), as a connector for Snowflake. This ensures efficient data flow, improved data accessibility, and enhanced reporting capabilities

**Comment by Ansumanbhujabal** [comment]
making  `pip uninstall snowflake` and then 'pip install snowflake-connector-python` while making sure that  you have not made any file name to `snowflake.py` solves the problem .
