### ISSUE TITLE
SNOW-696579: KeyError: 'keyring.backends'

### ISSUE THREAD

**Issue by 1234shel** [snowflakedb/snowflake-connector-python#1337]
Started getting this error all of a sudden this morning. 
My code is as follows:
```
%%capture
%pip install -r https://raw.githubusercontent.com/snowflakedb/snowflake-connector-python/v2.7.9/tested_requirements/requirements_37.reqs
%pip install snowflake-connector-python==2.7.9

import snowflake.connector
```

The error pops up on the import snowflake.connector line. This whole thing was working perfectly well yesterday and today it just broke. This code is running on AWS sagemaker notebook using the Python 3 (Data Science) kernel.

**Comment by marcellovictorino** [comment]
Exact same situation here. Is it perhaps the impact of a transient dependency?
Had some issues in the past with the infamous GLIB error due to packages like `cryptography` no longer supporting the old linux image used by AWS (specifically Lambda)

**Comment by 1234shel** [comment]
Thanks! I haven't tried that. I actually fixed the problem by switching to python base kernel and then just manually installing the packages I needed. I think there are some issues with sagemaker python 3 data science kernel.
