### ISSUE TITLE
Download concurrency control

### ISSUE THREAD

**Issue by artdgn** [snowflakedb/snowflake-connector-python#134]
It seems that there is no easy way to set the download concurrency settings for the connector. 

This results in very slow downloads for large result sets (as the default values are quite small).

From what I understand the smaller between `DEFAULT_CLIENT_RESULT_PREFETCH_SLOTS` and `DEFAULT_CLIENT_RESULT_PREFETCH_THREADS` controls the concurrency. 

At runtime those parameters are also received from the query response, but there doesn't seem to be a way to set them. Executing `ALTER SESSION SET CLIENT_PREFETCH_THREADS = 10` has no effect, and `ALTER SESSION SET CLIENT_RESULT_PREFETCH_SLOTS = 10` results in `invalid parameter 'CLIENT_RESULT_PREFETCH_SLOTS'` error.

What this causes is a very slow download, because if some chunk is slow to download or the connection is dropped, it delays the download of all other chunks.

Monkey patching the relevant parts of the code to increase those values at runtime results in much faster download speeds.

The questions are:
1) What is the supported way to increase concurrency? 
2) If there is none yet, will you be willing to accept a PR to the connector that enables a simpler override for those values?

**Comment by artdgn** [comment]
In case anyone is interested in the monkey-patch until a fix a proposed / created:
```python
import snowflake.connector
import snowflake.connector.chunk_downloader

class PatchedSnowflakeChunkDownloader(
    snowflake.connector.chunk_downloader.SnowflakeChunkDownloader):

    DEFAULT_CLIENT_RESULT_PREFETCH_SLOTS = 1000  # will be set to number of chunks
    DEFAULT_CLIENT_RESULT_PREFETCH_THREADS = 1000  # will be set to number of chunks

    def _pre_init(self, *args, **kwargs):
        kwargs.pop('prefetch_slots', None)
        kwargs.pop('prefetch_threads', None)
        snowflake.connector.chunk_downloader.logger.info('Setting download concurrency to maximum')
        super()._pre_init(*args,
                          prefetch_slots=self.DEFAULT_CLIENT_RESULT_PREFETCH_SLOTS,
                          prefetch_threads=self.DEFAULT_CLIENT_RESULT_PREFETCH_THREADS,
                          **kwargs)

snowflake.connector.connection.\
    DEFAULT_CONFIGURATION['chunk_downloader_class'] = PatchedSnowflakeChunkDownloader
```

**Comment by smtakeda** [comment]
Thanks for the patch. Currently there is no officially published parameter for Python Connector to control the concurrency in the result set downloader.

A parameter for JDBC is available but not for others.
https://docs.snowflake.net/manuals/sql-reference/parameters.html#client-prefetch-threads

We are planning to share the same parameters across all drivers to control it.

**Comment by artdgn** [comment]
Thanks for the quick response. I've written above that I've tried setting `CLIENT_PREFETCH_THREADS` parameter using `ALTER SESSION SET CLIENT_PREFETCH_THREADS = 10`, but it didn't have any effect. Probably because the values in the code are set from the response values for `CLIENT_RESULT_PREFETCH_THREADS` and `CLIENT_RESULT_PREFETCH_SLOTS` respectively and `CLIENT_PREFETCH_THREADS` is not referenced. The problem is that `CLIENT_RESULT_PREFETCH_THREADS` and `..SLOTS` are NOT settable in this way with a query (`ALTER SESSION SET ...`).

So, it seems there could be a way to set those parameters in the connector, if those values could be overriden by the value from `CLIENT_PREFETCH_THREADS`.

so [here](https://github.com/snowflakedb/snowflake-connector-python/blob/f0e81db88b2a1fd9f58128dced0d1bdc561e515e/cursor.py#L406) instead of :
```python
                if u'CLIENT_RESULT_PREFETCH_THREADS' in kv[u'name']:
                    self._client_result_prefetch_threads = kv[u'value']
                if u'CLIENT_RESULT_PREFETCH_SLOTS' in kv[u'name']:
                    self._client_result_prefetch_slots = kv[u'value']
```
change to:
```python 
                if u'CLIENT_PREFETCH_THREADS' in kv[u'name']:
                    self._client_result_prefetch_threads = kv[u'value']
                    self._client_result_prefetch_slots = kv[u'value']
```
This would allow to use that parameter to set the concurrency parameters, but would be a very difficult thing to discover.

Would be happy to make a PR with that change if it sounds ok to you.

**Comment by smtakeda** [comment]
will work on this but want to make it consistent with other drivers.

**Comment by artdgn** [comment]
@smtakeda Not sure if there's a special reason to have two parameters (slots and threads) if the only the smaller of their values is used in the end. But if you can use just one parameter, and just rename it to `_client_prefetch_threads`, and than it seems it will be consistent. Or did I miss something?

**Comment by smtakeda** [comment]
Fixing i #143.

Basically a new connection parameter is introduced: `client_prefetch_threads` to control the number of threads to download the result set. The behavior is equivalent to:
```
alter session set CLIENT_PREFETCH_THREADS=n
```
where n is between 1 to 10. This is consistent behavior with Snowflake JDBC and ODBC drivers.

It appeared `CLIENT_RESULT_PREFETCH_THREADS` and `CLIENT_RESULT_PREFETCH_SLOTS` are deprecated, so they are removed.

**Comment by artdgn** [comment]
@smtakeda thanks! I do still have a question that's bugging me if you don't mind - what are the considerations to set the maximum fetching threads to 10? 

I'm asking that because it seemed in my testing that due to downloads being started only after consecutive chunk consumption, what happens is that one slow chunk prevents all other threads from starting their next download, so with small number of threads and varying sizes of chunks this collapses to almost single threaded download. Allowing to set max threads to higher number might help with that.

An illustration: if we have the following chunks `s=slow, f=fast: [f,f,f,s,f,f,s,f,f,s,f,f]`, and 3 threads, the download will at first be concurrent, but after getting to the first slow chunk it will be in effect single threaded until the slow chunk is done: `r=ready, d=downloading, w=waiting : ([r,r,r,d,r,r,w,w,w]` (2 threads are waiting idle, despite being able to start next chunks) and than concurrent again, and than single-threaded again until slow is done, and than single-threaded again and so on.. 
So in effect the time to download will be determined by the equivalent of a single-thread downloading all the slowest chunks one by one which is far from ideal. The easiest way to alleviate this AFAI can see is to allow more threads to start, the main downside that I see is higher memory consumption, but that's the client's consideration. I guess that I'm missing some other problems with that workaround that prevent setting a higher thread number?

Another way would be to start the downloads regardless of the consumption (just mapping in the threadpool) and either hold in memory or pickle temporarily if memory is an issue.. But that would be a much a bigger change I guess.

**Comment by smtakeda** [comment]
If the results are unordered, the drivers could return chunks as their download finish. But that is acceptable, we could add the option.
Other way around is download all chunks to disk and read them from there, but one concern is security. The disk is not secure place, so when storing, it should be encrypted.
Aside from download strategy, the JSON like format is not optimal. That's one area we need to work on the server end.
