### ISSUE TITLE
SNOW-698916: Pyarrow 8 is not compatible with Python 3.11

### ISSUE THREAD

**Issue by noamcohen97** [snowflakedb/snowflake-connector-python#1345]
Pyarrow 10.0.1 just released today (supports Python 3.11), but snowflake-connector-python is bound to `pyarrow>=8.0.0,<8.1.0` which makes it impossible to run on Python 3.11.

1. What version of Python are you using?

   `Python 3.11.0 (main, Oct 24 2022, 22:24:46) [Clang 14.0.0 (clang-1400.0.29.102)]`

2. What operating system and processor architecture are you using?

   `macOS-13.0.1-arm64-arm-64bit`

3. What are the component versions in the environment (`pip freeze`)?

   `pyarrow==10.0.1`

4. What did you do?

   Install `snowflake-connector-python`

**Comment by sfc-gh-aling** [comment]
thanks @noamcohen97 for reaching out, we will prioritize the support for Python 3.11 in the first quarter of 2023 and will definitely take this into account.

**Comment by noamcohen97** [comment]
Checkout #1349
