### ISSUE TITLE
Large limit values causing server-side OOM errors.

### ISSUE THREAD

**Issue by artdgn** [snowflakedb/snowflake-connector-python#135]
A limit command with large values causes an out of memory error (on server-side - snowflake side) and the query fails (during execution, before any data is returned) even for a reasonable amount of results. 

Below are query-ids for actual queries that can be investigated.

The error reported is` "snowflake.connector.errors.ProgrammingError: 100130 (53200): baeb64b3-b38d-4e13-959a-c76ee79d59be: Out of memory error caused by LIMIT and/or OFFSET clause. Try reducing the number of rows requested."`. 

This happens in very puzzling circumstances. Example: 
1) query (`e07ca7cc-ee06-45a0-a39d-4be23808a463`) succeeds with a limit of 1M.
2) query (`e1eb2308-fd2a-49c6-8cf5-976d3180acc4`) succeeds and downloads results without a limit at all, but with 40M rows.
3) query (`df7154f4-5deb-4045-9af9-89968b34c9a2`) with limit of just 5M, which is a smaller number of results than the full query, fails with the aforementioned error on execution. 

From the wording of the error message this looks like a known issue already, but a limit clause is a very common and useful feature when only a subset of the full results set is needed. 

How is it possible to query for a limited (but large) amount of results?

**Comment by smtakeda** [comment]
@artdgn can you please reach out the Snowflake support? The github issue is mainly used to support the driver specific issues. Thanks.
