### ISSUE TITLE
Timestamp type converters slowing down fetching data.

### ISSUE THREAD

**Issue by artdgn** [snowflakedb/snowflake-connector-python#136]
It seems that fetching results with timestamps is very slow due to the way type conversion is handled in the connector. (I found this after working around the issue in #134, so the slowness described here is unrelated to the other issue).

From what I can understand the timestamps are downloaded as text float values, and later converted using various lamda and local functions using `datetime.datetime`. This is done one by one in a nested loop that goes over each row and each value and applies the lambdas. For large results set this tends to be actually slower than the download.

This issue is mainly to:
1) Report this slowness, so that hopefully some solution can be found.
2) Propose partial mitigations.
3) Document / share the workarounds I've tried so that other people with a similar problem may go straight to the ones that work (without going through the ones that don't).

Proposed solution: 
1) For large result sets with timestamps issue a `logger.warning('timestamp conversion may slow down fetching, if download is faster without timestamp data, try converting timestamp to epoch / string in the query'`
2) Allow controls to disable / control timestamp type conversion during the fetching stage, and just pass on the unix epoch in the results.
3) Batch convert using numpy / pandas e.g. `pd.to_datetime(epoch_seconds, unit='s')`, instead of one by one.

Workarounds that worked:
1) Converting timestamps in the query to epoch_seconds using `date_part(epoch, your_timestamp_column)`. And later (after having the data in an array / dataframe) using `pd.to_datetime(epoch_seconds, unit='s')`.
2) If you only need a timestamp as string and not as datetime object - cast it to string in the query using e.g. `your_timestamp_col::varchar`

Workarounds that don't work:
1) Trying to spread the conversion using multiprocessing. First of all, as in #81, the converter functions are lambdas / local scope functions so aren't pickleable. But even using a package like `pathos` that can pickle those, the overhead over pickling that much data back and forth and the actual slowness of using the converters that act on each individual value make this workaround slower rather faster for my case.
2) Trying other convertors (like numpy's, that are in the converter module)

**Comment by smtakeda** [comment]
Thanks for raising the issue. We did some experiments using multiple converters but haven't found the best solution for performance yet. Maybe it would have no conversion option having NullConverter, i.e., return string raw data as is, instead of having dependency on pandas/numpy.

**Comment by artdgn** [comment]
Thanks for the response @smtakeda . Would adding the warning message suggested above make sense in order to provide more information to whoever runs into this issue (conditioned on the download taking longer than a certain threshold and having timestamp converters in the converters)?

**Comment by smtakeda** [comment]
well, I feel adding `warning` would be too offensive and noisy as most applications don't ignore warning specifically. I would rather add a note to the doc and suggest NullConverter.

**Comment by smtakeda** [comment]
Adding nop/null converter that returns the raw output from Snowflake. It should remove overhead to gain better performance.
