### ISSUE TITLE
SNOW-709604: Documentation guidance on Python versions

### ISSUE THREAD

**Issue by sfc-gh-cstann** [snowflakedb/snowflake-connector-python#1373]
## What is the current behavior?

The [documentation](https://docs.snowflake.com/en/user-guide/python-connector-install.html) and repo have conflicting guidance on which Python versions are required. The documentation (screenshot below) limits Python versions to 3.6 - 3.9, but the connector has supported 3.10 since #982 and [requires Python >= 3.7](https://github.com/snowflakedb/snowflake-connector-python/blob/9286a9ee69952a4323f829a8ceecacda9eb52341/setup.cfg#L42).

<img width="907" alt="Screen Shot 2022-12-12 at 17 17 32" src="https://user-images.githubusercontent.com/117680068/207098288-4482cb8a-f4df-4bec-a406-c575a8ea2c4a.png">

## What is the desired behavior?

Align Python version dependency listed in the documentation to the repo.

## How would this improve `snowflake-connector-python`?

Provide clarity on which Python versions are supported.

**Comment by sfc-gh-aling** [comment]
we have fixed the documentation, thanks for bringing this up.
