### ISSUE TITLE
SNOW-710620: requirements_39.reqs breaking with snowflake-connector-python==2.9.0

### ISSUE THREAD

**Issue by shauncl** [snowflakedb/snowflake-connector-python#1374]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using? 3.9.15

2. What operating system and processor architecture are you using? macOS-12.6.1-x86_64-i386-64bit

3. What are the component versions in the environment (`pip freeze`)?

attrs==22.1.0
Authlib==1.1.0
boto3==1.26.6
botocore==1.29.6
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==38.0.3
idna==3.4
isodate==0.6.1
jmespath==1.0.1
lxml==4.9.1
platformdirs==2.5.4
pycparser==2.21
python-dateutil==2.8.2
pytz==2022.6
requests==2.28.1
requests-file==1.5.1
requests-toolbelt==0.10.1
s3transfer==0.6.0
sanitize-filename==1.2.0
simple-salesforce==1.12.2
six==1.16.0
urllib3==1.26.12
zeep==4.2.1

4. What did you do?

 python3 -m pip install -r https://raw.githubusercontent.com/snowflakedb/snowflake-connector-python/master/tested_requirements/requirements_39.reqs

5. What did you expect to see?

   Successful installation of requirements

6. Can you set logging to DEBUG and collect the logs?

  Nope but here's the output - ERROR: Could not find a version that satisfies the requirement snowflake-connector-python==2.9.0 (from versions: 1.3.17, 1.3.18, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.6.12, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.9.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9, 2.7.10, 2.7.11, 2.7.12, 2.8.0, 2.8.1, 2.8.2, 2.8.3)
#10 6.917 ERROR: No matching distribution found for snowflake-connector-python==2.9.0

**Comment by sfc-gh-sfan** [comment]
https://pypi.org/project/snowflake-connector-python/#history It seems 2.9.0 has not been released to PyPi yet.

**Comment by sfc-gh-achandrasekaran** [comment]
Version 2.9 is now out. @shauncl please let us know if this unblocks you

**Comment by shauncl** [comment]
Error is gone.  Thank you for the quick turnaround.
