### ISSUE TITLE
SNOW-720489: attribute 'OpenSSL_add_all_algorithms' depricated in pyopenssl version newer 22.0.0

### ISSUE THREAD

**Issue by RalfKow** [snowflakedb/snowflake-connector-python#1387]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

  Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

2. What operating system and processor architecture are you using?

   Windows-10-10.0.19044-SP0

3. What are the component versions in the environment (`pip freeze`)?

    ansiwrap==0.8.4
    asn1crypto==1.5.1
    attrs==22.1.0
    CacheControl==0.12.11
    cachy==0.3.0
    certifi==2022.6.15.1
    cffi==1.15.1
    charset-normalizer==2.1.1
    cleo==1.0.0a5
    clikit==0.6.2
    cloudpickle==2.0.0
    console-menu==0.7.0
    crashtest==0.3.1
    cryptography==38.0.3
    distlib==0.3.6
    dulwich==0.20.46
    filelock==3.8.0
    html5lib==1.1
    idna==3.3
    importlib-metadata==4.12.0
    importlib-resources==5.9.0
    jaraco.classes==3.2.2
    jsonschema==4.16.0
    keyring==23.9.1
    lockfile==0.12.2
    more-itertools==8.14.0
    msgpack==1.0.4
    numpy==1.23.4
    oscrypto==1.3.0
    packaging==20.9
    pandas==1.5.1
    pastel==0.2.1
    pexpect==4.8.0
    pkginfo==1.8.3
    pkgutil_resolve_name==1.3.10
    platformdirs==2.5.2
    poetry==1.2.0
    poetry-core==1.1.0
    poetry-plugin-export==1.0.6
    ptyprocess==0.7.0
    pyarrow==8.0.0
    pycparser==2.21
    pycryptodomex==3.15.0
    PyJWT==2.6.0
    pylev==1.4.0
    pyOpenSSL==22.1.0
    pyparsing==3.0.9
    pyrsistent==0.18.1
    python-dateutil==2.8.2
    pytz==2022.6
    pywin32==303
    pywin32-ctypes==0.2.0
    requests==2.28.1
    requests-toolbelt==0.9.1
    shellingham==1.5.0
    six==1.16.0
    snowflake-connector-python==2.8.1
    snowflake-snowpark-python==1.0.0
    textwrap3==0.9.2
    tomlkit==0.11.4
    typing_extensions==4.4.0
    urllib3==1.26.12
    virtualenv==20.16.5
    webencodings==0.5.1
    wget==3.2
    zipp==3.8.1

4. What did you do?

  I want to use it with snowpark for python.

5. What did you expect to see?

   Not use a newer version of pyopenssl than 22.0.0 because after that version it wont find the methode https://github.com/pyca/pyopenssl/blob/22.0.0/src/OpenSSL/crypto.py#L3268 in newer version since its depricated

6. Can you set logging to DEBUG and collect the logs?

============================= test session starts =============================
platform win32 -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0
rootdir: C:\dev\code\eap-blueprints-elt, configfile: pyproject.toml
plugins: anyio-3.6.2, dotenv-0.5.2
collected 5 items / 5 errors

=================================== ERRORS ====================================
_______ ERROR collecting tests/eap_blueprints_elt/test_feed_selector.py _______
tests\eap_blueprints_elt\test_feed_selector.py:4: in <module>
    from eap_blueprints_elt import feed_selector
src\eap_blueprints_elt\feed_selector.py:5: in <module>
    from eap_blueprints_elt.extraction import extract_api
src\eap_blueprints_elt\extraction\extract_api.py:10: in <module>
    from eap_blueprints_elt.eap_utils.snowpark.session_client import SessionClient
src\eap_blueprints_elt\eap_utils\snowpark\session_client.py:5: in <module>
    from snowflake.snowpark.session import Session
.venv\lib\site-packages\snowflake\snowpark\__init__.py:46: in <module>
    from snowflake.snowpark.async_job import AsyncJob
.venv\lib\site-packages\snowflake\snowpark\async_job.py:9: in <module>
    from snowflake.connector.options import pandas
.venv\lib\site-packages\snowflake\connector\__init__.py:16: in <module>
    from .connection import SnowflakeConnection
.venv\lib\site-packages\snowflake\connector\connection.py:25: in <module>
    from . import errors, proxy
.venv\lib\site-packages\snowflake\connector\errors.py:18: in <module>
    from .telemetry_oob import TelemetryService
.venv\lib\site-packages\snowflake\connector\telemetry_oob.py:20: in <module>
    from .vendored import requests
.venv\lib\site-packages\snowflake\connector\vendored\requests\__init__.py:119: in <module>
    from ..urllib3.contrib import pyopenssl
.venv\lib\site-packages\snowflake\connector\vendored\urllib3\contrib\pyopenssl.py:50: in <module>
    import OpenSSL.SSL
.venv\lib\site-packages\OpenSSL\__init__.py:8: in <module>
    from OpenSSL import crypto, SSL
.venv\lib\site-packages\OpenSSL\crypto.py:3268: in <module>
    _lib.OpenSSL_add_all_algorithms()
E   AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
_ ERROR collecting tests/eap_blueprints_elt/eap_utils/snowpark/test_session_client.py _

**Comment by connorwaldman** [comment]
I am having the same issue. It looks like this is related to cryptography and pyOpenSSL versions: https://github.com/pyca/cryptography/issues/7959.

**Comment by sfc-gh-mkeller** [comment]
I'm sorry @RalfKow I  cannot reproduce  your error with  the following environment:

<details>
<summary>My pip freeze</summary>

```
ansiwrap==0.8.4
asn1crypto==1.5.1
attrs==22.1.0
CacheControl==0.12.11
cachy==0.3.0
certifi==2022.6.15.1
cffi==1.15.1
charset-normalizer==2.1.1
cleo==1.0.0a5
clikit==0.6.2
cloudpickle==2.0.0
console-menu==0.7.0
crashtest==0.3.1
cryptography==38.0.3
distlib==0.3.6
dulwich==0.20.46
filelock==3.8.0
html5lib==1.1
idna==3.3
importlib-metadata==4.12.0
importlib-resources==5.9.0
jaraco.classes==3.2.2
jsonschema==4.16.0
keyring==23.9.1
lockfile==0.12.2
more-itertools==8.14.0
msgpack==1.0.4
numpy==1.23.4
oscrypto==1.3.0
packaging==20.9
pandas==1.5.1
pastel==0.2.1
pexpect==4.8.0
pkginfo==1.8.3
pkgutil_resolve_name==1.3.10
platformdirs==2.5.2
poetry==1.2.0
poetry-core==1.1.0
poetry-plugin-export==1.0.6
ptyprocess==0.7.0
pyarrow==8.0.0
pycparser==2.21
pycryptodomex==3.15.0
PyJWT==2.6.0
pylev==1.4.0
pyOpenSSL==22.1.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2022.6
requests==2.28.1
requests-toolbelt==0.9.1
shellingham==1.5.0
six==1.16.0
snowflake-connector-python==2.8.1
snowflake-snowpark-python==1.0.0
textwrap3==0.9.2
tomlkit==0.11.4
typing_extensions==4.4.0
urllib3==1.26.12
virtualenv==20.16.5
webencodings==0.5.1
wget==3.2
xattr==0.9.9
zipp==3.8.1
```

</details>

```console
(venv)
/tmp
❯ cat "/Users/mkeller/Library/Application Support/JetBrains/PyCharm2022.3/scratches/scratch_1.py"
import snowflake.connector

with snowflake.connector.connect(
    ...
) as conn:
    with conn.cursor() as cur:
        cur.execute(f"select 1")
        print(cur.fetchall())
(venv)
/tmp
❯ python "/Users/mkeller/Library/Application Support/JetBrains/PyCharm2022.3/scratches/scratch_1.py"
[(1,)]
``` 

Note that I'm using macos here, so I  skipped installing  `pywin32`  and  `pywin32-ctypes`.

Are you sure that your frozen environment  is used when running your code?
Your stack trace says:
```console
.venv\lib\site-packages\OpenSSL\crypto.py:3268: in
_lib.OpenSSL_add_all_algorithms()
```
which doesn't check out for the version in your pip freeze https://github.com/pyca/pyopenssl/blob/22.1.0/src/OpenSSL/crypto.py#L3268

However; the line number checks out for `v22.0.0` https://github.com/pyca/pyopenssl/blob/22.0.0/src/OpenSSL/crypto.py#L3268 Which also works for me locally.

Could you try recreating your virtualenv?

**Comment by RalfKow** [comment]
Thanks for your fast response. Maybe it has to do with me using poetry. Attached:
- the error code 
- poetry.lock file
- Intalled versions

Stack trace:
unittest-run.............................................................Failed
- hook id: unittest-run
- exit code: 2

============================= test session starts =============================
platform win32 -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0
rootdir: C:\devsbb\code\eap-blueprints-elt, configfile: pyproject.toml
plugins: anyio-3.6.2, dotenv-0.5.2
collected 5 items / 5 errors

=================================== ERRORS ====================================
_______ ERROR collecting tests/eap_blueprints_elt/test_feed_selector.py _______
tests\eap_blueprints_elt\test_feed_selector.py:4: in <module>
    from eap_blueprints_elt import feed_selector
src\eap_blueprints_elt\feed_selector.py:5: in <module>

    from eap_blueprints_elt.extraction import extract_api
src\eap_blueprints_elt\extraction\extract_api.py:10: in <module>
    from eap_blueprints_elt.eap_utils.snowpark.session_client import SessionClient
src\eap_blueprints_elt\eap_utils\snowpark\session_client.py:5: in <module>
    from snowflake.snowpark.session import Session
.venv\lib\site-packages\snowflake\snowpark\__init__.py:46: in <module>
    from snowflake.snowpark.async_job import AsyncJob
.venv\lib\site-packages\snowflake\snowpark\async_job.py:9: in <module>
    from snowflake.connector.options import pandas
.venv\lib\site-packages\snowflake\connector\__init__.py:16: in <module>
    from .connection import SnowflakeConnection
.venv\lib\site-packages\snowflake\connector\connection.py:25: in <module>
    from . import errors, proxy
.venv\lib\site-packages\snowflake\connector\errors.py:18: in <module>
    from .telemetry_oob import TelemetryService
.venv\lib\site-packages\snowflake\connector\telemetry_oob.py:20: in <module>
    from .vendored import requests
.venv\lib\site-packages\snowflake\connector\vendored\requests\__init__.py:119: in <module>
    from ..urllib3.contrib import pyopenssl
.venv\lib\site-packages\snowflake\connector\vendored\urllib3\contrib\pyopenssl.py:50: in <module>
    import OpenSSL.SSL
.venv\lib\site-packages\OpenSSL\__init__.py:8: in <module>
    from OpenSSL import crypto, SSL
.venv\lib\site-packages\OpenSSL\crypto.py:3268: in <module>
    _lib.OpenSSL_add_all_algorithms()
E   AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
_ ERROR collecting tests/eap_blueprints_elt/eap_utils/snowpark/test_session_client.py _
tests\eap_blueprints_elt\eap_utils\snowpark\test_session_client.py:3: in <module>
    from eap_blueprints_elt.eap_utils.snowpark.session_client import SessionClient
src\eap_blueprints_elt\eap_utils\snowpark\session_client.py:5: in <module>
    from snowflake.snowpark.session import Session
.venv\lib\site-packages\snowflake\snowpark\__init__.py:46: in <module>
    from snowflake.snowpark.async_job import AsyncJob
.venv\lib\site-packages\snowflake\snowpark\async_job.py:10: in <module>
    from snowflake.snowpark._internal.analyzer.analyzer_utils import result_scan_statement
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\analyzer_utils.py:9: in <module>
    from snowflake.snowpark._internal.analyzer.binary_plan_node import (
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\binary_plan_node.py:6: in <module>
    from snowflake.snowpark._internal.analyzer.expression import Expression
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\expression.py:13: in <module>
    from snowflake.snowpark._internal.error_message import SnowparkClientExceptionMessages
.venv\lib\site-packages\snowflake\snowpark\_internal\error_message.py:5: in <module>
    from snowflake.connector import OperationalError, ProgrammingError
.venv\lib\site-packages\snowflake\connector\__init__.py:16: in <module>
    from .connection import SnowflakeConnection
.venv\lib\site-packages\snowflake\connector\connection.py:25: in <module>
    from . import errors, proxy
.venv\lib\site-packages\snowflake\connector\errors.py:18: in <module>
    from .telemetry_oob import TelemetryService
.venv\lib\site-packages\snowflake\connector\telemetry_oob.py:20: in <module>
    from .vendored import requests
.venv\lib\site-packages\snowflake\connector\vendored\requests\__init__.py:119: in <module>
    from ..urllib3.contrib import pyopenssl
.venv\lib\site-packages\snowflake\connector\vendored\urllib3\contrib\pyopenssl.py:50: in <module>
    import OpenSSL.SSL
.venv\lib\site-packages\OpenSSL\__init__.py:8: in <module>
    from OpenSSL import crypto, SSL
.venv\lib\site-packages\OpenSSL\crypto.py:3268: in <module>
    _lib.OpenSSL_add_all_algorithms()
E   AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
_ ERROR collecting tests/eap_blueprints_elt/load/json/test_load_file_json.py __
tests\eap_blueprints_elt\load\json\test_load_file_json.py:3: in <module>
    from snowflake.snowpark.functions import col
.venv\lib\site-packages\snowflake\snowpark\__init__.py:46: in <module>
    from snowflake.snowpark.async_job import AsyncJob
.venv\lib\site-packages\snowflake\snowpark\async_job.py:10: in <module>
    from snowflake.snowpark._internal.analyzer.analyzer_utils import result_scan_statement
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\analyzer_utils.py:9: in <module>
    from snowflake.snowpark._internal.analyzer.binary_plan_node import (
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\binary_plan_node.py:6: in <module>
    from snowflake.snowpark._internal.analyzer.expression import Expression
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\expression.py:13: in <module>
    from snowflake.snowpark._internal.error_message import SnowparkClientExceptionMessages
.venv\lib\site-packages\snowflake\snowpark\_internal\error_message.py:5: in <module>
    from snowflake.connector import OperationalError, ProgrammingError
.venv\lib\site-packages\snowflake\connector\__init__.py:16: in <module>
    from .connection import SnowflakeConnection
.venv\lib\site-packages\snowflake\connector\connection.py:25: in <module>
    from . import errors, proxy
.venv\lib\site-packages\snowflake\connector\errors.py:18: in <module>
    from .telemetry_oob import TelemetryService
.venv\lib\site-packages\snowflake\connector\telemetry_oob.py:20: in <module>
    from .vendored import requests
.venv\lib\site-packages\snowflake\connector\vendored\requests\__init__.py:119: in <module>
    from ..urllib3.contrib import pyopenssl
.venv\lib\site-packages\snowflake\connector\vendored\urllib3\contrib\pyopenssl.py:50: in <module>
    import OpenSSL.SSL
.venv\lib\site-packages\OpenSSL\__init__.py:8: in <module>
    from OpenSSL import crypto, SSL
.venv\lib\site-packages\OpenSSL\crypto.py:3268: in <module>
    _lib.OpenSSL_add_all_algorithms()
E   AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
_ ERROR collecting tests/eap_blueprints_elt/load/kafka/test_flatten_kafka.py __
tests\eap_blueprints_elt\load\kafka\test_flatten_kafka.py:3: in <module>
    from snowflake.snowpark.session import col
.venv\lib\site-packages\snowflake\snowpark\__init__.py:46: in <module>
    from snowflake.snowpark.async_job import AsyncJob
.venv\lib\site-packages\snowflake\snowpark\async_job.py:10: in <module>
    from snowflake.snowpark._internal.analyzer.analyzer_utils import result_scan_statement
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\analyzer_utils.py:9: in <module>
    from snowflake.snowpark._internal.analyzer.binary_plan_node import (
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\binary_plan_node.py:6: in <module>
    from snowflake.snowpark._internal.analyzer.expression import Expression
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\expression.py:13: in <module>
    from snowflake.snowpark._internal.error_message import SnowparkClientExceptionMessages
.venv\lib\site-packages\snowflake\snowpark\_internal\error_message.py:5: in <module>
    from snowflake.connector import OperationalError, ProgrammingError
.venv\lib\site-packages\snowflake\connector\__init__.py:16: in <module>
    from .connection import SnowflakeConnection
.venv\lib\site-packages\snowflake\connector\connection.py:25: in <module>
    from . import errors, proxy
.venv\lib\site-packages\snowflake\connector\errors.py:18: in <module>
    from .telemetry_oob import TelemetryService
.venv\lib\site-packages\snowflake\connector\telemetry_oob.py:20: in <module>
    from .vendored import requests
.venv\lib\site-packages\snowflake\connector\vendored\requests\__init__.py:119: in <module>
    from ..urllib3.contrib import pyopenssl
.venv\lib\site-packages\snowflake\connector\vendored\urllib3\contrib\pyopenssl.py:50: in <module>
    import OpenSSL.SSL
.venv\lib\site-packages\OpenSSL\__init__.py:8: in <module>
    from OpenSSL import crypto, SSL
.venv\lib\site-packages\OpenSSL\crypto.py:3268: in <module>
    _lib.OpenSSL_add_all_algorithms()
E   AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
___ ERROR collecting tests/eap_blueprints_elt/load/kafka/test_load_kafka.py ___
tests\eap_blueprints_elt\load\kafka\test_load_kafka.py:4: in <module>
    from snowflake.snowpark.dataframe import col
.venv\lib\site-packages\snowflake\snowpark\__init__.py:46: in <module>
    from snowflake.snowpark.async_job import AsyncJob
.venv\lib\site-packages\snowflake\snowpark\async_job.py:10: in <module>
    from snowflake.snowpark._internal.analyzer.analyzer_utils import result_scan_statement
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\analyzer_utils.py:9: in <module>
    from snowflake.snowpark._internal.analyzer.binary_plan_node import (
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\binary_plan_node.py:6: in <module>
    from snowflake.snowpark._internal.analyzer.expression import Expression
.venv\lib\site-packages\snowflake\snowpark\_internal\analyzer\expression.py:13: in <module>
    from snowflake.snowpark._internal.error_message import SnowparkClientExceptionMessages
.venv\lib\site-packages\snowflake\snowpark\_internal\error_message.py:5: in <module>
    from snowflake.connector import OperationalError, ProgrammingError
.venv\lib\site-packages\snowflake\connector\__init__.py:16: in <module>
    from .connection import SnowflakeConnection
.venv\lib\site-packages\snowflake\connector\connection.py:25: in <module>
    from . import errors, proxy
.venv\lib\site-packages\snowflake\connector\errors.py:18: in <module>
    from .telemetry_oob import TelemetryService
.venv\lib\site-packages\snowflake\connector\telemetry_oob.py:20: in <module>
    from .vendored import requests
.venv\lib\site-packages\snowflake\connector\vendored\requests\__init__.py:119: in <module>
    from ..urllib3.contrib import pyopenssl
.venv\lib\site-packages\snowflake\connector\vendored\urllib3\contrib\pyopenssl.py:50: in <module>
    import OpenSSL.SSL
.venv\lib\site-packages\OpenSSL\__init__.py:8: in <module>
    from OpenSSL import crypto, SSL
.venv\lib\site-packages\OpenSSL\crypto.py:3268: in <module>
    _lib.OpenSSL_add_all_algorithms()
E   AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
=========================== short test summary info ===========================
ERROR tests/eap_blueprints_elt/test_feed_selector.py - AttributeError: module...
ERROR tests/eap_blueprints_elt/eap_utils/snowpark/test_session_client.py - At...
ERROR tests/eap_blueprints_elt/load/json/test_load_file_json.py - AttributeEr...
ERROR tests/eap_blueprints_elt/load/kafka/test_flatten_kafka.py - AttributeEr...
ERROR tests/eap_blueprints_elt/load/kafka/test_load_kafka.py - AttributeError...
!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 5 errors in 3.63s ==============================

[petry.lock.txt](https://github.com/snowflakedb/snowflake-connector-python/files/10342261/petry.lock.txt)

**Comment by yogevyuval** [comment]
Does this still happen after https://github.com/snowflakedb/snowflake-connector-python/pull/1386 ?

If not, it would be great to release a new version

**Comment by RalfKow** [comment]
I tried out
- updating snowflake-snowpark-python from 1.0.0 to 1.1.0 & pyarrow from 8.0.0 to 10.0.1 --> fixed error
