### ISSUE TITLE
Discussion: Use of keyring library

### ISSUE THREAD

**Issue by manugarri** [snowflakedb/snowflake-connector-python#139]
This is more of a discussion, and not a specific issue, but I thought it would make sense to put it out here.

Let me give you a bit of context so you see where I come from.

At my [company](https://github.com/daltix) we are implementing Airflow as our main scheduler. We just migrated to Snowflake from s3/athena, and we are pretty happy with it.

As part of the migration we need to set up jobs in Airflow that perform a set of ETL scripts that modify our Snowflake datalake.

*"No problem, I can set Airflow up"* I said, unknown to me that the next couple days would be hell.

See, I have set up Airflow multiple times. I spin a machine, build an AMI, spin up an ubuntu 18.04 EC2 instance to test the ami, set up a auth user and test some dags. 

At this moment I am a happy camper, but I just realize that I forgot to add the snowflake dependencies.

So on my builder script I just change 

`pip install apache-airflow[s3,slack]`

to:

`pip install apache-airflow[s3,slack,snowflake]`.

Then I run everything again,  seems to be ok, but surprise!, when I do: 

`from airflow.contrib.hooks.snowflake_hook import SnowflakeHook`

I get the following error:

```
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
```

*"Oh boy"* I think, lets  see how we can fix this. I start the research.

It turns out that the keyring package has [an outstanding bug in launchpad](https://bugs.launchpad.net/usd-importer/+bug/1794041). that doesnt help.

Then I see that the `keyring.util.escape` [has been deprecated since 15.0.0](https://github.com/jaraco/keyring/blob/master/CHANGES.rst#1500), if I do `pip freeze` I get that my installed version is `17.0.0`, why is it happening?

Well, it turns out, the keyring package is linked to the [python-cryptography package](https://github.com/pyca/cryptography/issues/3815) that is used on a OS level to do things like for example, allowing ssh into the machine.

A few hours later (i wont explain the details) I managed to fix the issue (I had to update the keyrings.alt package for my environment). And then I started thinking.

**Why the hell does Airflow Snowflake require all this mess with the keyring package**?

Then I find out that the [keyring is required](https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py#L50) in the snowflake-connector-python (this one), and it is used as a convenience so you can use your OS keyring to retrieve the passwords. I understand that for a person using the connector on a daily basis to analyze data this is very convenient (so they dont have to type their credentials again and again as a peasant).

But the thing is, not a  single Database connector in python does this! Why does a connection library care about how the user handles their secrets? How is it that somehow this minor convenience has ended up all the way in Apache Airflow dependencies for Snowflake?

I would very much suggest (and let me know if you need help with a PR, since it should be relatively easy to implement) to remove secret management from a DB connector and let other libraries handle that

**Comment by smtakeda** [comment]
`keyring` was added for the future enhancements. I understand it is not required for most use cases. Will look into this.

**Comment by manugarri** [comment]
@smtakeda great! in my opinion that use case should be added as an optional external utility at best

**Comment by smtakeda** [comment]
v1.7.4 made `keyring` optional.

**Comment by manugarri** [comment]
:+1
