### ISSUE TITLE
SNOW-733213: Add ability for write_pandas to truncate table instead of drop table

### ISSUE THREAD

**Issue by sfc-gh-cconner** [snowflakedb/snowflake-connector-python#1413]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   3.9.0

2. What operating system and processor architecture are you using?

macOS-13.1-x86_64-i386-64bit

3. What are the component versions in the environment (`pip freeze`)?

snowflake-connector-python==2.9.0

4. What did you do?

Using write_pandas with overwrite=true, the table on Snowflake side is dropped and then recreated.  This was decided in this git issue:

https://github.com/snowflakedb/snowflake-connector-python/issues/1175

The decision was made in order to maintain the dataframe schema.  However, drop tables loses grants on the table.

5. What did you expect to see?

We would like to have an option that truncates the table instead of dropping the table in order to maintain grants.

**Comment by sfc-gh-sfan** [comment]
Thanks for reporting! This is actually a good onboarding issue :)

**Comment by ttzhou** [comment]
Reading the code though, it appears to be doing "drop and swap/rename", not truncating. I don't see any "TRUNCATE" string anywhere else in that file...

**Comment by andreqaugusto** [comment]
per my personal experience and as @ttzhou pointed out, the code does not behave as the docstring says it so... I submitted a (probable) fix to this issue.
