### ISSUE TITLE
SNOW-734449: Version 3.0.0 on PyPI does not include source distribution or linux wheels!

### ISSUE THREAD

**Issue by mirosval** [snowflakedb/snowflake-connector-python#1417]
The version 3.0.0 published on PyPI does not include sources or linux wheels. There are only wheels for macos and windows.

The previous version 2.9.0 had those.

<img width="761" alt="Screenshot 2023-01-30 at 08 45 48" src="https://user-images.githubusercontent.com/1315417/215417590-ac0bafad-ba11-40b0-a851-78671a401060.png">

**Comment by calpaterson** [comment]
(This makes the package un-installable on Linux.)

**Comment by SetaSouto** [comment]
I can confirm this. Installed successfully in my Mac but failed when building a Docker image based on `python:3.9-slim` (Debian) with this dependency.

**Comment by seanabreau** [comment]
I can also confirm failed when building a Docker image on `python:3.11-slim`

**Comment by sfc-gh-kdama** [comment]
Pypi artifacts are updated. This is fixed now.
