### ISSUE TITLE
SNOW-735102: NumPy NaN not converted correctly during binding

### ISSUE THREAD

**Issue by nic-crouch-sfc** [snowflakedb/snowflake-connector-python#1419]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

Python 3.8.16 (default, Jan 17 2023, 16:39:35)
[Clang 14.0.6 ]

2. What operating system and processor architecture are you using?

 macOS-13.1-arm64-arm-64bit

3. What are the component versions in the environment (`pip freeze`)?

   snowflake-connector-python @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_50htu8jxga/croots/recipe/snowflake-connector-python_1662316547511/work

snowflake-snowpark-python @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_490_51r7yk/croot/snowflake-snowpark-python_1674852922485/work

numpy @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_d18vvv3mag/croot/numpy_and_numpy_base_1672336185310/work

4. What did you do?

import numpy as np
import snowflake.connector

'''
con = snowflake.connector.connect(
    user='',
    password='',
    account='',
  database='',
  schema='',
  warehouse='',
  paramstyle = 'pyformat'
)
'''
cs = con.cursor()

con.cursor().execute(
    """
    CREATE OR REPLACE TABLE test (v1 float, v2 float, nan_value float);
    """
    )

cs.execute(
    "INSERT INTO test "
    "VALUES(%s,%s,%s)", (
        float(0.1234),
        np.float16(0.1234),
        float('nan')
    )
 )

cs.close()

5. What did you expect to see?

   Expected to see NaN inserted into the test table. Got ProgrammingError:
ProgrammingError: 000904 (42000): SQL compilation error: error line 1 at position 38
invalid identifier 'NAN'

6. Can you set logging to DEBUG and collect the logs?

Log attached.

**Comment by sfc-gh-aling** [comment]
Hi @nic-crouch-sfc ,

as a a workaround, to insert `nan` you can specify the string to be `NaN`.
passing float('nan') as `s%` gives string `nan` which is of all lower cases that snowflake can not recognize.

**Comment by sfc-gh-achandrasekaran** [comment]
@nic-crouch-sfc did this work?
