### ISSUE TITLE
No module named 'azure.common'; 'azure' is not a package

### ISSUE THREAD

**Issue by bouke-nederstigt** [snowflakedb/snowflake-connector-python#144]
Since upgrading to v1.7.3 I get the following error when importing snowflake.connector.
No module named 'azure.common'; 'azure' is not a package

I'm running snowflake on Docker (python:3.6-slim-stretch), and install using pip. Reverting back to 1.7.2 resolves the issue, but obviously this isn't great in the long run.

**Comment by smtakeda** [comment]
1.7.3 updated azure package. can you please provide the following?
1. What version of Python are you using (`python --version`)?

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

3. What are the component versions in the environment (`pip list`)? 

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

5. What did you expect to see?

6. What did you see instead?

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by bouke-nederstigt** [comment]
1. Python 3.6.7
2. Linux-4.9.125-linuxkit-x86_64-with-debian-9.6
3. 
Package                    Version   
-------------------------- ----------
alembic                    0.8.10    
amazon-kclpy               1.5.0     
amqp                       2.3.2     
apache-airflow             1.9.0     
argh                       0.26.2    
asn1crypto                 0.24.0    
azure-common               1.1.16    
azure-nspkg                2.0.0     
azure-storage              0.36.0    
Babel                      2.6.0     
bcrypt                     3.1.4     
billiard                   3.5.0.5   
bleach                     2.1.2     
boto                       2.49.0    
boto3                      1.9.62    
botocore                   1.12.62   
celery                     4.1.1     
certifi                    2018.11.29
cffi                       1.11.5    
chardet                    3.0.4     
Click                      7.0       
configparser               3.5.0     
coverage                   4.5.2     
croniter                   0.3.26    
cryptography               2.4.2     
cycler                     0.10.0    
Cython                     0.29.1    
dill                       0.2.8.2   
docutils                   0.14      
entrypoints                0.2.3     
et-xmlfile                 1.0.1     
fbprophet                  0.3.post2 
filechunkio                1.8       
Flask                      0.11.1    
Flask-Admin                1.4.1     
Flask-Bcrypt               0.7.1     
Flask-Cache                0.13.1    
Flask-Login                0.2.11    
flask-swagger              0.2.13    
Flask-WTF                  0.14      
flower                     0.9.2     
funcsigs                   1.0.0     
future                     0.16.0    
gitdb2                     2.0.5     
GitPython                  2.1.11    
great-expectations         0.4.4     
gunicorn                   19.9.0    
html5lib                   1.0.1     
idna                       2.8       
ijson                      2.3       
ipaddress                  1.0.22    
itsdangerous               1.1.0     
JayDeBeApi                 1.1.1     
jdcal                      1.4       
jeepney                    0.4       
Jinja2                     2.8.1     
jmespath                   0.9.3     
JPype1                     0.6.3     
jsonschema                 2.6.0     
keyring                    17.0.0    
kinesis-events             0.1.0     
kiwisolver                 1.0.1     
kombu                      4.2.2     
lockfile                   0.12.2    
lxml                       3.8.0     
Mako                       1.0.7     
Markdown                   2.6.11    
MarkupSafe                 1.1.0     
marshmallow                2.15.0    
marshmallow-oneofschema    1.0.5     
matplotlib                 3.0.2     
mock                       1.0.1     
mysqlclient                1.3.14    
nose                       1.3.7     
numpy                      1.15.4    
openpyxl                   2.5.12    
ordereddict                1.1       
pandas                     0.23.4    
pip                        18.1      
psutil                     4.4.2     
pyasn1                     0.4.4     
pyasn1-modules             0.2.2     
pycodestyle                2.4.0     
pycparser                  2.19      
pycryptodomex              3.7.2     
Pygments                   2.3.0     
PyJWT                      1.7.1     
pyodbc                     4.0.24    
pyOpenSSL                  18.0.0    
pyparsing                  2.3.0     
pystan                     2.18.0.0  
python-daemon              2.1.2     
python-dateutil            2.7.5     
python-editor              1.0.3     
python-nvd3                0.14.2    
python-slugify             1.1.4     
pytz                       2018.7    
PyYAML                     3.13      
requests                   2.21.0    
s3transfer                 0.1.13    
scipy                      1.1.0     
scriptinep3                0.3.1     
SecretStorage              3.1.0     
setproctitle               1.1.10    
setuptools                 40.6.2    
six                        1.12.0    
smmap2                     2.0.5     
snowflake-connector-python 1.7.2     
snowflake-sqlalchemy       1.1.4     
SQLAlchemy                 1.2.14    
tabulate                   0.7.7     
thrift                     0.11.0    
tornado                    5.1.1     
Unidecode                  1.0.23    
urllib3                    1.24.1    
vine                       1.1.4     
webencodings               0.5.1     
Werkzeug                   0.14.1    
wheel                      0.32.3    
wrapt                      1.10.11   
WTForms                    2.2.1     
zope.deprecation           4.4.0  

4. The error is triggerd on ```import snowflake.connector```  as part of the following airflow operator. 

```import snowflake.connector
from airflow.hooks.dbapi_hook import DbApiHook
from airflow.models import BaseOperator
from airflow.plugins_manager import AirflowPlugin
from airflow.utils.decorators import apply_defaults

# This code is taken from the main airflow repository v 1.10.
# So it should be faily easy to remove this after upgrading airflow
from dags.helpers.string_mask import LogMasker


class SnowflakeHook(DbApiHook):
    """
    Interact with Snowflake.
    get_sqlalchemy_engine() depends on snowflake-sqlalchemy
    """

    conn_name_attr = 'snowflake_conn_id'
    default_conn_name = 'snowflake_default'
    supports_autocommit = True

    def __init__(self, connection_id='snowflake_default', *args, **kwargs):
        super(SnowflakeHook, self).__init__(*args, **kwargs)
        self.account = kwargs.pop("account", None)
        self.warehouse = kwargs.pop("warehouse", None)
        self.database = kwargs.pop("database", None)
        self.role = kwargs.pop("role", None)
        self.snowflake_conn_id = connection_id

    def _get_conn_params(self):
        """
        one method to fetch connection params as a dict
        used in get_uri() and get_connection()
        """
        conn = self.get_connection(self.snowflake_conn_id)
        account = conn.extra_dejson.get('account', None)
        warehouse = conn.extra_dejson.get('warehouse', None)
        database = conn.extra_dejson.get('database', None)
        role = conn.extra_dejson.get('role', None)

        conn_config = {
            "user": conn.login,
            "password": conn.password or '',
            "schema": conn.schema or '',
            "database": self.database or database or '',
            "account": self.account or account or '',
            "warehouse": self.warehouse or warehouse or '',
            "role": self.role or role or ''
        }
        return conn_config

    def get_uri(self):
        """
        override DbApiHook get_uri method for get_sqlalchemy_engine()
        """
        conn_config = self._get_conn_params()
        uri = 'snowflake://{user}:{password}@{account}/{database}/{schema}?warehouse={warehouse}'
        return uri.format(**conn_config)

    def get_conn(self):
        """
        Returns a snowflake.connection object
        """
        conn_config = self._get_conn_params()
        conn = snowflake.connector.connect(**conn_config)
        return conn

    def set_autocommit(self, conn, autocommit):
        conn.autocommit(autocommit)


class SnowflakeOperator(BaseOperator):
    """
    Executes sql code in a Snowflake database
    :param snowflake_conn_id: reference to specific snowflake connection id
    :type snowflake_conn_id: str
    :param sql: the sql code to be executed. (templated)
    :type sql: Can receive a str representing a sql statement,
        a list of str (sql statements), or reference to a template file.
        Template reference are recognized by str ending in '.sql'
    :param warehouse: name of warehouse which overwrite defined
        one in connection
    :type warehouse: str
    :param database: name of database which overwrite defined one in connection
    :type database: str
    """

    template_fields = ('sql',)
    template_ext = ('.sql',)
    ui_color = '#ededed'

    @apply_defaults
    def __init__(
            self, sql, snowflake_conn_id, parameters=None,
            autocommit=True, warehouse=None, database=None, *args, **kwargs):
        super(SnowflakeOperator, self).__init__(*args, **kwargs)
        self.snowflake_conn_id = snowflake_conn_id
        self.sql = sql
        self.autocommit = autocommit
        self.parameters = parameters
        self.warehouse = warehouse
        self.database = database

    def get_hook(self):
        return SnowflakeHook(connection_id=self.snowflake_conn_id,
                             warehouse=self.warehouse, database=self.database)

    def execute(self, context):
        masked_query = LogMasker().mask(self.sql, [("aws_key_id='", "',"), ("aws_secret_key='", "'")])
        self.log.info('Executing: %s', masked_query)
        self.log.info(self.parameters)
        hook = self.get_hook()
        hook.run(
            self.sql,
            autocommit=self.autocommit,
            parameters=self.parameters)


class TappSnowflakePlugin(AirflowPlugin):
    name = 'tapp_snowflake_plugin'

    operators = [SnowflakeOperator]

    # A list of class(es) derived from BaseHook
    hooks = [SnowflakeHook]

    # A list of class(es) derived from BaseExecutor
    executors = []
    # A list of references to inject into the macros namespace
    macros = []
    # A list of objects created from a class derived
    # from flask_admin.BaseView
    admin_views = []
    # A list of Blueprint object created from flask.Blueprint
    flask_blueprints = []
    # A list of menu links (flask_admin.base.MenuLink)
    menu_links = []
```
5. I expected to be able to run the SnowflakeOperator to execute Snowflake query's.
6. The following error ```No module named 'azure.common'; 'azure' is not a package```
7. Traceback for the error.
```worker_1            | [2018-12-24 10:47:51,202] {{plugins_manager.py:91}} ERROR - No module named 'azure.common'; 'azure' is not a package
worker_1            | Traceback (most recent call last):
worker_1            |   File "/usr/local/lib/python3.6/site-packages/airflow/plugins_manager.py", line 80, in <module>
worker_1            |     m = imp.load_source(namespace, filepath)
worker_1            |   File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
worker_1            |     module = _load(spec)
worker_1            |   File "<frozen importlib._bootstrap>", line 684, in _load
worker_1            |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
worker_1            |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
worker_1            |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
worker_1            |   File "/usr/local/airflow/plugins/fast_mysql.py", line 12, in <module>
worker_1            |     from dags.helpers import database_helper
worker_1            |   File "/usr/local/airflow/dags/helpers/database_helper.py", line 6, in <module>
worker_1            |     from plugins.tapp_snowflake import SnowflakeHook
worker_1            |   File "/usr/local/airflow/plugins/tapp_snowflake.py", line 1, in <module>
worker_1            |     import snowflake.connector
worker_1            |   File "/usr/local/lib/python3.6/site-packages/snowflake/connector/__init__.py", line 21, in <module>
worker_1            |     from .connection import SnowflakeConnection
worker_1            |   File "/usr/local/lib/python3.6/site-packages/snowflake/connector/connection.py", line 36, in <module>
worker_1            |     from .cursor import SnowflakeCursor
worker_1            |   File "/usr/local/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 31, in <module>
worker_1            |     from .file_transfer_agent import (SnowflakeFileTransferAgent)
worker_1            |   File "/usr/local/lib/python3.6/site-packages/snowflake/connector/file_transfer_agent.py", line 20, in <module>
worker_1            |     from .azure_util import SnowflakeAzureUtil
worker_1            |   File "/usr/local/lib/python3.6/site-packages/snowflake/connector/azure_util.py", line 8, in <module>
worker_1            |     from azure.common import (AzureMissingResourceHttpError, AzureHttpError)
```

Hope this helps. Let me know if you need more information.

**Comment by smtakeda** [comment]
Looks like Azure packages in the environment is out of date:
```
azure-common 1.1.16
azure-nspkg 2.0.0
azure-storage 0.36.0
```
which were the requirements for 1.7.2 or older versions.

The latest Python Connector pulls in the following packages:
```
>pip list | grep azure
azure-common               1.1.16    
azure-storage-blob         1.4.0     
azure-storage-common       1.4.0     
```

See the dependency requirements in the setup.py
https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py#L36

Do you use `requirements.txt` or something when running `pip install`? If so since the dependency was changed, `requirements.txt` require to update.

**Comment by bouke-nederstigt** [comment]
Mm, sorry for misunderstanding, but shouldn't pip automatically install package dependencies? Or is this normal behaviour? My requirements.txt file just specifies the snowflake-connecter, and no Azure packages.

**Comment by smtakeda** [comment]
I'm not sure what happened but `pip` is supposed to handle the dependency management.

**Comment by wadejensen** [comment]
2.0.1 is still affected. 
The `snowflake-python-connector` should by default pull in all the dependencies it needs via pip without user intervention.
