### ISSUE TITLE
SNOW-744607: Making cancel query a public API

### ISSUE THREAD

**Issue by tiwilliam** [snowflakedb/snowflake-connector-python#1441]
## What is the current behavior?
Currently need a named mangled method to cancel a query:
```py
cursor.__cancel_query(query)
```

This is possible to work around using the semi-private connection method:
```py
connection._cancel_query(query, cursor._request_id)
```

## What is the desired behavior?
Public and supported method for cancelling a query:
```py
cursor.cancel_query(query)
```

## How would this improve `snowflake-connector-python`?
Ability to cancel queries cross module updates.

**Comment by sfc-gh-aling** [comment]
hi @tiwilliam , thanks for your feedback. May I ask why you need the cancel behavior, can you describe your scenario?

**Comment by tiwilliam** [comment]
I'm building a Snowflake SQL client where I want users to be able to cancel queries.

**Comment by popcornylu** [comment]
You can use another query to cancel a running query.
https://docs.snowflake.com/en/user-guide/querying-cancel-statements

Here is an example.
https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/connections.py#L394-L407
