### ISSUE TITLE
SNOW-745203: Getting error while run a python script that contains snowflake connector import on jenkins. 

### ISSUE THREAD

**Issue by Kompal98** [snowflakedb/snowflake-connector-python#1443]
I am trying to fetch some data from snowflake. The script is running absolutely fine while running on local but when I am trying to run it on Jenkins while creating a freestyle project , its giving the following error -
import snowflake.connector ModuleNotFoundError: No module named 'snowflake.connector'; 'snowflake' is not a package.

pip install snowflake-connector-python command is already included in the cmd of jenkins.

Looking for a solution on prioriy basis.

**Comment by sfc-gh-aling** [comment]
how your working directory looks like, do you have a `snowflake` dir where your execution script is put?

**Comment by Kompal98** [comment]
@sfc-gh-aling I could not follow this snowflake dir where your execution script is put
but when I try to list the installed dir using pip list , I can fine snowflake and snowflake-connector-python present there

**Comment by sfc-gh-aling** [comment]
do you mind sharing the project/dir structure that you placed in the jenkins?

**Comment by Kompal98** [comment]
@sfc-gh-aling yes sure -
import snowflake.connector
import pandas as pd

# Replace with your Snowflake account information
con = snowflake.connector.connect(
    user = 'rxxxxxxg',
    password = 'wxxxxx3',
    account = 'cr000090',
    warehouse = 'COMPUTE_WH'
)
print("connection established")
result_list = []
product = "Sales"
query= "select usage_date ,account_name,sum(usage_in_currency) from snowflake.organization_usage.usage_in_currency_daily where usage_date = current_date() - 1 group by usage_date, account_name"
cursor = con.cursor()
cursor.execute(query)
result = cursor.fetchall()
print(result)

**Comment by sfc-gh-yixie** [comment]
@Kompal98 This error shows package `snowflake` doesn't exist at all. Did you see any python connector installation error?

**Comment by sfc-gh-achandrasekaran** [comment]
@Kompal98 is this still happening?

**Comment by sfc-gh-achandrasekaran** [comment]
Please reopen if this issue is still happening
