### ISSUE TITLE
SNOW-748919: Replace runtime dependency on setuptools with modern libraries

### ISSUE THREAD

**Issue by ofek** [snowflakedb/snowflake-connector-python#1447]
The use of `pkg_resources` that gets installed alongside setuptools is heavily discouraged now that functionality exists in the standard library and because importing that has a deleterious penalty to both start-up time and RSS memory.

**Comment by ofek** [comment]
Thanks! Is there any chance that this might be released by Friday?

**Comment by sfc-gh-mkeller** [comment]
> Thanks! Is there any chance that this might be released by Friday?

If everything goes well :) https://github.com/snowflakedb/snowflake-connector-python/commit/be500a08735504971de59690d1c13eec9ec1f7d6

**Comment by ofek** [comment]
Nice! It looks like CI is passing now, would the release automatically happen today?

**Comment by sfc-gh-mkeller** [comment]
It's not a fully automated process. We did discover a bug yesterday (unrelated to your change) that needed some workaround-ing temporarily :)
Actually, you have expertise in the field, so if you were interested I'd appreciate you 2 cents on issue 1452
