### ISSUE TITLE
SNOW-749971: No module named 'snowflake.connector'; 'snowflake' is not a package troubleshooting

### ISSUE THREAD

**Issue by arbitrio** [snowflakedb/snowflake-connector-python#1451]
1. What version of Python are you using?

   Python 3.9.13

2. What operating system and processor architecture are you using?

macOS-10.16-x86_64-i386-64bit

3. What are the component versions in the environment (`pip freeze`)?

 Alabaster, anaconda...not sure what else is needed here as it's a huge output.

4. What did you do?

Trying to load a connection to snowflake for the first time on a new computer. Installed Anaconda and Jupyter notebooks. When I execute pip show snowflake-connector-python I see:

Name: snowflake-connector-python
Version: 3.0.0
Summary: Snowflake Connector for Python
Home-page: https://www.snowflake.com/
Author: Snowflake, Inc
Author-email: snowflake-python-libraries-dl@snowflake.com
License: Apache-2.0
Location: /Users/(username)/opt/anaconda3/lib/python3.9/site-packages
Requires: asn1crypto, certifi, cffi, charset-normalizer, cryptography, filelock, idna, oscrypto, pycryptodomex, pyjwt, pyOpenSSL, pytz, requests, setuptools, typing-extensions, urllib3
Required-by: 

But then when I run import snowflake.connector I see:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/5w/02tbw9q5435djfsp3qg64pmh0000gp/T/ipykernel_1627/2515988102.py in <module>
----> 1 import snowflake.connector

ModuleNotFoundError: No module named 'snowflake.connector'; 'snowflake' is not a package

5. What did you expect to see?

 A successful connection to snowflake that will then allow me to import my user credentials and start querying from the database.

Note that I'm a little rusty with these installs and connections, so would appreciate any guidance and direction for troubleshooting and connecting properly.

Thanks!

**Comment by sfc-gh-aalam** [comment]
try: `pip install snowflake-connector-python`

**Comment by arbitrio** [comment]
> try: `pip install snowflake-connector-python`

When I do I get a bunch of lines that all say "Requirement already satisfied" for snowflake-connector-python, pyjwt<3.0.0, pycryptodomex!=3.5.0, pytz, cryptography<41.0.0,>=3.1.0, etc. If you need the full log let me know. When I then type in import snowflake.connector I get the same issue again "No module named 'snowflake.connector'

**Comment by sfc-gh-aalam** [comment]
it is possible you are using different versions of python between ipython and command line. can you run `python -c 'import snowflake.connector'` in the same environment as you did the pip install

**Comment by arbitrio** [comment]
When I do that I get:

  File "/var/folders/5w/02tbw9q5435djfsp3qg64pmh0000gp/T/ipykernel_1627/959504746.py", line 1
    python -c 'import snowflake.connector'
              ^
SyntaxError: invalid syntax

**Comment by sfc-gh-aalam** [comment]
I think you are writing this in your ipython notebook file. Instead I want you to write the `python -c ..` command on your terminal (from where you ran the `pip install` statements).

**Comment by sfc-gh-aalam** [comment]
the python command is to verify that the snowflake connector package is installed correctly. Once you have verified that, you need to figure out how to change the python interpreter for your ipython notebook to be the same as the one you are running in your teminal. [This](https://stackoverflow.com/questions/58645807/change-interpreter-in-jupyter-notebook) might be useful.

In any case, this is not a connector problem so I am closing out this issue.

**Comment by arbitrio** [comment]
Copy that. When I run python -c 'import snowflake.connector' in terminal it doesn't display anything afterwards.

**Comment by arbitrio** [comment]
As a note, in Jupyter when I look at the Kernel, the only option is Python3 (ipykernel)

**Comment by arbitrio** [comment]
It seems to me, after playing around with some other sites, that the input that I needed to put is:
!pip install "snowflake-connector-python"

I'm not sure if the ! is what Python needed or if something else happened. But it seems to be working for now. I appreciate the help again and hope this provides some lost soul direction if need.

**Comment by sfc-gh-aalam** [comment]
`python -c 'import snowflake.connector'` should give you a blank output. This statement is basically runs a python interpreter and executed the import statement. If there was something wrong with the pip install, you should have seen some errors.

I am glad you found a solution that works for you :)
