### ISSUE TITLE
SNOW-751706: allow to tell if a given sql string is "read only"

### ISSUE THREAD

**Issue by ni-todo-spot** [snowflakedb/snowflake-connector-python#1460]
## What is the current behavior?

Given a SQL string which received as an argument - Can't tell if it's "read only" or not.

## What is the desired behavior?

Tell if a given sql is consists only of commands which do not affect the data, but read from it or not (SELECTs).
Statements like DROP, INSERT, UPDATE, DELETE, REMOVE or basically anything which may change / affect current data are things I'd like to avoid executing. 

## References, Other Background

AS part of the project I'm working on I'd like a way to allow end users of my project to execute sql statements over my snowflake server.  
End users can interact with my snowflake server via a webpage I made.

The risk of such idea is that users may try to execute statement like: "DROP TABLE ...".

I'm looking for a solution which does not involve in editing permissions for user.

Thanks!

**Comment by sfc-gh-yixie** [comment]
@ni-todo-spot can you try this API? You can tell whether it's an update by looking into the result. (Some SQLs raises an exception. That's means it's not updating)

`conn.cursor().describe("select * from test_table")`

**Comment by ni-todo-spot** [comment]
Thanks I'll try it :)

**Comment by sfc-gh-dszmolka** [comment]
this question seems to be answered, so marking the Issue as closed for now. if you require further assistance, please do comment.
