### ISSUE TITLE
SNOW-752580: Python process crashes when Invalid date is read

### ISSUE THREAD

**Issue by kazanskiy** [snowflakedb/snowflake-connector-python#1466]
Snowflake column is defined as TIMESTAMP_NTZ(9) and contains value “52729727-09-15T16:33:20Z” (The value is displayed as “Invalid date” in Snowflake UI, I can see it only in Data Preview in the new “Snowsight” UI but this is not important to me)

Python project uses snowflake-connector-python==3.0.0

The row is read successfully by fetchall()

I can print the row with print(row_tuple). In this example: the second value is the Invalid date and is printed as <NULL>:

`(None, <NULL>, datetime.date(2022, 9, 23))`

**THE PROBLEM**: My Python process **just terminates** on attempt to read this date value, **I can’t even handle this error**.

Any of these lines will cause the termination:

`for item in row_tuple:`

`row_tuple[1]`

Thoughts about the cause: Python MAXYEAR is 9999 so year 52729727 is obviously out of range. The library should either raise an exception or put None value. What is `<NULL>` by the way? I can't find it defined anywhere.

**Comment by sfc-gh-aalam** [comment]
@kazanskiy could you also share what python version you are using.

**Comment by sfc-gh-aalam** [comment]
I tried this to reproduce the error.

1. Create a table in snowflake and add value you have provided.
  - `create or replace table timestamp_test(tz TIMESTAMP_NTZ(9))`
  - `insert into timestamp_test values(to_timestamp('52729727-09-15T16:33:20Z'))`
2. `SELECT * FROM timestamp_test` from Snowsight UI.
  - I get Invalid date error 
3. `SELECT * FROM timestamp_test` from snowflake-connector-python==3.0.0 python version 3.10.9 on M1 mac
  - `raise Error.errorhandler_make_exception(
snowflake.connector.errors.InterfaceError: 252005: Failed to convert current row, cause: year 52729727 is out of range`

**Comment by sfc-gh-achandrasekaran** [comment]
@kazanskiy could you share a code snippet you are using so we can triage further?
