### ISSUE TITLE
SNOW-761274: Generated stage name for `write_pandas` is sensitive to the RNG seed

### ISSUE THREAD

**Issue by cpcloud** [snowflakedb/snowflake-connector-python#1478]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

```
❯ python --version --version
Python 3.10.10 (main, Feb  7 2023, 12:19:31) [GCC 12.2.0]
```

2. What operating system and processor architecture are you using?

```
❯ python -c 'import platform; print(platform.platform())'
Linux-6.2.3-xanmod1-x86_64-with-glibc2.35
```

3. What are the component versions in the environment (`pip freeze`)?

Not using pip, but here's the version of `snowflake-connector-python` we're using

```
❯ poetry show snowflake-connector-python
 name         : snowflake-connector-python
 version      : 3.0.1
 description  : Snowflake Connector for Python
```

4. What did you do?

I tried to use `write_pandas` as part of the ibis library in our Snowflake CI, which uses `pytest-randomly` to catch tests that unintentionally rely on execution order.

By default `pytest-randomly` resets the RNG seed for every test case to a fixed value.

This causes `snowflake-connector-python` to generate the same temporary stage name for calls to `write_pandas`.

5. What did you expect to see?

I expected that since the stage for uploading parquet files created from DataFrames is temporary that setting the random seed wouldn't cause the upload to fail.

6. Can you set logging to DEBUG and collect the logs?

No, this isn't worth the effort.

Perhaps instead of constructing a string using `random`, this library should use the `uuid` module to construct such a string.

**Comment by sfc-gh-sfan** [comment]
This seems to be a very niche use case that I'm not sure if we should fix. @sfc-gh-mkeller : Do you see any issue using a uuid?

**Comment by cpcloud** [comment]
The general use case is testing write_pandas.

This problem is easy to trigger by simply running tests that use pytest-randomly and write_pandas together.

Ideally this library is friendly to other ecosystem tools and not dependent on random number generator state.

**Comment by cpcloud** [comment]
We're no longer using `write_pandas` in ibis for various reasons, so this is no longer an issue for us.
