### ISSUE TITLE
SNOW-787442: Support pandas 2.0

### ISSUE THREAD

**Issue by poudrouxj** [snowflakedb/snowflake-connector-python#1506]
## What is the current behavior?
The connector pins pandas at < 1.6.0 [ref](https://github.com/snowflakedb/snowflake-connector-python/blob/main/setup.cfg#L95)

## What is the desired behavior?
Connector supports pandas = 2.x with pyarrow backend

## How would this improve `snowflake-connector-python`?
Improved performance of data pipelines involving fetching data from snowflake and doing pandas related transformations outside snowflake.

## References, Other Background
- [Pandas 2.0 release notes](https://github.com/pandas-dev/pandas/releases/tag/v2.0.0) 
- https://pandas.pydata.org/pandas-docs/version/2.0/whatsnew/v2.0.0.html#argument-dtype-backend-to-return-pyarrow-backed-or-numpy-backed-nullable-dtypes

**Comment by saulbein** [comment]
This additionally blocks sqlalchemy 2.0 support in `snowflake-sqlalchemy`, as the pandas version used here uses sqlalchemy features that were removed/changed in 2.0.

**Comment by j-bennet** [comment]
Latest versions of `dask` support pandas 2.0, this feature would be useful to `dask-snowflake`.
