### ISSUE TITLE
SNOW-799415: Wrong type definitions (newtype instead of alias)

### ISSUE THREAD

**Issue by StefanUlbrich** [snowflakedb/snowflake-connector-python#1525]
I think there is a bug in the typing definitions in snowpark [here](https://github.com/snowflakedb/snowpark-python/blob/main/src/snowflake/snowpark/_internal/type_utils.py#L625-L635)

The issue is the usage of `NewType` that seems conceptually wrong. `NewTypes` are treated as types derived from the argument, (e.g., in `age=Newtype('age', int)`, `age` is treated as a subclass of `int` and a function that accepts `age` will consequently not accept `int`). In other words `Newtype` adds semantic to a type while here, while you want a type alias to make type annotations readable. For more information please consider having a look at this blog which explains it very well [link](https://justincaustin.com/blog/python-typing-newtype/)
Also a minimal example that fails to be checked with `mypy`:
 
```python
from snowflake.snowpark import Column
from snowflake.snowpark._internal.type_utils import ColumnOrLiteral
 
 
def some_function(col1: Column, col2: Column) -> Column:
   return col1 == col2
 
 
def some_function2(col2: Column) -> Column:
   return some_function3(7, col2)
 
 
def some_function3(col1: ColumnOrLiteral, col2: Column) -> Column:
   return col1 == col2
```

**Comment by sfc-gh-aalam** [comment]
Will soon review the PR.

**Comment by sfc-gh-mkeller** [comment]
Issue moved to https://github.com/snowflakedb/snowpark-python/issues/810
