### ISSUE TITLE
SNOW-810810: AttributeError when using SOCKS5 Proxy

### ISSUE THREAD

**Issue by stan-janssen** [snowflakedb/snowflake-connector-python#1550]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

```
Python 3.9.16 (main, May  8 2023, 20:48:22) 
[GCC 11.3.0]
```

2. What operating system and processor architecture are you using?

```
Linux-5.19.0-41-generic-x86_64-with-glibc2.35
```

3. What are the component versions in the environment (`pip freeze`)?

   Replace with the output of `python -m pip freeze`

4. What did you do?

Attempt to connect to Snowflake through a SOCKS5 proxy:

Use a minimal SOCKS5 proxy. From a second computer (`computer2`), open a SOCKS5 proxy on `computer1`

```
user@computer2:~$ ssh -R 1080 user@computer1.local
```

On `computer1`:

```
HTTPS_PROXY="socks5://localhost:1080" python3 -c "import snowflake.connector; snowflake.connector.connect(...)"
```

5. What did you expect to see?

The above test results in:

```
  File "/home/stan/Ontwikkeling/snowflake-connector-python/src/snowflake/connector/network.py", line 1042, in _request_exec
    raw_ret = session.request(
  File "/home/stan/Ontwikkeling/snowflake-connector-python/src/snowflake/connector/vendored/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/stan/Ontwikkeling/snowflake-connector-python/src/snowflake/connector/vendored/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/stan/Ontwikkeling/snowflake-connector-python/src/snowflake/connector/vendored/requests/adapters.py", line 455, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/stan/Ontwikkeling/snowflake-connector-python/src/snowflake/connector/network.py", line 274, in get_connection
    proxy_manager.proxy_headers["Host"] = parsed_url.hostname
AttributeError: 'SOCKSProxyManager' object has no attribute 'proxy_headers'
```

This is because the [SOCKSProxyManager](https://github.com/snowflakedb/snowflake-connector-python/blob/97c25993eb3fb43e0df634fd41f98f9e9ebf20bd/src/snowflake/connector/vendored/urllib3/contrib/socks.py#L159) is a subclass of [PoolManager](https://github.com/snowflakedb/snowflake-connector-python/blob/97c25993eb3fb43e0df634fd41f98f9e9ebf20bd/src/snowflake/connector/vendored/urllib3/poolmanager.py#L140) Which does not have the property `proxy_headers`. It does have a property `headers`.

I modified the code to not set the header when using a SOCKS5 proxy, which seems to work. The connection succeeds over the SOCKS5 proxy. It also works if I set the `headers` property instead of the `proxy_headers` property.

I offer a pull request for the first solution (not setting the `proxy_headers` when using a SOCKS5 proxy), but I leave it up to someone more knowledgable to decide whether this is the desired solution to this.

**Comment by sfc-gh-aling** [comment]
thanks for the feedback and the pull request! we will take a look!

**Comment by vajeeAtt** [comment]
Hey everyone, I'm facing the same issue with the missing attribute. Is there any reason why this is not merged, I couldn't find any other resolution for this issue.

**Comment by sfc-gh-achandrasekaran** [comment]
We will review this PR next week. FYI @sfc-gh-aling

**Comment by vajeeAtt** [comment]
Thank you

**Comment by vajeeAtt** [comment]
> We will review this PR next week. FYI @sfc-gh-aling

Is there anything I can do to help to move this further

**Comment by vajeeAtt** [comment]
@sfc-gh-aling , any updates on this? thank you

**Comment by gpgn** [comment]
Running into this as well, would be great if this could be merged soon 👍

**Comment by gpgn** [comment]
As a temporary workaround using [PySocks](https://pypi.org/project/PySocks/) works:
```python
import socks
import socket

socks.set_default_proxy(**{
    "proxy_type": socks.SOCKS5,
    "addr": os.environ["PROXY_ADDR"],
    "username": os.environ["PROXY_USERNAME"],
    "password": os.environ["PROXY_PASSWORD"],
})
socket.socket = socks.socksocket

with snowflake.connector.connect(...) as con:
    cursor = con.cursor()
```

But this is no fix for other solutions that rely on the environment variables.

**Comment by vajeeAtt** [comment]
@sfc-gh-aling I would like to know if there are any changes needed to promote this issue, thanks.

**Comment by sfc-gh-aling** [comment]
We just merged the PR which shall fix the issue and it will be carried in our next release
