### ISSUE TITLE
SNOW-811503: Cannot perform CREATE TEMPSTAGE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.

### ISSUE THREAD

**Issue by KarthikRajashekaran** [snowflakedb/snowflake-connector-python#1553]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Python 3.9.6 (default, Mar 10 2023, 20:16:38)
[Clang 14.0.3 (clang-1403.0.22.14.1)]

2. What operating system and processor architecture are you using?

macOS-13.3.1-x86_64-i386-64bit

3. What are the component versions in the environment (`pip freeze`)?

dbt-snowflake==1.5.0
snowflake-connector-python==3.0.3
snowflake-sqlalchemy==1.4.7

4. What did you do?
I wrote a customOperator in Airflow with template as below
```
        source_hook = SnowflakeHook(snowflake_conn_id=self.source_conn_id)
        dest_hook = SnowflakeHook(snowflake_conn_id=self.dest_conn_id)

        # Execute the SQL to fetch data from source Snowflake account
        df = pd.read_sql(self.sql, source_hook.get_conn())
        
        # Set the schema for the destination connection
        dest_hook.run(f"USE SCHEMA ABC")

        # Load data into destination Snowflake account using Pandas
        write_pandas(conn=dest_hook.get_conn(), df=df, table_name=self.dest_table,
                     database='dev',schema='abc')
```

5. What did you expect to see?

Should execute and written into the table but  got an error as 
```
Cannot perform CREATE TEMPSTAGE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name
```

**Comment by sfc-gh-yixie** [comment]
Can you try with `use schema dev.abc`?
Or`use database dev` then `use schema abc`.

**Comment by sfc-gh-achandrasekaran** [comment]
@KarthikRajashekaran let us know if this ^ solves the issue

**Comment by RameshGangineni** [comment]
@KarthikRajashekaran, I had a similar error, later when I debug further realized, user doesn't have access to the schema.
`Schema 'ABC' does not exist or not authorized`. Check if that's the case with you well. Thanks.
