### ISSUE TITLE
SNOW-818558: Support configuring file paths for private key authentication

### ISSUE THREAD

**Issue by sfc-gh-hachouraria** [snowflakedb/snowflake-connector-python#1565]
## What is the current behavior?

Python Connector requires manually reading and decrypting a private key file (and optional passphrase), documented at https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-example#using-key-pair-authentication-key-pair-rotation

Passing file paths and passphrases directly into the config is not currently supported

The .NET driver supports such an option (via `PRIVATE_KEY_FILE` and `PRIVATE_KEY_PWD`): https://github.com/snowflakedb/snowflake-connector-net#create-a-connection

The ODBC driver also supports such options (via `PRIV_KEY_FILE` and `PRIV_KEY_FILE_PWD`): https://docs.snowflake.com/en/developer-guide/odbc/odbc-parameters#using-key-pair-authentication

## What is the desired behavior?

Support convenience options (e.g. `private_key_file` and `private_key_file_passphrase`) that perform reading and decrypting private key files automatically, and reduces the work required to use key-pair authentication with the connector.

## How would this improve `snowflake-connector-python`?

These options would simplify configuring private key authentication in higher level applications such as SQLAlchemy, and Django backend for Snowflake (related issues: https://github.com/Snowflake-Labs/django-snowflake/issues/67 and https://github.com/Snowflake-Labs/django-snowflake/issues/72)

**Comment by sfc-gh-spanaite** [comment]
@sfc-gh-anugupta Can you please review this feature request?
