### ISSUE TITLE
SNOW-822511: Support for `pyarrow>=10.0.0`

### ISSUE THREAD

**Issue by csubhodeep** [snowflakedb/snowflake-connector-python#1566]
## What is the current behavior?
Currently this connector is very strict about the `pyarrow` dependency and needs it to be `(>=10.0.1,<10.1.0)`

## What is the desired behavior?
Relax `pyarrow` version so that other packages in the same project that use newer versions can also be resolved together with this connector.

## How would this improve `snowflake-connector-python`?
Relates to #1506 
Be able to install this connector together with other packages which use latter versions of `pyarrow`

## References, Other Background
1. https://github.com/apache/arrow/pull/34878

**Comment by sfc-gh-aling** [comment]
thanks for the feedback, we're currently working on a project which help avoid pinning version of pyarrow

**Comment by sfc-gh-anugupta** [comment]
Hi All ,

We have released a new preview version of connector with reduced sized with nanoarrow and removing the restriction of pyarrow dependency  which you can check at this blog post https://medium.com/snowflake/supercharging-the-snowflake-python-connector-with-nanoarrow-8388cb57eeba

Do let us know your feedback. Do note this is still in preview, so we dont recommend it used for production.

Thanks
Anurag

**Comment by der-eismann** [comment]
Is there some kind of roadmap or intermediate solution? Right now it's impossible to install `snowflake-connector-python[pandas]` in Airflow using their [constraints file](https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.10.txt), since it pins `pyarrow==11.0.0`

**Comment by sfc-gh-aling** [comment]
hey @der-eismann , can you try installing the alpha release of snowflake-connector-python via 
`pip install "snowflake-connector-python[pandas]==3.1.0a2"`?

**Comment by kstine** [comment]
I have tested out "snowflake-connector-python[pandas]==3.1.0a2" with Alpine and it does allow install without errors- but if pyarrow is installed with Alpine's py3-pyarrow package (not via pip) an error is triggered for a file "arrow_iterator" not being found.

**Comment by MartinNowak** [comment]
Any update on this, 3.2 still seems to be pinned to 10.0.

**Comment by meastham** [comment]
We're also being impacted by this, it would be great if there were a way to use a newer version of pyarrow with the `pandas` extra.

**Comment by nicornk** [comment]
When are you releasing the final version without pyarrow pin?

**Comment by sfc-gh-anugupta** [comment]
We are happy to update   the  snowflake-connector-python v3.3.0 is successfully been released which by default uses apache-nanoarrow project as the result arrow data converter, and it is fully backward compatible. Nanoarrow integration will help reduces the size of the connector down to 5MB and remove the hard dependency on PyArrow .
More details at  https://pypi.org/project/snowflake-connector-python/3.3.0/ and https://medium.com/snowflake/supercharging-the-snowflake-python-connector-with-nanoarrow-8388cb57eeba

Please note as this a significant design refactoring of the python connector,  v3.3.0 will still  pins the dependency of pyarrow to v10 as it bundles the old arrow converter, allowing users to switch back to the old arrow data converter in case of an unexpected issue.
 If everything moves well as planned, we will do another release by the end of this month, shifting to pure nanoarrow-based python connector, which reduces the package size significantly and unpins the dependency of pyarrow.

**Comment by nicornk** [comment]
Thanks for the update - looking forward to the removal of pyarrow v10 as dependency. This will significantly reduce workarounds on our side.

**Comment by sfc-gh-aling** [comment]
Hi all, we're thrilled to announce that snowflake-connector-python 3.5.0 is released which removes the restriction of pyarrow dependency as well as reduces the package size: https://pypi.org/project/snowflake-connector-python/3.5.0/

please give it a try!
