### ISSUE TITLE
SNOW-826443: tested_requirements files reference an unreleased version

### ISSUE THREAD

**Issue by sfc-gh-pbennes** [snowflakedb/snowflake-connector-python#1581]
#1575 bumped snowflake-connector-python in tested_requirements to 3.0.4, apparently prior to its release. `pip install` referencing these files fails because 3.0.4 hasn't been published yet. There is no 3.0.4 on https://pypi.org/project/snowflake-connector-python/.

Might be worth separating those steps to publish then bump as well as add some tests that pip install on those requirements files works.

```sh
pip3.11 install -r 'https://raw.githubusercontent.com/snowflakedb/snowflake-connector-python/main/tested_requirements/requirements_311.reqs
...
ERROR: No matching distribution found for snowflake-connector-python==3.0.4
```

**Comment by sfc-gh-pbennes** [comment]
Ah that makes sense given the PyPi requirement. We pinned on tag 3.0.3 for the moment.

Enhancement is appropriate: I guess the ask is to have a kept-up-to-date tested_requirements we can point at to consume new releases as they come without having to manually pull in updates.

One possible approach would be to tag a new release separately from the main branch and merge it in to main once released, but I'm not sure how that would work mechanically, but like tag v3.0.4 outside main, wait for publish, merge to main?

**Comment by DustinMoriarty** [comment]
I am running into something seriously weird with this package with requirements. I see that 3.0.4 is now released in pypi. 

https://pypi.org/project/snowflake-connector-python/3.0.4/#history

However, it does not install with pip. 
```
% python -m pip install snowflake-connector-python==3.0.4
ERROR: Could not find a version that satisfies the requirement snowflake-connector-python==3.0.4 (from versions: 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.6.12, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.9.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9, 2.7.10, 2.7.11, 2.7.12, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.9.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3)
ERROR: No matching distribution found for snowflake-connector-python==3.0.4
```
I tried using python 3.9 and 3.10. If I use poetry, it flat out refuses to install any version of this repository. 
```
% poetry add  snowflake-connector-python 
Using version ^3.0.4 for snowflake-connector-python

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing snowflake-connector-python (3.0.4): Failed

  RuntimeError

  Unable to find installation candidates for snowflake-connector-python (3.0.4)

  at /opt/homebrew/Cellar/poetry/1.4.2/libexec/lib/python3.11/site-packages/poetry/installation/chooser.py:109 in choose_for
      105│ 
      106│             links.append(link)
      107│ 
      108│         if not links:
    → 109│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      110│ 
      111│         # Get the best link
      112│         chosen = max(links, key=lambda link: self._sort_key(package, link))
```

Even when I try to peg earlier versions and I have no other dependencies installed, I still cannot get this package to install at all with poetry. What is going on this the metadata for this package to make all the package managers so completely break? I have applications with pegged requirements from 4 months ago which won't even build now.

**Comment by sfc-gh-achandrasekaran** [comment]
@DustinMoriarty not all wheels have been published because we ran into a space issue on PyPi. We have filed a ticket to increase it and will publish the rest of the wheels when it is done.

**Comment by ironScripter** [comment]
Any update on this? I am still having this issue?

**Comment by mjclarke94** [comment]
I'm also still getting this issue with a `poetry add`. Pinning to `3.0.3` resolves it, so unlikely to be due to conflicts in my project.

**Comment by sfc-gh-dszmolka** [comment]
marking this one as closed as it seems to be long resolved now; but if you have similar issues with any recent versions, please do comment and we can reopen and look further.
