### ISSUE TITLE
SNOW-830320: fetch_pandas_all returns duplicated indexes

### ISSUE THREAD

**Issue by andrugiache** [snowflakedb/snowflake-connector-python#1589]
1. What version of Python are you using?

Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]

2. What operating system and processor architecture are you using?

Windows-10-10.0.22621-SP0

3. What are the component versions in the environment (`pip freeze`)?

appdirs==1.4.4
asn1crypto==1.5.1
attrs==22.2.0
black==22.3.0
boto3==1.20.41
botocore==1.23.54
cachetools==5.2.0
certifi==2022.9.24
cffi==1.15.1
cfgv==3.3.1
chardet==5.1.0
charset-normalizer==2.0.12
click==8.0.4
colorama==0.4.5
cryptography==36.0.2
diff-cover==7.4.0
distlib==0.3.6
et-xmlfile==1.1.0
exceptiongroup==1.1.0
filelock==3.9.0
Flask==2.0.3
fsspec==2022.10.0
google-api-core==2.10.2
google-api-python-client==2.36.0
google-auth==2.13.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.6
googleapis-common-protos==1.56.4
httplib2==0.20.4
identify==2.5.15
idna==3.4
iniconfig==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==0.10.0
MarkupSafe==2.1.1
mypy-extensions==0.4.3
nodeenv==1.7.0
numpy==1.21.5
oauth2client==4.1.3
oauthlib==3.2.2
openpyxl==3.0.9
oscrypto==1.3.0
packaging==23.0
pandas==1.3.5
pathspec==0.10.1
platformdirs==2.5.2
pluggy==1.0.0
pre-commit==2.20.0
protobuf==4.21.8
pyarrow==6.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodomex==3.15.0
Pygments==2.14.0
PyJWT==2.6.0
pyOpenSSL==21.0.0
pyparsing==3.0.9
pytest==7.2.1
python-dateutil==2.8.2
pytz==2021.3
PyYAML==6.0
regex==2022.10.31
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.9
s3fs==0.4.2
s3transfer==0.5.2
six==1.16.0
snowflake-connector-python==2.7.3
sqlfluff==1.4.2
tblib==1.7.0
toml==0.10.2
tomli==1.2.3
tqdm==4.64.1
typing_extensions==4.4.0
uritemplate==4.1.1
urllib3==1.26.12
virtualenv==20.17.1
Werkzeug==2.2.2
xlrd==2.0.1

4. What did you do?
The dataframe returned by the fetch_pandas_all contains duplicated indexes. The function _fetch_pandas_batches called in _fetch_pandas_all (result_set.py) is returning 2 dataframes and it is not reseting the indexes after concatening the dataframes, so the function fetch_pandas_all is returning duplicated indexes in the df. The query executed is a simple select.
![image](https://github.com/snowflakedb/snowflake-connector-python/assets/77515771/78951682-7518-4e85-a178-696b916a210d)

5. What did you expect to see?
I expect that the DF returned by the function fetch_pandas_all contains unique indexes

**Comment by sfc-gh-spanaite** [comment]
@andrugiache You are using an old version of the Python connector and this issue has been fixed starting with v2.7.5, see here: https://github.com/snowflakedb/snowflake-connector-python/pull/1068
Can you upgrade your connector to latest version and let us know if you still have the issue?

**Comment by sfc-gh-achandrasekaran** [comment]
@andrugiache could you check and let us know please?

**Comment by andrugiache-ourplace** [comment]
Sorry @sfc-gh-achandrasekaran, yes, I have updgraded the version to 2.7.5 and it is working fine. Thank you!

**Comment by andrugiache** [comment]
Sorry for the late response @sfc-gh-achandrasekaran, yes I have upgraded to the version 2.7.5 and it is working fine. Thank you!

**Comment by sfc-gh-spanaite** [comment]
Thanks for confirming @andrugiache. Taking this into account I am closing this issue as resolved.
