### ISSUE TITLE
SNOW-831506: Bump cryptography max major version dependency

### ISSUE THREAD

**Issue by benhiller** [snowflakedb/snowflake-connector-python#1592]
## What is the current behavior?

Right now setup.cfg prevents using cryptography v41: https://github.com/snowflakedb/snowflake-connector-python/blob/main/setup.cfg#L48, which was released by the cryptography project recently: https://cryptography.io/en/latest/changelog/#v41-0-0 

## What is the desired behavior?

Change the max version to <42.0.0 and allow using cryptography v41 as a dependency. It looks like dependabot already created a PR for this, merging https://github.com/snowflakedb/snowflake-connector-python/pull/1590 would make the desired change.

## How would this improve `snowflake-connector-python`?

We already depend on cryptography 41.0.1, so this would let us add `snowflake-connector-python` as a dependency without having to downgrade that dependency.

**Comment by tomwojcik** [comment]
Worth mentioning that there's a vuln fixed in 41.0 https://github.com/advisories/GHSA-5cpq-8wj7-hf2v

**Comment by xesf** [comment]
In our case our Package Auditing Vulnerability checks are failing because of it. Would be great to merge changes from #1590 

![image](https://github.com/snowflakedb/snowflake-connector-python/assets/751076/2f48b46b-71d7-4c39-b46e-d0c8053a8490)

**Comment by hauntsaninja** [comment]
See also https://github.com/snowflakedb/snowflake-connector-python/issues/1284

cc @sfc-gh-aling @sfc-gh-mkeller

**Comment by nffdiogosilva** [comment]
I'm also being affected by this. Would much appreciate it to be fixed ASAP.

**Comment by sfc-gh-stan** [comment]
Hi all, we are merging https://github.com/snowflakedb/snowflake-connector-python/pull/1590.

**Comment by sfc-gh-spanaite** [comment]
Closing this issue as the next release which will be in the second week of July will include this change via [PR 1590](https://github.com/snowflakedb/snowflake-connector-python/pull/1590)

**Comment by cforcey** [comment]
Many thanks for expediting this and for the heads up on the release schedule.  That is a big help in planning and communicating with our security team.

**Comment by quinot** [comment]
Hello @sfc-gh-spanaite, can you provide an update regarding the release plan? Thanks!

**Comment by sfc-gh-spanaite** [comment]
Hi @quinot the release goes out usually the last week of the month if nothing major comes up in between.

**Comment by hauntsaninja** [comment]
Any thoughts on how to avoid this in the future? See https://github.com/snowflakedb/snowflake-connector-python/issues/1284, https://github.com/snowflakedb/snowflake-connector-python/issues/1259, https://github.com/snowflakedb/snowflake-connector-python/issues/1118, etc. Are you sure putting your releases on the critical path for security upgrades is in the best interest of your users?

**Comment by hauntsaninja** [comment]
@sfc-gh-spanaite any thoughts? also cc @sfc-gh-aling @sfc-gh-mkeller since we discussed this in #1284

**Comment by quinot** [comment]
@sfc-gh-spanaite @sfc-gh-achandrasekaran You previously announced [2nd week of July](https://github.com/snowflakedb/snowflake-connector-python/issues/1592#issuecomment-1594556084), then [last week of July](https://github.com/snowflakedb/snowflake-connector-python/issues/1592#issuecomment-1637583859), for a release including this fix. Can you share some visibility on plans? Thanks!

**Comment by lukehsiao** [comment]
@quinot the latest they've said is Monday: https://github.com/snowflakedb/snowflake-connector-python/pull/1590#issuecomment-1592114986
