### ISSUE TITLE
SNOW-832868: Old versions were removed from PyPi

### ISSUE THREAD

**Issue by donchkat** [snowflakedb/snowflake-connector-python#1593]
Hi, I noticed that the oldest versions until 1.4.4 including were removed from PyPi. 
Is there a reason for removing them? Because I saw the release notes from a week ago that fixes and changes were made in those versions as well so they are not withdrawn or at their end of life. 
<img width="1168" alt="image" src="https://github.com/snowflakedb/snowflake-connector-python/assets/74149435/fc8b0e2e-36ee-4717-a998-64fda075d096">

I notices this because I maintain a DB with PyPi data and the available versions for it's packages. 
<img width="661" alt="image" src="https://github.com/snowflakedb/snowflake-connector-python/assets/74149435/c19c2eeb-0f38-4d72-b801-5d8da0ccef38">

Would appreciate if you could explain why they were removed.

**Comment by sfc-gh-aling** [comment]
@donchkat we removed the older versions because of hitting the space constraints of pypi that we can't release new wheels, apologize for the inconvenience.

we've made application to pypi for more space, so this should be less likely to happen in the future.

**Comment by sfc-gh-spanaite** [comment]
Closing since no action is needed anymore.
