### ISSUE TITLE
SNOW-843716: Cryptography library cleanup

### ISSUE THREAD

**Issue by geofft** [snowflakedb/snowflake-connector-python#1605]
### What is the current behavior?

Hi! It looks like the connector depends on five cryptography-related packages, `asn1crypto`, `cryptography`, `oscrypto`, `pyOpenSSL`, and `pycryptodome`.

Would there be interest in consolidating these as far as possible? I think most of this can be consolidated onto just the cryptography library. I'd be happy to contribute a pull request, just wanted to check with you all first. The one I'm least sure about is `asn1crypto`, but it looks like that one's being used for OCSP support, which `cryptography` has high-level functions for. From a quick look, everything else seems like stuff I'm pretty sure `cryptography` can handle.

### What is the desired behavior?

Ideally, the connector should depend on a single, well-maintained cryptography library.

### How would this improve `snowflake-connector-python`?

This would reduce maintenance overhead and security risk.

**Comment by waltervos** [comment]
If you can get rid of urllib3.contrib.pyopenssl this way, that should also solve #1586

**Comment by kpark-hrp** [comment]
Getting rid of `oscrypto` with #1616 will be super nice because `from oscrypto import asymmetric` attempts to import OpenSSL shared libraries which breaks simple Python containers without OpenSSL/LibreSSL.

Wondering if #1616 can be expedited as it will resolve our pain point? @sfc-gh-spanaite

**Comment by DustinMoriarty** [comment]
oscrypto has had this bug since August. 

https://github.com/wbond/oscrypto/pull/76

The fix was merged. However, the fix was never released to pypi. An issue was raised to request a release. However, there has been no response.

https://github.com/wbond/oscrypto/issues/78

The repo has had almost no commits since then. The repo does not appear to be well supported. It could be that oscrypto is a case of an open source library that just does not have enough maintainers to make it reliable.

**Comment by jfo8001** [comment]
Debian 12 Bookworm just busted for us too - very hard to work around this issue in the various libraries we use.  Would be great to remove dependency on oscrypto.

**Comment by sfc-gh-aling** [comment]
thanks for all the feedback, we're going to remove the dependency on oscrpyto and pycryptodomex in our next connector release and we will do a release for snowsql accordingly.

I have created an announcement issue: https://github.com/snowflakedb/snowflake-connector-python/issues/1781

**Comment by sfc-gh-aling** [comment]
we have released v3.4.0 removing oscrypto and pycryptodomex, thank you!
