### ISSUE TITLE
SNOW-844371: Add support for SECONDARY_ROLE in the Python SDK

### ISSUE THREAD

**Issue by poudrouxj** [snowflakedb/snowflake-connector-python#1607]
### What is the current behavior?

If a user can have access to multiple secondary roles (f.i. when working on different levels of PII-related data) any user of the snowflake-python-connector would need to run a primary query beforehand to select the secondary role:

```python

with snowflake.connector.connect(**connection_params) as con:
    cur = con.cursor()
    cur.execute('USE SECONDARY ROLE <ROLE>')
    cur.execute(<MY_QUERY>)
```

### What is the desired behavior?

Include a session parameter in the connection_params:

```python

connection_params['SECONDARY_ROLE']=<MY_SECONDARY_ROLE>

with snowflake.connector.connect(**connection_params) as con:
    cur = con.cursor()
    cur.execute(<MY_QUERY>)
```

### How would this improve `snowflake-connector-python`?

Simplify the snowflake api

### References and other background

It seems that SECONDARY_ROLE is a session oriented parameter, but I'm not seeing any support for it besides running a separate query:
https://docs.snowflake.com/en/user-guide/security-access-control-overview#enforcement-model-the-primary-role-and-secondary-roles

Feel free to give feedback if its intentional to include this or not.

**Comment by tempoxylophone** [comment]
This would be very helpful, especially for asynchronous queries in the [Cursor's](https://docs.snowflake.com/developer-guide/python-connector/python-connector-api#object-cursor) `execute_async` function. 

There doesn't seem to be an obvious way to do this. Best lead I found was to use `execute_string` from the [Connection](https://docs.snowflake.com/developer-guide/python-connector/python-connector-api#object-connection) object, from this community post [thead](https://community.snowflake.com/s/question/0D50Z000092erxOSAQ/how-do-you-run-multiple-query-statements-created-when-using-the-python-connector).

**Comment by tempoxylophone** [comment]
It looks like Cursor supports a `num_statements` parameter in both `execute` and `execute_async`. Main branch has this here, see line [726 in cursor.py](https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/cursor.py#L693C1-L694C1). According to the SQL API doc page [here](https://docs.snowflake.com/en/developer-guide/sql-api/intro), it seems like this is the only way to support secondary roles:

>The following commands and statements are supported only within a [request that specifies multiple statements]
> (https://docs.snowflake.com/en/developer-guide/sql-api/submitting-multiple-statements.html):
> 
> Commands that perform explicit transactions, including:
> 
> - [BEGIN](https://docs.snowflake.com/en/sql-reference/sql/begin.html)
> 
> - [COMMIT](https://docs.snowflake.com/en/sql-reference/sql/commit.html)
> 
> - [ROLLBACK](https://docs.snowflake.com/en/sql-reference/sql/rollback.html)
> 
> Commands that change the context of the session, including:
> 
> - [**USE** <object>](https://docs.snowflake.com/en/sql-reference/sql/use.html)
>

**Comment by sfc-gh-yqiu** [comment]
Hi, I looked into this and unfortunately, the backend only supports activating the primary role when establishing a connection. An exception is when activating an account, during which all secondary roles are activated with no finer control. If by chance enabling all secondary roles automatically is what you want, consider using `ALTER USER <user> SET DEFAULT_SECONDARY_ROLES = ( 'ALL' );`

It does sound like your best bet is, as @tempoxylophonementioned, executing `USE SECONDARY ROLE <role>` in either `execute_string` or `execute` with the `num_statements` parameter set.

**Comment by sfc-gh-yqiu** [comment]
Hi, I looked into this and unfortunately, the backend only supports activating the primary role when establishing a connection. An exception is when one is activating an account, during which all secondary roles are activated (with no finer control). If by chance enabling all secondary roles automatically is what you want, consider using `ALTER USER <user> SET DEFAULT_SECONDARY_ROLES = ( 'ALL' );`

Otherwise, it does sound like your best bet is, as @tempoxylophonementioned, executing `USE SECONDARY ROLE <role>` in either `execute_string` or `execute` with the `num_statements` parameter set.
