### ISSUE TITLE
database/schema in constructor

### ISSUE THREAD

**Issue by bt-wil** [snowflakedb/snowflake-connector-python#162]
When creating a `SnowflakeConnection`, the `database`/`schema` can be passed in as argument.  Should/does that obsolete the need to explicitly call `use database/schema ...`?

https://docs.snowflake.net/manuals/user-guide/python-connector-example.html#using-the-database-schema-and-warehouse

**Comment by smtakeda** [comment]
Thanks for suggestion. We still need use command for other use cases but definitely can improve the doc recommending to have them in the connection parameter.

**Comment by smtakeda** [comment]
Forwarded this to the doc writer.

**Comment by bt-wil** [comment]
Running the script with database/schema args passed in to the constructor gives an error:
```
snowflake.connector.errors.ProgrammingError: 002003 (42S02): SQL compilation error:
Object 'CUSTOMER' does not exist.
```

However, If I explicitly run the script which explicitly calls `use database/schema`, the queries returns with the result.  From your post, it seems like that is not the expected behavior.

I'm using `snowflake-connector-python==1.7.9`

```
import base64
from snowflake.connector import SnowflakeConnection, DictCursor


ACCOUNT = '...'
USER = '...'
PRIVATE_KEY = '...'
DATABASE = 'SNOWFLAKE_SAMPLE_DATA',
SCHEMA = 'TPCH_SF1',
WAREHOUSE = 'XS_WH'


def sf_conn():
    return SnowflakeConnection(
        user=USER,
        account=ACCOUNT,
        region='us-east-1',
        private_key=base64.b64decode(PRIVATE_KEY),
        warehouse=WAREHOUSE,
        database=DATABASE,
        schema=SCHEMA,
        timezone='UTC',
    )


def run_query():
    with sf_conn() as conn, conn.cursor(DictCursor) as curs:
        # curs.execute('use database identifier(%(db)s)', {'db': DATABASE})
        # curs.execute('use schema identifier(%(schema)s)', {'schema': SCHEMA})
        curs.execute('select count(*) from customer')
        print('result: {}'.format(curs.fetchall()))


if __name__ == '__main__':
    run_query()
```

**Comment by smtakeda** [comment]
what is the current role? Can the role use the table CUSTOMER?
role parameter can be added the connection.

**Comment by bt-wil** [comment]
The default role for the user is `ACCOUNTADMIN`.  I've tried adding the `role='ACCOUNTADMIN'` parameter in the constructor and got the same error message.  I'm assuming that if it was a role issue, explicitly running with `use database/schema` would not work as well.

**Comment by smtakeda** [comment]
can you run
```select current_role(), current_database(), current_schema(), current_warehouse();
```
right after the connection to ensure the db and schema are valid?

**Comment by bt-wil** [comment]
Here is the output of the `current_*` after connecting, and after explicit `use <db/schema>`:
```
after connecting: {
  "CURRENT_ROLE()":"ACCOUNTADMIN",
  "CURRENT_DATABASE()":null,
  "CURRENT_SCHEMA()":null,
  "CURRENT_WAREHOUSE()":"XS_WH"
}

after explicit use <db/schema>: {
  "CURRENT_ROLE()":"ACCOUNTADMIN",
  "CURRENT_DATABASE()":"SNOWFLAKE_SAMPLE_DATA",
  "CURRENT_SCHEMA()":"TPCH_SF1",
  "CURRENT_WAREHOUSE()":"XS_WH"
}
```

**Comment by smtakeda** [comment]
hmm, I cannot reproduce it:
```
import snowflake.connector
import os
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization

with open("rsa_key.p8", "rb") as key:
    p_key= serialization.load_pem_private_key(
        key.read(),
        password=os.environ['PRIVATE_KEY_PASSPHRASE'].encode(),
        backend=default_backend()
    )

pkb = p_key.private_bytes(
    encoding=serialization.Encoding.DER,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption())

ctx = snowflake.connector.connect(
    user='admin',
    account='testaccount5',
    # role='accountadmin',
    database='SNOWFLAKE_SAMPLE_DATA',
    schema='TPCH_SF1',
    private_key=pkb)

for rec in ctx.cursor().execute("select current_role(), current_database(), current_schema(), current_warehouse()"):
    print(rec)
ctx.close()
```
```
> python keypair.py
('ACCOUNTADMIN', 'SNOWFLAKE_SAMPLE_DATA', 'TPCH_SF1', 'DONTDROP')
```
If I remove `database` and `schema` parameter, the default ones are returned:
```
>python keypair.py
('ACCOUNTADMIN', 'STAKEDA_DB', None, 'DONTDROP')
```
In either case, this doesn't look like a Python connector issue. For further investigation, please reach out to the support.

**Comment by bt-wil** [comment]
Turns out to be user error.
```
DATABASE = 'SNOWFLAKE_SAMPLE_DATA',
SCHEMA = 'TPCH_SF1',
```
The `,` created a tuple.

**Comment by shaikshakeel** [comment]
Hi @bt-wil  What is the actual error?  did you solve this? I didn't get you.
