### ISSUE TITLE
SNOW-856910: Authenticate with key-pair and MFA

### ISSUE THREAD

**Issue by scottypate** [snowflakedb/snowflake-connector-python#1628]
### What is the current behavior?

Current behavior is that MFA with key-pair authentication is not possible. If a user has MFA enabled then authenticates with a key-pair, an MFA callback is not triggered. 

### What is the desired behavior?

A key-pair authentication requires an MFA callback if the user has enrolled in MFA. 

### How would this improve `snowflake-connector-python`?

We currently use the python connector with DBT to auth all of our dev and prod workloads. Production workloads with DBT use a service account that is secured with a network policy only allowing ingress from particular IPs. Our development workloads currently use the `externalbrowser` authenticator to open a browser screen and initiate SSO through Okta. We would like to move our development workloads to a docker container, and we can't trigger a browser authentication from inside the docker container. Key pair authentication works will for this workload, but our developers have levels of access that need to be protected by MFA in case a device is stolen or a private key is compromised. This change would enable MFA protections for our key pair authentications during development and testing.

### References and other background

Our team is more than happy to make the contributions to add this feature. We are looking for some input from the team on possible pitfalls or where we may fail.

**Comment by sfc-gh-mkeller** [comment]
As long as our back-end supports it you should be able to do this without any input from us. 😄 
We have made authentication pluggable for this reason specifically (introduced in #1215 ).

So you should be able to add the MFA callback to key-pair authentication yourself, see my personal demo where I use 1Password for key-pair auth:
```python
import shlex
import subprocess
import snowflake.connector

from cryptography.hazmat.primitives import serialization

from snowflake.connector.auth.keypair import AuthByKeyPair


class AuthBy1Password(AuthByKeyPair):
    def __init__(self, vault: str, name: str) -> None:
        private_key = subprocess.run(
            shlex.split(
                f'op item get {name} --vault {vault} --fields "private key"'
            ),
            capture_output=True,
        ).stdout.strip(b'"\n')
        loaded_pk = serialization.load_pem_private_key(private_key, None)
        super().__init__(
            loaded_pk.private_bytes(
                encoding=serialization.Encoding.DER,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.NoEncryption(),
            )
        )


if __name__ == "__main__":
    auth = AuthBy1Password(vault="Private", name="keypair_auth")
    with snowflake.connector.connect(
        account="sfctest0",
        user="test_sqlapi_python",
        auth_class=auth,
    ) as conn:
        with conn.cursor() as cur:
            print(cur.execute("select 'I\\'ve authenticated'").fetchone())
```

Hopefully my documentation in https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/auth/by_plugin.py will be helpful in explaining what each of the functions are intended to do.

This should help you at least prototype it for your own use and once it's working please do share it with us as a PR.

**Comment by scottypate** [comment]
Perfect! Just what I was looking for. Thank you @sfc-gh-mkeller.

**Comment by sfc-gh-aling** [comment]
I'm closing the issue now, let us know if more help is needed.
