### ISSUE TITLE
SNOW-862855: Newer version of snowflake-connector-python

### ISSUE THREAD

**Issue by mahashg** [snowflakedb/snowflake-connector-python#1640]
### What is the current behavior?

I was wondering when will newer version of snowflake-connector-python be released ? I'm looking for the version which has support for cryptography 41.0.0. I see a code has been committed but since no new version is out, its not used

### What is the desired behavior?

newer release

### How would this improve `snowflake-connector-python`?

None

**Comment by sfc-gh-achandrasekaran** [comment]
It will come out next week

**Comment by JulesLandrySimard** [comment]
@sfc-gh-achandrasekaran Any update on the release schedule?
