### ISSUE TITLE
Make LOG_MAX_QUERY_LENGTH configurable

### ISSUE THREAD

**Issue by coreyatc1** [snowflakedb/snowflake-connector-python#165]
It would be very helpful for debug and auditing purposes if LOG_MAX_QUERY_LENGTH were configurable at connect time.

1. What version of Python are you using (`python --version`)?
3.6

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Multiple

3. What are the component versions in the environment (`pip list`)?
Not relevant for a feature request.

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I enabled logging per instructions https://docs.snowflake.net/manuals/user-guide/python-connector-example.html#logging

5. What did you expect to see?
The full query text of the queries that were run.

6. What did you see instead?
The first 80 characters of the query, which is a pity because we had the whole query and chose to abbreviate it.

7. Can you set logging to DEBUG and collect the logs?
No, but I can see that the information is truncated at
https://github.com/snowflakedb/snowflake-connector-python/blob/5be6b8c6531aac7c2ca3858be784c5f5f714a0e4/cursor.py#L68

**Comment by smtakeda** [comment]
v1.7.11 has the option:
```
log_max_query_length=120
```

**Comment by coreyatc1** [comment]
is there a way to set the value to unlimited?

**Comment by smtakeda** [comment]
hmm, how about `log_max_query_length=sys.maxint`?

**Comment by coreyatc1** [comment]
that would be a large query.

**Comment by woropajj** [comment]
Noob question but where and how can I set this option?
