### ISSUE TITLE
SNOW-878938: OKTA authentication with EXTERNALBROWSER auth uses random ports making it hard to work with in VSCode DevContainers

### ISSUE THREAD

**Issue by jfo8001** [snowflakedb/snowflake-connector-python#1670]
### Python version

Python 3.9.2 (default, Feb 28 2021, 17:03:44) 

### Operating system and processor architecture

Linux-5.15.49-linuxkit-pr-aarch64-with-glibc2.31

### Installed packages

```python
[tool.poetry.dependencies]

python = ">=3.8,<4.0"
snowflake-connector-python = {extras = ["pandas"], version = "3.0.3"}
```

### What did you do?

The code we use is this -  inside a VSCode dev container instance
```
    context = snowflake.connector.connect(
        user=snowflake_user, 
        account=snowflake_account, 
        warehouse=snowflake_warehouse, 
        role=snowflake_role, 
        authenticator="externalbrowser" 
 ``` 

So here's the problem - trying to use OKTA for small projects but we are in a [devcontainer](https://code.visualstudio.com/docs/devcontainers/containers) environment - which means that the code being executed is inside the a docker container and we're running out of a shell inside VSCode.  Links are port forwarded out of docker and opened on the desktop environment. 

When we go to use this connector, we get the prompt to go log into OKTA, and half of the time the link out to localhost does not forward correctly out of the container.   When I manually adjust the dev container to forward that port it starts working better.

The problem is this is not a permanent solution because the python connector appears to be starting random ports each time.   I think I have the ability to do a range of ports in the .devcontainer settings.

### What did you expect to see?

We should be getting the the "you can go back to where you came from screen"

Quite often I get the "you cannot load this page" message - and we have to smash the reload button several times.  

This makes it an unusable workflow for my developers.

Additionally because the Auth is built into the connector itself - if an app establishes 2 or three connections to snowflake - EACH TIME it forces you to re-log in.   Its super painful experience.

Notably the node connector suffers some of the same problems but the python one is distinctively more painful.

**Comment by RobbertDM** [comment]
Can you use the `SF_AUTH_SOCKET_PORT` environment variable to fix this port? https://github.com/snowflakedb/snowflake-connector-python/blob/9b6b0a63887e472e7c05365e5db896bf4d818db1/src/snowflake/connector/auth/webbrowser.py#L122

**Comment by sfc-gh-dszmolka** [comment]
marking this one as closed as workaround has been provided but please let us know if you still see the issue, and we can look further.
