### ISSUE TITLE
Nones not accepted with qmark parameter style!!

### ISSUE THREAD

**Issue by ztane** [snowflakedb/snowflake-connector-python#168]
Python 3.6.7 on Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic, and 
snowflake-connector-python 1.7.10

I had set the `snowflake.connector.paramstyle = 'qmark'` to circumvent the bug #37 in snowflake-connector-python, and everything worked fine and dandy *until* I noticed that `qmark` parameter style does not support `None`s for input?!!!

```
import snowflake.connector
snowflake.connector.paramstyle = 'qmark'

con = snowflake.connector.connect(...)
con.cursor().execute('USE WAREHOUSE DEMO_WH')
con.cursor().execute('USE demo_db.public')
con.cursor().execute('CREATE TABLE foo(bar text)')
con.cursor().execute('INSERT INTO foo VALUES (?)', [None])
```

and I get the exception `snowflake.connector.errors.ProgrammingError: 252011: None: Python data type [nonetype] cannot be automatically mapped to Snowflake data type. Specify the snowflake data type explicitly.`

The [PEP 249 -- Python Database API Specification v2.0](https://www.python.org/dev/peps/pep-0249/) very clearly states that 

> SQL NULL values are represented by the Python `None` singleton on input and output.

This is not fun anymore because I've got a tight schedule in this project and essential bug reports to the Connector (#37 for example) seem to have been closed without correct resolution, with a referral to a "fix" that creates even more problems down the road and I feel I am in general spending more time tracking various "features" in Snowflake and the Connector and the SQLAlchemy dialect than I am writing actual code (including problems with closing the connections upon exception being thrown / program hanging / weird SIGINT rebinding etc).

**Comment by ztane** [comment]
This has been broken ever since 1.5.1 when the qmark interpolation appeared in the connector. Reproducible with Ubuntu Python 2.7.15rc1 too, fresh virtualenv with

```
Package                    Version 
-------------------------- --------
asn1crypto                 0.24.0  
azure-common               1.1.18  
azure-nspkg                2.0.0   
azure-storage              0.34.2  
azure-storage-blob         1.5.0   
azure-storage-common       1.4.0   
azure-storage-nspkg        3.1.0   
boto3                      1.4.8   
botocore                   1.8.50  
certifi                    2019.3.9
cffi                       1.12.2  
chardet                    3.0.4   
configparser               3.7.4   
cryptography               2.1.4   
docutils                   0.14    
entrypoints                0.3     
enum34                     1.1.6   
future                     0.17.1  
futures                    3.2.0   
idna                       2.8     
ijson                      2.3     
ipaddress                  1.0.22  
jmespath                   0.9.4   
keyring                    18.0.1  
pip                        19.0.3  
pkg-resources              0.0.0   
pyasn1                     0.4.5   
pyasn1-modules             0.2.4   
pycparser                  2.19    
pycryptodome               3.8.1   
pycryptodomex              3.8.1   
PyJWT                      1.7.1   
pyOpenSSL                  17.5.0  
python-dateutil            2.8.0   
pytz                       2019.1  
requests                   2.21.0  
s3transfer                 0.1.13  
SecretStorage              2.3.1   
setuptools                 41.0.0  
six                        1.12.0  
snowflake-connector-python 1.5.1   
urllib3                    1.24.1  
wheel                      0.33.1  
```

**Comment by smtakeda** [comment]
will look into this soon.

**Comment by keller00** [comment]
I already started @smtakeda

**Comment by keller00** [comment]
Fix has been submitted, @ztane 
Keep an eye out for the new connector release on Monday the 22nd, if your deadline is tighter than that then please email me.

**Comment by smtakeda** [comment]
v1.7.11 has the fix.
