### ISSUE TITLE
SNOW-887899: 3.1.0a2 has incorrect version number

### ISSUE THREAD

**Issue by cpcloud** [snowflakedb/snowflake-connector-python#1684]
### Python version

3.10

### Operating system and processor architecture

N/A

### Installed packages

```python
N/A
```

### What did you do?

```python
I observed the version number.
```

### What did you expect to see?

I expect to see an alpha release that is later than the current non-alpha release, perhaps 3.2.0a1, since 3.1.0 is already out.

The way Python tooling sorts version numbers can be seen in the release history of a project on PyPI:

![image](https://github.com/snowflakedb/snowflake-connector-python/assets/417981/579a5b9d-caa5-4115-80c6-498c80d483f0)

This is showing that 3.1.0a2 came **before** 3.1.0. This is clearly incorrect, and can be easily remedied by bumping to any valid release identifier after 3.1.0 like 3.1.1a1, 3.2.0a1, etc.

### Can you set logging to DEBUG and collect the logs?

```bash
N/A
```

**Comment by sfc-gh-yixie** [comment]
@sfc-gh-aling This makes sense. Thoughts?

**Comment by sfc-gh-aling** [comment]
thanks @cpcloud for your feedback!

I agree that this should be a minor version bump. We will bump the version number correctly in our next alpha release.
however I don't think it's worthwhile to re-release the package this time as it's not impacting the usage of the alpha release. I get your point on complying with the versioning story.
