### ISSUE TITLE
SNOW-890678: Create a type stub package

### ISSUE THREAD

**Issue by yuanstanley** [snowflakedb/snowflake-connector-python#1691]
### What is the current behavior?

When using this package I'm getting this error on this import when running mypy

```
import snowflake.connector
```

```
file.py:18: error: Cannot find implementation or library stub for module named "snowflake.connector"
file.py:18: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
file.py:18: error: Cannot find implementation or library stub for module named "snowflake"
```

### What is the desired behavior?

Would be great to have a type stub package so I don't have to ignore it. (Or not sure if it does work already and I need to adjust some sort of configuration?)

### How would this improve `snowflake-connector-python`?

would make importing the package more seamless for codebases that use `mypy`.

### References and other background

I see that there was this issue (https://github.com/snowflakedb/snowflake-connector-python/issues/991) that was resolved but I think they're different?

**Comment by sfc-gh-sfan** [comment]
We have https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/py.typed so that ideally linters should not do the check in the files. I might be missing something but I wonder if there is some config that we could set to respect `py.typed`?

**Comment by sfc-gh-dszmolka** [comment]
marking this Issue as closed as it seems to be answered. if you require further help here, please do comment and we can look further. Thank you !
