### ISSUE TITLE
SNOW-890992: Include version name in release title

### ISSUE THREAD

**Issue by tekumara** [snowflakedb/snowflake-connector-python#1693]
### What is the current behavior?

All Github releases are titled "Release"
<img width="219" alt="CleanShot 2023-08-11 at 12 15 57@2x" src="https://github.com/snowflakedb/snowflake-connector-python/assets/125105/b2c93ee6-a815-4ab2-aa75-9921298079b4">

### What is the desired behavior?

The release is titled after it's version, eg "3.1.0"

### How would this improve `snowflake-connector-python`?

Make it easier to see the latest release version at a glance.

**Comment by sfc-gh-sfan** [comment]
@tekumara Thanks for the suggestion. I personally like the idea of making release titled, but this needs a larger discussion because all drivers follow the same format today. We'll discuss internally.

**Comment by sfc-gh-aling** [comment]
closing the issue as we're already including the release version in the release title
