### ISSUE TITLE
SNOW-893112: Bump platformdirs upper bound (ideally to be <4)

### ISSUE THREAD

**Issue by tmcclintock** [snowflakedb/snowflake-connector-python#1695]
### Python version

Python 3.9.17 (main, Jun 29 2023, 09:32:35)  [Clang 14.0.3 (clang-1403.0.22.14.1)]

### Operating system and processor architecture

macOS-13.5-arm64-arm-64bit

### Installed packages

```python
asn1crypto==1.5.1
certifi==2023.7.22
cffi==1.15.1
cfgv==3.4.0
charset-normalizer==3.2.0
cryptography==41.0.3
distlib==0.3.7
filelock==3.12.2
identify==2.5.26
idna==3.4
nodeenv==1.8.0
oscrypto==1.3.0
packaging==23.1
platformdirs==3.10.0
pre-commit==3.3.3
pycparser==2.21
pycryptodomex==3.18.0
PyJWT==2.8.0
pyOpenSSL==23.2.0
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
snowflake-connector-python==3.1.0
sortedcontainers==2.4.0
typing_extensions==4.7.1
urllib3==1.26.16
virtualenv==20.24.3
```

### What did you do?

```python
pip install snowflake-connector-python>=3.1.0
pip install pre-commit
```

### What did you expect to see?

This is the error generated by `pip`:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
snowflake-connector-python 3.1.0 requires platformdirs<3.9.0,>=2.6.0, but you have platformdirs 3.10.0 which is incompatible.
```

This is a bad dependency snare since pre-commit and snowflake connector are both common in many stacks.

Pre-commit depends on `virtualenv` which is very aggressive in their lower bounds. They lower bound `platformdirs<4,>=3.9.1"` [here](https://github.com/pypa/virtualenv/blob/main/pyproject.toml#L47).

Dependabot updated this dependency in June for this project in [this commit](https://github.com/snowflakedb/snowflake-connector-python/pull/1613). It would be great if it could update again and support `platformdirs<4` so that these dependency snares are avoided.

Thank you!

### Can you set logging to DEBUG and collect the logs?

```bash
import logging
import os

for logger_name in ('snowflake.connector',):
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by mattyoungberg** [comment]
+1 to prioritize to get compatible with the latest of pre-commit.

**Comment by alexfetterman** [comment]
+1 to prioritize to get compatible with pre-commit. We cannot use it on our dbt project without the upgrade. 😢

**Comment by sfc-gh-mkeller** [comment]
Unfortunately since `platformdirs`'s base class uses `abc.ABC` even their backwards compatible features can break us. I'll bump the version!

**Comment by sfc-gh-mkeller** [comment]
Okay, in the attached PR I swapped how I do our version to a Protocol instead of implementing the base class, we should be able to open up the versioning now!

**Comment by tmcclintock** [comment]
I know it's overdue but thank you @sfc-gh-mkeller, you're the hero we needed!
