### ISSUE TITLE
SNOW-923450: Misleading log message for query that times out

### ISSUE THREAD

**Issue by aneeshdurg** [snowflakedb/snowflake-connector-python#1738]
### Python version

Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ]

### Operating system and processor architecture

macOS-12.6.7-arm64-arm-64bit

### Installed packages

```python
NA
```

### What did you do?

```python
Run a query with a short timeout and enable debug logging
```

### What did you expect to see?

A log message indicating that the timer fired and cancelled the query, however, the same log message is emitted whether the query timed out or not.

### Can you set logging to DEBUG and collect the logs?

```bash
import logging
import os

for logger_name in ('snowflake.connector',):
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by sfc-gh-yixie** [comment]
@aneeshdurg To double confirm, for "Run a query with a short timeout and enable debug logging", did you set `STATEMENT_TIMEOUT_IN_SECONDS `?

**Comment by aneeshdurg** [comment]
@sfc-gh-yixie , no I set the `timeout` parameter of `SnowflakeCursor.execute`. The timeout functionality works, but the log message is just slightly misleading, see the PR I opened to fix this.
