### ISSUE TITLE
SNOW-933561: Allow the use of an environment variable to disable build time compilation

### ISSUE THREAD

**Issue by ofek** [snowflakedb/snowflake-connector-python#1754]
### What is the current behavior?

Currently, compilation always occurs when there is no wheel and the required dependencies are satisfied.

### What is the desired behavior?

An environment variable that when set to `1` or `true` will prevent compilation even if the required dependencies are able to be imported.

### How would this improve `snowflake-connector-python`?

When building for some systems like CentOS 6 we do not want to compile as it does not work out-of-the-box without extra configuration.

### References and other background

https://github.com/snowflakedb/snowflake-connector-python/pull/1750#issuecomment-1751011802

**Comment by sfc-gh-sfan** [comment]
I thought this is a good first issue but given it has to deal with build, it might not be as straightforward. I don't think we can prioritize this unfortunately, but we are happy to review PRs :)

**Comment by sfc-gh-mkeller** [comment]
I think #1769 addresses this
