### ISSUE TITLE
NOTICE: v3.4.0 is going to remove the dependency on oscrypto and pycryptodomex

### ISSUE THREAD

**Issue by sfc-gh-aling** [snowflakedb/snowflake-connector-python#1781]
in our next release v3.4.0, snowflake-connector-python is going to remove the dependency on `oscrypto` and `pycryptodomex`, which will be replaced by the usage of `cryptography` library. This is because 1) `oscrypto` is not actively maintained and 2) we would love to consolidate the usage of the libraries as suggested by the community.

This means that when installing `snowflake-connector-python`, `oscrypto` and `pycryptodomex` are no longer installed along with the connector. Please explicitly specify your own oscrypto and pycryptodomex dependency if your application depends on the two libraries.

for more context, please check the following issues discussing the usage of crypto libraries.
https://github.com/snowflakedb/snowflake-connector-python/issues/1605
https://github.com/snowflakedb/snowflake-connector-python/issues/1767

PR merged: https://github.com/snowflakedb/snowflake-connector-python/pull/1779

we will also release snowsql which will be built upon the latest release of snowflake-connector-python.
however, snowsql still will have `pycryptodomex` as dependency as it's using functionality from the library.

cc: @sfc-gh-mkeller

**Comment by sfc-gh-aling** [comment]
v3.4.0 is released removing dependencies oscrypto and pycryptodomex

**Comment by davidln777** [comment]
@sfc-gh-aling /  @sfc-gh-mkeller - Hi, Do you have any ETA on the snowsql fix? 
Thanks
