### ISSUE TITLE
SNOW-956671: We should change the user-agent of the diagnostic report so we can track it's usage

### ISSUE THREAD

**Issue by sfc-gh-cconner** [snowflakedb/snowflake-connector-python#1788]
### What is the current behavior?

Currently there is no user agent sent with the diagnostic report.

### What is the desired behavior?

Send a user-agent of snowflake-connector-diagnostic so we can track usage.

### How would this improve `snowflake-connector-python`?

This will allow us to tack usage compared to snowcd and push use away from snowcd.

**Comment by sfc-gh-cconner** [comment]
https://github.com/snowflakedb/snowflake-connector-python/pull/1789

**Comment by sfc-gh-dszmolka** [comment]
thanks for the issue and the fix ;) it seems to be approved for quite some time now, could you please consider merging it (or closing it if it's not needed anymore)
thank you !
