### ISSUE TITLE
SNOW-985624: `write_pandas` casts `pd.Timestamp` --> `INTEGER` when creating a table

### ISSUE THREAD

**Issue by GTLangseth** [snowflakedb/snowflake-connector-python#1820]
### What is the current behavior?

Currently, `write_pandas` performs the following actions create a table from a Pandas DataFrame:

- The Pandas DataFrame is written to parquet in a staged location
- Snowflake's `infer_schema` function is called on the staged file to make a *guess* about which data types to use
- Due to the way that parquet encodes timestamp data, `infer_schema` fails to correctly interpret TIMESTAMP data types and loads as INTEGER values instead

The above behavior regarding `infer_schema` is a known issue and is described in this [knowledge base](https://community.snowflake.com/s/article/infer-schema-parquet-timestamps-seen-as-number) article.

But even [the documentation](https://docs.snowflake.com/en/sql-reference/functions/infer_schema#usage-notes) for `infer_schema` makes very little guarantees about how TIMESTAMP types are handled:

> All the variations of timestamp data types are retrieved as TIMESTAMP_NTZ without any time zone information.

### What is the desired behavior?

1. *Probably* there should be some way of overriding the types returned by `infer_schema` via some dictionary object that is passed in to the `write_pandas` function call
2. *Perhaps* it would be nice if there was some additional code that handled pd.Timestamp and dt.datetime types automatically so we didn't have to override manually

### How would this improve `snowflake-connector-python`?

- DataFrames containing timestamps could be written correctly to Snowflake

**Comment by GTLangseth** [comment]
Thanks! That fixes the issue. I'll close the ticket.

**Comment by GTLangseth** [comment]
Yea sure thing!

Here's a simple script:

```python
import pandas as pd
from snowflake import connector

df_in = pd.DataFrame(
    {
        "timestamp_ntz": pd.date_range("2021-01-01", "2021-01-10"),
        "timestamp_tz": pd.date_range("2021-01-01", "2021-01-10", tz="America/New_York")
    }
)
conn = connector.connect(**connection_kwargs)
connector.pandas_tools.write_pandas(conn, df, "test_pandas_tz", overwrite=True, use_logical_type=True)

df_out = fetch_pandas_df("select * from test_pandas_tz")
```

Given the above, I'd expect to receive data back in the same way it was submitted - but this is not the case. Timezones have been coerced to UTC:

```python
# check input types
df_in.dtypes

>>> timestamp_ntz                      datetime64[ns]
    timestamp_tz     datetime64[ns, America/New_York]
    dtype: object

# check output types
df_out.dtypes

>>> timestamp_ntz                      datetime64[ns]
    timestamp_tz                  datetime64[ns, UTC]
    dtype: object
```

Data in:

|    | timestamp_ntz       | timestamp_tz              |
|---:|:--------------------|:--------------------------|
|  0 | 2021-01-01 00:00:00 | 2021-01-01 00:00:00-05:00 |
|  1 | 2021-01-02 00:00:00 | 2021-01-02 00:00:00-05:00 |
|  2 | 2021-01-03 00:00:00 | 2021-01-03 00:00:00-05:00 |
|  3 | 2021-01-04 00:00:00 | 2021-01-04 00:00:00-05:00 |
|  4 | 2021-01-05 00:00:00 | 2021-01-05 00:00:00-05:00 |

Data out:

|    | timestamp_ntz       | timestamp_tz              |
|---:|:--------------------|:--------------------------|
|  0 | 2021-01-01 00:00:00 | 2021-01-01 05:00:00+00:00 |
|  1 | 2021-01-02 00:00:00 | 2021-01-02 05:00:00+00:00 |
|  2 | 2021-01-03 00:00:00 | 2021-01-03 05:00:00+00:00 |
|  3 | 2021-01-04 00:00:00 | 2021-01-04 05:00:00+00:00 |
|  4 | 2021-01-05 00:00:00 | 2021-01-05 05:00:00+00:00 |

**Comment by sfc-gh-mkeller** [comment]
Okay, I went ahead and transformed your repro script into a test, I'm going to post it for public repro purposes:
```
def test_timezone_write_pandas(conn_cnx):
    df_in = pandas.DataFrame(
        {
            "timestamp_ntz": pandas.date_range("2021-01-01", "2021-01-10"),
            "timestamp_tz": pandas.date_range("2021-01-01", "2021-01-10", tz="America/New_York")
        }
    )
    with conn_cnx() as conn:
        write_pandas(conn, df_in, "test_pandas_tz", overwrite=True, use_logical_type=True)
        with conn.cursor() as cur:
            df_out = cur.execute("select * from \"test_pandas_tz\"").fetch_pandas_all()
    assert df_out == df_in
```
When I look at the generated parquet file with `parquet meta /var/folders/r5/16cxd62s049c7zbsy5kytnwm0000gn/T/tmpyq_lzwys/file0.txt` I get:
```
File path:  /var/folders/r5/16cxd62s049c7zbsy5kytnwm0000gn/T/tmpyq_lzwys/file0.txt
Created by: parquet-cpp-arrow version 10.0.1
Properties:
        pandas: {"index_columns": [{"kind": "range", "name": null, "start": 0, "stop": 10, "step": 1}], "column_indexes": [{"name": null, "field_name": null, "pandas_type": "unicode", "numpy_type": "object", "metadata": {"encoding": "UTF-8"}}], "columns": [{"name": "timestamp_ntz", "field_name": "timestamp_ntz", "pandas_type": "datetime", "numpy_type": "datetime64[ns]", "metadata": null}, {"name": "timestamp_tz", "field_name": "timestamp_tz", "pandas_type": "datetimetz", "numpy_type": "datetime64[ns]", "metadata": {"timezone": "America/New_York"}}], "creator": {"library": "pyarrow", "version": "10.0.1"}, "pandas_version": "2.0.3"}
  ARROW:schema: /////4ADAAAQAAAAAAAKAA4ABgAFAAgACgAAAAABBAAQAAAAAAAKAAwAAAAEAAgACgAAAKQCAAAEAAAAAQAAAAwAAAAIAAwABAAIAAgAAAB8AgAABAAAAG4CAAB7ImluZGV4X2NvbHVtbnMiOiBbeyJraW5kIjogInJhbmdlIiwgIm5hbWUiOiBudWxsLCAic3RhcnQiOiAwLCAic3RvcCI6IDEwLCAic3RlcCI6IDF9XSwgImNvbHVtbl9pbmRleGVzIjogW3sibmFtZSI6IG51bGwsICJmaWVsZF9uYW1lIjogbnVsbCwgInBhbmRhc190eXBlIjogInVuaWNvZGUiLCAibnVtcHlfdHlwZSI6ICJvYmplY3QiLCAibWV0YWRhdGEiOiB7ImVuY29kaW5nIjogIlVURi04In19XSwgImNvbHVtbnMiOiBbeyJuYW1lIjogInRpbWVzdGFtcF9udHoiLCAiZmllbGRfbmFtZSI6ICJ0aW1lc3RhbXBfbnR6IiwgInBhbmRhc190eXBlIjogImRhdGV0aW1lIiwgIm51bXB5X3R5cGUiOiAiZGF0ZXRpbWU2NFtuc10iLCAibWV0YWRhdGEiOiBudWxsfSwgeyJuYW1lIjogInRpbWVzdGFtcF90eiIsICJmaWVsZF9uYW1lIjogInRpbWVzdGFtcF90eiIsICJwYW5kYXNfdHlwZSI6ICJkYXRldGltZXR6IiwgIm51bXB5X3R5cGUiOiAiZGF0ZXRpbWU2NFtuc10iLCAibWV0YWRhdGEiOiB7InRpbWV6b25lIjogIkFtZXJpY2EvTmV3X1lvcmsifX1dLCAiY3JlYXRvciI6IHsibGlicmFyeSI6ICJweWFycm93IiwgInZlcnNpb24iOiAiMTAuMC4xIn0sICJwYW5kYXNfdmVyc2lvbiI6ICIyLjAuMyJ9AAAGAAAAcGFuZGFzAAACAAAAcAAAAAQAAACo////AAABChAAAAAoAAAABAAAAAAAAAAMAAAAdGltZXN0YW1wX3R6AAAAAAgADAAGAAgACAAAAAAAAwAEAAAAEAAAAEFtZXJpY2EvTmV3X1lvcmsAAAAAEAAUAAgABgAHAAwAAAAQABAAAAAAAAEKEAAAACQAAAAEAAAAAAAAAA0AAAB0aW1lc3RhbXBfbnR6AAYACAAGAAYAAAAAAAMAAAAAAA==
Schema:
message schema {
  optional int64 timestamp_ntz (TIMESTAMP(MICROS,false));
  optional int64 timestamp_tz (TIMESTAMP(MICROS,true));
}


Row group 0:  count: 10  39.00 B records  start: 4  total(compressed): 390 B total(uncompressed):346 B 
--------------------------------------------------------------------------------
               type      encodings count     avg size   nulls   min / max
timestamp_ntz  INT64     G _ R     10        19.50 B    0       "2021-01-01T00:00:00.000000" / "2021-01-10T00:00:00.000000"
timestamp_tz   INT64     G _ R     10        19.50 B    0       "2021-01-01T05:00:00.00000..." / "2021-01-10T05:00:00.00000..."
```

Note the important part: `"timezone": "America/New_York"`. So so far so good, but once the test finishes f I look at the table's content on the UI I see:
<img width="211" alt="Screenshot 2024-01-19 at 14 23 42" src="https://github.com/snowflakedb/snowflake-connector-python/assets/63477823/2505fa62-e2de-4176-b8e3-2408941b4a3e">
Which is technically correct, but I'd claim this to be not correct.
@sfc-gh-yuliu could your team please take a look at the above?

However; when I execute `"select * from \"test_pandas_tz\""` from the Python connector I get back the following:
```
  timestamp_ntz              timestamp_tz
0    2021-01-01 2021-01-01 05:00:00+00:00
1    2021-01-02 2021-01-02 05:00:00+00:00
2    2021-01-03 2021-01-03 05:00:00+00:00
3    2021-01-04 2021-01-04 05:00:00+00:00
4    2021-01-05 2021-01-05 05:00:00+00:00
5    2021-01-06 2021-01-06 05:00:00+00:00
6    2021-01-07 2021-01-07 05:00:00+00:00
7    2021-01-08 2021-01-08 05:00:00+00:00
8    2021-01-09 2021-01-09 05:00:00+00:00
9    2021-01-10 2021-01-10 05:00:00+00:00
```
So there's definitely something wrong in the connector too...

**Comment by skwijeratne** [comment]
@GTLangseth @sfc-gh-aalam @sfc-gh-mkeller Is there a work around for this issue?

**Comment by sfc-gh-aalam** [comment]
@skwijeratne I found the below works for me. You need to set you session timezone same as the pandas dataframe timezone.

```
def test_timezone_write_pandas(conn):
    df_in = pandas.DataFrame(
        {
            "timestamp_ntz": pandas.date_range("2021-01-01", "2021-01-10"),
            "timestamp_tz": pandas.date_range("2021-01-01", "2021-01-10", tz="America/New_York")
        }
    )

    write_pandas(conn, df_in, "test_pandas_tz", overwrite=True, use_logical_type=True)
    with conn.cursor() as cur:
        cur.execute("alter session set timezone='America/New_York'")
        df_out = cur.execute("select * from \"test_pandas_tz\"").fetch_pandas_all()
    print("df_in", df_in)
    print("df_out", df_out)
    assert df_in.equals(df_out)
```

**Comment by KingAkhenaten** [comment]
I would like to add a comment regarding usage of write_pandas within a stored procedure.
session.write_pandas does not support the `use_logical_type` parameter. I have the following workaround:

**Inside a stored procedure**
```
CREATE OR REPLACE PROECDURE ...
...
from snowflake.connector.pandas_tools import write_pandas
...
write_pandas(session.connection, ..., use_logical_type=True)
```

**Comment by sfc-gh-dszmolka** [comment]
thanks everyone for adding the bits here for posterity; i'm now going to close this issue out as it seems all open questions have been answered.
if i misjudged, do comment please on what is left to handle and we can take this further accordingly. thank you !
