### ISSUE TITLE
SNOW-986347: Compilation issue on arm/linux (missing cstdin include)

### ISSUE THREAD

**Issue by w08r** [snowflakedb/snowflake-connector-python#1823]
Trying to build on docker on arm (so arm64/linux) and hitting a compile error.

https://github.com/snowflakedb/snowflake-connector-python/blob/7bd365cdd42bf1b799356f858e50d513897cb8e1/src/snowflake/connector/nanoarrow_cpp/ArrowIterator/SnowflakeType.hpp#L18

unit_8 not defined so needs cstdint.  Apologies if I'm missing something.

**Comment by sfc-gh-aling** [comment]
hi @w08r , what's the compiler in your docker image used to build the connector?

we set `std=c++17` to compile the connector on linux, can you check if it's compatible with your compiler?

https://github.com/snowflakedb/snowflake-connector-python/blob/7bd365cdd42bf1b799356f858e50d513897cb8e1/setup.py#L142-L145

**Comment by w08r** [comment]
Hi @sfc-gh-aling ; the docker image is `ubuntu:mantic-20231128` and it's the default `apt` installed compiler:
```
gcc version 13.2.0 (Ubuntu 13.2.0-4ubuntu3) 
```

I'm slightly confused though, I'm out of touch with c++ but does the latest standard include a definition for uint8_t by default, should not the header be included anyway?

```
root@e703d7dcb9ac:/# cat /tmp/test.cpp 
enum class Type: uint8_t {};
root@e703d7dcb9ac:/# g++ -std=c++17 /tmp/test.cpp 
/tmp/test.cpp:1:6: warning: elaborated-type-specifier for a scoped enum must not use the 'class' keyword
    1 | enum class Type: uint8_t {};
      | ~~~~ ^~~~~
      |      -----
/tmp/test.cpp:1:16: error: found ':' in nested-name-specifier, expected '::'
    1 | enum class Type: uint8_t {};
      |                ^
      |                ::
/tmp/test.cpp:1:12: error: 'Type' has not been declared
    1 | enum class Type: uint8_t {};
      |            ^~~~
/tmp/test.cpp:1:26: error: expected unqualified-id before '{' token
    1 | enum class Type: uint8_t {};
      |                          ^

```

**Comment by sfc-gh-aling** [comment]
interesting, I think you are right, uint8_t comes from the stdint header which means there must be some place where the header file is included.

btw have you tried adding `#include "stdint.h"` in `SnowflakeType.hpp` and see if you can compile the connector inside the docker?

**Comment by w08r** [comment]
> interesting, I think you are right, uint8_t comes from the stdint header which means there must be some place where the header file is included.
> 
> btw have you tried adding `#include "stdint.h"` in `SnowflakeType.hpp` and see if you can compile the connector inside the docker?

I'll have a blast.  If it fixes I will make a PR.

**Comment by w08r** [comment]
@sfc-gh-aling created PR which fixes.

Steps to recreate (not added to automated tests but can do if you advise approach).

```
docker run --rm -it ubuntu:mantic-20231128 ...

export DEBIAN_FRONTEND=noninteractive
apt update                                  &&
  apt install -y unattended-upgrades        &&
  apt install -y unixodbc                   &&
  apt install -y python3.11 python3.11-venv &&
  apt install -y gcc g++ python3-dev git

python3 -m venv venv
. venv/bin/activate
git clone https://github.com/snowflakedb/snowflake-connector-python.git
cd snowflake-connector-python/
python -m pip install -U pip setuptools wheel build
python -m build --wheel .

```

Compiles with the header included.

**Comment by w08r** [comment]
@sfc-gh-aling happy new year!  any thoughts on the attached PR?

**Comment by padhia** [comment]
Fails to build on the latest (unstable) Nixos. This seems to be a known [gcc 13 issue](https://gcc.gnu.org/gcc-13/porting_to.html).

**Comment by sfc-gh-aling** [comment]
thanks folks for sharing the information with us.
@w08r thanks for the PR, I think it's fairly straightforward and we should take it. can you help resolve the conflict and then we test & merge the PR.

**Comment by joelthelion** [comment]
Is a release with this fix planned any time soon? I'd love to use snowflake but I can't 😄
