### ISSUE TITLE
SNOW-1045652: Bump platformdirs upper bound (again)?

### ISSUE THREAD

**Issue by bdewilde** [snowflakedb/snowflake-connector-python#1876]
### What is the current behavior?

The latest version of this package can't be installed alongside the latest version of `meltano`, owing to incompatible version constraints on `platformdirs` -- here's [theirs](https://github.com/meltano/meltano/blob/main/pyproject.toml#L63) vs [yours](https://github.com/snowflakedb/snowflake-connector-python/blob/main/setup.cfg#L62).

I see that this dependency has [caused you trouble](https://github.com/snowflakedb/snowflake-connector-python/issues/1695) in the past, so understand if your hands are tied here.

### What is the desired behavior?

It would be great if these two packages could be installed alongside each other! In particular, I want (_am professionally obliged_) to upgrade `meltano` to v3.3 in order to address an outstanding CVE, and this version incompatibility is preventing me from doing so.

### How would this improve `snowflake-connector-python`?

Many developers on Snowflake also develop using meltano. :)

**Comment by si-te** [comment]
Can confirm this is currently stopping using meltano in 3.3.1 with the dbt-snowflake utility. platformdirs should be bumped to at least 4.2.0

**Comment by varun196** [comment]
+1 to prioritize to get compatible with the latest platformdirs 4.2.0

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for drawing our attention to this gap; we'll see how it can be prioritized

**Comment by sfc-gh-dszmolka** [comment]
PR under review https://github.com/snowflakedb/snowflake-connector-python/pull/1900

**Comment by sfc-gh-dszmolka** [comment]
The PR has been merged and can be now either installed when connector installed from `main` or it will be also available in the next driver version, ought to be released towards end of March

**Comment by bdewilde** [comment]
Thanks very much for the quick fix!

**Comment by sfc-gh-dszmolka** [comment]
fix released with v3.8.0, thank you for bearing with us !

**Comment by bdewilde** [comment]
thanks a ton! upgrading at this very moment 👍
