### ISSUE TITLE
SNOW-1045815: Connector fails when using a connections.toml file with an encrypted private key file and specifying the private_key_file_pwd in the file

### ISSUE THREAD

**Issue by rosspb3** [snowflakedb/snowflake-connector-python#1877]
### Python version

Python 3.9.6 (default, Dec  7 2023, 05:42:47)  [Clang 15.0.0 (clang-1500.1.0.2.5)]

### Operating system and processor architecture

macOS-14.3-arm64-arm-64bit

### Installed packages

```python
asn1crypto==1.5.1
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
cryptography==41.0.7
filelock==3.13.1
idna==3.6
packaging==23.2
platformdirs==3.11.0
pycparser==2.21
PyJWT==2.8.0
pyOpenSSL==23.3.0
pytz==2024.1
requests==2.31.0
snowflake-connector-python==3.7.0
sortedcontainers==2.4.0
tomlkit==0.12.3
typing_extensions==4.9.0
urllib3==1.26.18
```

### What did you do?

```python
Created a file ~/.snowflake/connections.toml
[test_connection]
account = "test_account"
user = "test_user"
private_key_file = "/path/to/rsa_key.pem"
private_key_file_pwd = "key_file_password"

Then attempted to use connection ...
with snowflake.connector.connect(
    connection_name='test_connection'
) as con:
    result = con.cursor().execute("select current_version()").fetchone()
    logger.info(f"current version = {result[0]}")
```

### What did you expect to see?

I expected to see the current version printed after a successful connection.
However I received an exception due to the password passed being of type string instead of bytes.
[snowflake_connector.log](https://github.com/snowflakedb/snowflake-connector-python/files/14199980/snowflake_connector.log)

Adding a bytes representation of the password to the parameters does work around the issue, but somewhat negates the benefit of using a file for configuration.

`with snowflake.connector.connect(
    connection_name='test_connection',
    private_key_file_pwd=b'test_password'
) as con:
    result = con.cursor().execute("select current_version()").fetchone()
    logger.info(f"current version = {result[0]}")
`

### Can you set logging to DEBUG and collect the logs?

```bash
import logging
import os

for logger_name in ('snowflake.connector',):
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by sfc-gh-aling** [comment]
thanks @rosspb3 for reaching out and appreciate your PR.
we will take a look at the issue and PR.
