### ISSUE TITLE
Potgres SQL vs Snowflake SQL aggregation (resample)

### ISSUE THREAD

**Issue by delijati** [snowflakedb/snowflake-connector-python#192]
Hi,

this is probably not the right place to post this but as i'm using the python sdk i post it here:

The resulting query behaves different between postgres and snowflake [1] On snowflake simply happens nothing.

[1]

>     CREATE TABLE usage_sample
>     (
>       id serial primary key, 
>       category text NOT NULL,
>       val int NOT NULL,
>       name text NOT NULL,
>       sample_time timestamp with time zone NOT NULL
>     );
>     
>     
>     INSERT INTO usage_sample
>     (category, val, name, sample_time)
>     VALUES
>     ('action', 3, 'one',   '2013/03/14 4:23:03'),
>     ('action', 4, 'one',   '2013/03/14 4:23:13'),
>     ('action', 8, 'two',   '2013/03/14 4:23:10'),
>     ('action', 1, 'two',   '2013/03/14 4:23:12'),
>     ('action', 3, 'three', '2013/03/14 4:23:20'),
>     ('action', 4, 'three', '2013/03/14 4:23:30'),
>     ('action', 4, 'one',   '2013/03/14 4:25:03'),
>     ('action', 6, 'two',   '2013/03/14 4:25:20'),
>     ('action', 4, 'three', '2013/03/14 4:26:06'),
>     ('action', 1, 'one',   '2013/03/14 4:27:03'),
>     ('action', 7, 'one',   '2013/03/14 4:27:13'),
>     ('action', 2, 'two',   '2013/03/14 4:27:10'),
>     ('action', 2, 'two',   '2013/03/14 4:27:20'),
>     ('action', 45, 'three', '2013/03/14 4:27:20'),
>     ('action', 24, 'three', '2013/03/14 4:27:30'),
>     ('action', 8, 'one',   '2013/03/14 4:28:03'),
>     ('action', 4, 'two',   '2013/03/14 4:28:20'),
>     ('action', 2, 'three', '2013/03/14 4:29:06'),
>     ('action', 4, 'one',   '2013/03/14 5:30:03'),
>     ('action', 8, 'two',   '2013/03/14 5:30:10'),
>     ('action', 4, 'three', '2013/03/14 5:30:20');
> 
> <pre>
> ✓
> 
21 rows affected
> </pre>

>     -- aggregate by one hour
>     SELECT to_timestamp((
>     	CAST(EXTRACT(epoch FROM sample_time) AS INTEGER) / 3600) * 3600) AS foo
>     FROM usage_sample
>     GROUP BY foo
>     ORDER BY foo ASC;
>     
>     -- aggregate by 5 minutes
>     SELECT to_timestamp((
>     	CAST(EXTRACT(epoch FROM sample_time) AS INTEGER) / 300) * 300) AS foo
>     FROM usage_sample
>     GROUP BY foo
>     ORDER BY foo ASC;

> 
> <pre>
> | foo                    |
> | :--------------------- |
> | 2013-03-14 04:00:00+00 |
> | 2013-03-14 05:00:00+00 |
> 
> | foo                    |
> | :--------------------- |
> | 2013-03-14 04:20:00+00 |
> | 2013-03-14 04:25:00+00 |
> | 2013-03-14 05:30:00+00 |
> </pre>

*db<>fiddle [here](https://dbfiddle.uk/?rdbms=postgres_9.6&fiddle=d78d36243563de381c54889e91ab1962)*

**Comment by smtakeda** [comment]
can you please reach out the customer support or post the question https://support.snowflake.net/s/ about SQL?

**Comment by delijati** [comment]
Sure thanks
