### ISSUE TITLE
SNOW-1366543: Log Error coming from line CArrowTableIterator.cpp#L230 making a lot noise 

### ISSUE THREAD

**Issue by rajathpatel23** [snowflakedb/snowflake-connector-python#1939]
We are getting this log error while processing data from Snowflake. It seems to be making a lot of noise; I would like to understand - what was the change made in the [snowflake ticket](https://snowflakecomputing.atlassian.net/browse/SNOW-1269820)? I feel the [logger there](https://github.com/snowflakedb/snowflake-connector-python/blob/8cdca67faf3fa2a6d31a545d78326b76c31c4c64/src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowTableIterator.cpp#L230) is more of debug logger than actual log error.

The changes introduced in this [PR](https://github.com/snowflakedb/snowflake-connector-python/pull/1907/files) seem to be start to give us the log error 

Could you help me with this? Also, can you provide more info on the support for pandas that have come with this change?

**Comment by rajathpatel23** [comment]
I tried raising a support ticket - however I could not create one, hence having this issue as a placeholder for now.

**Comment by sfc-gh-dszmolka** [comment]
ah, late to the party :)

**Comment by rajathpatel23** [comment]
@sfc-gh-jrose Thank you so much for taking a look at this quickly.

**Comment by sfc-gh-jrose** [comment]
The version for this fix should be published later this week.

**Comment by sfc-gh-dszmolka** [comment]
version 3.10.1 released with the fix
