### ISSUE TITLE
Snowflake pyasn1 requirements issue

### ISSUE THREAD

**Issue by chad-ongstad** [snowflakedb/snowflake-connector-python#196]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
2.7.16
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Ubuntu 16
3. What are the component versions in the environment (`pip list`)? 

The snowflake connection does not work with the following components which are installed as part of the pip install. 
pyasn1==0.4.7 and pyasn1-modules==0.2.6

When attempting to connect I received the following error 
snowflake.connector.errors.OperationalError: 250003: Failed to execute request: Attempted "__iter__" operation on ASN.1 schema object

Instead I had to use pyasn1==0.4.5 and pyasn1-modules==0.2.5 and the connection worked properly.

**Comment by smtakeda** [comment]
hmm, it is not reproducible for me.
```
>pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                    Version  
-------------------------- ---------
asn1crypto                 0.24.0   
azure-common               1.1.23   
azure-nspkg                3.0.2    
azure-storage-blob         2.1.0    
azure-storage-common       2.1.0    
azure-storage-nspkg        3.1.0    
boto3                      1.9.226  
botocore                   1.12.226 
certifi                    2019.6.16
cffi                       1.12.3   
chardet                    3.0.4    
cryptography               2.7      
docutils                   0.15.2   
enum34                     1.1.6    
future                     0.17.1   
futures                    3.3.0    
idna                       2.8      
ijson                      2.4      
ipaddress                  1.0.22   
jmespath                   0.9.4    
pip                        19.2.3   
pyasn1                     0.4.7    
pyasn1-modules             0.2.6    
pycparser                  2.19     
pycryptodomex              3.9.0    
PyJWT                      1.7.1    
pyOpenSSL                  19.0.0   
python-dateutil            2.8.0    
pytz                       2019.2   
requests                   2.22.0   
s3transfer                 0.2.1    
setuptools                 41.2.0   
six                        1.12.0   
snowflake-connector-python 1.9.0    
urllib3                    1.25.3   
wheel                      0.33.6 
```

The test script:
```
import snowflake.connector
con = snowflake.connector.connect(
...  (connection parameters)
)

cur = con.cursor()
cur.execute("select 1")
print(cur.sfqid)
con.close()
```

The results:
```
>python test_connection.py 
018ecdb7-02b5-287a-0000-000000082041
```

Python version
```
>python --version
Python 2.7.10
```

**Comment by chad-ongstad** [comment]
This appears to occur with snowflake-connector-python 1.5.3 and does not occur with 1.9.0

`pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package                       Version  
----------------------------- ---------
amqp                          2.5.1    
aniso8601                     7.0.0    
APScheduler                   3.6.1    
asn1crypto                    0.24.0   
azure-common                  1.1.23   
azure-nspkg                   2.0.0    
azure-storage                 0.34.2   
azure-storage-blob            2.1.0    
azure-storage-common          2.1.0    
azure-storage-nspkg           3.1.0    
backports.functools-lru-cache 1.5      
bcrypt                        3.1.7    
beautifulsoup4                4.8.0    
billiard                      3.5.0.5  
bitarray                      1.0.1    
boto3                         1.5.25   
botocore                      1.8.50   
cachetools                    3.1.1    
celery                        4.0.2    
certifi                       2019.6.16
cffi                          1.12.3   
chardet                       3.0.4    
Click                         7.0      
conda                         4.7.11   
conda-package-handling        1.3.11   
crontab                       0.21.3   
cryptography                  2.1      
ctds                          1.10.0   
cx-Oracle                     7.0.0    
Cython                        0.25.2   
docutils                      0.15.2   
dominate                      2.4.0    
enum-compat                   0.0.2    
enum34                        1.1.6    
eventlet                      0.20.1   
fastavro                      0.17.1   
Flask                         0.12     
Flask-APScheduler             1.7.0    
Flask-Bcrypt                  0.7.1    
Flask-Bootstrap               3.3.7.1  
Flask-Compress                1.4.0    
Flask-HTTPAuth                3.2.3    
Flask-Login                   0.4.0    
Flask-RESTful                 0.3.6    
Flask-Session                 0.3.1    
Flask-SocketIO                2.8.5    
Flask-SQLAlchemy              2.2      
Flask-Static-Compress         1.0.2    
Flask-WTF                     0.14     
funcsigs                      1.0.2    
future                        0.17.1   
futures                       3.3.0    
gevent                        1.2.1    
gevent-websocket              0.10     
google-api-python-client      1.7.4    
google-auth                   1.5.0    
google-auth-httplib2          0.0.3    
greenlet                      0.4.15   
gunicorn                      19.7.1   
hdfs3                         0.3.0    
httplib2                      0.13.1   
hyperloglog                   0.0.12   
idna                          2.8      
IfxPy                         2.7.1    
ijson                         2.4      
importlib                     1.0.4    
impyla                        0.14.0   
ipaddress                     1.0.22   
itsdangerous                  1.1.0    
jac                           0.17.2   
JayDeBeApi                    1.0.0    
Jinja2                        2.10.1   
jmespath                      0.9.4    
JPype1                        0.7.0    
kombu                         4.1.0    
libarchive-c                  2.8      
MarkupSafe                    1.1.1    
mysqlclient                   1.3.12   
ndg-httpsclient               0.4.2    
numpy                         1.16.5   
ordereddict                   1.1      
pandas                        0.20.3   
paramiko                      2.2.1    
pip                           19.1.1   
protobuf                      3.3.2    
psutil                        5.2.2    
psycopg2                      2.7      
pyasn1                        0.4.7    
pyasn1-modules                0.2.6    
pycosat                       0.6.3    
pycparser                     2.19     
pycryptodome                  3.4.11   
pycryptodomex                 3.9.0    
PyJWT                         1.7.1    
PyNaCl                        1.3.0    
pyodbc                        4.0.23   
pyOpenSSL                     16.2.0   
PySocks                       1.7.0    
python-dateutil               2.8.0    
python-engineio               3.9.3    
python-ldap                   2.4.41   
python-socketio               1.7.2    
pytz                          2019.2   
requests                      2.22.0   
rjsmin                        1.1.0    
rsa                           4.0      
ruamel-yaml                   0.15.46  
s3transfer                    0.1.13   
salesforce-bulk               2.1.0    
sasl                          0.2.1    
setuptools                    41.0.1   
simple-salesforce             0.74.2   
six                           1.12.0   
snowflake-connector-python    1.5.3    
socketIO-client               0.7.2    
soupsieve                     1.9.3    
SQLAlchemy                    1.1.6    
sqlparse                      0.2.4    
tabulate                      0.7.7    
thrift                        0.9.3    
thrift-sasl                   0.2.1    
tqdm                          4.32.1   
tzlocal                       2.0.0    
ujson                         1.35     
unicodecsv                    0.14.1   
uritemplate                   3.0.0    
urllib3                       1.24.2   
vine                          1.3.0    
visitor                       0.1.3    
websocket-client              0.56.0   
Werkzeug                      0.15.6   
wheel                         0.33.4   
wsaccel                       0.6.2    
WTForms                       2.1`

Results:
`snowflake.connector.errors.OperationalError: 250003: Failed to execute request: Attempted "__iter__" operation on ASN.1 schema object`

Python version Python 2.7.16 :: Anaconda, Inc.
