### ISSUE TITLE
SNOW-1471963: Is there any default max chunk sizes that limits results from cursor.fetchall()?

### ISSUE THREAD

**Issue by mjnur** [snowflakedb/snowflake-connector-python#1969]
Hi,

My code looks something like this:

```python
connection = snowflake.connector.connect(
    ....
    ....
)
cursor = connection.cursor()
cursor.execute(query)
df = cursor.fetch_pandas_all()
```
and I see logging messages like this:
```
INFO:snowflake.connector.cursor:Number of results in first chunk: 5
```
I'm wondering, is there any default chunking that happens to my results? or if I run `result = cursor.fetchall()`, will I be guaranteed to always return the full results? I couldn't find this information in documentation, but sorry in advance if I missed it.

Thanks!

**Comment by sfc-gh-dszmolka** [comment]
hi there and thanks for raising this question! regarding `cursor.fetchall()`, we do document here https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-example#using-cursor-to-fetch-values that:

> If you need to get all results at once:
>```
> results = con.cursor().execute("SELECT col1, col2 FROM testtable").fetchall()
> for rec in results:
>     print('%s, %s' % (rec[0], rec[1]))
> ```

regarding the chunks, yes it does happen in the background, on the server side, right after the query is run. It's the backend who determines the number and size of chunks. If the resultset is small enough, there might be only one result chunk which is then directly returned to the client. If the result is big enough, the backend puts it down first to cloud storage (S3, Azure blob etc) and the client retrieves directly from cloud storage.
The chunks might (== probably, will) differ in number of rows they carry and thus size too.

This part (directly streaming to client vs. putting it to cloud storage) is sorta documented here https://docs.snowflake.com/en/user-guide/querying-persisted-results

Hope this answers the question here

**Comment by sfc-gh-dszmolka** [comment]
closing this one as has been answered, but if any open questions remain, please comment and i can reopen and look further
