### ISSUE TITLE
execute_stream documentation is out of sync with implementation

### ISSUE THREAD

**Issue by stanorama** [snowflakedb/snowflake-connector-python#197]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.7

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Win10 x64

3. What are the component versions in the environment (`pip list`)? 
n/a

4. What did you do?
`for cur in self.con.execute_stream(f, remove_comments=True, return_cursors=True):`

5. What did you expect to see?
The documentation:
https://docs.snowflake.net/manuals/user-guide/python-connector-api.html#execute_string
Shows the execute_stream taking 2 optional parameters.
Looking at the source it appears there is no implementation for parameter 'return_cursors'.
The documentation should be updated.

6. What did you see instead?
TypeError: execute_stream() got an unexpected keyword argument 'return_cursors'

**Comment by smtakeda** [comment]
https://docs.snowflake.net/manuals/user-guide/python-connector-api.html#execute_stream
is the right doc, which doesn't have `return_cursors` option. The method always return cursors.

```
import snowflake.connector
con = snowflake.connector.connect(
    account=account,
    user=user,
    password=password,
)
with open('external_script.sql') as f:
    for cur in con.execute_stream(f):
        for ret in cur:
            print(ret)
```
