### ISSUE TITLE
Using python datetime in `SELECT` statement confusion

### ISSUE THREAD

**Issue by IanQS** [snowflakedb/snowflake-connector-python#198]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

`Python 3.6`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

`Darwin-18.7.0-x86_64-i386-64bit`

3. What are the component versions in the environment (`pip list`)? 

```
snowflake-connector-python        1.8.4
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```
con = snowflake.connector.connect(
  user='user',
  password='pwd',
  account='account',
  warehouse='wh',
  database='db',
  schema='schema'
)

date = datetime.date.today()

query = """
SELECT *
FROM MY_TABLE
WHERE LAST_UPDATE_DATE={}
LIMIT 100""".format(date)
res = con.cursor().execute(query).fetchall()
```

5. What did you expect to see?

All the data where `LAST_UPDATE_DATE` = datetime.date.today()

6. What did you see instead?

The following error

```
ProgrammingError: 001038 (22023): SQL compilation error:
Can not convert parameter '(2019 - 9) - 7' of type [NUMBER(6,0)] into expected type [DATE]
```

I also tried using 

`WHERE LAST_UPDATE_DATE=("TIMESTAMP_TZ", {})` from googling around but that didn't work. I don't really know what I'm doing...

It seems like all the resources involved `INSERT` but I'm trying to filter on it

7. Can you set logging to DEBUG and collect the logs?

No, I don't have access to the actual machine where the DB is

**Comment by smtakeda** [comment]
Bind variable using `?` placeholder:
```
import snowflake.connector
import datetime
snowflake.connector.paramstyle = 'qmark'
con = snowflake.connector.connect(
  user='user',
  password='pwd',
  account='account',
  warehouse='wh',
  database='db',
  schema='schema'
)

cur = con.cursor()
con.cursor().execute("create or replace table t (c1 int, c2 date)")
con.cursor().execute("insert into t(c1,c2) values(1, current_date()),(2, '2019-01-20')")
for rec in con.cursor().execute("select * from t where c2=?",
    (datetime.date.today(),)):
    print(rec)
con.close()
```

`{}` is a placefolder for Python's string format function and not the same as binding.

**Comment by IanQS** [comment]
Thanks! 

I'm getting a 

`TypeError: not all arguments converted during string formatting`

when I try to run the following

```
print(con.cursor().execute(
    "select * FROM PROD.DATA_SCIENCE.VOLATILITY_MONITORING WHERE LAST_UPDATE_DATE=?",(date)
).fetchone())
```

Any intuition into what I might be doing wrong?

**Comment by smtakeda** [comment]
Ensure adding this right after import `snowflake.connector`:
```
snowflake.connector.paramstyle = 'qmark'
```

**Comment by IanQS** [comment]
Thank you so so much! I'm going to close this
