### ISSUE TITLE
query_result method throws KeyError u'rowtype' for long running queries

### ISSUE THREAD

**Issue by tanmaypatil1812** [snowflakedb/snowflake-connector-python#199]
1. What version of Python are you using (`python --version`)?
**Python 2.7**

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
**Linux-4.15.0-20-generic-x86_64-with-debian-buster-sid**

3. What are the component versions in the environment (`pip list`)? 
**snowflake-connector-python        1.6.5**

4. What did you do?
At the time of query execution on Snowflake, I need its query id. So I am using following code snippet:
```
cursor.execute(query, _no_results=True)
query_id = cursor.sfqid
cursor.query_result(query_id)
```
This code snippet working fine for small running queries. But for query which takes more than 40-45 seconds to execute, **query_result** function fails with KeyError u'rowtype'.

Stack trace:
```
File "snowflake/connector/cursor.py", line 631, in query_result
self._init_result_and_meta(data, _use_ijson)
File "snowflake/connector/cursor.py", line 591, in _init_result_and_meta
for column in data[u'rowtype']:
KeyError: u'rowtype'
```

5. What did you expect to see?
Above code snippet should work for long running queries.

6. What did you see instead?
Got KeyError **u'rowtype'**.

**Comment by smtakeda** [comment]
Sounds like the result set is not ready as the execution was not completed.
`_no_results=True` is temporary solution until providing a full async API.

**Comment by tanmaypatil1812** [comment]
When will we get full support for async API?
Currently is there any alternate way to do that?

**Comment by smtakeda** [comment]
I don't have exact timeline about async API but will be in the planning meeting...
A workaround is hit UI endpoint to get the query status, but I cannot guarantee it would continue working.
