### ISSUE TITLE
SNOW-1530499: Bump urllib3 version to 2.2.2

### ISSUE THREAD

**Issue by sfc-gh-dbouassida** [snowflakedb/snowflake-connector-python#1997]
### What is the current behavior?

The current version of `urllib3` used is `1.26.18`.

### What is the desired behavior?

Update the `urllib3` version to `2.2.2`.

### How would this improve `snowflake-connector-python`?

The main feature of interest in urllib3 2.2.2 is the support for decompression of zstd when the content-encoding header is set to zstd. This update will allow the connector to handle zstd-encoded content.

### References and other background

A PR with the new version will be created initially to check if all merge gates pass. This is primarily an experimental change to assess compatibility and improvements.

**Comment by sfc-gh-dszmolka** [comment]
<issue raised for tracking>

**Comment by jimmyxie-figma** [comment]
this is fixed in using python3.10
