### ISSUE TITLE
This project breaks boto3?

### ISSUE THREAD

**Issue by ivankixeye** [snowflakedb/snowflake-connector-python#2]
To repro:
```python
import snowflake.connector as snowflake_connector
import boto3

sqs = boto3.resource('sqs')

if __name__ == '__main__':
    queue = sqs.get_queue_by_name(QueueName='<queue-name>')
```
Will raise `snowflake.connector.errors.OperationalError: 254007: The certificate attached is not for OCSP signing.`

**Comment by smtakeda** [comment]
Yes, we learned the AWS SQS certification was updated recently and revealed an issue.
Fixed in https://github.com/snowflakedb/snowflake-connector-python/commit/ad6e8584a629acd5f88d08e188d5bef4b0901cfa

We'll release the next version this Thursday.

**Comment by ivankixeye** [comment]
Thank you!
