### ISSUE TITLE
SNOW-1538754: Update keyring upper bound

### ISSUE THREAD

**Issue by dwreeves** [snowflakedb/snowflake-connector-python#2001]
### What is the current behavior?

Keyring 25.x is not supported

### What is the desired behavior?

That keyring 25.x is supported

### How would this improve `snowflake-connector-python`?

Because I am using keyring 25.x

**Comment by sfc-gh-dszmolka** [comment]
hi - thanks for letting us know of this requirement and also for your contribution! the team will review.

**Comment by sfc-gh-aling** [comment]
PR merged: https://github.com/snowflakedb/snowflake-connector-python/pull/2004, the update shall be released this week
