### ISSUE TITLE
SNOW-1616500: Compatibility with urllib 2.2.2

### ISSUE THREAD

**Issue by GorbataiCristian** [snowflakedb/snowflake-connector-python#2016]
### What is the current behavior?

 snowflake-connector-python 3.12.0(latest version as of the creation of this issue) depends on urllib3<2.0.0 and >=1.21.1

### What is the desired behavior?

 snowflake-connector-python is compatible with urllib>2.0.0 (ideally 2.2.2)

### How would this improve `snowflake-connector-python`?

urllib3<2.0.0 has potential security issues on some operating systems.
![image](https://github.com/user-attachments/assets/ce1901e2-224a-4102-90f6-14da2555a469)

### References and other background

I noticed a different issue that has the same goal, meaning a potential upgrade to the urllib version([this one](https://github.com/snowflakedb/snowflake-connector-python/issues/1997)). However, the reason for the request was different.

**Comment by sfc-gh-dszmolka** [comment]
hi - thanks for raising this request. let's see how https://github.com/snowflakedb/snowflake-connector-python/pull/1998 fares.

**Comment by jimmyxie-figma** [comment]
can we bump it further to 2.2.3 we have dependency conflict with dagster and that what dagster is on

**Comment by sfc-gh-dszmolka** [comment]
closing as a duplicate of https://github.com/snowflakedb/snowflake-connector-python/issues/1997
