### ISSUE TITLE
update snowflake-connector-python-no-azure to latest version

### ISSUE THREAD

**Issue by dbachelder** [snowflakedb/snowflake-connector-python#202]
The snowflake connectorwithout azure deps is still on 1.7.11

https://pypi.org/project/snowflake-connector-python-no-azure/

Is this  package maintained by snowflake? Are there plans to update it to the latest verion?

**Comment by notkriswagner** [comment]
@dbachelder we are planning to release the snowflake connector where azure and boto are optional dependencies. See this issue: https://github.com/snowflakedb/snowflake-connector-python/issues/124

**Comment by dbachelder** [comment]
@notkriswagner that's great news! I don't suppose you have an approximate timing for that (Q3/Q4/2020, etc)

**Comment by notkriswagner** [comment]
We currently don't have an approximate timing for when this will land. I would guess sooner rather than later though. We'll update https://github.com/snowflakedb/snowflake-connector-python/issues/124 when this new functionality lands.

**Comment by dbachelder** [comment]
sounds good. closing this issue. thanks!
