### ISSUE TITLE
SNOW-1619390: Compatibility with cryptograph=43.0.0 

### ISSUE THREAD

**Issue by flowconic** [snowflakedb/snowflake-connector-python#2020]
### What is the current behavior?

snowflake-connector-python 3.12.0(latest version as of the creation of this issue) depends on cryptography<43.0.0

### What is the desired behavior?

snowflake-connector-python 3.12.0 compatible with cryptography=43.0.0

### How would this improve `snowflake-connector-python`?

Use latest patches and improvements and quickly able to address upcoming CVE security vulnerabilities. 

### References and other background

![image](https://github.com/user-attachments/assets/9648d9bb-0288-4ffc-921b-f18208d71c61)

**Comment by sfc-gh-aling** [comment]
thanks for reaching out!

I have a PR out to unpin cryptography: https://github.com/snowflakedb/snowflake-connector-python/pull/2021

**Comment by flowconic** [comment]
> thanks for reaching out!
> 
> I have a PR out to unpin cryptography: #2021

Amazing, thank you for jumping on this so quickly.

**Comment by sfc-gh-aling** [comment]
we have released v3.12.1 which unpins the cryptography dependency, please take a try!

**Comment by flowconic** [comment]
> we have released v3.12.1 which unpins the cryptography dependency, please take a try!

Thank you so much. We will do this week. 
Really appreciate the quick resolution.

**Comment by irikeish** [comment]
@sfc-gh-aling Could you please update the release note about cryptography dependency? Thanks.
