### ISSUE TITLE
Support other session parameters

### ISSUE THREAD

**Issue by countergram** [snowflakedb/snowflake-connector-python#203]
The JDBC docs note that any session parameter can be included in a connection string: https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#other-parameters

This would be useful in the Python connector as well. E.g. we try to keep query_tags on as many of our workloads as possible and would would like to make it part of all of our connection params by default.

Note - if this is already possible using the `kwargs` to connect, I wasn't able to get it to work with tagging.

**Comment by smtakeda** [comment]
Try this:
```
import snowflake.connector

con = snowflake.connector.connect(
    user='XXXX',
    password='XXXX',
    account='XXXX',
    session_parameters={
        'QUERY_TAG': 'HelloImHere',
    }
)
```

**Comment by countergram** [comment]
That worked - thank you. So I think this is a documentation issue.

**Comment by smtakeda** [comment]
Raised the JIRA to the documentation team.
