### ISSUE TITLE
Float loss of precision. I tried to insert a number like 0.12345678901 at real column but a received 0.123456789

### ISSUE THREAD

**Issue by ericksc** [snowflakedb/snowflake-connector-python#205]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.6.7

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Linux-4.9.184-linuxkit-x86_64-with-debian-buster-sid

3. What are the component versions in the environment (`pip list`)? 
Package                    Version
-------------------------- ---------
appdirs                    1.4.3
asn1crypto                 0.24.0
astroid                    2.2.5
atomicwrites               1.3.0
attrs                      19.1.0
awscli                     1.16.112
azure-common               1.1.23
azure-nspkg                2.0.0
azure-storage              0.36.0
backcall                   0.1.0
bleach                     3.1.0
blosc                      1.7.0
bokeh                      1.3.4
boto3                      1.9.102
botocore                   1.12.102
certifi                    2019.6.16
cffi                       1.12.3
chardet                    3.0.4
Click                      7.0
cloudpickle                0.8.0
colorama                   0.3.9
coverage                   4.5.3
croniter                   0.3.30
cryptography               2.7
Cython                     0.29.5
cytoolz                    0.10.0
dask                       2.3.0
decorator                  4.4.0
defusedxml                 0.5.0
distributed                2.3.0
docker                     4.0.2
docker-pycreds             0.4.0
docutils                   0.15.2
entrypoints                0.3
fsspec                     0.4.1
future                     0.17.1
heapdict                   1.0.0
idna                       2.8
ijson                      2.4
importlib-metadata         0.18
ipykernel                  5.1.2
ipython                    7.6.1
ipython-genutils           0.2.0
ipywidgets                 7.5.1
isort                      4.3.21
jedi                       0.15.1
Jinja2                     2.10.1
jmespath                   0.9.4
jsonschema                 3.0.2
jupyter                    1.0.0
jupyter-client             5.3.1
jupyter-console            6.0.0
jupyter-core               4.4.0
jupyterdevview             1.0.1
jupyterlab                 0.35.4
jupyterlab-server          0.2.0
jupyternotify              0.1.15
lazy-object-proxy          1.4.1
locket                     0.2.0
MarkupSafe                 1.1.1
marshmallow                3.0.0
marshmallow-oneofschema    2.0.1
mccabe                     0.6.1
mistune                    0.8.4
mock                       3.0.5
more-itertools             7.2.0
msgpack                    0.6.1
mypy-extensions            0.4.1
nbconvert                  5.6.0
nbformat                   4.4.0
notebook                   6.0.0
numexpr                    2.7.0
numpy                      1.17.0
nxpy                       16.0.0
olefile                    0.46
packaging                  19.0
pandas                     0.23.4
pandocfilters              1.4.2
parso                      0.5.1
partd                      1.0.0
pathlib2                   2.3.4
pendulum                   2.0.5
pexpect                    4.7.0
pickleshare                0.7.5
Pillow                     6.1.0
pip                        19.1.1
pluggy                     0.12.0
prefect                    0.6.0
prometheus-client          0.7.1
prompt-toolkit             2.0.9
psutil                     5.6.3
ptyprocess                 0.6.0
py                         1.8.0
pyasn1                     0.4.6
pycparser                  2.19
pycryptodomex              3.8.1
pydot                      1.4.1
pydotplus                  2.0.2
Pygments                   2.4.2
pyinstrument               3.0.3
pyinstrument-cext          0.2.2
PyJWT                      1.7.1
pylint                     2.3.1
pyodbc                     4.0.26
pyOpenSSL                  19.0.0
pyparsing                  2.4.2
pyrsistent                 0.15.4
PySocks                    1.7.0
pytest                     5.1.0
pytest-pylint              0.14.0
pytest-runner              5.1
python-dateutil            2.8.0
python-gnupg               0.4.4
python-slugify             3.0.3
pytz                       2019.2
pytzdata                   2019.2
PyYAML                     3.13
pyzmq                      18.0.2
qtconsole                  4.5.3
requests                   2.22.0
rsa                        3.4.2
s3transfer                 0.2.1
Send2Trash                 1.5.0
setuptools                 41.0.1
six                        1.12.0
snowflake-connector-python 1.8.5
sortedcontainers           2.1.0
sqlparse                   0.3.0
stackprinter               0.2.3
tables                     3.5.2
tabulate                   0.8.3
tblib                      1.4.0
terminado                  0.8.2
testpath                   0.4.2
text-unidecode             1.2
toml                       0.10.0
toolz                      0.10.0
tornado                    6.0.3
traitlets                  4.3.2
typed-ast                  1.4.0
typing                     3.6.4
typing-extensions          3.7.4
Unidecode                  1.1.1
urllib3                    1.24.3
wcwidth                    0.1.7
webencodings               0.5.1
websocket-client           0.56.0
wheel                      0.33.6
widgetsnbextension         3.5.1
wrapt                      1.11.2
xlrd                       1.2.0
zict                       1.0.0
zipp                       0.5.2

4. What did you do?
I am using snowflake-connector-python 1.8.5  
I am getting float loss precision when  I tried to insert a number like 0.12345678901 at real column but a received 0.123456789.  is it a known issue?  

5. What did you expect to see?

Insert number with more than 13 to 17 decimal digits

6. What did you see instead?
Lost precision:
I tried to insert a number like 0.12345678901 at real column but a received 0.123456789.

**Comment by smtakeda** [comment]
yes, this is a known precision issue as the data is transmitted from drivers to the server in JSON. There is a plan to address this but ETA is unknown.
