### ISSUE TITLE
SNOW-1854999: No documentation for show_progress_bar option

### ISSUE THREAD

**Issue by vineelsai26** [snowflakedb/snowflake-connector-python#2118]
### What is the current behavior?

Currently, the flag for `show_progress_bar` has no documentation, at least none that I could find. If there is one, can anyone point me to it? If it doesn't exist, can anyone provide me with an example of how to use it?

<img width="587" alt="image" src="https://github.com/user-attachments/assets/5a43b4f3-de32-49b1-9473-99aeb706ed9f" />

### What is the desired behavior?

A documentation page where the info about how to use the flag should exist

### How would this improve `snowflake-connector-python`?

Improves the ease of use of the module

**Comment by sfc-gh-sghosh** [comment]
Hello @vineelsai26 ,

Thanks for raising the question.
The parameter 'show_progress_bar' is for internal file transfer status, its not available for public users to use. Its purely for purpose only, since its internal, there is no public documentation

Regards,
Sujan
