### ISSUE TITLE
Installing snowflake requires cython even when ENABLE_EXT_MODULES is false

### ISSUE THREAD

**Issue by beckjake** [snowflakedb/snowflake-connector-python#212]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
`Python 3.7.4`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
`Linux-4.9.184-linuxkit-x86_64-with`

3. What are the component versions in the environment (`pip list`)? 
```
/ # pip list
Package    Version
---------- -------
pip        19.2.3
setuptools 41.2.0
wheel      0.33.6
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

1) make this Dockerfile:
```
FROM python:3.7-alpine
RUN apk add --no-cache build-base libffi-dev openssl-dev
RUN pip install snowflake-connector-python
```
2) run `docker build .`

5. What did you expect to see?
I expected snowflake to install!

6. What did you see instead?
```
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z73b_b7g/pyarrow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z73b_b7g/pyarrow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-z73b_b7g/pyarrow/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z73b_b7g/pyarrow/setup.py", line 29, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

7. Can you set logging to DEBUG and collect the logs?
We don't get that far.

Looking through the code, I think the fix for this is to only add `pyarrow` to `install_requires` if `isBuildExtEnabled == 'true'`.

**Comment by howryu** [comment]
@beckjake Thanks for reporting. There is a plan to move pyarrow to optional dependency.

**Comment by LyleScott** [comment]
@howryu any idea of a timeline for this? snowflake connector seems completely broken for 2.x for similar reasons as above.

**Comment by smtakeda** [comment]
ETA is the end of Oct.

**Comment by howryu** [comment]
@Janatbek Please use 1.9.1 for now. Sorry for the inconvenience.

**Comment by smtakeda** [comment]
v2.0.2 is released.
