### ISSUE TITLE
None value instead of having text value while querying SNOWFLAKE.information_schema.TABLE_STORAGE_METRICS

### ISSUE THREAD

**Issue by GetheBeber** [snowflakedb/snowflake-connector-python#217]
Python 3.6.1

Package                    Version
-------------------------- ---------
APScheduler                3.5.1
asn1crypto                 0.24.0
azure-common               1.1.23
azure-storage-blob         2.1.0
azure-storage-common       2.1.0
boto3                      1.6.1
botocore                   1.9.1
certifi                    2017.11.5
cffi                       1.12.3
chardet                    3.0.4
cryptography               2.7
cycler                     0.10.0
docutils                   0.14
et-xmlfile                 1.0.1
future                     0.17.1
idna                       2.6
ijson                      2.5.1
jdcal                      1.3
jmespath                   0.9.3
matplotlib                 2.0.2
numpy                      1.17.2
openpyxl                   2.4.9
pandas                     0.21.0
patsy                      0.4.1
pg8000                     1.11.0
pip                        19.2.3
psycopg2                   2.7.4
pyarrow                    0.15.0
pycparser                  2.19
pycryptodomex              3.9.0
PyJWT                      1.7.1
pymongo                    3.5.1
pyodbc                     4.0.17
pyOpenSSL                  19.0.0
pyparsing                  2.2.0
python-dateutil            2.6.1
pytz                       2017.2
requests                   2.18.4
retrying                   1.3.3
s3transfer                 0.1.13
schedule                   0.5.0
scipy                      1.0.0
setuptools                 28.8.0
six                        1.10.0
snowflake-connector-python 2.0.1
statsmodels                0.8.0
tzlocal                    1.5.1
urllib3                    1.22

I tried to get data from SNOWFLAKE.information_schema.TABLE_STORAGE_METRICS through snowflake-connector-python with a select instruction.

I expected same data as in Snowflake interface but ,"None" value is returned instead of text value.

thanks for help

Regards

Bertrand.

**Comment by smtakeda** [comment]
Can you please double check the role? ACCOUNTADMIN, for example, has the privilege to access the view.
```
use role ACCOUNTADMIN;
select * from SNOWFLAKE.information_schema.TABLE_STORAGE_METRICS;
```

**Comment by GetheBeber** [comment]
Hello

my bad, I was on the bad role.

Sorry for the inconvenience.

Bertrand.
