### ISSUE TITLE
Error on 2.0.3: ssl_wrap_socket_with_ocsp() got an unexpected keyword argument 'cert_reqs'

### ISSUE THREAD

**Issue by VSorokoumov** [snowflakedb/snowflake-connector-python#228]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
**3.5.2**

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
**Linux-4.15.0-1050-azure-x86_64-with-Ubuntu-16.04-xenial**

3. What are the component versions in the environment (`pip list`)? 
**ansi2html                          1.1.1                 
asn1crypto                         1.2.0                 
azure-common                       1.1.23                
azure-storage-blob                 2.1.0                 
azure-storage-common               2.1.0                 
backports.shutil-get-terminal-size 1.0.0                 
boto                               2.42.0                
boto3                              1.10.8                
botocore                           1.13.8                
brewer2mpl                         1.4.1                 
certifi                            2019.3.9              
cffi                               1.13.2                
chardet                            2.3.0                 
colorama                           0.3.7                 
configobj                          5.0.6                 
cryptography                       2.5                   
cycler                             0.10.0                
Cython                             0.24.1                
decorator                          4.0.10                
docutils                           0.14                  
enum34                             1.1.6                 
et-xmlfile                         1.0.1                 
freetype-py                        1.0.2                 
funcsigs                           1.0.2                 
fusepy                             2.0.4                 
future                             0.18.2                
ggplot                             0.6.8                 
html5lib                           0.999                 
idna                               2.8                   
ijson                              2.5.1                 
ipaddress                          1.0.16                
ipython                            2.2.0                 
ipython-genutils                   0.1.0                 
jdcal                              1.2                   
Jinja2                             2.8                   
jmespath                           0.9.0                 
llvmlite                           0.13.0                
lxml                               3.6.4                 
MarkupSafe                         0.23                  
matplotlib                         1.5.3                 
mpld3                              0.2                   
msgpack-python                     0.4.7                 
ndg-httpsclient                    0.3.3                 
numba                              0.28.1                
numpy                              1.15.0                
openpyxl                           2.3.2                 
oscrypto                           1.1.0                 
pandas                             0.23.4                
pathlib2                           2.1.0                 
patsy                              0.4.1                 
pexpect                            4.0.1                 
pickleshare                        0.7.4                 
Pillow                             3.3.1                 
pip                                19.3.1                
ply                                3.9                   
prompt-toolkit                     1.0.7                 
psycopg2                           2.6.2                 
ptyprocess                         0.5.1                 
py4j                               0.10.3                
pyasn1                             0.1.9                 
pycparser                          2.14                  
pycryptodomex                      3.9.1                 
pycurl                             7.43.0                
Pygments                           2.1.3                 
pygobject                          3.20.0                
PyJWT                              1.7.1                 
pyOpenSSL                          19.0.0                
pyparsing                          2.2.0                 
pypng                              0.0.18                
python-apt                         1.1.0b1+ubuntu0.16.4.4
python-dateutil                    2.5.3                 
python-geohash                     0.8.5                 
pytz                               2016.6.1              
requests                           2.11.1                
s3transfer                         0.2.1                 
scikit-learn                       0.18.1                
scipy                              0.18.1                
scour                              0.32                  
setuptools                         40.6.2                
simplejson                         3.8.2                 
singledispatch                     3.4.0.3               
six                                1.10.0                
snowflake-connector-python         2.0.3                 
snowflake-sqlalchemy               1.1.16                
SQLAlchemy                         1.3.10                
ssh-import-id                      5.5                   
statsmodels                        0.6.1                 
traitlets                          4.3.0                 
unattended-upgrades                0.1                   
urllib3                            1.24.3                
virtualenv                         16.1.0                
wcwidth                            0.1.7                 
wheel                              0.33.4** 

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Install snowflkae python connector and snowflake sql alchemy and run a simple script running a query against snowflake.

import sqlalchemy
import snowflake.sqlalchemy 
import pandas as pd
import datetime

URL = snowflake.sqlalchemy.URL(account = 'xxxx',
                               user = 'xxxx',
                               password = 'xxxx',
                               database = 'xxxx',
                               schema = 'xxxx',
                               warehouse = 'xxxx',
                               role='xxxx')
engine = sqlalchemy.create_engine(URL)
df = pd.read_sql_query("SELECT 1", engine)
print(df)

5. What did you expect to see?
No error

6. What did you see instead?
ssl_wrap_socket_with_ocsp() got an unexpected keyword argument 'cert_reqs'

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```
**2019-11-04 11:46:25,216 - MainThread connection.py:178 - __init__() - INFO - Snowflake Connector for Python Version: 2.0.3, Python Version: 3.5.2, Platform: Linux-4.15.0-1050-azure-x86_64-with-Ubuntu-16.04-xenial
2019-11-04 11:46:25,217 - MainThread connection.py:478 - connect() - DEBUG - connect
2019-11-04 11:46:25,217 - MainThread connection.py:717 - __config() - DEBUG - __config
2019-11-04 11:46:25,218 - MainThread connection.py:792 - __config() - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2019-11-04 11:46:25,218 - MainThread converter.py:140 - __init__() - DEBUG - use_numpy: False
2019-11-04 11:46:25,218 - MainThread connection.py:643 - __open_connection() - DEBUG - REST API object was created: xxxx.west-europe.azure.snowflakecomputing.com:443
2019-11-04 11:46:25,219 - MainThread auth.py:129 - authenticate() - DEBUG - authenticate
2019-11-04 11:46:25,223 - MainThread auth.py:153 - authenticate() - DEBUG - assertion content: *********
2019-11-04 11:46:25,223 - MainThread auth.py:165 - authenticate() - DEBUG - account=xxxx, user=xxxx, database=xxxx, schema=xxxx, warehouse=xxxx, role=xxxx, request_id=c2d7954e-eac8-4815-a5ee-8ee24ee21489
2019-11-04 11:46:25,223 - MainThread auth.py:191 - authenticate() - DEBUG - body['data']: {'CLIENT_APP_ID': 'PythonConnector', 'LOGIN_NAME': 'xxxx', 'SVN_REVISION': None, 'CLIENT_ENVIRONMENT': {'PYTHON_VERSION': '3.5.2', 'APPLICATION': 'PythonConnector', 'PYTHON_COMPILER': 'GCC 5.4.0 20160609', 'OS': 'Linux', 'OS_VERSION': 'Linux-4.15.0-1050-azure-x86_64-with-Ubuntu-16.04-xenial', 'PYTHON_RUNTIME': 'CPython', 'OCSP_MODE': 'FAIL_OPEN'}, 'ACCOUNT_NAME': 'xxxx', 'SESSION_PARAMETERS': {'AUTOCOMMIT': False, 'CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY': 900, 'CLIENT_PREFETCH_THREADS': 4}, 'CLIENT_APP_VERSION': '2.0.3'}
2019-11-04 11:46:25,224 - MainThread network.py:940 - _use_requests_session() - DEBUG - Active requests sessions: 1, idle: 0
2019-11-04 11:46:25,225 - MainThread network.py:639 - _request_exec_wrapper() - DEBUG - remaining request timeout: 120, retry cnt: 1
2019-11-04 11:46:25,225 - MainThread network.py:778 - _request_exec() - DEBUG - socket timeout: 60
2019-11-04 11:46:25,242 - MainThread network.py:953 - _use_requests_session() - DEBUG - Active requests sessions: 0, idle: 1**

**Comment by snowstakeda** [comment]
Upgrade `requests` to the latest one that doesn't have embedded `urllib3`:
```
pip install requests==2.22.0
```

**Comment by VSorokoumov** [comment]
Thanks, that has helped.
