### ISSUE TITLE
azure-storage-blob 12.0.0 breaks connector version 1.9.1

### ISSUE THREAD

**Issue by alexnastetsky** [snowflakedb/snowflake-connector-python#229]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

Python 2.7.15rc1

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Linux-3.10.0-514.21.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core

3. What are the component versions in the environment (`pip list`)? 

snowflake-connector-python==1.9.1
azure-common==1.1.23
azure-core==1.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.0.0
azure-storage-nspkg==3.1.0

4. What did you do?

import snowflake.connector

5. What did you expect to see?

no error

6. What did you see instead?

```
line 6, in <module>
    import snowflake.connector
  File "/home/etlprod/venv/di-measurements/lib/python2.7/site-packages/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/home/etlprod/venv/di-measurements/lib/python2.7/site-packages/snowflake/connector/connection.py", line 44, in <module>
    from .cursor import SnowflakeCursor, LOG_MAX_QUERY_LENGTH
  File "/home/etlprod/venv/di-measurements/lib/python2.7/site-packages/snowflake/connector/cursor.py", line 26, in <module>
    from .file_transfer_agent import (SnowflakeFileTransferAgent)
  File "/home/etlprod/venv/di-measurements/lib/python2.7/site-packages/snowflake/connector/file_transfer_agent.py", line 20, in <module>
    from .azure_util import SnowflakeAzureUtil
  File "/home/etlprod/venv/di-measurements/lib/python2.7/site-packages/snowflake/connector/azure_util.py", line 9, in <module>
    from azure.storage.blob import BlockBlobService
ImportError: cannot import name BlockBlobService
```

The fix was to uninstall azure-storage-blob 12.0.0 and install azure-storage-blob 2.1.0.

**Comment by VSorokoumov** [comment]
we experience the same issue with connector version 2.0.1.

Microsoft has released azure-storage-blob 12.0.0 on October, 31st - we have been facing the issue since, November 1st, 2019.

I guess the root cause for this is missing version specification for azure storage blob library dependency in setup.py.

 install_requires=[
        'azure-common',
        'azure-storage-blob',

So, everyone who rebuilds an environment will face this issue. We ran into this.

I would really appreciate if this could be improved in the future. 

Thank!

**Comment by rcramblit** [comment]
They have released a fix on [v2.0.3](https://github.com/snowflakedb/snowflake-connector-python/blob/v2.0.3/setup.py#L161)

A patch fix on the 1.9.x version would be very nice as well.

**Comment by snowstakeda** [comment]
Sorry but at the moment there is no plan to release v1.9.x for this issue.
Please try v2.0.3.

**Comment by guneetsinghbhatia** [comment]
v2.0.3 is also not working.
According to link below there is problem with v2.0.x and is recommended to use 1.9.1
I have tried to use previous version of azure-storage -blob but still facing the issue.
Here is Graph of dependencies from pipenv
snowflake-sqlalchemy==1.1.16
  - snowflake-connector-python [required: Any, installed: 1.9.1]
    - asn1crypto [required: <1.0.0, installed: 0.24.0]
    - azure-common [required: Any, installed: 1.1.23]
    - azure-storage-blob [required: Any, installed: 2.1.0]
      - azure-common [required: >=1.1.5, installed: 1.1.23]
      - azure-storage-common [required: ~=2.1, installed: 2.1.0]
        - azure-common [required: >=1.1.5, installed: 1.1.23]
        - cryptography [required: Any, installed: 2.8]
          - cffi [required: >=1.8,!=1.11.3, installed: 1.13.2]
            - pycparser [required: Any, installed: 2.19]
          - six [required: >=1.4.1, installed: 1.12.0]
        - python-dateutil [required: Any, installed: 2.6.1]
          - six [required: >=1.5, installed: 1.12.0]
        - requests [required: Any, installed: 2.22.0]
          - certifi [required: >=2017.4.17, installed: 2019.9.11]
          - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
          - idna [required: >=2.5,<2.9, installed: 2.8]
          - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.6]

error message in lambda 
cannot import name 'BlockBlobService': ImportError
Traceback (most recent call last):
File "/var/task/handler.py", line 602, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 245, in lambda_handler
handler = cls()
File "/var/task/handler.py", line 139, in __init__
self.app_module = importlib.import_module(self.settings.APP_MODULE)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/var/task/application.py", line 2, in <module>
from api import create_app
File "/var/task/api/__init__.py", line 4, in <module>
from api.models.db import db
File "/var/task/api/models/__init__.py", line 1, in <module>
from .db import db
File "/var/task/api/models/db.py", line 3, in <module>
from api.settings.default import SQLALCHEMY_DATABASE_SCHEMA
File "/var/task/api/settings/default.py", line 2, in <module>
from snowflake.sqlalchemy import URL
File "/var/task/snowflake/sqlalchemy/__init__.py", line 8, in <module>
from . import snowdialect
File "/var/task/snowflake/sqlalchemy/snowdialect.py", line 25, in <module>
from snowflake.connector.constants import UTF8
File "/var/task/snowflake/connector/__init__.py", line 21, in <module>
from .connection import SnowflakeConnection
File "/var/task/snowflake/connector/connection.py", line 44, in <module>
from .cursor import SnowflakeCursor, LOG_MAX_QUERY_LENGTH
File "/var/task/snowflake/connector/cursor.py", line 26, in <module>
from .file_transfer_agent import (SnowflakeFileTransferAgent)
File "/var/task/snowflake/connector/file_transfer_agent.py", line 20, in <module>
from .azure_util import SnowflakeAzureUtil
File "/var/task/snowflake/connector/azure_util.py", line 9, in <module>
from azure.storage.blob import BlockBlobService
ImportError: cannot import name 'BlockBlobService'

**Comment by guneetsinghbhatia** [comment]
@snowstakeda when using v2.0.3 I am encountering below error message

No module named 'snowflake.sqlalchemy': ModuleNotFoundError
Traceback (most recent call last):
File "/var/task/handler.py", line 602, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 245, in lambda_handler
handler = cls()
File "/var/task/handler.py", line 139, in __init__
self.app_module = importlib.import_module(self.settings.APP_MODULE)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/var/task/application.py", line 2, in <module>
from api import create_app
File "/var/task/api/__init__.py", line 4, in <module>
from api.models.db import db
File "/var/task/api/models/__init__.py", line 1, in <module>
from .db import db
File "/var/task/api/models/db.py", line 3, in <module>
from api.settings.default import SQLALCHEMY_DATABASE_SCHEMA
File "/var/task/api/settings/default.py", line 2, in <module>
from snowflake.sqlalchemy import URL
ModuleNotFoundError: No module named 'snowflake.sqlalchemy'

**Comment by snowstakeda** [comment]
My working pip list is this:
```
>pip list
Package                    Version  
-------------------------- ---------
asn1crypto                 1.2.0    
azure-common               1.1.23   
azure-storage-blob         2.1.0    
azure-storage-common       2.1.0    
boto3                      1.10.9   
botocore                   1.13.9   
certifi                    2019.9.11
cffi                       1.13.2   
chardet                    3.0.4    
cryptography               2.8      
docutils                   0.15.2   
future                     0.18.2   
idna                       2.8      
ijson                      2.5.1    
jmespath                   0.9.4    
oscrypto                   1.1.0    
pip                        19.3.1   
pycparser                  2.19     
pycryptodomex              3.9.1    
PyJWT                      1.7.1    
pyOpenSSL                  19.0.0   
python-dateutil            2.8.0    
pytz                       2019.3   
requests                   2.22.0   
s3transfer                 0.2.1    
setuptools                 41.1.0   
six                        1.12.0   
snowflake-connector-python 2.0.3    
snowflake-sqlalchemy       1.1.16   
SQLAlchemy                 1.3.10   
urllib3                    1.24.3   
```

and the sample code:
```
#!/usr/bin/env python
import logging
for logger_name in ['snowflake.connector','botocore']:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.FileHandler('log')
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)


import os
import snowflake.connector
from snowflake.connector.file_transfer_agent import SnowflakeProgressPercentage

from snowflake.sqlalchemy import URL
from sqlalchemy import *

engine = create_engine(URL(
    account='ACCOUNT',
    user='USER',
    password='PASSWORD',
    database='DATABASE',
    schema='SCHEMA',
    warehouse='WAREHOUS',
    ),
)
...
engine.dispose()
```

**Comment by guneetsinghbhatia** [comment]
Have you tried deploying on AWS Lambda?

**Comment by snowstakeda** [comment]
Verified it worked.

```
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine

def lambda_handler(event, context):
    engine = create_engine(URL(
        account='ACCOUNT',
        user='USER',
        password='PASSWORD',
    ))
    con = engine.connect()
    print("connected")
    con.close()
    engine.dispose()
```

```
#!/bin/bash -e

# blindly clean up from previous executions if they exist
rm -rf lambda_function
rm -f lambda_function.zip
python3.6 -m venv lambda_function
source lambda_function/bin/activate
pip install --upgrade pip
pip install --upgrade snowflake-connector-python
pip install --upgrade snowflake-sqlalchemy
zip -9 lambda_function.zip lambda_function.py
touch $VIRTUAL_ENV/lib/python3.6/site-packages/snowflake/__init__.py
DIR=`pwd`
cd $VIRTUAL_ENV/lib/python3.6/site-packages
zip -r9 $DIR/lambda_function.zip .
cd $VIRTUAL_ENV/lib64/python3.6/site-packages
zip -r9 $DIR/lambda_function.zip .
```

```
>pip list
Package                    Version  
-------------------------- ---------
asn1crypto                 1.2.0    
azure-common               1.1.23   
azure-storage-blob         2.1.0    
azure-storage-common       2.1.0    
boto3                      1.10.10  
botocore                   1.13.10  
certifi                    2019.9.11
cffi                       1.13.2   
chardet                    3.0.4    
cryptography               2.8      
docutils                   0.15.2   
future                     0.18.2   
idna                       2.8      
ijson                      2.5.1    
jmespath                   0.9.4    
oscrypto                   1.1.0    
pip                        19.3.1   
pycparser                  2.19     
pycryptodomex              3.9.1    
PyJWT                      1.7.1    
pyOpenSSL                  19.0.0   
python-dateutil            2.8.0    
pytz                       2019.3   
requests                   2.22.0   
s3transfer                 0.2.1    
setuptools                 36.5.0   
six                        1.13.0   
snowflake-connector-python 2.0.3    
snowflake-sqlalchemy       1.1.16   
SQLAlchemy                 1.3.10   
urllib3                    1.24.3   
```

By any chance, you don't have `touch $VIRTUAL_ENV/lib/python3.6/site-packages/snowflake/__init__.py` ?

**Comment by guneetsinghbhatia** [comment]
No I have not touched. But when I go inside snowflake folder __init__.py file is missing

**Comment by guneetsinghbhatia** [comment]
My Snowflake folder has two sub folders connectors and sqlalchemy.

Also I have snowflake = "==0.0.3" in my pipenv file. Will this make any difference?

**Comment by snowstakeda** [comment]
@guneetsinghbhatia because `snowflake` is a namespace package, it cannot have `__init__.py`
https://www.python.org/dev/peps/pep-0420/
But Python on AWS lambda doesn't recognize namespace package, so `__init__.py` needs to be added.

**Comment by us-shergill** [comment]
> Verified it worked.
> 
> ```
> from snowflake.sqlalchemy import URL
> from sqlalchemy import create_engine
> 
> def lambda_handler(event, context):
>     engine = create_engine(URL(
>         account='ACCOUNT',
>         user='USER',
>         password='PASSWORD',
>     ))
>     con = engine.connect()
>     print("connected")
>     con.close()
>     engine.dispose()
> ```
> 
> ```
> #!/bin/bash -e
> 
> # blindly clean up from previous executions if they exist
> rm -rf lambda_function
> rm -f lambda_function.zip
> python3.6 -m venv lambda_function
> source lambda_function/bin/activate
> pip install --upgrade pip
> pip install --upgrade snowflake-connector-python
> pip install --upgrade snowflake-sqlalchemy
> zip -9 lambda_function.zip lambda_function.py
> touch $VIRTUAL_ENV/lib/python3.6/site-packages/snowflake/__init__.py
> DIR=`pwd`
> cd $VIRTUAL_ENV/lib/python3.6/site-packages
> zip -r9 $DIR/lambda_function.zip .
> cd $VIRTUAL_ENV/lib64/python3.6/site-packages
> zip -r9 $DIR/lambda_function.zip .
> ```
> 
> ```
> >pip list
> Package                    Version  
> -------------------------- ---------
> asn1crypto                 1.2.0    
> azure-common               1.1.23   
> azure-storage-blob         2.1.0    
> azure-storage-common       2.1.0    
> boto3                      1.10.10  
> botocore                   1.13.10  
> certifi                    2019.9.11
> cffi                       1.13.2   
> chardet                    3.0.4    
> cryptography               2.8      
> docutils                   0.15.2   
> future                     0.18.2   
> idna                       2.8      
> ijson                      2.5.1    
> jmespath                   0.9.4    
> oscrypto                   1.1.0    
> pip                        19.3.1   
> pycparser                  2.19     
> pycryptodomex              3.9.1    
> PyJWT                      1.7.1    
> pyOpenSSL                  19.0.0   
> python-dateutil            2.8.0    
> pytz                       2019.3   
> requests                   2.22.0   
> s3transfer                 0.2.1    
> setuptools                 36.5.0   
> six                        1.13.0   
> snowflake-connector-python 2.0.3    
> snowflake-sqlalchemy       1.1.16   
> SQLAlchemy                 1.3.10   
> urllib3                    1.24.3   
> ```
> 
> By any chance, you don't have `touch $VIRTUAL_ENV/lib/python3.6/site-packages/snowflake/__init__.py` ?

Hi I have a question . I tried your steps in AWs LAmbda . Instead of the version of the snowflake I'm getting null . I followed each and every step you had
