### ISSUE TITLE
Snowflake Docs Inaccurate for 2.0

### ISSUE THREAD

**Issue by aaronbannin** [snowflakedb/snowflake-connector-python#233]
Please answer these questions before submitting your issue. Thanks!

4. What did you do?
Looking at the [Snowflake documentation](https://docs.snowflake.net/manuals/user-guide/python-connector-example.html#connecting-using-the-default-authenticator), it still shows using the `snowflake.connector.connect` method instead of instantiating the `SnowflakeConnection` class.

5. What did you expect to see?
```
from snowflake.connector import SnowflakeConnection
con = SnowflakeConnection(
  user=USER,
  password=PASSWORD,
  account=ACCOUNT,
  warehouse=WAREHOUSE,
  database=DATABASE,
  schema=SCHEMA
)
```

**Comment by smtakeda** [comment]
No change was made for 2.0.
`snowflake.connector.connect()` still works. In fact, it is not intended that `SnowflakeConnection` is used by the application.

**Comment by aaronbannin** [comment]
Interesting. I made the change according to PyCharm linting warnings.
