### ISSUE TITLE
Set current schema in connection string containing special characters 

### ISSUE THREAD

**Issue by tamas-ac** [snowflakedb/snowflake-connector-python#236]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
   Python 3.6.5 (default, Jun 17 2018, 12:13:06) 
   [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
   Darwin-18.7.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 
    I'm using snowflake-connector-python 2.0.4    

4. What did you do?
     I want to set the current database and schema in the connection string, but it is not picked up if it contains special characters. The specified objects exists and I'm able to set the current database and schema with the "USE SCHEMA ..." statement once the connection is established.
    I think it is due to a missing urllib.parse.unqoute call before sending the string to authenticate()
```
   engine = create_engine(URL(
      account = '...',
      user = '...',
      password = '...',
      database = 'a/b/c',
      schema = 'd/e',
  ))

  conn = engine.connect()
```
   
5. What did you expect to see?
  [res for res in conn.execute("select current_warehouse(), current_database(), current_schema();")]
   [('...', 'a/b/c', 'd/e')]

6. What did you see instead?
    [res for res in conn.execute("select current_warehouse(), current_database(), current_schema();")]
   [('...', None, None)]

7. Can you set logging to DEBUG and collect the logs?
   Logs indicate that the string is not unescaped before passing it to authenticate, but authenticate will perform another url encoding on the string

    2019-11-13 10:53:59,915 - MainThread auth.py:165 - authenticate() - DEBUG - account=...., user=......, database=a%2Fb%2Fc,

**Comment by smtakeda** [comment]
I don't believe Snowflake supports `/` in the identifier.
```
snowman#REGRESS@TESTDB.TESTSCHEMA>create table 'a/b/c';
001003 (42000): SQL compilation error:                                          
syntax error line 1 at position 13 unexpected ''a/b/c''.
snowman#REGRESS@TESTDB.TESTSCHEMA>create table a/b/c;
001003 (42000): SQL compilation error:                                          
syntax error line 1 at position 14 unexpected '/'.
syntax error line 1 at position 14 unexpected '/'.
syntax error line 1 at position 16 unexpected '/'.
syntax error line 1 at position 18 unexpected ';'.
snowman#REGRESS@TESTDB.TESTSCHEMA>create database 'a/b/c';
001003 (42000): SQL compilation error:                                          
syntax error line 1 at position 16 unexpected ''a/b/c''.
snowman#REGRESS@TESTDB.TESTSCHEMA>create database 'a\/b\/c';
001003 (42000): SQL compilation error:                                          
syntax error line 1 at position 16 unexpected ''a\/b\/c''.
snowman#REGRESS@TESTDB.TESTSCHEMA>create database a\/b\/c;
001003 (42000): SQL compilation error:                                          
parse error line 1 at position 18 near '47'.
parse error line 1 at position 21 near '47'.
```

Are you able to create a database including slash?

**Comment by tamas-ac** [comment]
Yes, I can create the table if I escape the name with double quotes:

`create table "a/b/c"`

However, I tried out the below and it does not work either:


```
engine = create_engine(URL(
      account = '...',
      user = '...',
      password = '...',
      database = '"a/b/c"',
      schema = '"d/e"',
  ))

  conn = engine.connect()
```
, while  `use schema "a/b/c"."d/e"` does work.

**Comment by smtakeda** [comment]
hmm, I cannot create the table including slash..
```
>create table "a/b/c";
001003 (42000): SQL compilation error:                                          
syntax error line 1 at position 20 unexpected ';'.
```
Tried from snowsql and UI.

can you see the table by show command?
```
show tables;
```

**Comment by tamas-ac** [comment]
I think you're missing the columns specification, e.g.

`create table "a/b/c" (a number);`

However tables are not relevant for current database and schema, so these might be a better reference instead:

`create database "test/db/name";`
`create schema "test/db/name"."test/schema/name";`

**Comment by smtakeda** [comment]
ah, silly mistake... looking.

**Comment by smtakeda** [comment]
Looks like this is not connector issue but how the server treats the case of names. Can you try using "A/B/C" and set the dbname to either "a/b/c" or "A/B/C"?

**Comment by tamas-ac** [comment]
I think it's probably an SQLAlchemy issue, because I just found the following:

```
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine

engine = create_engine(URL(
    account = ...,
    user = dhuser1,
    password = ...,
    database = '"A/b/C"',
    schema = '"d/E"',
))
conn = engine.connect()
[res for res in conn.execute("select current_warehouse(), current_database(), current_schema();")]
>>> [('DHUSER1', None, None)]
```
but 
```
from snowflake.connector import connect

conn = connect(
    account = ...,
    user = 'dhuser1',
    password = ...,
    database = '"A/b/C"',
    schema = '"d/E"',
)
[res for res in conn.cursor().execute("select current_warehouse(), current_database(), current_schema();")]
>>> [('DHUSER1', 'A/b/C', 'd/E')]
```

I've created an "A/B/C"."D/E" and a "A/b/C"."d/E" schema to test, but even the SQLAlchemy connection can switch correctly:

```
[res for res in conn.execute("select current_warehouse(), current_database(), current_schema();")]
>>> [('DHUSER1', None, None)]
[res for res in conn.execute("use schema \"A/b/C\".\"d/E\"")]
>>> [('Statement executed successfully.',)]
[res for res in conn.execute("select current_warehouse(), current_database(), current_schema();")]
>>> [('DHUSER1', 'A/b/C', 'd/E')]
```

And finally, using the uppercase didn't work either:

```
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine

engine = create_engine(URL(
    account = ...,
    user = 'dhuser1',
    password = ...,
    database = '"A/B/C"',
    schema = '"D/E"',
    warehouse = 'dhuser1',
))
conn = engine.connect()
[res for res in conn.execute("select current_warehouse(), current_database(), current_schema();")]
>>> [('DHUSER1', None, None)]
```

**Comment by smtakeda** [comment]
ok, thanks for the update. Assigning this to the engineer in the team for further investigation.

**Comment by keller00** [comment]
This is actually a `snowflake-sqlalchemy` issue, I have fixed it and will be included in our next sqlalchemy release.

**Comment by tamas-ac** [comment]
Thanks guys, much appreciated!
