### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable" from cursor class;

### ISSUE THREAD

**Issue by gthelukuntla** [snowflakedb/snowflake-connector-python#243]
1. What version of Python are you using (`python --version`)?
2.7.16

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Linux-4.14.138-89.102.amzn1.x86_64-x86_64-with-glibc2.2.5

3. What are the component versions in the environment (`pip list`)? 
Package                    Version   Location                                                                                      
-------------------------- --------- ----------------------------------------------------------------------------------------------
alembic                    0.9.10    
amqp                       2.5.2     
apache-airflow             1.10.0    /usr/lib/virtualenv/airflow/1.10.0/lib/python2.7/site-packages/apache_airflow-1.10.0-py2.7.egg
appdirs                    1.4.3     
asn1crypto                 1.2.0     
attrs                      19.3.0    
awscli                     1.16.60   
azure-common               1.1.23    
azure-core                 1.0.0     
azure-nspkg                3.0.2     
azure-storage              0.34.0    
azure-storage-blob         2.1.0     
azure-storage-common       2.1.0     
azure-storage-nspkg        3.1.0     
Babel                      2.7.0     
backports-abc              0.5       
bcrypt                     3.1.4     
billiard                   3.5.0.5   
bleach                     2.1.4     
boto                       2.49.0    
boto3                      1.9.253   
botocore                   1.12.50   
cached-property            1.5.1     
cachetools                 3.1.1     
celery                     4.1.1     
certifi                    2019.9.11 
cffi                       1.13.2    
chardet                    3.0.4     
Click                      7.0       
colorama                   0.3.9     
configparser               3.5.0     
croniter                   0.3.25    
cryptography               2.8       
datadog                    0.12.0    
decorator                  4.4.1     
defusedxml                 0.6.0     
dill                       0.2.5     
docutils                   0.13.1    
enum34                     1.1.6     
et-xmlfile                 1.0.1     
Flask                      0.12.4    
Flask-Admin                1.4.1     
Flask-AppBuilder           1.12.1    
Flask-Babel                0.12.2    
Flask-Cache                0.13.1    
Flask-Caching              1.3.3     
Flask-Login                0.4.1     
Flask-OpenID               1.2.5     
Flask-SQLAlchemy           2.3.2     
flask-swagger              0.2.13    
Flask-WTF                  0.14.2    
flower                     0.9.2     
funcsigs                   1.0.0     
future                     0.16.0    
futures                    3.3.0     
gitdb2                     2.0.6     
GitPython                  2.1.11    
google-api-core            1.8.2     
google-api-python-client   1.6.3     
google-auth                1.0.1     
google-auth-httplib2       0.0.2     
google-auth-oauthlib       0.1.0     
google-cloud-bigquery      1.11.2    
google-cloud-container     0.2.1     
google-cloud-core          0.27.1    
google-compute-engine      2.8.13    
google-resumable-media     0.2.3     
googleads                  15.0.0    
googleapis-common-protos   1.5.3     
gunicorn                   19.9.0    
html5lib                   1.0.1     
httplib2                   0.12.0    
hvac                       0.5.0     
idna                       2.8       
ijson                      2.5.1     
inflection                 0.3.1     
ipaddress                  1.0.23    
iso8601                    0.1.12    
isodate                    0.6.0     
itsdangerous               1.1.0     
jdcal                      1.4.1     
Jinja2                     2.8       
jmespath                   0.9.4     
kombu                      4.6.3     
lockfile                   0.12.2    
lxml                       4.2.5     
Mako                       1.1.0     
Markdown                   2.6.6     
MarkupSafe                 1.1.1     
marshmallow                2.20.5    
marshmallow-sqlalchemy     0.18.0    
monotonic                  1.5       
msrest                     0.6.10    
mysql-connector            2.1.7     
MySQL-python               1.2.5     
ndg-httpsclient            0.5.1     
numpy                      1.16.5    
oauth2client               4.1.3     
oauthlib                   3.1.0     
openpyxl                   2.6.2     
ordereddict                1.1       
oscrypto                   1.1.0     
pandas                     0.23.4    
pandas-gbq                 0.2.0     
paramiko                   2.4.1     
pendulum                   1.4.4     
pip                        19.3.1    
prometheus-client          0.4.2     
protobuf                   3.10.0    
psutil                     4.4.2     
psycopg2                   2.7.3.1   
pyarrow                    0.13.0    
pyasn1                     0.4.7     
pyasn1-modules             0.2.7     
pycparser                  2.19      
pycryptodomex              3.9.4     
pydata-google-auth         0.1.3     
Pygments                   2.1.3     
PyJWT                      1.7.1     
PyNaCl                     1.3.0     
pyOpenSSL                  16.2.0    
python-daemon              2.1.2     
python-dateutil            2.7.5     
python-editor              1.0.4     
python-nvd3                0.15.0    
python-openid              2.2.5     
python-slugify             3.0.3     
pytz                       2019.3    
pytzdata                   2019.3    
PyYAML                     3.13      
qds-sdk                    1.9.8     
redis                      2.7.6     
requests                   2.22.0    
requests-oauthlib          1.3.0     
requests-toolbelt          0.9.1     
rsa                        3.4.2     
s3transfer                 0.2.1     
schedule                   0.5.0     
setproctitle               1.1.10    
setuptools                 41.6.0    
simple-salesforce          0.74.3    
simplejson                 3.16.0    
singledispatch             3.4.0.3   
six                        1.10.0    
smmap2                     2.0.5     
snakebite                  2.11.0    
snowflake-connector-python 2.0.4     
SQLAlchemy                 1.1.18    
statsd                     3.3.0     
suds-jurko                 0.6       
tabulate                   0.8.2     
tenacity                   5.0.2     
text-unidecode             1.2       
thrift                     0.9.3     
tornado                    5.1.1     
typing                     3.7.4.1   
tzlocal                    1.5.1     
unicodecsv                 0.14.1    
uritemplate                3.0.0     
urllib3                    1.24.3    
vine                       1.3.0     
webencodings               0.5.1     
Werkzeug                   0.14.1    
wheel                      0.33.6    
WTForms                    2.1       
xmltodict                  0.12.0    
zeep                       3.4.0     
zope.deprecation           4.3.0    

4. What did you do?
Initially i was on 1.7.8 version for a while but i restarted my airflow server and got into Blob issue to resolve that I tried 1.9.1 version and pined the azure-storage-blob==2.1.0 but it didn't work so i tried different version (2.0.1, 2.0.2, 2.0.3, 2.0.4) nothing is working for me. 
Tasks are running but once the sql execution is done i'm running into this cursor return iteration issue.

5. What did you expect to see?
Execute snowsql through this connector

6. What did you see instead?
"TypeError: 'NoneType' object is not iterable" from cursor class

**Comment by smtakeda** [comment]
How are you run snowsql from the connector? What is the version of SnowSQL?
```
snowsql -v
```

**Comment by gthelukuntla** [comment]
I'm using Airflow Hook and Operator to run the sql using the connector.

**Comment by gthelukuntla** [comment]
Found the root cause for this issue. We iterate on the cursor to log the snowflake response, since we have trailing whitespace characters at the end of the query the cursor is empty which is causing this issue.
Note that, Previously we were using 1.7.7 in this version tailing white spaces or extra new line character after the query worked fine but that's not the case with 2.0.3
