### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:snowflake in AWS Lambda Python 3.6

### ISSUE THREAD

**Issue by us-shergill** [snowflakedb/snowflake-connector-python#246]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.6
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

docker lambda environment
lambci/lambda

3. What are the component versions in the environment (`pip list`)? 
asn1crypto==1.2.0
azure-common==1.1.23
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
boto3==1.10.34
botocore==1.13.34
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
docutils==0.15.2
future==0.18.2
idna==2.8
ijson==2.5.1
jmespath==0.9.4
numpy==1.17.4
oscrypto==1.1.0
pandas==0.25.3
pycparser==2.19
pycryptodomex==3.9.4
PyJWT==1.7.1
pyOpenSSL==19.1.0
python-dateutil==2.8.0
pytz==2019.3
requests==2.22.0
s3transfer==0.2.1
six==1.13.0
snowflake-connector-python==2.1.0
snowflake-sqlalchemy==1.1.17
SQLAlchemy==1.3.11
urllib3==1.25.7

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine

def lambda_handler(event, context):
    engine = create_engine(URL(
        account='i',
        user='',
        password='',
    ))
    con = engine.connect()
    print("connected")
    results = con.execute('select current_version()').fetchone()
    print(results[0])
    con.close()
    engine.dispose()
    return results[0]

if __name__ == "__main__":
    lambda_handler(None,None)

5. What did you expect to see?
Successfully connect to snowflake . Running on my local mac environment is totally fine . I install the packages using pip in docker lambda and push to zip to aws lambda 3.6 .

6. What did you see instead?
{
  "errorMessage": "Can't load plugin: sqlalchemy.dialects:snowflake",
  "errorType": "NoSuchModuleError",
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      13,
      "lambda_handler",
    ],
7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by gaurcs** [comment]
@us-shergill How did you solve the issue?
