### ISSUE TITLE
fetch_pandas_all yields wrong results for NUMBER(38,x) fields

### ISSUE THREAD

**Issue by ludokriss** [snowflakedb/snowflake-connector-python#259]
Hi,

Came over an issue using the connector together with pandas. I have tried and tried to see if I have done something wrong, but I don't think so (but I at least, never know). 

1. What version of Python are you using (`python --version`)?
python 3.7.6
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Windows-10-10.0.18362-SP0
3. What are the component versions in the environment (`pip list`)? 
2.1.3
4. What did you do?
Basically this looks like an issue mainly with the decimal implementation. The problem is a difference in translating NUMBER(38,x) (only tried with x=10) from Snowflake to pandas, so using cur.fetch_pandas_all() vs pd.DataFrame(cur.fetchall(), columns={<columns>}) will not yield the same result. Specifically, most (if not all) columns with number(38,x>0) data type will show erroneous results for fetch_pandas_all. It may be a problem with pyarrow, but want to put it here so you know about it

5. What did you expect to see?
The same result
6. What did you see instead?
Different values when converted to a DataFrame
7. Can you set logging to DEBUG and collect the logs?
N/A

**Comment by howryu** [comment]
I don't think right now it would work with python3.8. As you said, we used pyarrow (https://pypi.org/project/pyarrow/#files), which does not have a 3.8 wheel file, so our python connector does not have a 3.8 wheel file(https://pypi.org/project/snowflake-connector-python/#files) , which means if you install snowflake python connector, it will install tarball, which does not have dynamic library required for arrow data format. So the query result is transfer back is json.

**Comment by ludokriss** [comment]
Sorry, managed to fat-finger that. I am actually using 3.7.6, updated the issue now. I can test on some other versions and on a mac as well.

**Comment by howryu** [comment]
I will try to reproduce it. It would be great if you can share your script as well.

**Comment by snowstakeda** [comment]
@ludokriss can you please try 2.2.0? We fixed an issue related to `cur.fetch_pandas_all()` that return wrong result for column type decimal (38, 10).
