### ISSUE TITLE
The connector can silently fail to connect to the requested database or schema

### ISSUE THREAD

**Issue by atrigent** [snowflakedb/snowflake-connector-python#26]
When connecting to snowflake, the `database` and `schema` parameters to the `connect` method (https://docs.snowflake.net/manuals/user-guide/python-connector-api.html#connect) can be silently ignored if they don't exist or the user does not have the required permissions on them. It seems to be possible to double-check with something like this:

```
conn = snowflake.connector.connect(
    ...,
    database='dbdoesnotexist',
    schema='schemadoesnotexist'
)

if conn.schema != 'schemadoesnoteixst' or conn._database != 'dbdoesnotexist':
    raise something
```

...but it feels like the connector should detect this case itself (and also, the `schema` and `_database` attributes are undocumented).

Then again, this is also how `snowsql` behaves, so maybe this is expected behavior?

**Comment by smtakeda** [comment]
Yes, that's how Python Connector and SnowSQL works as of today. Since the original implementation didn't check and raise errors, we have not changed it, since raising error/exception may break the existing customer code.

Similar issue/request came to JDBC, so let me think how to address this.

**Comment by atrigent** [comment]
If you don't want to break existing code, I'd be satisfied with a built-in way to activate the stricter behavior. Perhaps another connect parameter, or a method to raise an error on this case (similar to this: http://docs.python-requests.org/en/master/api/#requests.Response.raise_for_status)?

**Comment by smtakeda** [comment]
Adding `validate_default_parameters` to the connect string to control the behavior.

**Comment by smtakeda** [comment]
Committed the change.
