### ISSUE TITLE
Allow cloud-specific optional dependencies

### ISSUE THREAD

**Issue by sburns** [snowflakedb/snowflake-connector-python#265]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

3.7.5

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Darwin-18.7.0-x86_64-i386-64bit (but also Linux)

3. What are the component versions in the environment (`pip list`)? 

<details>
<pre>
Package                    Version   
-------------------------- ----------
appdirs                    1.4.3     
asn1crypto                 1.3.0     
atomicwrites               1.3.0     
attrs                      19.3.0    
azure-common               1.1.24    
azure-storage-blob         2.1.0     
azure-storage-common       2.1.0     
black                      19.3b0    
boltons                    20.0.0    
boto3                      1.9.253   
botocore                   1.12.253  
certifi                    2019.11.28
cffi                       1.13.2    
chardet                    3.0.4     
Click                      7.0       
cryptography               2.8       
docutils                   0.15.2    
face                       20.1.1    
future                     0.18.2    
glom                       19.10.0   
hvac                       0.9.6     
idna                       2.8       
ijson                      2.6.1     
importlib-metadata         1.5.0     
jmespath                   0.9.4     
more-itertools             8.2.0     
oscrypto                   1.2.0     
packaging                  20.1      
pip                        19.0.3    
pluggy                     0.13.1    
py                         1.8.1     
pycparser                  2.19      
pycryptodomex              3.9.6     
PyJWT                      1.7.1     
pyOpenSSL                  19.1.0    
pyparsing                  2.4.6     
pytest                     5.2.0     
python-dateutil            2.8.1     
pytz                       2019.3    
requests                   2.22.0    
s3transfer                 0.2.1     
setuptools                 40.8.0    
six                        1.14.0    
snowflake-connector-python 2.1.3     
snowflake-sqlalchemy       1.1.17    
SQLAlchemy                 1.3.13    
structlog                  19.2.0    
toml                       0.10.0    
urllib3                    1.24.3    
wcwidth                    0.1.8     
zipp                       2.1.0     
</pre>

</details>

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

`$ pip install snowflake-connector-python`

5. What did you expect to see?

I'd like to be able to specify [optional dependencies](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) to get cloud-specific packages. As it stands, this package installs boto3 (thereby including a bunch including botocore, s3transfer, etc) and azure-{common, storage-blob, storage-common}. For those on AWS, we don't need the Azure stuff, vice versa for those on Azure. For those working locally or not in a cloud, they get double-unwanted things!

I would like to be able to `$ pip install snowflake-connector-python[aws]==X.Y.Z` and specify a specific version w/ only AWS packages in our requirements.txt as well.

6. What did you see instead?

All cloud-specific packages get installed, no matter what.

7. Can you set logging to DEBUG and collect the logs?

(this is not worth logging)

**Comment by keller00** [comment]
Please see other open issues and PRs.
