### ISSUE TITLE
SNOW-139082: Extreme datetimes get mangled from Snowflake to pandas

### ISSUE THREAD

**Issue by RoyalTS** [snowflakedb/snowflake-connector-python#277]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

3.7.3

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Linux-4.15.0-1060-aws-x86_64-with-debian-buster-sid

3. What are the component versions in the environment (`pip list`)? 

```
pandas                          0.25.3
snowflake-connector-python       2.1.3
snowflake-sqlalchemy             1.2.0
```

4. What did you do?

```python
# %%
import pandas as pd
import numpy as np
import sqlalchemy as sa

# %% [markdown]
# # Snowflake Python Connector

# %%
db_config = dict(
    YOUR_CREDENTIALS_HERE
)

# %%
import snowflake.connector

con_sf = snowflake.connector.connect(**db_config)

# %%
cur = con_sf.cursor()
cur.execute(query_sf)
df_sfc = cur.fetch_pandas_all()

# %%
df_sfc.dtypes

# %%
# large datetime gets cast to np.datetime64 for which it is out of range
df_sfc

# %% [markdown]
# # Snowflake SQLAlchemy

# %%
from pnc_core import db

# %%
from snowflake.sqlalchemy import URL

engine_sf = sa.create_engine(URL(**db_config))

# %%
query_sf = """SELECT
    '2000-12-31 04:04:06.789'::TIMESTAMP x,
    '9999-12-31 04:04:06.789'::TIMESTAMP y
"""

# %%
df_sfe = pd.read_sql(query_sf, engine_sf)

# %%
df_sfe.dtypes

# %%
# a microsecond gets added to the datetime
df_sfe

# %% [markdown]
# # SQLite

# %%
import sqlite3

# %%
engine_sqlalchemy = sa.create_engine('sqlite:///test.db')

# %%
query_sqlite = """SELECT
    strftime('%Y-%m-%d %H:%M:%f', '2000-12-31 04:04:06.789') x,
    strftime('%Y-%m-%d %H:%M:%f', '9999-12-31 04:04:06.789') y
"""

df_sqlite = pd.read_sql(query_sqlite, engine_sqlalchemy)

# %%
df_sqlite.dtypes

# %%
df_sqlite
```
5. What did you expect to see?

The large date `9999-12-31 04:04:06.789` correctly transferred to pandas, either by keeping it as `object` or by casting it to `datetime` appropriately

6. What did you see instead?

Either an out-of-range date (Python connector) or a datetime that's off by a microsecond (SQLAlchemy dialect)

**Comment by RoyalTS** [comment]
possibly related to #266

**Comment by sfc-gh-mkeller** [comment]
@RoyalTS can you show me what you used to trigger the out-of-range date? I think your code is missing it's beginning.
On the positive side I fixed the off by one millisecond error, it is a problem with Python and you can see it by doing this:
```
from datetime import datetime
datetime.fromtimestamp(datetime(9999, 12, 31, 4, 4, 6, 789000).timestamp())
```
Damn you floating points...

**Comment by sfc-gh-mkeller** [comment]
So after a lot of digging we have pinpointed the issue.
https://github.com/python/cpython/blob/951ab58024de9b5a21f0b979cdbea51e1049d781/Lib/datetime.py#L1672
We calculate that this won't really be an issue unless you insert times around, or after 2200.
However, fixing this will make timestamp conversion ~3 times slower, so we are going to leave this for now.

Let's keep this issue open and please if anyone who experiences this issue please let us know what timestamp triggers it.

I'll include what converter worked for me the fastest that didn't use floats, but still it's about 3 times slower than our float converter.

If anyone wants to use this and is okay with it being slower, you can just replace the timestamp converters with something similar to this.

```python
def conv_precise(value):
    """This is the slower way to convert timestamp, but it is precise even with very big numbers"""
    microseconds = int(decimal.Decimal(value).scaleb(6))
    return (ZERO_EPOCH + timedelta(microseconds=microseconds)).astimezone(tzinfo)
```

**Comment by srdennett** [comment]
Just ran into this issue.  After some testing I found the error is triggered with a timestamp on or after 2262-04-11 23:47:17.000.

**Comment by sfc-gh-achandrasekaran** [comment]
To clean up and re-prioritize bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please re-create them. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response

**Comment by awal11** [comment]
Also run into it.
Leaving it closed does not seem a reasonable approach, this affects real users and leaves them clueless.

At minimum I would suggest: catching the exception "error: (snowflake.connector.errors.InterfaceError) 252005: 252005: Failed to convert current row, cause: int too big to convert" and rethrowing with a more useful message for investigation.

Going a bit further - if you can catch that exception - applying the slower code path as a second attempt - would be a huge improvement.
