### ISSUE TITLE
SNOW-141553: azure-storage-blob breaks version 2.2.1 (using azure-storage-file-datalake)

### ISSUE THREAD

**Issue by kapziel** [snowflakedb/snowflake-connector-python#285]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
`Python 3.8.0`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
`Windows-10-10.0.17763-SP0`

3. What are the component versions in the environment (`pip list`)? 
```
Package                     Version
--------------------------- ---------
adal                        1.2.2
asn1crypto                  1.3.0
astroid                     2.3.1
autopep8                    1.4.4
azure-common                1.1.24
azure-core                  1.2.2
azure-storage-blob          12.2.0
azure-storage-common        2.1.0
azure-storage-file-datalake 12.0.0b7
boto3                       1.11.17
botocore                    1.14.17
cached-property             1.5.1
certifi                     2019.9.11
cffi                        1.13.2
chardet                     3.0.4
colorama                    0.4.1
configparser                4.0.2
cryptography                2.8
docutils                    0.15.2
etl-utils                   0.1.11
humanize                    0.5.1
idna                        2.8
ijson                       2.6.1
isodate                     0.6.0
isort                       4.3.21
jmespath                    0.9.5
lazy-object-proxy           1.4.2
mccabe                      0.6.1
msrest                      0.6.11
msrestazure                 0.6.2
nltk                        3.2.4
numpy                       1.17.3
oauthlib                    3.1.0
oscrypto                    1.2.0
pandas                      1.0.1
pip                         20.0.2
preprocessing               0.1.13
progressbar                 2.2
pycodestyle                 2.5.0
pycparser                   2.19
pycryptodomex               3.9.7
PyJWT                       1.7.1
pylint                      2.4.2
pyOpenSSL                   19.1.0
pysingleton                 0.2.1
python-dateutil             2.8.0
pytz                        2019.3
requests                    2.22.0
requests-oauthlib           1.3.0
s3transfer                  0.3.3
setuptools                  45.1.0
six                         1.12.0
snowflake-connector-python  2.2.1
sphinx-rtd-theme            0.2.4
termcolor                   1.1.0
urllib3                     1.25.6
wrapt                       1.11.2
xmltodict                   0.12.0

```

4. What did you do?

Running snowflake-connector along with azure-storage-file-datalake which requires the latest version of azure-storage-blob produces incompatibilities.

5. What did you expect to see?
Harmony between libraries

6. What did you see instead?
```
ERROR: snowflake-connector-python 2.2.1 has requirement azure-storage-blob<12.0.0, but you'll have azure-storage-blob 12.2.0 which is incompatible.
```

**Comment by kevinpauli** [comment]
Yeah I have some code that needs to access both snowflake and azure.  Now I have to go rewrite all my azure-related code, to make it compatible with the ancient version of azure-storage-blob mandated by snowflake...  and I don't even use the snowflake-azure integration.  Would be nice to have a way to not even load that stuff in snowflake.connector.azure_util.py

**Comment by keller00** [comment]
Hi @kevinpauli you could also use that time to submit a PR to update our implementation to the new azure code (since it is a complete redesign of the library).
That'd probably be a better use of your time! 👍

**Comment by kevinpauli** [comment]
I might if I used the snowflake-azure integration... but I don't.  Would be nice to make it optional, like "pip install snowflake[azure]" if we wanted it

**Comment by keller00** [comment]
Then you can just ignore the warning.

**Comment by kevinpauli** [comment]
No, I couldn't ignore it.  Because microsoft changed the class names between versions 2 and 12, It actually failed at runtime with a failed import, with snowflake connector code attempting to load classes from the way things used to be named in azure-storage-blob 2, while I had azure-storage-blob 12 .  

Eventually I capitulated and rewrote my code to use the older azure-storage-blob 2 classes.
