### ISSUE TITLE
'NoneType' object has no attribute 'upload_file' when running PUT command

### ISSUE THREAD

**Issue by daniel-sali** [snowflakedb/snowflake-connector-python#29]
Hi,

When uploading a couple of hundred ORC data files with sizes around 50-100MB with a single PUT statement, multiple uploads fail with a `'NoneType' object has no attribute 'upload_file'` error.

In the debug log, the error happens when an S3 HeadObject request is performed with a return code  of 400 - Bad request, the stack trace is:
```
Traceback (most recent call last):
  File "snowflake/connector/file_transfer_agent.py", line 330, in upload_one_file
  File "snowflake/connector/s3_util.py", line 634, in upload_one_file_to_s3_with_retry
  File "snowflake/connector/s3_util.py", line 193, in upload_one_file_to_s3
AttributeError: 'NoneType' object has no attribute 'upload_file'
```
This error happens because in in line 193 of `s3_util.py`, the `akey` variable is `None`, because when it is initialised in line 153 by the 
`akey = SnowflakeS3Util.get_s3_file_object(meta, meta[u'dst_file_name'])`
statement, the `get_s3_file_object` function returns None in line 660 in case of a metadata retrieval error (return code 400), which happened during the request.

**Comment by smtakeda** [comment]
Thanks for reporting an issue. Looking into this.

**Comment by smtakeda** [comment]
Version 1.4.2 will be pushed this Thursday.
