### ISSUE TITLE
SNOW-146730: Support pandas 1.0

### ISSUE THREAD

**Issue by xhochy** [snowflakedb/snowflake-connector-python#291]
Currently `pandas` is pinned to `<1` in https://github.com/snowflakedb/snowflake-connector-python/blob/fbd29c07c25043dd07c69abd412fea276203d606/setup.py#L230 What is the reason for this? Can you support newer pandas versions?

**Comment by keller00** [comment]
Hi @xhochy it failed our internal testing before, but recent testing revealev that this was not the case anymore. I blame either flaky tests, or some sort of dependency error (which happens fairly often).
Anyway, I reran tests last week and updated our dependency to support the newest pandas release now. Watch out for this in the next release.

**Comment by RoyalTS** [comment]
What's the ETA for the next release?
