### ISSUE TITLE
SNOW-147625: compatiblity issues with azure-storage-blob from snowflake and azure

### ISSUE THREAD

**Issue by tanikella** [snowflakedb/snowflake-connector-python#292]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.8.2
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Windows-10-10.0.17134-SP0
3. What are the component versions in the environment (`pip list`)? 
Package                    Version
-------------------------- ----------
asn1crypto                 1.3.0
astroid                    2.3.3
attrs                      19.3.0
azure-common               1.1.24
azure-core                 1.3.0
azure-storage-blob         12.0.0
azure-storage-common       2.1.0
azure-storage-file         2.1.0
azure-storage-file-share   12.1.1
backcall                   0.1.0
bitstring                  3.1.6
bleach                     3.1.3
boto3                      1.11.17
botocore                   1.14.17
certifi                    2019.11.28
cffi                       1.13.2
chardet                    3.0.4
click                      7.1.1
colorama                   0.4.3
cryptography               2.8
cx-Oracle                  7.3.0
decorator                  4.4.2
defusedxml                 0.6.0
docutils                   0.15.2
entrypoints                0.3
future                     0.18.2
idna                       2.8
ijson                      2.6.1
ipykernel                  5.1.4
ipython                    7.13.0
ipython-genutils           0.2.0
isodate                    0.6.0
isort                      4.3.21
jedi                       0.16.0
Jinja2                     2.11.1
jmespath                   0.9.5
json5                      0.9.3
jsonschema                 3.2.0
jupyter-client             6.0.0
jupyter-core               4.6.3
jupyterlab                 2.0.1
jupyterlab-server          1.0.7
lazy-object-proxy          1.4.3
MarkupSafe                 1.1.1
mccabe                     0.6.1
mistune                    0.8.4
msrest                     0.6.11
nbconvert                  5.6.1
nbformat                   5.0.4
notebook                   6.0.3
oauthlib                   3.1.0
oscrypto                   1.2.0
pandocfilters              1.4.2
parso                      0.6.2
pickleshare                0.7.5
pip                        20.0.2
prometheus-client          0.7.1
prompt-toolkit             3.0.4
pyasn1                     0.4.8
pyasn1-modules             0.2.8
pycparser                  2.19
pycryptodomex              3.9.7
Pygments                   2.6.1
PyJWT                      1.7.1
pylint                     2.4.4
pyodbc                     4.0.30
pyOpenSSL                  19.1.0
pyrsistent                 0.15.7
python-dateutil            2.8.1
python-ldap                3.2.0
pytz                       2019.3
pywin32                    227
pywinpty                   0.5.7
pyzmq                      19.0.0
requests                   2.22.0
requests-oauthlib          1.3.0
ruamel.yaml                0.16.10
ruamel.yaml.clib           0.2.0
s3transfer                 0.3.3
Send2Trash                 1.5.0
setuptools                 41.2.0
six                        1.14.0
snowflake-connector-python 2.2.2
snowflake-sqlalchemy       1.2.1
SQLAlchemy                 1.3.13
terminado                  0.8.3
testpath                   0.4.4
tornado                    6.0.4
traitlets                  4.3.3
urllib3                    1.25.8
wcwidth                    0.1.8
webencodings               0.5.1
wrapt                      1.11.2
4. What did you do?
from azure.storage.blob import BlobServiceClient

uploading files to Azure blob Container requires 'BlobServiceClient' from azure.storage.blob
this is missing from azure.storage.blob provided from snowflake-connector-python
so I installed azure-storage-blob==12.0.0 (this is only compatible version with snowflake)

this messed up 'BlockBlobService' from 'azure.storage.blob', of snowflake-connector-python
now my python scripts are not working, upgrading snowflake-connector-python gave this error.

ERROR: snowflake-connector-python 2.2.2 has requirement azure-storage-blob<12.0.0, but you'll have azure-storage-blob 12.0.0 which is incompatible.

5. What did you expect to see?
azure-storage-blob supporting both BlobServiceClient and BlockBlobService

6. What did you see instead?
ERROR: snowflake-connector-python 2.2.2 has requirement azure-storage-blob<12.0.0, but you'll have azure-storage-blob 12.0.0 which is incompatible.

**Comment by jakezatecky** [comment]
This relates to #225.

The developers have pinned the old `v2.1.0` version and it is incompatible with `v12`. If you are using `v12` in your own code, you will have to downgrade to `v2.1.0` (and make adjustments in your code).

Preferably, the Snowflake connector would be updated to use the latest version of `azure-storage-blob` such that developers are not forced to use the outdated version when you want to interact with Azure.

**Comment by tanikella** [comment]
thanks @jakezatecky, I'll close this defect as duplicate to #225.

**Comment by Josh-a-e** [comment]
@tanikella seems like this could be reopened as #225 is closed? Does anyone have any idea when this might be fixed?

**Comment by keller00** [comment]
Working on this

**Comment by tanikella** [comment]
@keller00 is this to fix azure-storage-blob v12 dependency or patch to continue using v2.1?
