### ISSUE TITLE
SNOW-157438: Feature request: print `sso_url` when unable to open browser when using federated auth

### ISSUE THREAD

**Issue by ValentinMoullet** [snowflakedb/snowflake-connector-python#303]
Hi,

When working with tools like Google Colab or other Jupyter-based tools, it often happens that data scientists or engineers are connected to a more powerful instance (generally a VM without any browser) to work with a lot of data. If a company is using federated authentication (such as G Suite) in order to allow their employees to access data, they currently cannot connect to a Snowflake database with such a setup because calling `connect` with `authenticator='externalbrowser'` will fail with `ER_UNABLE_TO_OPEN_BROWSER` error code. A very simple solution that would help this use case (and which is used by other tools, such as https://github.com/googlecolab/colabtools) is to simply print out the `sso_url` when we are unable to open a browser. The user can then click on the link, open it using their own local browser, and authenticate from there.

I tried it myself, by just replacing the lines in the if-block (https://github.com/snowflakedb/snowflake-connector-python/blob/d83d7fbeaf56d42aa433079dc9622737a061436a/auth_webbrowser.py#L108) by a simple `print(sso_url)`, and it worked fine!

It probably also works for other IdP than Google, but I only tried with Google given that this is our setup.

I was wondering what you thought about that, and if you think it would be useful to also implement it for other languages. I find it especially useful for Python as this is a common use case for data scientists/engineers, which are most of the time using Python.

Thanks in advance for considering this simple feature request that would us quite a bit!

**Comment by groodt** [comment]
I would very much like to see a feature like this as well.

There are other similar issues with MFA and using the snowflake-connector-python on remote machines without browsers.

**Comment by groodt** [comment]
@ValentinMoullet For my scenario, printing out the `sso_url` takes me to Okta, then redirects back to a port on `localhost` via SAML RelayState, which obviously fails for us. We then have to manually change the host from localhost and it works.

Are you seeing similar? Or is this a different, but related issue?

**Comment by ValentinMoullet** [comment]
@groodt In our case, as we are using Google, it directly redirects us to the "right page" when we visit the `sso_url` from our local computer (even though the link was generated on a virtual machine), no need to manually change the host to localhost.

**Comment by pecigonzalo** [comment]
Hi! I see we now have #847 but this does not seem to be fully resolved as we still give way to `handle_error` and this I believe causes the something like `dbt debug` to fail. 

Maybe an additional request here but we should try and use a fixed port or at least take an argument/env-var for it as otherwise we cant map the port from environments like Docker.

What are the next step here? Happy to submit a PR.

**Comment by iserko** [comment]
While #847 does exactly what it says, it does not help this issue.

Once the `sso_url` is printed, the code should pause and wait for the user to paste in the URL that they are redirected to by the SSO process.

**Comment by iserko** [comment]
@pecigonzalo would you mind giving https://github.com/snowflakedb/snowflake-connector-python/pull/883 a try and see if it works for you?

**Comment by pecigonzalo** [comment]
I think my colleague @feluelle gave it a look and commented that it worked. He commented on the PR.

**Comment by feluelle** [comment]
Hi @iserko, correct. I tested it out and it worked like a charm. :) We only faced some issues regarding caching the token, but they, for some reason, have solved themselves :D
