### ISSUE TITLE
SNOW-162284: Documentation question for write_pandas

### ISSUE THREAD

**Issue by fdosani** [snowflakedb/snowflake-connector-python#311]
More of a question with regards to the docs here: https://docs.snowflake.com/en/user-guide/python-connector-api.html#write_pandas

It specifically says: `and uses the COPY INTO <location> ` Should this be `and uses the COPY INTO <table> `? Looking at the code the variable is called `location` but it should be `COPY INTO <table>` in theory?

 Thanks for the hard work on the connector :)

**Comment by sfc-gh-mkeller** [comment]
Ahh right,  I'll pass this onto the docs team. Thank you for letting us know!
You're welcome, hope you like it.
