### ISSUE TITLE
SNOW-163889: Support azure-storage-blob v12 api

### ISSUE THREAD

**Issue by markledwich2** [snowflakedb/snowflake-connector-python#314]
I have a project using `python 3.8.2` with code written against `azure-storage-blob 12.3.1`

The problem is `snowflake-connector-python 2.2.6` has requirement `azure-storage-blob<12.0.0`.

I'm not keen re-writing my code for the older azure azure-storage-blob sdk which is quite different. Please keep this library up to date with the latest version of dependencies or internalize them somehow.

**Comment by sfc-gh-mkeller** [comment]
Please look out for the next release!
