### ISSUE TITLE
SNOW-165420: How to use SQL PUT with a file-like object

### ISSUE THREAD

**Issue by dylrich** [snowflakedb/snowflake-connector-python#317]
Hi! I am trying to do fully in-memory ETL with the Snowflake Python client and I'm wondering if it's possible to utilize the PUT bulk-copy API with an in-memory, file-like Python object like StringIO or BytesIO. I'd expect it to look something like:

```python
f = StringIO()
con.cursor().execute("PUT %s @%testtable", f)
```

From [the docs here](https://docs.snowflake.com/en/sql-reference/sql/put.html#syntax) it seems like this command is hard-coded to expect a file path on disk and I don't see any examples which don't point to a location on disk. Is this impossible or am I missing something?

Thanks a ton!

**Comment by keller00** [comment]
Hey @dylrich 
This is not currently possible, but I think we should in the future support this. I’ll bring this up to the team!
Have you considered using `/dev/shm` in the short term (assuming you are on Linux)?

**Comment by dylrich** [comment]
I hadn't considered `/dev/shm`, but that would certainly work in the interim. I'm also considering just managing writing files to our object storage myself. Thanks for the confirmation on this, anyhow! I'd be happy to test an implementation should one land in a branch.

**Comment by keller00** [comment]
Let's keep this issue to track progress.
