### ISSUE TITLE
SNOW-165626: Support cffi v1.14.0

### ISSUE THREAD

**Issue by george-nw** [snowflakedb/snowflake-connector-python#318]
Hello,

Would there be any issue supporting cffi v1.14.0?

Currently we are restricted to versions between 1.9 and less than 1.14:
```
'cffi>=1.9,<1.14',
```
https://github.com/snowflakedb/snowflake-connector-python/blob/v2.25/setup.py#L188

**Comment by sfc-gh-mkeller** [comment]
Passed testing, merged setup.py change. Will be included in the next release!
