### ISSUE TITLE
Autocommit should be off by default

### ISSUE THREAD

**Issue by atrigent** [snowflakedb/snowflake-connector-python#33]
From https://www.python.org/dev/peps/pep-0249/#commit:

```
Note that if the database supports an auto-commit feature, this must be initially off. An interface method may be provided to turn it back on.
```

**Comment by smtakeda** [comment]
Add `autocommit=True` to the connection string.

There is more or less historical reason why Python Connector doesn't follow it. When I implemented Python Connector, there was no choice; autocommit support only. No transaction exists 2.5 years ago, so there was no way to turn off autocommit at that time, and as certain number of customers already used Python Connector, we deferred the fix, but it was too late to change the default behavior completely. So we added `autocommit=True` to the connection parameter.

In contrast, SQLAlchemy for Snowflake turns off autocommit by default. We eventually implemented transaction then, and we understood that behavior is more appropriate. It was a new component, so we didn't need to worry about compatibility issue.
