### ISSUE TITLE
SNOW-178458: Running with Python 3.8 raises DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats

### ISSUE THREAD

**Issue by bvlaming** [snowflakedb/snowflake-connector-python#343]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.8.3

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
macOS-10.13.6-x86_64-i386-64bit
However, the run is triggered from a Docker image; within the image, the result is:
Linux-4.19.76-linuxkit-x86_64-with-glibc2.2.5

3. What are the component versions in the environment (`pip list`)? 
`Package                    Version
-------------------------- ------------
absl-py                    0.9.0
aiocontextvars             0.2.2
aiohttp                    3.6.2
appdirs                    1.4.3
asn1crypto                 1.3.0
astor                      0.8.1
astroid                    2.3.3
astunparse                 1.6.3
async-timeout              3.0.1
attrs                      19.3.0
azure-common               1.1.25
azure-core                 1.7.0
azure-storage-blob         12.3.2
azure-storage-common       2.1.0
black                      19.10b0
boto3                      1.11.17
botocore                   1.14.17
cachetools                 4.1.1
certifi                    2020.6.20
cffi                       1.14.0
chardet                    3.0.4
click                      7.1.1
coverage                   5.1
cryptography               2.9.2
cycler                     0.10.0
darglint                   1.1.3
decorator                  4.4.2
docutils                   0.15.2
entrypoints                0.3
flake8                     3.7.9
flake8-bugbear             20.1.4
gast                       0.3.3
google-auth                1.19.2
google-auth-oauthlib       0.4.1
google-pasta               0.2.0
grpcio                     1.30.0
h5py                       2.10.0
idna                       2.9
ijson                      2.6.1
importlab                  0.5.1
importlib-metadata         1.7.0
iso8601                    0.1.12
isodate                    0.6.0
isort                      4.3.21
jmespath                   0.10.0
joblib                     0.16.0
Keras-Applications         1.0.8
Keras-Preprocessing        1.1.2
kiwisolver                 1.2.0
lazy-object-proxy          1.4.3
Markdown                   3.2.2
matplotlib                 3.1.3
mccabe                     0.6.1
mimetype-match             1.0.4
more-itertools             8.2.0
msrest                     0.6.17
multidict                  4.7.6
networkx                   2.4
ninja                      1.9.0.post1
numpy                      1.18.5
oauthlib                   3.1.0
opt-einsum                 3.3.0
oscrypto                   1.2.0
packaging                  20.4
pandas                     1.0.5
pathspec                   0.8.0
pendulum                   2.0.5
picnic-aiohttp             0.1.3
picnic-database            2.1.0
picnic-guide               0.1.6
picnic-model-publisher     0.0.9
picnic-model-tracker       0.0.4
picnic-prp                 0.7.2
picnic-s3-client           0.2.2
picnic-tools               0.7.0
pip                        20.0.2
pluggy                     0.13.1
protobuf                   3.12.2
py                         1.8.1
pyasn1                     0.4.8
pyasn1-modules             0.2.8
pycodestyle                2.5.0
pycparser                  2.20
pycryptodomex              3.9.8
pydocstyle                 5.0.2
pyflakes                   2.1.1
PyJWT                      1.7.1
pylint                     2.4.4
pyOpenSSL                  19.1.0
pyparsing                  2.4.7
pyperclip                  1.8.0
pytest                     5.4.1
pytest-cov                 2.8.1
python-dateutil            2.8.1
pytype                     2020.2.20
pytz                       2020.1
pytzdata                   2020.1
PyYAML                     3.13
regex                      2020.4.4
requests                   2.23.0
requests-oauthlib          1.3.0
rsa                        4.6
s3transfer                 0.3.3
scikit-learn               0.22.2.post1
scipy                      1.4.1
setuptools                 46.1.3
six                        1.15.0
slackclient                1.3.0
snowballstemmer            2.0.0
snowflake-connector-python 2.2.9
snowflake-sqlalchemy       1.2.3
SQLAlchemy                 1.3.18
sqlparse                   0.3.1
tenacity                   5.0.4
tensorboard                2.2.2
tensorboard-plugin-wit     1.7.0
tensorflow                 2.2.0
tensorflow-estimator       2.2.0
termcolor                  1.1.0
toml                       0.10.0
typed-ast                  1.4.1
urllib3                    1.25.10
wcwidth                    0.1.9
websocket-client           0.57.0
Werkzeug                   1.0.1
wheel                      0.34.2
wrapt                      1.12.1
xgboost                    0.90
yarl                       1.4.2
zipp                       3.1.0`

4. What did you do?
Calling the `fetchone()` method in `cursor.py` raises a `/.venv/lib/python3.8/site-packages/snowflake/connector/cursor.py:805: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats` . This warning is raised since Python 3.8 is released: https://bugs.python.org/issue36381

5. What did you expect to see?
I would not expect the warning.

6. What did you see instead?
The warning.

7.
 `/.venv/lib/python3.8/site-packages/snowflake/connector/cursor.py:805: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats`

This seems to be a setting that needs to be defined on the Snowflake connector side.

**Comment by rsermas** [comment]
were you able to solve this? having the same issue currently

**Comment by sfc-gh-hkapre** [comment]
We will pick this up in Q3.

**Comment by sfc-gh-mkeller** [comment]
This was fixed as part of https://github.com/snowflakedb/snowflake-connector-python/commit/11365966a2ce1d2487920ed8a5468c2a6076f0e8
Please re-open this issue if you think we have made a mistake!
