### ISSUE TITLE
SNOW-179577: Issue while using pd_writer: **MissingDependencyError: Missing optional dependency: pandas**

### ISSUE THREAD

**Issue by Sangeetha-Sara** [snowflakedb/snowflake-connector-python#345]
Python version -- 3.7.3
pyarrow -- 0.17.1 
snowflake-connector-python -- 2.2.8     
Operating system and processor architecture: Windows-10-10.0.17763-SP0

I'm trying to write a dataframe to snowflakes using pd_writer
So to import i used the below code:  
**from snowflake.connector.pandas_tools import pd_writer** 

I got the error:
**MissingDependencyError: Missing optional dependency: pandas**

**Comment by sfc-gh-mkeller** [comment]
Hi, @Sangeetha-Sara make sure to install the connector with the `pandas` optional dependency group. See: https://docs.snowflake.com/en/user-guide/python-connector-pandas.html#installation

**Comment by Sangeetha-Sara** [comment]
@sfc-gh-mkeller Thanks, it worked
