### ISSUE TITLE
SNOW-183608: Error executing a basic select query without use a cursor fetch

### ISSUE THREAD

**Issue by AlbCM** [snowflakedb/snowflake-connector-python#359]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
**Python 3.7.7**

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
**Linux-5.3.0-7648-generic-x86_64-with-Ubuntu-19.10-eoan**

3. What are the component versions in the environment (`pip list`)?
asn1crypto==1.3.0
boto3==1.14.32
botocore==1.17.32
certifi==2020.4.5.2
cffi==1.13.2
chardet==3.0.4
cryptography==2.9.2
docutils==0.15.2
idna==2.9
ijson==2.6.1
isodate==0.6.0
jmespath==0.10.0
msrest==0.6.16
numpy==1.19.1
oauthlib==3.1.0
oscrypto==1.2.0
pandas==1.1.0
psycopg2-binary==2.8.5
pycparser==2.20
pycryptodomex==3.9.7
PyJWT==1.7.1
pyOpenSSL==19.1.0
python-dateutil==2.8.1
pytz==2020.1
requests==2.23.0
requests-oauthlib==1.3.0
s3transfer==0.3.3
six==1.15.0
snowflake-connector-python==2.2.9
snowflake-sqlalchemy==1.2.3
SQLAlchemy==1.3.18
urllib3==1.25.9
xlrd==1.2.0
s3fs==0.4.2
flask==1.1.2
gunicorn==20.0.4
sentry-sdk==0.16.2
pyarrow==0.17.0

4. What did you do?

Execute a query using cursor with the following method.

```
    def execute(self, sql: str, **kwargs):
        cur = self.connection.cursor()
        try:
            cur.execute(sql.strip(), kwargs)
        except Exception as e:
            ExceptionHandler.capture_exception(e)
            self.connection.rollback()
            raise e
        finally:
            cur.close()
```

5. What did you expect to see?
The behaviour gotten but with no retries and exit code 0 at finish all the process.

6. What did you see instead?
The method execute queries (we can watch the query log of the query through Snowflake history with details correctly), but We receive the following exception when We select tables with rows >= 25K, the query execute the query properly but after sconds the snowflake connector retries again and again until get a timeout, this exception does not happen when we use some fetch method in the cursor for instance (cur.fetchone()) but in our use case it's not necessary. 

![image](https://user-images.githubusercontent.com/10161576/90269274-02779d00-de1e-11ea-95ad-e228dcccbc18.png)

```
    def execute(self, sql: str, **kwargs):
        cur = self.connection.cursor()
        try:
            cur.execute(sql.strip(), kwargs)
            print(cur.fetchone())
        except Exception as e:
            ExceptionHandler.capture_exception(e)
            self.connection.rollback()
            raise e
        finally:
            cur.close()
```

The code above works without exception just using a print 

This issue was throw on snowflake-connector-python >=2.7.7. We are using now 2.0.0 version and this works without retries and as we expect.

**Comment by sfc-gh-mkeller** [comment]
Hi @AlbCM 
I'm unable to reproduce your issue, could you please open a support ticket with us, please?
