### ISSUE TITLE
SNOW-183856: Snowflake missing out on all that free testing from it's users

### ISSUE THREAD

**Issue by arterrey** [snowflakedb/snowflake-connector-python#360]
This is come up a bunch of times in the issues about aggressive version pinning from this package. I understand that you have a solid testing infrastructure so you can verify things work with other things, however, version pinning is a downstream concern from the package maintainer unless there is a known incompatibility or bug, additionally I don't believe that your testing infrastructure covers all the use cases that your users are striving to implement. You have all these talented uses testing your software on version combinations and implementation scenarios you could never cover.

Additionally - bugs in dependencies become your bugs because you locked yourself into them without allowing users to upgrade themselves out of an issue - that would require extra handling of bugs which are just not relevant to snowflake-connector python. For example, even at a discussion level, in some of the threads it is there is mention of interactions between boto3 and requests, but why is that even a discussion? There is no bug in snowflake-connector-python, and energy is wasted discussing and pain in inherited by the users of snowflake-connector-python for needing to deal with the issue at a level that it needed to be dealt with.

I would suggest that documenting a known good version set from your testing would be very helpful and appreciated or documenting frequently encountered problems that may occur in implementing the package would be the simplest approach.

Additionally additionally - it is a wast of time to debug issues or submit bugs reports on old versions of software. If one encounter a bug in boto3 or requests (more likely boto3) then the first action should be to upgrade it - nobody appreciates bug reports for bugs they have fixed already.

**Comment by sfc-gh-mkeller** [comment]
Hi @arterrey 

> This is come up a bunch of times in the issues about aggressive version pinning from this package. I understand that you have a solid testing infrastructure so you can verify things work with other things, however, version pinning is a downstream concern from the package maintainer unless there is a known incompatibility or bug, additionally I don't believe that your testing infrastructure covers all the use cases that your users are striving to implement. You have all these talented uses testing your software on version combinations and implementation scenarios you could never cover.

I agree with you. However `pip` is so forgiving with versions of dependencies, so there's nothing stopping our users from updating their own packages (after installing our connector) and letting us know that things are working well for them afterwards (I believe no one has done this). Maybe you could start this trend @arterrey 

Be aware that newer `requests` versions actually break compatibility with our connector.

> I would suggest that documenting a known good version set from your testing would be very helpful and appreciated or documenting frequently encountered problems that may occur in implementing the package would be the simplest approach.

So this is what https://github.com/snowflakedb/snowflake-connector-python/tree/master/tested_requirements was for and we stopped updating it when we moved out of our monorepo to this repo. I need to get this working again, just don't really have the time when there are actual bugs to be fixed first.

> Additionally additionally - it is a wast of time to debug issues or submit bugs reports on old versions of software. If one encounter a bug in boto3 or requests (more likely boto3) then the first action should be to upgrade it - nobody appreciates bug reports for bugs they have fixed already.

We have never done this.

This is about the same as #284 , please continue the discussion there.

**Comment by manugarri** [comment]
> when there are actual bugs to be fixed first.

I would argue that the current situation (builds periodically breaking) is a bug on itself.

  Im surprised that given the current Snowflake situation (IPO) and, python being the main language for data engineering, that this issue hasnt been flagged to potential investors.
