### ISSUE TITLE
SNOW-188393: Type conversion issues when using fetch_pandas_all()

### ISSUE THREAD

**Issue by rparvat14** [snowflakedb/snowflake-connector-python#384]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

Version 3.7.1

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Windows-10-10.0.18362-SP0

3. What are the component versions in the environment (`pip list`)?
pip 20.2.2
snowflake-connector-python 2.3.1
pyarrow 0.17.1

4. What did you do?
ctx=snowflake.connector.connect(
    user = 'xxxxxxx',
    password = 'xxxxxxxxxxxxx',
    account = 'xxxxxxxxxxxxxxxxx',
    warehouse = 'xxxxxxxxxxxxx',
    database = 'xxxxxx',
    schema = 'xxxxxxxxxxx',
    role='xxxxxxxxxx'
)   

cur = ctx.cursor()

query="select * from table x"
cur.execute(query)
data = cur.fetch_pandas_all()

data.info()

when displaying the dtypes of variables variable with floats are being converted into type objects, also different types of integers like int64,int32,int8 are being produced. 

Same query when used pd.read_sql(query,engine) gives perfect datatypes for the columns.

5. What did you expect to see?

Same result when using both pd.read_sql and fetch_pandas_all()

6. What did you see instead?

when displaying the dtypes of variables variable with floats are being converted into type objects, also different types of integers like int64,int32,int8 are being produced. 

Same query when used pd.read_sql(query,engine) gives perfect datatypes for the columns.

7. Can you set logging to DEBUG and collect the logs?

**Comment by annedegraafzipline** [comment]
Hi, have there been any updates on this issue? I'm running into a similar problem.

**Comment by sfc-gh-mkeller** [comment]
@rparvat14 Would you be able to provide how you created this table with some sample data?

**Comment by sfc-gh-jbahk** [comment]
@rparvat14 could you provide some examples as to how you reproduced this? If not, I'm happy to close this for you to reopen later if it happens again.
