### ISSUE TITLE
SNOW-189907: Unclosed file handler

### ISSUE THREAD

**Issue by SSgtSpoon** [snowflakedb/snowflake-connector-python#385]
https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/file_util.py#L93 should use a context manager (`with open(...) as f:`) instead, as the current code is failing to close the file handler, causing warnings to be shown in the terminal during unit tests.

**Comment by sfc-gh-mkeller** [comment]
Thank you for letting us know @SSgtSpoon I have fixed the issue and the fix will be included in our next release.
