### ISSUE TITLE
SNOW-194062: feature request: `fetch_dask_dataframe()`

### ISSUE THREAD

**Issue by jameslamb** [snowflakedb/snowflake-connector-python#397]
I've been working with this library for a few days. Thanks so much for maintaining it! It has made it really easy to work with data from Snowflake using PyData libraries.

I'd like to propose a feature that I think could improve the experience of using Snowflake results with other PyData libraries (like `dask`, `dask-ml`, and `scikit-learn`).

### Feature Request

Would you support a pull request that adds a `fetch_dask_dataframe()`? This method would have a similar API to `fetch_pandas_all()`, but would return a [Dask DataFrame](https://examples.dask.org/dataframe.html) instead of a `pandas` data frame.

I'd be happy to contribute this if you're interested in it.

### How this feature would improve `snowflake-connector-python`

Dask is a popular open source tool for working with larger-than-memory datasets in Python. Efficiently creating a Dask Dataframe from a Snowflake result today requires a lot of knowledge of Dask and Snowflake, and having a client method that does this would reduce a lot of friction for users trying to work with large query results in Python.

This feature would provide an easy path to working with large query results in Python.

### Overview 

Today, there are two ways to read the results of a query into a data frame in a Python session (documented [here](https://docs.snowflake.com/en/user-guide/python-connector-pandas.html#reading-data-from-a-snowflake-database-to-a-pandas-dataframe)):

* `fetch_pandas_all()`: pull the entire result into a single `pandas` data frame
* `fetch_pandas_batches()`: iterate over chunks of a query result one `pandas` data frame at a time

If your query result, once it's been converted to a `pandas` data frame, is too large to fit in memory on the machine where your code is running, `fetch_pandas_all()` will run out of memory and fail. One way to get around this is to iterate over smaller chunks one at a time with `fetch_pandas_batches()` and then do something with each batch, like writing it to a file.

Another option for working with a larger-than-memory dataset might be to create a [Dask DataFrame](https://examples.dask.org/dataframe.html). This would allow you to work with larger-than-memory data and have Dask handle the details of spilling to / reading from disk.

To do this, you'd have to template your query and create a series of `dask delayed` functions. Each function could get a piece of the query, execute it, and call `fetch_pandas_all()` on the result. That work will be spread across the Dask cluster (or executed as individual tasks on one machine, if you're using a Dask `LocalCluster`).

Something like this:

```python
from dask import delayed
import dask.dataframe as dd

query = """
    SELECT
        C_BIRTH_DAY, C_BIRTH_MONTH, C_BIRTH_YEAR
    FROM
        customer
    WHERE
        C_BIRTH_DAY = %s
    """

@delayed
def get_chunk(conn_info, query, day_of_month):
    conn = snowflake.connector.connect(**conn_info)
    cur = conn.cursor().execute(query, day_of_month)
    return cur.fetch_pandas_all()

ddf = dd.from_delayed(
    [
        get_chunk(conn_info, query, day_of_month)
        for day_of_month in range(10, 15)
    ],
)
ddf
```

This is doable, but it opens up a lot of room for user error and requires a lot of knowledge of Dask.

I think there is an opportunity to simplify this and make it not rely on any details of the query, by taking advantage of the existing code this package has for chunking up a query result: https://github.com/snowflakedb/snowflake-connector-python/blob/0cf126e0791787d9841bb4849feb781597e8671f/src/snowflake/connector/arrow_result.pyx#L244-L248.

Then the interface might look like just

```python
ddf = conn.cursor().execute(query).fetch_dask_dataframe()
```

If you're open to the feature, I'll spend some time investigating this and propose a pull request.

### Requested Information 

I've answered the questions in the issue template, but they seem specific to the case where someone is reporting a problem, so I've hidden them here

<details><summary>requested answers (click me) </summary>

1. What version of Python are you using (`python --version`)?

This feature should work on all versions of Python supported by `snowflake-connector-python`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

This feature should work on all operating systems supported by `snowflake-connector-python`.

3. What are the component versions in the environment (`pip list`)?

N/A - this is not relevant for a feature request

4. What did you do?

N/A - this is not relevant for a feature request

5. What did you expect to see?

N/A - this is not relevant for a feature request

6. What did you see instead?

N/A - this is not relevant for a feature request

7. Can you set logging to DEBUG and collect the logs?

N/A - this is not relevant for a feature request

</details>

--------------------------

Thank you for your time and consideration!

**Comment by xhochy** [comment]
I know that there is a connector for Spark that can retrieve batches in parallel from different machines. This is probably implemented with a slightly different Snowflake API in the driver. This would probably also be useful here. I guess one either needs to dive into the Spark<->Snowflake connector code for this? Or is there maybe some documentation about the Arrow-based API used for communication between client and server?

**Comment by jameslamb** [comment]
I've only just started digging in to the internals here, but my hope was that I could get into how `SnowflakeChunkDownloader` is implemented and know the URLs of each chunk of a result ahead of time:

https://github.com/snowflakedb/snowflake-connector-python/blob/0cf126e0791787d9841bb4849feb781597e8671f/src/snowflake/connector/chunk_downloader.py#L68-L75

And then distributed those URLs to the Dask workers and have them each read their own slices of the data.

**Comment by jameslamb** [comment]
I've opened a new draft PR to with a working implementation to show the direction I'm considering: #401 

I can confirm that it's possible, with the existing result chunking mechanism in this package, to create a Dask data frame from a large result without the Dask client ever needing to touch the data. This means you can take advantage of Dask to pull data in parallel, and to hold it all in memory in a distributed data frame.

I won't go any further on that PR until maintainers here weigh in on whether they're open to this feature.

Thanks for your time and consideration!

**Comment by sfc-gh-mkeller** [comment]
Hi everyone,

It's apparent from all of the emojis on #400 that there's a general interest in this feature.
While it must have seen like we just ignored this request from Saturn Cloud, my team and I have been hard at work on re-designing and re-implementing ResultSets in a way that makes distributing them easier for not only Dask, but for all distributed systems.

So I'm now happy to announce #688 that was just merged and it introduces pickleable `ResultBatch` s and integrates these new classes into our regular non-distributed workflow as well.

Please note that nice documentation is still in the works on how to use this new feature, but the code is complete. If anyone is interested in looking at how to use `ResultBatch` classes please see the tests added in #688 or trace out what `ResultSet` and `SnowflakeCursor` fetch functions do.

We'd like to get some feedback from our users, this includes but isn't only limited to @jameslamb 
Hope everyone finds this change useful! 🥳 🎊

**Comment by bchatterjee** [comment]
Do we really need pandas, dask etc in the method names? Can the name of these methods be more friendly? Example, I know my object is panda or dask. So, I can I just refer them as fetch_batches, fetch_all etc? I'm just curious..

**Comment by sfc-gh-mkeller** [comment]
@bchatterjee Of course it would be possible, however:
1. There has to be a clear positive outcome for changing already existing behavior.
2. Some result types can be fetched into multiple objects. For example you can fetch arrow results into Arrow Tables, Python objects in tuples and Pandas DataFrames too. How would you handle this case?

Feel free to open an issue with your design idea, we can discuss it!

**Comment by bchatterjee** [comment]
> @bchatterjee Of course it would be possible, however:
> 
> 1. There has to be a clear positive outcome for changing already existing behavior.
> 2. Some result types can be fetched into multiple objects. For example you can fetch arrow results into Arrow Tables, Python objects in tuples and Pandas DataFrames too. How would you handle this case?
> 
> Feel free to open an issue with your design idea, we can discuss it!

thanks @sfc-gh-mkeller. what's your thoughts on naming something like this fetch_all().to_pandas_df(), or fetch_all().as_pandas_df(), or something similar like this. that way, we know fetch_all() fetching whatever domain object and then its getting explicitly converted to target object. I'm thinking if we can keep the utility methods close to object's responsibilities and use conversational methods when converting into other objects. I know python is a flexible language and there are lots of possibilities of doing things differently.
