### ISSUE TITLE
SNOW-198021: Convenience parameter in `connect` to use the named connections in ~/.snowsql/config

### ISSUE THREAD

**Issue by snosrap** [snowflakedb/snowflake-connector-python#417]
## What is the current behavior?
Currently, to create a new connection, one calls [connect](https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/connection.py#L406) with several parameters from [this list](https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/connection.py#L90) (e.g., `account`, `username`, `password`, etc.).

Example:
```python
con = snowflake.connector.connect(account='my_account.west-us-2.azure', user='my_user', password='my_password')
```

However, many developers who have the [snowsql cli](https://docs.snowflake.com/en/user-guide/snowsql.html) client installed already have many of these connection settings stored in their `~/.snowsql/config` file for use with the `--connection` switch, like this:

```ini
[connections.my_connection]
accountname = my_account.west-us-2.azure
username = my_user
password = my_password
```

## What is the desired behavior?
Could `connect` be modified to accept an additional `connection_name` parameter that would configure the connection using the settings from the `~/.snowsql/config` file?

## How would this improve `snowflake-connector-python`?
* This would make it easier to write quick scripts, similar to passing the `--connection` parameter to the snowsql cli
* One could argue this would be better from a security perspective, since sensitive data (e.g., passwords) would be stored in only one location (rather than scattered through various scripts)

**Comment by sfc-gh-achandrasekaran** [comment]
To clean up and re-prioritize bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please re-create them. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response
