### ISSUE TITLE
Connection has to be explicitly closed

### ISSUE THREAD

**Issue by theianrobertson** [snowflakedb/snowflake-connector-python#42]
Not sure if this is a documentation issue or something that could be handled in code (or maybe it's just my issue), but I was having issues with a connection object not being closed.  Version 1.4.9 of the connector:

```python
import snowflake.connector

conn = snowflake.connector.connect(
    user='some_user',
    password='some_pwd',
    account='some_account'
)
cursor = conn.cursor()
cursor.execute('USE WAREHOUSE some_warehouse;')
cursor.execute('USE DATABASE some_db;')
cursor.execute(some_sql)
for row in cursor:
    #do something
cursor.close()
```

If I don't close the connection at the end (`conn.close()`) then my code will never finish - it just sits there with an idle connection.  If users are expected to manually close the connection I think it could be a bit clearer in the docs.  Or else maybe there's a way to automatically close the connection or switch to a `with` structure?

**Comment by smtakeda** [comment]
Yes, it is recommended that the connection should be closed explicitly, or the session will remain on the server for a while. If not closed, Python connector attempts to close by GC, but often it is too late as GC already takes away HTTP library from Python Connector and miss a chance to tell the server to close the session. Note the sessions will be purged eventually but would take N days or weeks.

Context manager can be used to ensure closing the connection:

```
with snowflake.connector(...) as con:
    con.cursor().execute(...)
```

or try & finally pattern can be used.

```
con = snowflake.connector.connect(...)
try:
    con.cursor().execute(...)
finally:
    con.close()
```

**Comment by theianrobertson** [comment]
Awesome.  Is that something that could be added to the docs?  I'm happy to use a with context, just didn't realize I needed to.  The snippets in the [docs](https://docs.snowflake.net/manuals/user-guide/python-connector-example.html) only close the cursor.
