### ISSUE TITLE
SNOW-200089: unsupported operand type(s) for +: 'int' and 'str' in write_pandas

### ISSUE THREAD

**Issue by kavier6n** [snowflakedb/snowflake-connector-python#438]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.7.3

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Windows-10-10.0.18362-SP0

3. What are the component versions in the environment (`pip freeze`)?

```
asn1crypto==1.4.0
azure-common==1.1.25
azure-core==1.8.1
azure-storage-blob==12.5.0
boto3==1.14.63
botocore==1.17.63
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
cryptography==2.9.2
docutils==0.15.2
idna==2.9
isodate==0.6.0
jmespath==0.10.0
msrest==0.6.19
numpy==1.19.2
oauthlib==3.1.0
oscrypto==1.2.1
pandas==1.0.5
pyarrow==0.17.1
pycparser==2.20
pycryptodomex==3.9.8
PyJWT==1.7.1
pyOpenSSL==19.1.0
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
requests==2.23.0
requests-oauthlib==1.3.0
s3transfer==0.3.3
six==1.15.0
snowflake-connector-python==2.3.2
tqdm==4.49.0
urllib3==1.25.10

```

4. What did you do?
calling write_pandas() to write a df to snowflake, errors out at ```sum(e[3] for e in copy_results)``` in pandas_tools, works fine when I change it to ```sum(int(e[3]) for e in copy_results)```

5. What did you expect to see?
e[3] to be an int

6. What did you see instead?
e[3] is str

**Comment by alaparthy** [comment]
Hi @sfc-gh-mkeller , could you let me know if this an bug or something I could be doing incorrectly

**Comment by sfc-gh-mkeller** [comment]
Hi @alaparthy 
What does your data look like? What does copy_results` look like?

According to https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#output that should be a number and it has been our tests.

**Comment by sfc-gh-mkeller** [comment]
I'm sorry, I clicked on the wrong button! 😅

**Comment by alaparthy** [comment]
![image](https://user-images.githubusercontent.com/34084253/98058159-03630e00-1e12-11eb-9681-c62848dec40c.png)

**Comment by alaparthy** [comment]
Hi @sfc-gh-mkeller , attached the `copy_results` screencap

**Comment by alaparthy** [comment]
@sfc-gh-mkeller any estimate on when SNOW-200089 can be merged?

**Comment by sfc-gh-mkeller** [comment]
I'm sorry, I reached out to the back-end team to see if they would know what might have caused the ROWS_PARSED to be returned as a string. I'm waiting on their response.

**Comment by AbdullahAlsayed** [comment]
hi
i'm getting the same error
what should i do to solve this
