### ISSUE TITLE
SNOW-212916: qmark BINDING Issue for tables that exist

### ISSUE THREAD

**Issue by terry-campbell-od** [snowflakedb/snowflake-connector-python#492]
When using the snowflake.connector.paramstyle = u'qmark' the bind fails when trying to get the column list for the existing table.  This works when the table doesn't exist and it works with the pyformat paramstyle.  It appears the pyformat parmstyle is used for getting the column list even though the paramstyle is set to qmark.  

Error - 
ProgrammingError: (snowflake.connector.errors.ProgrammingError) 252004: Binding parameters must be a list: {'table_schema': 'TEMPDB'}
[SQL: 
            SELECT /* sqlalchemy:_get_schema_columns */
                   ic.table_name,
                   ic.column_name,
                   ic.data_type,
                   ic.character_maximum_length,
                   ic.numeric_precision,
                   ic.numeric_scale,
                   ic.is_nullable,
                   ic.column_default,
                   ic.is_identity,
                   ic.comment
              FROM information_schema.columns ic
             WHERE ic.table_schema=%(table_schema)s
             ORDER BY ic.ordinal_position]
[parameters: {'table_schema': 'TEMPDB'}]
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by TimothyVermeirenBiztory** [comment]
I am having the same issue. Here is a query I'm seeing being issued:
```
SELECT user.id AS user_id, user.username AS user_username, <more fields>, user.authenticated AS user_authenticated 
FROM user 
WHERE user.id = %(param_1)s
[parameters: {'param_1': 5918730}]
```
I need paramstyle to be qmark for the same reasons as in this issue comment: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/142#issuecomment-583503447; being able to insert a large amount of data.

**Comment by ybaktir** [comment]
Is there an update on this? We still have the same problem
