### ISSUE TITLE
SNOW-213428: Snowflake connector fail with: Failed to import optional packages, pyarrow

### ISSUE THREAD

**Issue by miandreu** [snowflakedb/snowflake-connector-python#497]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.7.5

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Linux-3.10.0-693.11.6.el7.x86_64-x86_64-with-centos-7.3.1611-Core
3. What are the component versions in the environment (`pip freeze`)?
```
asn1crypto==1.4.0
azure-common==1.1.25
azure-core==1.8.2
azure-storage-blob==12.5.0
boto3==1.14.63
botocore==1.17.63
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
cryptography==2.9.2
decorator==4.4.2
docutils==0.15.2
future==0.18.2
idna==2.9
install==1.3.4
isodate==0.6.0
JayDeBeApi==1.2.3
jmespath==0.10.0
JPype1==1.0.2
msrest==0.6.19
numpy==1.19.2
oauthlib==3.1.0
oscrypto==1.2.1
py==1.9.0
pyarrow==0.17.1
pycparser==2.20
pycryptodomex==3.9.8
PyHive==0.6.1
PyJWT==1.7.1
pyOpenSSL==19.1.0
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
requests==2.23.0
requests-oauthlib==1.3.0
retry==0.9.2
s3transfer==0.3.3
sasl==0.2.1
setuptools-scm==4.1.2
six==1.14.0
snowflake-connector-python==2.3.3
thrift==0.13.0
thrift-sasl==0.3.0
typing-extensions==3.7.4.3
urllib3==1.25.9
```

4. What did you do?
I install snowflake-connector with pip create a snowflake connection like this
```
    def get_connection(self) -> SnowflakeConnection:

        return snowflake.connector.connect(
            user=self.user,
            account=self.account,
            warehouse=self.warehouse,
            private_key=self._decrypt_rsa_private_key(),
            role=self.role
        )
```

5. What did you expect to see?
Snowflake connection working, being able to run some queries against our data
6. What did you see instead?
`snowflake.connector.arrow_result - INFO - Failed to import optional packages, pyarrow`

**Comment by miandreu** [comment]
The issue is fixed when specify the pandas requirements but this shouldn't be necessary as me never use anything related to the pandas module, this libraries should be under the install requirements

**Comment by sfc-gh-mkeller** [comment]
Hi @miandreu 
That is actually not an error, just a logging for debugging purposes.
You can actually safely ignore it, it was useful in some cases before so we left it in the code.

**Comment by amiruci** [comment]
@sfc-gh-mkeller thanks for your response. Would you please consider turning it into `DEBUG` instead of `INFO`? We're seeing this log in all our apps that have `snowflake-connector-python` installed, without a) it being informative, and b) being able to do much about it. We don't need the pandas requirements so we'd prefer to not install it just to get rid of this log line. We'd also prefer to not silence the entire `snowflake-connector-python` package's `INFO` logs. What do you think?

**Comment by sfc-gh-mkeller** [comment]
@amiruci Sure, I can bring it up to my team.
In the meantime I'd recommend adding a filter yourself to your logger to filter these messages out https://docs.python.org/3/library/logging.html#filter

**Comment by dslove** [comment]
+1. This should be DEBUG not INFO so not to confuse users since it doesn't bring values to users but developers.
