### ISSUE TITLE
SNOW-216284: Release fix for cryptography security issue

### ISSUE THREAD

**Issue by ChristineTChen** [snowflakedb/snowflake-connector-python#514]
Hi! Can we get a release of the recent cryptography dependency pin update #500 ? We're depending on this release to resolve the security issue fixed in pyca/cryptography#5507. Thanks!

**Comment by ChristineTChen** [comment]
cc @sfc-gh-mkeller

**Comment by sfc-gh-stakeda** [comment]
@sfc-gh-abhatnagar what is the next release date?

**Comment by sfc-gh-abhatnagar** [comment]
@sfc-gh-stakeda next release is on 11/16 . Release dates are always updated here https://snowflakecomputing.atlassian.net/wiki/spaces/EN/pages/904891767/Client+Driver+Release+Schedule.

**Comment by mark-saad** [comment]
@sfc-gh-abhatnagar is there a way we can install a nightly build or something similar?

**Comment by sfc-gh-mkeller** [comment]
We just released v2.3.5, which is like 2.3.4, but with the newest `cryptography` pin https://pypi.org/project/snowflake-connector-python/2.3.5/
Please install it and if you run into any issues don't hesitate to let us know!
