### ISSUE TITLE
SNOW-221203: Make cloud provider dependencies optional

### ISSUE THREAD

**Issue by sauln** [snowflakedb/snowflake-connector-python#528]
## What is the current behavior?

This package currently lists packages for Azure and AWS as required dependencies.  I expect more often than not, people will use just one major cloud provider.   

## What is the desired behavior?

Make cloud provider specific packages optional for installation.

## How would this improve `snowflake-connector-python`?

Make the package size smaller.

## References, Other Background

Out of the box, this package is too big to deploy within a lambda.  It's not necessary to bundle some of the optional dependencies in the package.

**Comment by sfc-gh-mkeller** [comment]
Duplicate of #284
