### ISSUE TITLE
snowflake.connector.errors.ProgrammingError) 001795 (42601)

### ISSUE THREAD

**Issue by RiteshM1993** [snowflakedb/snowflake-connector-python#55]
Hi smtakeda
i made a script for loading the data from sql server to snowflake we have tried to load 1.5millions to record into snowflake and that worked fine for me but it took more than half hour to perform it and load the data in chunks i.e chunksize= 15000 i believe it snowflake limitation is 16000 .
so i want to load 50 millions of data into snowflake with python script
my question is how we can increase the chunksize of snowflake and and how can increase the performance .
please suggest?

below is the code

```
import pandas as pd
from sqlalchemy import *
import snowflake.connector

try:
  # ms Sql Connnection
  mssql_engine = create_engi@localhost:1433/testdb')
  conn = mssql_engine.connect()
  print "Connected To Ms SQl using Sql Alchemy..."

# Snowflake connector
  snowflake_conn = 
  snowflake.connector.connect(user='account=',)
  snowflake_cursor = snowflake_conn.cursor()
  print "Connected to Snowflake..."

  if snowflake_cursor:
    snowflake_cursor.execute("CREATE DATABASE IF NOT EXISTS ms_to_sql_testdb")
    snowflake_cursor.execute("USE DATABASE ms_to_sql_testdb")
    snowflake_cursor.execute("CREATE SCHEMA IF NOT EXISTS ms_to_sql_testdb_schema")
    snowflake_cursor.execute("USE SCHEMA ms_to_sql_testdb_schema")

    # Snow Flake SQL Alchemy connection
    snw_flk_engine = create_engine(
        'snowflake://{user}:{password}@{account}/{db}'.format(user,account='decisionminds', db='ms_to_sql_testdb'))
    snw_flk_conn = snw_flk_engine.connect()
    print "Connected to SQL Alchemy..."
    #  for loop to fetch dataframe

    if snw_flk_conn:
        count = 1
        for data in pd.read_sql_query('SELECT * FROM onelakhrecords', conn,chunksize=16000):
            results = data.to_sql("onelakhrecords", snw_flk_conn, if_exists='append',index=False,index_label=None, schema='ms_to_sql_testdb_schema')
            print str(count) + ' Chunk Uploaded...'
            count += 1
        print 'data uploaded successfully'
    else:
        print "Snow Flake Connection error"
else:
    print "An error occured while inserting a table"
except Exception as error:
  print error
  print "Connection error"

finally:
  snowflake_cursor.close()
  conn.close()
  snw_flk_conn.close()
```
 @smtakeda
 Collaborator
smtakeda commented 10 minutes ago
@RiteshM1993 the limitation came from the size of SQL, e.g., INSERT INTO followed by all data in a single statement implemented in executemany

can you try the connection parameter paramstyle=qmark? It is undocumented, but I believe it is worth to try. Binding data happens in the server end instead of composing a sql in the clients

If any issue is found, please file a new issue. This is issue was already closed, so it would be easier for us to track the open issue separately.
@RiteshM1993
  
            
 
Write

**Comment by RiteshM1993** [comment]
@smtakeda , can you please do changes in the above code as you want me to do.

**Comment by smtakeda** [comment]
Reformatted the code and removed the password.
@RiteshM1993, Sorry I tried it myself and hit some issue. Let me fix it and back to you later.

**Comment by smtakeda** [comment]
Ok, I found a cause of failure in Python Connector when using `qmark` paramstyle along with SQLAlchemy. Running tests with the fix.

@RiteshM1993, do you mind waiting for the release? If not, I can push the change to a branch so that you can build a package and try.

**Comment by smtakeda** [comment]
FYI, a quick perf test shows it will improve 1.5x.

If you want to try, I'll give the detail instruction how to build and change your application as well.

**Comment by RiteshM1993** [comment]
can you please send me the working code ?

**Comment by smtakeda** [comment]
Python connector 1.5.1 is available:
https://pypi.python.org/pypi/snowflake-connector-python/

Add this line right after, `import snowflake.connector`

```
snowflake.connector.paramstyle='qmark'
```

so that the binding will happen with `?` instead of `%s`

**Comment by smtakeda** [comment]
@RiteshM1993 hi, did you have a chance to try 1.5.1? All you have to do is add one line
```
snowflake.connector.paramstyle='qmark'
```
