### ISSUE TITLE
SNOW-232587: can not install airflow 1.10.13 with snowflake connector - requests package conflicts

### ISSUE THREAD

**Issue by dark-spark2** [snowflakedb/snowflake-connector-python#550]
Hi, 
I a m using python 3.7.9 with airflow 1.10.13.
I can not install snowflake-connector-python because the requirements for airflow 1.10.13
conflicts with the following message:
The conflict is caused by:
    The user requested requests==2.24.0
    apache-airflow 1.10.13 depends on requests<3 and >=2.20.0
    retry-requests 1.0.0 depends on requests
    snowflake-connector-python 2.3.6 depends on requests<2.24.0
please bump requests to  <=2.24.0

Thanks!

**Comment by sfc-gh-mkeller** [comment]
It seems to me like it should work. See https://github.com/apache/airflow/blob/67acdbdf92a039ba424704e2f9b4dc67a914f3bb/setup.cfg#L124

The Apache people were nice enough to introduce a `snowflake` specific dependency group to work with Snowflake as well. https://github.com/apache/airflow/blob/67acdbdf92a039ba424704e2f9b4dc67a914f3bb/setup.py#L398

Do you use a requirements file to install dependencies?

**Comment by dark-spark2** [comment]
Hi,
this is the requirement file for 1.10.13 (may be the fix is on future version):
[(https://github.com/apache/airflow/blob/1.10.13/requirements/requirements-python3.7.txt)]
Thanks:)

**Comment by sfc-gh-mkeller** [comment]
I don't think airflow ever stopped supporting compatibility with 2.23.0, they just pinned newest available version because why not.
It should be safe for you to change `requests==2.24.0` to `requests==2.23.0` in the requirements file.
