### ISSUE TITLE
SNOW-240336: Add support for Python 3.9

### ISSUE THREAD

**Issue by idanw206** [snowflakedb/snowflake-connector-python#562]
Hi!

As of now, the package can't be installed on Python 3.9

I believe that it'll be quite easy after `pyarrow` will officially support Python 3.9 (Either by uploading a new version to pypi or merging this PR: https://github.com/apache/arrow/pull/8386)

Thanks!

**Comment by hhmahmood** [comment]
When we are expecting snowflake-connector-python support for python 3.9?

**Comment by idanw206** [comment]
Related to #610
