### ISSUE TITLE
SNOW-277252: Alembic revision fails with 'qmark' paramstyle due to binding parameter issue

### ISSUE THREAD

**Issue by jamesoswald-dyno** [snowflakedb/snowflake-connector-python#622]
1. What version of Python are you using (`python --version`)?
Python 3.7.7
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Darwin-19.4.0-x86_64-i386-64bit
3. What are the component versions in the environment (`pip freeze`)?

snowflake-connector-python==2.3.7
snowflake-sqlalchemy==1.2.4
SQLAlchemy==1.3.18
alembic==1.4.1

4. What did you do?
    Set snowflake.connector.paramstyle = 'qmark' globally
    Run alembic revision --autogenerate -m "initial revision"

5. What did you expect to see?
     an alembic_version table is created in snowflake.

6. What did you see instead?
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 252004: Binding parameters must be a list: {'table_schema': 'DATA_WAREHOUSE'}
[SQL:
            SELECT /* sqlalchemy:_get_schema_columns */
                   ic.table_name,
                   ic.column_name,
                   ic.data_type,
                   ic.character_maximum_length,
                   ic.numeric_precision,
                   ic.numeric_scale,
                   ic.is_nullable,
                   ic.column_default,
                   ic.is_identity,
                   ic.comment
              FROM information_schema.columns ic
             WHERE ic.table_schema=%(table_schema)s
             ORDER BY ic.ordinal_position]
[parameters: {'table_schema': 'DATA_WAREHOUSE'}]

**Comment by sfc-gh-mkeller** [comment]
Ahh, I think this is connected to https://github.com/snowflakedb/snowflake-sqlalchemy/pull/209
Which I ran, but it had some issues. I'll revisit it when I get some time. Let's move this conversation there!
