### ISSUE TITLE
SNOW-286452: Could you release a new version of snowflake-connector-python with python 3.9 support?

### ISSUE THREAD

**Issue by fday** [snowflakedb/snowflake-connector-python#630]
## What is the current behavior?
The latest version of snowflake-connector-python (2.3.10) does not officially support python 3.9 and does not have wheels for cp39 in pypi.org.

## What is the desired behavior?
1. snowflake-connector-python supports python 3.9 (seems it was implemented here https://github.com/snowflakedb/snowflake-connector-python/pull/565).
2. snowflake-connector-python in pypi.org has wheels for cp39 (https://pypi.org/project/snowflake-connector-python/#files)

**Comment by sfc-gh-mkeller** [comment]
Next scheduled release is at the beginning of March. It's coming soon!
