### ISSUE TITLE
SNOW-298002: Feature Request : Is there a way to mask queries with sensitive information like passwords ?

### ISSUE THREAD

**Issue by tamathew** [snowflakedb/snowflake-connector-python#651]
Is there a way to mask certain queries within a query history?

**Comment by sfc-gh-mheimel** [comment]
@tamathew Snowflake automatically redacts sensitive arguments to certain functions (e.g. the passphrase/password or clear text passed to ENCRYPT/DECRYPT/ENCRYPT_RAW/DECRYPT_RAW) in the query logs. If you can still see these values in the history, it would be a bug that needs to be fixed. Did you encounter a case where arguments to these functions show up in the query history?
