### ISSUE TITLE
SNOW-300853: snowflake-connector-python[pandas] size too large for AWS Lambda

### ISSUE THREAD

**Issue by Dhruv-Shah913** [snowflakedb/snowflake-connector-python#660]
I am using Python Version 3.7 and trying to use snowflake-connector-python[pandas] version 2.4.1

The issue is that I cannot add a snowflake-connector-python[pandas] layer to aws lambda as it complains that the file size is too large. I tried many alternative techniques for trying to upload this module to lambda, such uploading the lambda through a zip file with the snowflake-connector-python[pandas] library and its dependencies installed. Removing the pyarrow dependency was not an option for me as I needed it for my project.

I was wondering if future releases for snowflake-connecter-python[pandas] will smaller in size or if there is any workaround to use this library on aws lambda.

**Comment by sfc-gh-mkeller** [comment]
@sfc-gh-sbasavana could you help out here? How do we deploy the Python connector on AWS Lambda successfully?

**Comment by sfc-gh-sbasavana** [comment]
We use serverless framework for deploying lambda functions and in the framework we use serverless plugin called "serverless-python-requirements".  We specify the  snowflake-connector-python package in the requirements.txt file and the plugin takes care of making the modules available in the right path for the function to use. 
We use something like this in our serverless.yml - 

```
plugins:
    - serverless-python-requirements

custom:
    pythonRequirements:
        dockerizePip: non-linux
```

Helpful links for additional info:
[](https://www.serverless.com/plugins/serverless-python-requirements)
[](https://www.serverless.com/blog/serverless-python-packaging)

**Comment by Dhruv-Shah913** [comment]
@sfc-gh-sbasavana have you tried to import snowflake-connector-python[pandas] library specifically to aws Lambda using the serverless framework? The library size is ~300mb and the lambda limit is 256mb.

**Comment by plotneishestvo** [comment]
We started to use AWS lambdas with Docker because of libraries size: https://docs.aws.amazon.com/lambda/latest/dg/images-create.html
Also, you can try to use pyarrow 3.0.0 it has smaller size from 200+ mb to around 30 but I guess it is anyway too big if we add pandas to that

**Comment by sfc-gh-mkeller** [comment]
> Also, you can try to use pyarrow 3.0.0 it has smaller size from 200+ mb to around 30 but I guess it is anyway too big if we add pandas to that

@plotneishestvo we do https://github.com/snowflakedb/snowflake-connector-python/blob/765d0fe50755179d953113241df76388895f2a92/setup.py#L46

> I was wondering if future releases for snowflake-connecter-python[pandas] will smaller in size or if there is any workaround to use this library on aws lambda.

Yes, this is in our work queue.

**Comment by uyankdi** [comment]
@sfc-gh-mkeller Any update on when this will be released?

**Comment by sfc-gh-jbahk** [comment]
Hello, we've reduced the package size considerably but unfortunately pyarrow 5.0.0 (our latest requirement) is 80MB. We will continue to look into this.

**Comment by abdurrahman160903** [comment]
Here are some useful links:
https://ff-tools.blogspot.com/2023/06/importing-snowflake-python-libraries-in.html
