### ISSUE TITLE
SNOW-352499: cursor.execute_async(<stmt>, timeout) stops after 300s (5 mins)

### ISSUE THREAD

**Issue by paupinger** [snowflakedb/snowflake-connector-python#700]
## Working with:
- Python 3.8.0
- macOS-10.16-x86_64-i386-64bit
- snowflake-connector-python==2.4.2

## Issue:

The `timeout` parameter does not change the `queryAbortsAfterSecs` parameter, hence all queries that run longer than 300 seconds get cancelled by snowflake.

However this behaviour is governed by the ABORT_DETACHED_QUERY parameter on snowflake.

## Expected behaviour:

`timeout` parameter changes the `queryAbortsAfterSecs` parameter when running async queries, such that longer queries (>300s) can be run asynchronously.

## Solution/Workaround:

alter session set ABORT_DETACHED_QUERY = false

**Comment by sfc-gh-hkapre** [comment]
@paupinger can you provide a code sample to reproduce? This should only be an issue if the session is somehow terminated. We would like to see your code to determine if there might be an issue on our side with the session handling.

**Comment by sfc-gh-hkapre** [comment]
Please reopen if this is still an issue.
