### ISSUE TITLE
SNOW-353738: Support idna > 3

### ISSUE THREAD

**Issue by fabaff** [snowflakedb/snowflake-connector-python#705]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

3.8/3.9

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

NixOS, all platforms

3. What are the component versions in the environment (`pip freeze`)?

N/A

4. What did you do?

Build `snowflake-connector-python`

5. What did you expect to see?

The build of the package to complete

6. What did you see instead?

Build failure as [idna](https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py#L225) has a constraints. `idna-3.0` dropped support for [Python 2](https://github.com/kjd/idna/blob/master/HISTORY.rst), thus at first glance allowing `idna>3.0` should work as the min. requirement is [Python 3.6](https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py#L203).

**Comment by sfc-gh-mkeller** [comment]
Hi @fabaff 
It should yes, but it doesn't: https://github.com/snowflakedb/snowflake-connector-python/pull/609

**Comment by sfc-gh-hkapre** [comment]
We are looking into this one as part of #609
