### ISSUE TITLE
SNOW-363198: setup.py defines two certifi package versions

### ISSUE THREAD

**Issue by jsyrjala** [snowflakedb/snowflake-connector-python#732]
setup.py defines two `certifi` versions

- `certifi<2021.0.0`
  located at: https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py#L214
- `certifi>=2017.4.17`
 located at: https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py#L230

Both of those rules resolved to same version `2020.12.5` until recently. Now two days ago `certifi` 2021.5.30 was released: https://pypi.org/project/certifi/#history

Now following is possible:
- some app installs latests certifi package, getting version 2021.5.30
- installing snowflake-connector-python fails because it wants certifi<2021.0.0

Is there a reason for disallowing certifi 2021 versions? Is it a good practice to have several times the same package in `install_requires` with differing version restrictions?

**Comment by jsyrjala** [comment]
Seems that there already is a PR fixing this issue #730

**Comment by jowparks** [comment]
Same issue reporting here:
https://github.com/snowflakedb/snowflake-connector-python/issues/734
We will need a release to fix this.

**Comment by sfc-gh-mkeller** [comment]
Hi guys, please be aware that you can always very easily install the newest master code by running the following command:
`pip install "git+https://github.com/snowflakedb/snowflake-connector-python.git@main#egg=snowflake-connector-python"`

**Comment by jowparks** [comment]
This doesn’t work for productionized builds that use pypi as a source. I am using this package in an automated docker image build.

**Comment by jsyrjala** [comment]
#730 fixed this by setting `certifi<2022.0.0>=2017.4.17`, which means that in year 2022 or later we'll have this exact problem again when certifi 2022.x.x gets released.

**Comment by ClassyLion** [comment]
Why is it even necessary to define both upper and lower limits for certifi version? I was looking for the reason why in Pipelinewise, our deploy is breaking due to certifi version issues. Came across this and it seems strange that both lower and upper limit is defined.

**Comment by sfc-gh-mkeller** [comment]
You are right, I've made a mistake by bumping the upper pin instead of removing it. Correcting my mistake right now!
