### ISSUE TITLE
SNOW-365365: error executemany()

### ISSUE THREAD

**Issue by lemonsong** [snowflakedb/snowflake-connector-python#742]
when running the [example code ](https://docs.snowflake.com/en/user-guide/python-connector-api.html#executemany), it returns error.
Code:
```
stmt1 = "create table testy (V1 varchar, V2 varchar)"
cur.execute(stmt1)

# A list of lists
sequence_of_parameters1 = [ ['Smith', 'Ann'], ['Jones', 'Ed'] ]
# A tuple of tuples
sequence_of_parameters2 = ( ('Cho', 'Kim'), ('Cooper', 'Pat') )

stmt2 = "insert into testy (v1, v2) values (?, ?)"
cur.executemany(stmt2, sequence_of_parameters1)
cur.executemany(stmt2, sequence_of_parameters2)
```
Error message:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/code/launch_kernel.py in <module>()
      8 
      9 stmt2 = "insert into testy (v1, v2) values (?, ?)"
---> 10 cur.executemany(stmt2, sequence_of_parameters1)
     11 cur.executemany(stmt2, sequence_of_parameters2)

/usr/local/lib/python3.7/dist-packages/snowflake/connector/cursor.py in executemany(self, command, seqparams)
    785                     logger.debug(u'parameter: %s', param)
    786                     values.append(fmt % self._connection._process_params(
--> 787                         param, self))
    788                 command = command.replace(fmt, u','.join(values), 1)
    789                 self.execute(command)

TypeError: not all arguments converted during string formatting

**Comment by juhap** [comment]
Try setting the params style to question marks (qmark) before running your code

```` 
from snowflake import connector
connector.paramstyle='qmark' 
````

**Comment by sfc-gh-mkeller** [comment]
@juhap is correct

@sfc-gh-dyoshinaga could we update the documentation linked here to include the bit posted by @juhap

**Comment by onerishabh** [comment]
Hi @sfc-gh-dyoshinaga , 

This is my first ever request on Github to work on an issue. I have been developing using this tool for over a year at work. 

Is it possible that I try my hand at this issue?

**Comment by sfc-gh-dyoshinaga** [comment]
Hi @onerishabh , thank you. The documentation is actually in a separate private repository. I've sent @sfc-gh-mkeller a fix for the documentation.

**Comment by sfc-gh-mkeller** [comment]
@onerishabh if you would like to contribute feel free to look at the issues marked with the following label https://github.com/snowflakedb/snowflake-connector-python/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22
