### ISSUE TITLE
SNOW-366546: write_pandas not working when column names are numeric

### ISSUE THREAD

**Issue by jhockx** [snowflakedb/snowflake-connector-python#745]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.7.9

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Windows-10-10.0.19041-SP0

3. What are the component versions in the environment (`pip freeze`)?
```
asn1crypto==1.4.0
azure-common==1.1.27
azure-core==1.15.0
azure-storage-blob==12.8.1
boto3==1.17.90
botocore==1.20.90
certifi==2021.5.30
cffi==1.14.5
chardet==3.0.4
cryptography==3.4.7
idna==2.10
isodate==0.6.0
jmespath==0.10.0
msrest==0.6.21
numpy==1.20.3
oauthlib==3.1.1
oscrypto==1.2.1
pandas==1.2.4
pyarrow==3.0.0
pycparser==2.20
pycryptodomex==3.10.1
PyJWT==2.1.0
pyOpenSSL==20.0.1
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
requests-oauthlib==1.3.0
s3transfer==0.4.2
six==1.16.0
snowflake-connector-python==2.4.4
urllib3==1.26.5
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
from snowflake.connector.pandas_tools import write_pandas
df = pd.DataFrame([['adsf', 'dfjk'], ['bla', 'blabla']], columns=['1', '2'])
write_pandas(conn, df=df, database=database, schema=schema, table_name=table)
```
Where `conn`, `database`, `schema` and `table_name` are defined elsewhere. Before the statements above are run, a table is created using a CREATE OR REPLACE TABLE "schema"."table" while using the correct database. Making the table is done with the same user, so there are no privilege problems.

5. What did you expect to see?
To see the data added in the table like it normally would. If the column names are non-numeric, e.g. `df = pd.DataFrame([['adsf', 'dfjk'], ['bla', 'blabla']], columns=['a', 'b'])`, `write_pandas` just works as it should.

6. What did you see instead?
```
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 129 unexpected '1'.
syntax error line 1 at position 134 unexpected '2'.
```

7. Can you set logging to DEBUG and collect the logs?
There are no extra logs

**Comment by sfc-gh-mkeller** [comment]
Hi @jhockx
I have a fix for your issue in the branch `mkeller-SNOW-299658-quote_column_names`, but since this is a potential breaking change the fix will only be released next month, once we given enough of a heads up to everyone to update their code usages.

**Comment by jhockx** [comment]
Great, thanks for the fix!
