### ISSUE TITLE
SNOW-366691: Is there a python 3.9 requirements file or python 3.9 support?

### ISSUE THREAD

**Issue by olvgrolle** [snowflakedb/snowflake-connector-python#746]
## What is the current behavior?
the snowflake python connector provides a requirements file  up to python 3.8

## What is the desired behavior?
the snowflake python connector should provide a requirements file for python 3.9 - (released 2020-10-05, 9 month ago).

## How would this improve `snowflake-connector-python`?
snoflake-connector-python could be used with the currently recommended version of python

## References, Other Background
https://www.python.org/downloads/ see for python 3.9 release date.

**Comment by sfc-gh-mkeller** [comment]
Hi, @olvgrolle
Yes, we support 3.9!

Those requirements files haven't been updated in a while, I want to move their creation and update over from our internal workflow to our public GH actions.

**Comment by olvgrolle** [comment]
Very nice - in fact I have now tried the 3.8 requirements file on 3.9 and that indeed works, but it probably not optimal. 
It uninstalled a bunch of newer releases of the required packages… 
If you have a newer requirements file or a different way to install (I followed the snowflake python doc), I’d be happy to close this issue.

**Comment by sfc-gh-hkapre** [comment]
Will get this updated shortly.

**Comment by sfc-gh-mkeller** [comment]
Hi @olvgrolle 
I have updated the requirements files in: https://github.com/snowflakedb/snowflake-connector-python/commit/fb52f054246701052deaa8b587f669cc09325b24
Please find them here: https://github.com/snowflakedb/snowflake-connector-python/tree/master/tested_requirements
