### ISSUE TITLE
SNOW-368531: Corrupted dates with executemany

### ISSUE THREAD

**Issue by juhap** [snowflakedb/snowflake-connector-python#750]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

Python 3.8.5

2. What operating system and processor architecture are you using?

Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29 (Ubuntu 20.04 under WSL2)

3. What are the component versions in the environment?

asn1crypto==1.4.0
azure-common==1.1.27
azure-core==1.15.0
azure-storage-blob==12.8.1
boto3==1.17.94
botocore==1.20.94
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
cryptography==3.4.7
idna==2.10
install==1.3.4
isodate==0.6.0
jmespath==0.10.0
msrest==0.6.21
oauthlib==3.1.1
oscrypto==1.2.1
pycparser==2.20
pycryptodomex==3.10.1
PyJWT==2.1.0
pyOpenSSL==20.0.1
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
requests-oauthlib==1.3.0
s3transfer==0.4.2
six==1.16.0
snowflake-connector-python==2.4.4
urllib3==1.26.5

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```
import datetime
import logging
import os

from snowflake import connector


def test():
    # This will pick the connection information from env variables like SNOWFLAKE_USER etc.
    variables = ['account', 'user', 'password', 'database', 'schema', 'role', 'warehouse']
    envprefix = 'SNOWFLAKE'
    names = dict({f:f'{envprefix}_{f.upper()}' for f in variables})
    params = dict({name: os.environ.get(env_name, None) for name, env_name in names.items()})
    connector.paramstyle='qmark'
    connection = connector.connect(**params)
    cursor = connection.cursor()

    # Before running create a test table in Snowflake
    """"
    create table date_test (
        birth_date date
    );
    """

    # Insert 1969-02-07
    cursor.executemany(
        'INSERT INTO date_test (birth_date) values (?)',
        [[datetime.date(1969, 2, 7)]]
    )
    cursor.close()

    # Insert 1969-01-01
    cursor = connection.cursor()
    cursor.executemany(
        'INSERT INTO date_test (birth_date) values (?)',
        [[datetime.date(1969, 1, 1)]]
    )
    cursor.close()

    # Insert 1969-02-07 and 1969-01-01
    cursor = connection.cursor()
    cursor.executemany(
        'INSERT INTO date_test (birth_date) values (?)',
        [[datetime.date(1969, 2, 7)],[datetime.date(1969, 1, 1)]]
    )
    cursor.close()

if __name__ == '__main__':
    for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']:
        logger = logging.getLogger(logger_name)
        logger.setLevel(logging.DEBUG)
        ch = logging.StreamHandler()
        ch.setLevel(logging.DEBUG)
        ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
        logger.addHandler(ch)

    test()

```
5. What did you expect to see?

Selecting the inserted dates from the database, with `SELECT birth_date FROM date_test` I would expect to see
```
1969-02-07
1969-01-01
1969-02-07
1969-01-01
```

6. What did you see instead?
```
1071-12-20
1969-01-01
1071-12-20
0970-08-31
```

It seems to be that something goes wrong with some specific dates, for example 1969-02-07. When this happens, also other dates inserted with same executemany get corrupted. This seems to happen only when datetime.date is used. Specifying the dates as strings ("1969-02-07") works fine. 

7. Can you set logging to DEBUG and collect the logs?

I can provide log if needed.

**Comment by sfc-gh-hkapre** [comment]
@juhap We are looking into this one.
