### ISSUE TITLE
SNOW-392648: Warehouse name is forced to be uppercase

### ISSUE THREAD

**Issue by jesumyip** [snowflakedb/snowflake-connector-python#795]
Using version 2.4.6 of the Snowflake library, and Python v3.7.3.

Consider the code snippet below:

```
import snowflake.connector as sf

const_dbUser = "TEST_USER"
const_dbPassword = "SOMEPASSWORD"
const_dbRole = "TEST_ROLE"
const_dbSchema = "TEST_SCHEMA"

dbName = "123-abc_MYDB"
dbWarehouse = "123-abc_MYWH"

ctx = sf.connect(
	user=const_dbUser,
	password=const_dbPassword,
	account="xxxxxxx.xxxxxx",
	warehouse=dbWarehouse,
	database=dbName,
	role=const_dbRole,
	schema=const_dbSchema)

```
After executing the code above, I run

`print (ctx.warehouse)`

and I see the output as “123-ABC_MYWH”. Using the `ctx` object to issue SELECT statements causes an error:

`sferror :  000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.`

If I then do this prior to issuing the SELECT statement:

```
warehousestring = "USE WAREHOUSE \"" + dbWarehouse + "\""
ctx.cursor().execute(warehousestring)
```

I am able to retrieve data from Snowflake. Also, after executing the USE command above, printing ctx.warehouse now shows "123-abc_MYWH" (as opposed to "123-ABC_MYWH").

**Comment by sfc-gh-mkeller** [comment]
Hi @jesumyip
I just took a look and it looks like you should be able to surround your warehouse name with double quotes to get the expected behavior.
Could you try doing `dbWarehouse = "\"123-abc_MYWH\""` and let me know if this works for you?

Here's my full reproduction code:
```python

CONNECTION_PARAMETERS = {
    "account": redacted,
    "warehouse": '"mkellerTest"',
}

with snowflake.connector.connect(**CONNECTION_PARAMETERS) as cnx:
    with cnx.cursor() as cur:
        print(cnx.warehouse)
        cur.execute(f"select current_warehouse()")
        print(cur.fetchall())
        cur.execute(f"select 1/2;")
        print(cur.fetchall())
```

**Comment by jesumyip** [comment]
Thank you mkeller. That seems to do the trick.
