### ISSUE TITLE
SNOW-406936: Add aarch64 wheels support

### ISSUE THREAD

**Issue by tbbharaj** [snowflakedb/snowflake-connector-python#808]
Summary: 
Installing snowflake-connector-python on aarch64 via pip using command "pip3 install snowflake-connector-python" tries to build wheel from source code which also fails due to pyarrow wrong version dependency.

Problem: 
1. snowflake-connector-python doesn't have wheel for aarch64 on PyPI repository. 
2. Need to update pyarrow version while building aarch64 wheels

This PR: https://github.com/snowflakedb/snowflake-connector-python/pull/801 addresses the issue to build and publish aarch64 wheels for snowflake connector

**Comment by sfc-gh-hkapre** [comment]
Officially releasing arm builds is something we are looking into based on demand, but this is not currently in plan.

We're happy to bump any dependency to assist you building the connector for arm in the short term. If the associated PR does not address this, we will work with you to see how we can help unblock this.

**Comment by sfc-gh-hkapre** [comment]
Closing for now. We don't yet have a plan for ARM support.

**Comment by tbbharaj** [comment]
@sfc-gh-hkapre I understand you may not have a plan for ARM support but I have this PR #801, if this looks good to you, do you think we can have this PR merged so that we can get wheels available for ARM
