### ISSUE TITLE
SNOW-414668: Add support for pyarrow 5.0

### ISSUE THREAD

**Issue by ruiyang2015** [snowflakedb/snowflake-connector-python#815]
we have other code that depends on pyarrow 5.0, but snowflake is pined at 3.0.0, wondering if it is possible to upgrade the dep of snowflake python connector to the latest pyarrow 5.0

**Comment by sfc-gh-kterada** [comment]
We are looking to provide this functionality in the September timeframe.

**Comment by mdagost** [comment]
I'd like to add a bump to this issue.  There are quite a few problems installing older versions of pyarrow on M1 Mac's, which basically means it's impossible to use the snowflake python connector on M1 Mac's.  September seems like a pretty long timeframe to be 2 major versions behind.

**Comment by mdagost** [comment]
I've asked pyarrow if they can help, but right now anybody that is getting a new Apple laptop with Apple silicon is going to be unable to use the snowflake client, which seems not great...

https://issues.apache.org/jira/browse/ARROW-13583

**Comment by sfc-gh-mkeller** [comment]
> September seems like a pretty long timeframe to be 2 major versions behind.

@mdagost We apologize for the inconvenience, #817 will address the issue as soon as possible. In the meantime if you need this immediately you can install the code from the PR's branch with `pyarrow>=5.0.0` with the following command:

```console
python -m pip install git+https://github.com/snowflakedb/snowflake-connector-python.git@mkeller-SNOW-414668-bump_pyarrow_5
```

Please note that you should have the following things up to date: `python -m pip install -U pip setuptools wheel` and that you'll need a compiler for our C++ code (if these are not available see the next part of this post).

We have a good reason for being 2 major versions behind, there was a build bug in Arrows `4.x.x` releases. Please see the conversation here: https://github.com/snowflakedb/snowflake-connector-python/pull/762#issuecomment-863528241 and link to the Arrow Jira ticket for a more detailed description of what was happening.

> which basically means it's impossible to use the snowflake python connector on M1 Mac's

Our team made sure that the connector can be installed without `pyarrow` and our compiled C++ code.
You can use the following command to install the `2.5.1` version with only the pure Python parts:

```console
python -m pip install --no-use-pep517 git+https://github.com/snowflakedb/snowflake-connector-python.git@v2.5.1
```

Please be aware that `pandas` functionality will be unavailable and the connector will be using JSON for retrieving results (which is less efficient than arrow).
