### ISSUE TITLE
Add option to specify location for temporary files created for PUT commands

### ISSUE THREAD

**Issue by munircontractor** [snowflakedb/snowflake-connector-python#84]
When PUT command is executed from a cursor, the connector creates a temporary gzip file using Python's `tmpfile` standard library. However, since these files are created in memory, it causes out of memory errors, if the file is large and there is not enough memory on the system to accomodate the file in `/tmp`. 

Please add an option to specify alternate locations for the temporary files so larger files can be created on disk instead of in memory.

**Comment by smtakeda** [comment]
can you try `TMPDIR`, `TEMP` or `TMP` to set the temp directory?

**Comment by munircontractor** [comment]
Uhh...don't know why I didn't try that in the first place. Thanks.

**Comment by smtakeda** [comment]
please close this issue if it works.

**Comment by smtakeda** [comment]
can I close the issue? let me know.

**Comment by sachabest** [comment]
Which one of those variables sets the directory? Would be worth adding to the documentation

**Comment by smtakeda** [comment]
https://docs.snowflake.net/manuals/user-guide/python-connector-install.html#step-3-specify-a-temporary-directory
