### ISSUE TITLE
SNOW-440448: Auto-close of the browser tab on success

### ISSUE THREAD

**Issue by MarcinZukowski** [snowflakedb/snowflake-connector-python#840]
## What is the current behavior?
When I connect to Snowflake multiple times, each connection opens a new tab. After some time I often find myself having many "SAML Response" tabs just filling up my browser.

## What is the desired behavior?
I would like an option to have the "SAML Response" tabs auto-close, perhaps only on success.
I assume this would need to be optional.

## How would this improve `snowflake-connector-python`?
Make it more user-friendly, IMO.

## References, Other Background

Example change I did in my local sources:

```diff
--- a/src/snowflake/connector/auth_webbrowser.py
+++ b/src/snowflake/connector/auth_webbrowser.py
@@ -216,7 +216,9 @@ class AuthByWebBrowser(AuthByPlugin):
         else:
             msg = """
 <!DOCTYPE html><html><head><meta charset="UTF-8"/>
-<title>SAML Response for Snowflake</title></head>
+<title>SAML Response for Snowflake</title>
+<script>setTimeout(window.close, 5000);</script>
+</head>
 <body>
 Your identity was confirmed and propagated to Snowflake {}.
 You can close this window now and go back where you started from.
```

**Comment by sfc-gh-hkapre** [comment]
@MarcinZukowski Closing this for now. Please confirm once you have had a chance to test out the SSO Token Cache feature which should cover this.
