### ISSUE TITLE
SNOW-452575: Replace pyopenssl with python's default ssl implementation

### ISSUE THREAD

**Issue by thomasaarholt** [snowflakedb/snowflake-connector-python#857]
## What is the current behavior?
`snowflake-connector-python` will not run on M1 Macs (Silicon, Arm processor): See #799 and  dbt-labs/dbt#3722.
That error is due to pyca/pyopenssl#873. [This comment](https://github.com/pyca/pyopenssl/issues/873#issuecomment-915146615) implies that a fix will not be forthcoming, and that it would be better to swap out the relevant pyopenssl functionality for [Python's built-in SSL library](https://docs.python.org/3/library/ssl.html). Would this be possible?

## What is the desired behavior?
A functioning snowflake-connector-python on M1 macs.

## How would this improve `snowflake-connector-python`?
Macs are heavily used in the data science world. At the moment, one has to run dbt through the rosetta emulator in order to run it on Mac, which makes it very difficult for non-technical users to use `snowflake-connector-python` or one of its dependants. One currently either has to [install brew in rosetta and then dbt in that](https://github.com/dbt-labs/dbt/issues/3722#issuecomment-897432525), or miniconda in rosetta and dbt in that).

**Comment by sfc-gh-hkapre** [comment]
@thomasaarholt This is not currently possible due to our use of OCSP. We are starting to look into what will be needed to support M1 and will provide an update once we have completed our analysis.

**Comment by sfc-gh-mkeller** [comment]
Same thing as in https://github.com/snowflakedb/snowflake-connector-python/issues/799#issuecomment-1115353505
Please reach out if the issue still persists for some reason!

**Comment by jpzhangvincent** [comment]
Ya using "snowflake-connector" on Mac M1 is really challenging . Is it possible to remove the "pyopenssl" dependencies?

**Comment by sfc-gh-achandrasekaran** [comment]
Please follow this [workaround](https://docs.snowflake.com/en/developer-guide/snowpark/python/setup.html#prerequisites) on M1 machines
