### ISSUE TITLE
SNOW-454134: Parameters do not support lists of dates.

### ISSUE THREAD

**Issue by stevebeck89** [snowflakedb/snowflake-connector-python#858]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Replace with the output of `2.5.0`

2. What operating system and processor architecture are you using?

   Replace with the output of `Darwin-20.6.0-x86_64-i386-64bit`

3. What are the component versions in the environment (`pip freeze`)?

   N/A

4. What did you do?

   Execute SQL with pyformat params that contain lists of dates.  For example
   ```sql
   SELECT *
   FROM MY_TABLE
   WHERE DATE_COLUMN in (%s);
   ```
   with params: `([datetime.date(2021, 9, 7), datetime.date(2021, 9, 8)])`
   
   Here is the bit of the converter that is not working as intended.
   ```py
   import datetime
   from snowflake.connector.converter import SnowflakeConverter
   converter = SnowflakeConverter()
   assert converter.to_snowflake(['asdd']) == ["'asdd'"]
   assert converter.to_snowflake(datetime.date(2021, 9, 7)) == '2021-09-07'
   assert converter.to_snowflake([datetime.date(2021, 9, 7)]) == ["'2021-09-07'"]
   assert converter.to_snowflake([datetime.date(2021, 9, 7), datetime.date(2021, 9, 8),]) == ["'2021-09-07'", "'2021-09-08'"]
   assert converter.to_snowflake([1, 2,]) == ['1', '2']
   ```
  
   Today this results in:
   ```py
    Traceback (most recent call last):
      File "paramstest.py", line 17, in <module>
        assert converter.to_snowflake([datetime.date(2021, 9, 7)]) == ["'2021-09-07'"]
      File "../site-packages/snowflake/connector/converter.py", line 426, in to_snowflake
        type_name=type_name))(value)
      File "../site-packages/snowflake/connector/converter.py", line 552, in _list_to_snowflake
        [SnowflakeConverter.escape(v) for v in value]]
      File "../site-packages/snowflake/connector/converter.py", line 552, in <listcomp>
        [SnowflakeConverter.escape(v) for v in value]]
      File "../site-packages/snowflake/connector/converter.py", line 599, in escape
        res = res.replace('\\', '\\\\')
    TypeError: an integer is required (got type str)
   ```

5. What did you expect to see?

   The above asserts should all pass.  The connector should handle parameters with lists fully.  It only supports lists of simple types at the moment.

6. Can you set logging to DEBUG and collect the logs?

   N/A

**Comment by chamini2** [comment]
Can we reopen this issue?
