### ISSUE TITLE
SNOW-456633: Environment variables for proxy being ignored

### ISSUE THREAD

**Issue by mosqueteiro** [snowflakedb/snowflake-connector-python#865]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0]

2. What operating system and processor architecture are you using?

inside docker container: Linux-5.10.47-linuxkit-x86_64-with-debian-bullseye-sid

3. What are the component versions in the environment (`pip freeze`)?

adal==1.2.7
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1623682242266/work
amply @ file:///home/conda/feedstock_root/build_artifacts/amply_1601814141062/work
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1626998551461/work/dist
argcomplete @ file:///home/conda/feedstock_root/build_artifacts/argcomplete_1619128689661/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1610522577486/work
asn1crypto @ file:///home/conda/feedstock_root/build_artifacts/asn1crypto_1595949944546/work
astroid @ file:///home/conda/feedstock_root/build_artifacts/astroid_1630357317673/work
async-generator==1.10
async-timeout==3.0.1
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work
azure-common @ file:///home/conda/feedstock_root/build_artifacts/azure-common_1616832252463/work
azure-core @ file:///home/conda/feedstock_root/build_artifacts/azure-core_1621242197799/work
azure-storage-blob @ file:///home/conda/feedstock_root/build_artifacts/azure-storage-blob_1619120215689/work
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1619719576210/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.entry-points-selectable==1.1.0
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
black @ file:///home/conda/feedstock_root/build_artifacts/black-recipe_1630308806869/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1629908509068/work
blinker==1.4
boto3 @ file:///home/conda/feedstock_root/build_artifacts/boto3_1631269309670/work
botocore @ file:///home/conda/feedstock_root/build_artifacts/botocore_1631258106597/work
brotlipy==0.7.0
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1619593780156/work
certifi==2021.5.30
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1625835301720/work
cfgv==3.3.1
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1602255309768/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1621503711357/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1616851478755/work
cycler==0.10.0
Cython==0.29.24
dataclasses @ file:///home/conda/feedstock_root/build_artifacts/dataclasses_1628958434797/work
datacompy @ file:///home/conda/feedstock_root/build_artifacts/datacompy_1613055001859/work
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1627074840854/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1621187651333/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
distlib==0.3.2
flake8 @ file:///home/conda/feedstock_root/build_artifacts/flake8_1620668104928/work
google-api-core @ file:///home/conda/feedstock_root/build_artifacts/google-api-core-split_1630497386783/work
google-auth @ file:///home/conda/feedstock_root/build_artifacts/google-auth_1630497566688/work
google-cloud-core @ file:///home/conda/feedstock_root/build_artifacts/google-cloud-core_1629901439640/work
google-cloud-storage @ file:///home/conda/feedstock_root/build_artifacts/google-cloud-storage_1629296869288/work
google-crc32c @ file:///home/conda/feedstock_root/build_artifacts/google-crc32c_1611954245352/work
google-resumable-media @ file:///home/conda/feedstock_root/build_artifacts/google-resumable-media_1630660997192/work
googleapis-common-protos @ file:///home/conda/feedstock_root/build_artifacts/googleapis-common-protos-feedstock_1616710767141/work
grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpcio_1624380491840/work
identify==2.2.14
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1630267469306/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1631195232667/work/dist/ipykernel-6.4.0-py3-none-any.whl
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1630172533129/work
ipython-genutils==0.2.0
isodate==0.6.0
isort @ file:///home/conda/feedstock_root/build_artifacts/isort_1627548912727/work
jdcal==1.4.1
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1610146791823/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1621419064915/work
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1589369830981/work
joblib==1.0.1
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1600692310011/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1614815863336/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1630336909568/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1612125257337/work
jupyter-server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1631218027728/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1631119946949/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1631050937958/work
kiwisolver==1.3.2
lazy-object-proxy @ file:///home/conda/feedstock_root/build_artifacts/lazy-object-proxy_1616506790273/work
linearmodels==4.24
lxml @ file:///home/conda/feedstock_root/build_artifacts/lxml_1616532288511/work
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1621455667184/work
matplotlib==3.4.3
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
mccabe==0.6.1
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1624941291602/work
msrest @ file:///home/conda/feedstock_root/build_artifacts/msrest_1611725634474/work
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1610319002430/work
mypy-extensions @ file:///home/conda/feedstock_root/build_artifacts/mypy_extensions_1610127163566/work
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1621947328608/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1629120697898/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert_1624472657203/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1617383142101/work
nbstripout==0.5.0
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1617163391303/work
nodeenv==1.6.0
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1628690102344/work
numpy==1.18.5
oauthlib @ file:///home/conda/feedstock_root/build_artifacts/oauthlib_1622563202229/work
openpyxl @ file:///home/conda/feedstock_root/build_artifacts/openpyxl_1615404969632/work
oscrypto @ file:///home/conda/feedstock_root/build_artifacts/oscrypto_1610205902676/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1625323647219/work
pandas==1.0.4
pandocfilters==1.4.2
parsimonious==0.8.1
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1617148930513/work
pathspec @ file:///home/conda/feedstock_root/build_artifacts/pathspec_1626613672358/work
patsy==0.5.1
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==8.3.2
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1630400214373/work
pre-commit==2.15.0
progressbar==2.5
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1622586138406/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1629903925368/work
property-cached==1.6.4
protobuf==3.16.0
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
PuLP @ file:///home/conda/feedstock_root/build_artifacts/pulp_1628716533520/work
pyarrow==5.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycodestyle @ file:///home/conda/feedstock_root/build_artifacts/pycodestyle_1615833610040/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
pycryptodomex @ file:///home/conda/feedstock_root/build_artifacts/pycryptodomex_1612963451163/work
pyflakes @ file:///home/conda/feedstock_root/build_artifacts/pyflakes_1616623675904/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1629119114968/work
pyhdfe==0.1.0
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1619620644068/work
pylint @ file:///home/conda/feedstock_root/build_artifacts/pylint_1629774645767/work
pyodbc @ file:///home/conda/feedstock_root/build_artifacts/pyodbc_1629418792422/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1608055815057/work
pyparsing==2.4.7
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1610146801408/work
pysd @ file:///home/conda/feedstock_root/build_artifacts/pysd_1631275833936/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1610291444829/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1612179539967/work
pyu2f @ file:///home/conda/feedstock_root/build_artifacts/pyu2f_1604248910016/work
PyYAML==5.4.1
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1628232914112/work
regex @ file:///home/conda/feedstock_root/build_artifacts/regex_1630103887193/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1608156231189/work
requests-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/requests-oauthlib_1595492159598/work
requests-unixsocket==0.2.0
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1614171254180/work
s3transfer @ file:///home/conda/feedstock_root/build_artifacts/s3transfer_1626384238958/work
scikit-learn==0.24.2
scipy==1.4.1
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1628511208346/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1610318316464/work
snowflake-connector-python @ file:///home/conda/feedstock_root/build_artifacts/snowflake-connector-python_1630686864997/work
statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1630699917471/work
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1631128156863/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1621261527237/work
threadpoolctl==2.2.0
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1628264172148/work
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1610094704591/work
tqdm==4.62.2
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1630423529112/work
typed-ast @ file:///home/conda/feedstock_root/build_artifacts/typed-ast_1618337592858/work
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1622748266870/work
unittest-xml-reporting @ file:///home/conda/feedstock_root/build_artifacts/unittest-xml-reporting_1626353776810/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1624634538755/work
virtualenv==20.7.2
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1610127652206/work
wrapt @ file:///home/conda/feedstock_root/build_artifacts/wrapt_1610094880759/work
xarray @ file:///home/conda/feedstock_root/build_artifacts/xarray_1627311788418/work
xlrd==1.2.0
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1603108300259/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1625284368454/work

4. What did you do?

   Need: Snowflake server that only accepts whitelisted IPs and proxy server whose IP is whitelisted for Snowflake
              server. Environment variables set for SNOWFLAKE_USER, SNOWFLAKE_PASSWORD, HTTP_PROXY,
              HTTPS_PROXY
   
   ```
   >>> from snowflake.connector import connect
   >>> import os
   >>> args = {
           'account': "account.region.platform",
           'user': os.environ["SNOWFLAKE_USER"],
           'password': os.environ["SNOWFLAKE_PASSWORD"],
           'warehouse': 'warehouse_name',
           'role': 'role_name',
           'paramstyle': 'qmark',
       }
   >>> con = connect(**args)
   ```
    

5. What did you expect to see?

A connection instance should have been created, instead an OperationError is raised

`OperationalError: Failed to get the response. Hanging? method: post, url: https://...`

In previous versions this worked fine (last I tested v2.4.3 the environment variables for proxy still work). Now the environment variables for proxy don't work. I can get around this by using the `proxy_host` and `proxy_port` parameters in the connect class init, however, the [snowflake docs state that this usage is deprecated](https://docs.snowflake.com/en/user-guide/python-connector-example.html#using-a-proxy-server). 

It makes way more sense to be able to explicitly pass proxy info to the connector than be locked into only using environment variables, but the environment variables should probably still work. In my case I only use this proxy for Snowflake but having to set an environment variable means I now have to set exceptions for everything but Snowflake to avoid using the proxy for everything else.

6. Can you set logging to DEBUG and collect the logs?

   ```
   import logging
   import os

   for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']:
       logger = logging.getLogger(logger_name)
       logger.setLevel(logging.DEBUG)
       ch = logging.StreamHandler()
       ch.setLevel(logging.DEBUG)
       ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
       logger.addHandler(ch)
   ```
log (redacted)
```
2021-09-10 18:50:12,199 - MainThread connection.py:275 - __init__() - INFO - Snowflake Connector for Python Version: 2.6.0, Python Version: 3.7.10, Platform: Linux-5.10.47-linuxkit-x86_64-with-debian-bullseye-sid
2021-09-10 18:50:12,200 - MainThread connection.py:501 - connect() - DEBUG - connect
2021-09-10 18:50:12,200 - MainThread connection.py:766 - __config() - DEBUG - __config
2021-09-10 18:50:12,200 - MainThread connection.py:891 - __config() - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2021-09-10 18:50:12,200 - MainThread connection.py:908 - __config() - INFO - Setting use_openssl_only mode to False
2021-09-10 18:50:12,201 - MainThread converter.py:142 - __init__() - DEBUG - use_numpy: False
2021-09-10 18:50:12,201 - MainThread connection.py:669 - __open_connection() - DEBUG - REST API object was created: *******.*****.***.snowflakecomputing.com:443
2021-09-10 18:50:12,201 - MainThread auth.py:169 - authenticate() - DEBUG - authenticate
2021-09-10 18:50:12,202 - MainThread auth.py:199 - authenticate() - DEBUG - assertion content: *********
2021-09-10 18:50:12,202 - MainThread auth.py:211 - authenticate() - DEBUG - account=*******, user=username, database=None, schema=None, warehouse=warehousename, role=rolename, request_id=*************
2021-09-10 18:50:12,202 - MainThread auth.py:237 - authenticate() - DEBUG - body['data']: {'CLIENT_APP_ID': 'PythonConnector', 'CLIENT_APP_VERSION': '2.6.0', 'SVN_REVISION': None, 'ACCOUNT_NAME': '*******', 'LOGIN_NAME': 'username', 'CLIENT_ENVIRONMENT': {'APPLICATION': 'PythonConnector', 'OS': 'Linux', 'OS_VERSION': 'Linux-5.10.47-linuxkit-x86_64-with-debian-bullseye-sid', 'PYTHON_VERSION': '3.7.10', 'PYTHON_RUNTIME': 'CPython', 'PYTHON_COMPILER': 'GCC 9.3.0', 'OCSP_MODE': 'FAIL_OPEN', 'TRACING': 10, 'LOGIN_TIMEOUT': 120, 'NETWORK_TIMEOUT': None}, 'SESSION_PARAMETERS': {'CLIENT_PREFETCH_THREADS': 4}}
2021-09-10 18:50:12,203 - MainThread retry.py:333 - from_int() - DEBUG - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-09-10 18:50:12,204 - MainThread retry.py:333 - from_int() - DEBUG - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-09-10 18:50:12,204 - MainThread network.py:1104 - _use_requests_session() - DEBUG - Session status for SessionPool '*******.*****.***.snowflakecomputing.com', SessionPool 1/1 active sessions
2021-09-10 18:50:12,204 - MainThread network.py:823 - _request_exec_wrapper() - DEBUG - remaining request timeout: 120, retry cnt: 1
2021-09-10 18:50:12,204 - MainThread network.py:801 - add_request_guid() - DEBUG - Request guid: ***************
2021-09-10 18:50:12,205 - MainThread network.py:970 - _request_exec() - DEBUG - socket timeout: 60
2021-09-10 18:50:12,208 - MainThread connectionpool.py:975 - _new_conn() - DEBUG - Starting new HTTPS connection (1): *******.*****.***.snowflakecomputing.com:443
2021-09-10 18:50:12,340 - MainThread retry.py:576 - increment() - DEBUG - Incremented Retry for (url='/session/v1/login-request?request_id=*************&warehouse=warehousename&roleName=rolename&request_guid=***************'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2021-09-10 18:50:12,341 - MainThread connectionpool.py:781 - urlopen() - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])"))': /session/v1/login-request?request_id=*************&warehouse=warehousename&roleName=rolename&request_guid=***************
2021-09-10 18:50:12,342 - MainThread connectionpool.py:975 - _new_conn() - DEBUG - Starting new HTTPS connection (2): *******.*****.***.snowflakecomputing.com:443
2021-09-10 18:50:12,415 - MainThread network.py:1031 - _request_exec() - DEBUG - Hit non-retryable SSL error, HTTPSConnectionPool(host='*******.*****.***.snowflakecomputing.com', port=443): Max retries exceeded with url: /session/v1/login-request?request_id=*************&warehouse=warehousename&roleName=rolename&request_guid=*************** (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))
2021-09-10 18:50:12,420 - MainThread network.py:937 - _handle_unknown_error() - ERROR - Failed to get the response. Hanging? method: post, url: https://*******.*****.***.snowflakecomputing.com:443/session/v1/login-request?request_id=*************&warehouse=warehousename&roleName=rolename&request_guid=***************, headers:{'Content-Type': 'application/json', 'accept': 'application/snowflake', 'User-Agent': 'PythonConnector/2.6.0 (Linux-5.10.47-linuxkit-x86_64-with-debian-bullseye-sid) CPython/3.7.10', 'Content-Encoding': 'gzip'}, data: {"data": {"CLIENT_APP_ID": "PythonConnector", "CLIENT_APP_VERSION": "2.6.0", "SVN_REVISION": null, "ACCOUNT_NAME": "*******", "LOGIN_NAME": "username", "CLIENT_ENVIRONMENT": {"APPLICATION": "PythonConnector", "OS": "Linux", "OS_VERSION": "Linux-5.10.47-linuxkit-x86_64-with-debian-bullseye-sid", "PYTHON_VERSION": "3.7.10", "PYTHON_RUNTIME": "CPython", "PYTHON_COMPILER": "GCC 9.3.0", "OCSP_MODE": "FAIL_OPEN", "TRACING": 10, "LOGIN_TIMEOUT": 120, "NETWORK_TIMEOUT": null}, "PASSWORD": "********", "SESSION_PARAMETERS": {"CLIENT_PREFETCH_THREADS": 4}}}
2021-09-10 18:50:12,427 - MainThread network.py:1110 - _use_requests_session() - DEBUG - Session status for SessionPool '*******.*****.***.snowflakecomputing.com', SessionPool 0/1 active sessions
```

**Comment by sfc-gh-kwagner** [comment]
@mosqueteiro can you reach out to Snowflake support for help with this issue. That's the proper channel for this type of issue

**Comment by sfc-gh-hchaturvedi** [comment]
Hey @mosqueteiro did you get a chance to reach out to Snowflake support? 

Also I noticed that there is an SSL Handshake error with the proxy.
`connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])"))':
` 
 Just curious if you've explored the possibility of a proxy configuration problem?

**Comment by mosqueteiro** [comment]
I haven't been able to identify a configuration problem with the proxy I am using. It is a docker container running the latest version of _tinyproxy_

**Comment by mosqueteiro** [comment]
@sfc-gh-hchaturvedi  I have reached out to Snowflake support but so far that has been a convoluted process. I would like to point back to the fact that if I use the `proxy_host` and `proxy_port` arguments I do not get this error. This is why I believe this is an issue with the code and not my configuration. I am also advocating for keeping the parameters `proxy_host` and `proxy_port`. If the connector relies on environmental variables alone —especially the system recognized variables— a computer will have to be configured to route ALL traffic through the proxy when only the Snowflake traffic might be desired to be routed.

**Comment by mosqueteiro** [comment]
I was able to resolve the issue with the Snowflake support team. For `HTTPS_PROXY` changing the address prefix _https_ to _http_ resolved the issue.

Hopefully, defining the proxy at the connection level will come back as I believe there are advantages to keeping this functionality but as far as this issue is concerned I believe it is resolved.

**Comment by sfc-gh-mkeller** [comment]
For anyone that finds this issue after it was closed:

I've now completed a RCA and this issue is caused by: https://github.com/urllib3/urllib3/commit/691679f738ae098ce024aeae90cfdd8013b8e1e7

So installing `snowflake-connector-python>=2.4.6` will have the new behavior where `HTTPS_PROXY=https://...` will cause your proxy to not work, but previous versions will have no problem with this proxy setting.

The issue and it's solution is well documented here: https://urllib3.readthedocs.io/en/stable/advanced-usage.html?highlight=use_forwarding_for_https#your-proxy-appears-to-only-use-http-and-not-https but since we use `requests` there doesn't seem to be an option for us to revert to the old implementation.
