### ISSUE TITLE
SNOW-470745: No module named 'dataclasses' when calling AWS Lambda

### ISSUE THREAD

**Issue by gabrielgirodo** [snowflakedb/snowflake-connector-python#880]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]

2. What operating system and processor architecture are you using?

   Windows-10-10.0.17763-SP0

3. What are the component versions in the environment (`pip freeze`)?

   absl-py==0.11.0
appdirs==1.4.4
asn1crypto==1.0.1
astor==0.8.1
astroid==2.2.5
astunparse==1.6.3
atomicwrites==1.4.0
attrs==21.2.0
autopep8==1.5.4
azure-common==1.1.27
azure-core==1.18.0
azure-storage-blob==12.9.0
backcall==0.1.0
bleach==3.1.5
boto3==1.9.118
botocore==1.12.253
cachetools==4.2.1
certifi==2020.12.5
cffi==1.12.3
chardet==4.0.0
Click==7.0
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==1.6.0
colorama==0.4.4
coverage==4.5.4
cryptography==3.4.8
cycler==0.10.0
dataclasses==0.8
decorator==4.4.2
defusedxml==0.6.0
distlib==0.3.2
docutils==0.14
entrypoints==0.3
filelock==3.0.12
Flask==1.0.2
flatbuffers==1.12
freezegun==0.3.12
gast==0.3.3
google-auth==1.27.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
GPy==1.9.9
GPyOpt==1.2.6
grpcio==1.32.0
gym==0.18.3
h5py==2.10.0
idna==2.10
importlib-metadata==4.0.1
importlib-resources==5.1.4
iniconfig==1.1.1
ipykernel==5.2.1
ipython==7.14.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isodate==0.6.0
isort==4.3.21
itsdangerous==1.1.0
jedi==0.17.0
Jinja2==2.10
jmespath==0.9.4
joblib==0.14.1
jsonpickle==1.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
kaggle==1.5.10
Keras==2.4.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keras-rl2==1.0.5
kivy-deps.angle==0.3.0
kivy-deps.glew==0.3.0
Kivy-Garden==0.1.4
kiwisolver==1.2.0
lazy-object-proxy==1.4.2
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.2.0
mccabe==0.6.1
mistune==0.8.4
mlxtend==0.18.0
mock==2.0.0
more-itertools==7.2.0
msgpack==1.0.2
msgpack-numpy==0.4.4.3
msrest==0.6.21
munch==2.5.0
nbconvert==5.6.1
nbformat==5.0.6
nltk==3.5
notebook==6.0.3
numpy==1.19.5
oauthlib==3.1.0
olefile==0.46
opencv-python==4.5.1.48
openrouteservice==2.3.3
opt-einsum==3.3.0
oscrypto==1.2.1
packaging==20.9
pandas==1.1.5
pandocfilters==1.4.2
paramz==0.9.5
parso==0.7.0
patsy==0.5.1
pbr==5.1.3
pickleshare==0.7.5
Pillow==7.1.1
pluggy==0.13.1
prometheus-client==0.7.1
prompt-toolkit==3.0.5
protobuf==3.14.0
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycparser==2.19
pycryptodomex==3.10.4
pygame==1.9.6
pyglet==1.5.15
Pygments==2.6.1
PyJWT==2.1.0
pylint==2.3.1
pyOpenSSL==20.0.1
pyparsing==2.4.7
pypiwin32==223
pyproj==3.0.1
pyrsistent==0.16.0
pyshp==1.1.7
pytesseract==0.3.7
pytest==6.2.4
pytest-cov==2.8.1
python-dateutil==2.8.1
python-slugify==4.0.1
pytz==2020.1
pywin32==227
pywinpty==0.5.7
PyYAML==5.4.1
pyzmq==19.0.1
qtconsole==4.7.4
QtPy==1.9.0
regex==2020.11.13
requests==2.25.1
requests-oauthlib==1.3.0
rope==0.14.0
rsa==4.7.2
s3transfer==0.2.0
scikit-learn==0.23.0
scipy==1.4.1
seaborn==0.10.1
Send2Trash==1.5.0
Shapely==1.7.1
six==1.15.0
sklearn==0.0
snowflake-connector-python==2.6.1
statsmodels==0.12.2
tabulate==0.8.3
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-estimator==2.4.0
tensorpack==0.9.4
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
text-unidecode==1.3
tgan==0.1.0
threadpoolctl==2.0.0
toml==0.10.2
torch==1.7.1
tornado==6.0.4
tqdm==4.56.0
traitlets==4.3.3
typed-ast==1.4.0
typing-extensions==3.7.4.3
urllib3==1.24.1
virtualenv==20.4.7
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.0
widgetsnbextension==3.5.1
wincertstore==0.2
wrapt==1.12.1
xgboost==1.3.3
xlrd==1.2.0
zipp==3.4.1

4. What did you do?

   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

5. What did you expect to see?

   I installed SNOWFLAKE-CONNECTOR-PYTHON in my virtual environment and when I run my application locally using Flask it works perfectly.
  Then I downloaded the WHL file for LINUX (because I deploy my application in AWS as a Lambda function). I extracted the package and zipped together with my code, after that I deploy it. When I call my lambda function I get the following error message: "Unable to import module 'application/handlers/self_test_handler': No module named 'dataclasses'"

6. Can you set logging to DEBUG and collect the logs?

   No.

**Comment by sfc-gh-kterada** [comment]
@gabrielgirodo, are you able to upgrade to Python 3.7.x which does not have a dependency on the module noted? Thank you.
