### ISSUE TITLE
SNOW-477347: Bug and standardization request: fix conflicting requirements.txt and snowflake-connector package requirements. Standardize install process

### ISSUE THREAD

**Issue by eddyojb88** [snowflakedb/snowflake-connector-python#896]
1. What version of Python are you using?
 `python --version 3.7`

2. What operating system and processor architecture are you using?
_Ubuntu but deemed irrelevant._

3. What are the component versions in the environment (`pip freeze`)?
_Deemed irrelevant._

4. What did you do?
_Installed using requirements as stated here:_
```
https://github.com/snowflakedb/snowflake-connector-python/blob/master/tested_requirements/requirements_37.reqs
```

5. What did you expect to see?
_An installation process that is in line with the rest of the Python community_

6. Can you set logging to DEBUG and collect the logs?
_No but here is the output from Pip. I have request pytz inline with the Snowflake requirements doc, which conflicts with what is in the package by the looks of it._

```
The conflict is caused by:
    The user requested pytz==2021.1
    pandas 1.1.4 depends on pytz>=2017.2
    snowflake-connector-python 2.3.6 depends on pytz<2021.0
```

**Comment by eddyojb88** [comment]
This bug just goes on and on with dependency conflicts caused by the snowflake-connector package. Here is my 5th dependency conflict:

```
The conflict is caused by:
    The user requested certifi==2021.5.30
    snowflake-connector-python 2.3.6 depends on certifi<2021.0.0
```

**Comment by eddyojb88** [comment]
Thanks.

Can you write some normal requirements and documentation please, its a mess. 

A simple solution would have been to include the version of the snowflake connector in the requirements file, not as a comment.

**Comment by eddyojb88** [comment]
I am using Python 3.7 and am using the requirements as[ laid out here.](https://github.com/snowflakedb/snowflake-connector-python/blob/master/tested_requirements/requirements_37.reqs)

```
The user requested PyJWT==2.3.0
    snowflake-connector-python 2.7.0 depends on pyjwt<3.0.0
```

This makes no sense.

**Comment by sfc-gh-mkeller** [comment]
@eddyojb88 would you be able to post the full output?
This by itself seems fine to me as `2.3.0` is in `<3.0.0`
