### ISSUE TITLE
SNOW-488688: fetch_pandas_all() raises error in pyinstaller executable

### ISSUE THREAD

**Issue by chetansurwade** [snowflakedb/snowflake-connector-python#912]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Replace with the output of `Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]`

2. What operating system and processor architecture are you using?

   Replace with the output of `Windows-10-10.0.19041-SP0`

3. What are the component versions in the environment (`pip freeze`)?

   Replace with the output of `snowflake-connector-python==2.6.2, pyinstaller==4.5.1,pandas==1.3.4`

4. What did you do?

   Created a pyinstaller executable build and used fetch_pandas_all() method which through error in the attached screenshot. But pd.read_sql works fine

5. What did you expect to see?

fetch_pandas_all() to improve the query performance.

6. Can you set logging to DEBUG and collect the logs?
![image](https://user-images.githubusercontent.com/29613800/137940086-0bc2634b-22ee-4a16-a29f-61934dee9b10.png)

**Comment by lilian-arnaud** [comment]
I just faced the same issue and I copied all the *py files from site-dist/snowflake/connector into my DIST/snowflake/connector folder and it worked

**Comment by sfc-gh-aling** [comment]
I'm closing the issue as this is expected be resolved by copying and pasting all the files under site-dist folder to the destination dir.

**Comment by rob-dumoulin** [comment]
> I just faced the same issue and I copied all the *py files from site-dist/snowflake/connector into my DIST/snowflake/connector folder and it worked

I have this error on Windows.  Script runs fine interactively but crashes when complied.  I cannot determine what this 'fix' is. Can somebody be more specific on what files need to be put where?.
