### ISSUE TITLE
SNOW-499491: Cryptography dependancy is pinned at too low a version

### ISSUE THREAD

**Issue by howardsandford** [snowflakedb/snowflake-connector-python#923]
## What is the current behavior?
snowflake-connector-python has pinned cryptography to version <4.0.0 and >=3.1.0

## What is the desired behavior?
Cryptography has changed it's versioning scheme, and is now on version 35.0.0
Don't limit the version to 4.0.0 in snowflake-connector-python

## References, Other Background
https://cryptography.io/en/latest/changelog/#main

**Comment by sfc-gh-mkeller** [comment]
recreate jira

**Comment by sfc-gh-hchaturvedi** [comment]
@howardsandford based on the changelog the newer versions seem to be backwards incompatible. Thanks for bringing this up, we will run some tests internally and make changes accordingly. Thank you for your patience!

**Comment by hauntsaninja** [comment]
We're running into this as well. In general, it's pretty unfortunate to be pinning a dependency like cryptography, where it can be really important to get updates.

You can see more about cryptography's version policy here: https://cryptography.io/en/latest/api-stability/#deprecation

**Comment by sfc-gh-aling** [comment]
closing the issue as we've already loosened the restriction on the version of cryptography in our latest release.
