### ISSUE TITLE
SNOW-499492: Cannot write Snowflake table

### ISSUE THREAD

**Issue by frankduan68** [snowflakedb/snowflake-connector-python#924]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?
3.8.10
2. What operating system and processor architecture are you using?
Windows 7
3. What are the component versions in the environment (`pip freeze`)?
pip
4. What did you do?

I got no errors from my code running

5. What did you expect to see?
new records get inserted

And my code FYI:
import pandas as pd
from sqlalchemy import create_engine
from snowflake.sqlalchemy import URL
from config import config

engine = create_engine(URL(account=config.account, 
                  user=config.username, 
                  password=config.password, 
                  warehouse=config.warehouse, 
                  database=config.database, 
                  schema=config.schema,))

conn = engine.connect()

df = pd.DataFrame([('AAA', '1234'), ('BBB', '5678')], columns=['name', 'pswd'])
df.to_sql('demo_db.public.test_f1', con=engine, index=False, if_exists='append', index_label=None)
    
df = pd.read_sql_query('select * from demo_db.public.test_f1', conn)
print(df.head(5))

conn.close()
engine.dispose()

**Comment by sfc-gh-mkeller** [comment]
recreate jira
