### ISSUE TITLE
SNOW-499493: Some interval math off by one microsecond for years beyond ~2250

### ISSUE THREAD

**Issue by timgraham** [snowflakedb/snowflake-connector-python#926]
Python 3.9.5, Linux, snowflake-connector-python==2.6.2
```python
>>> import snowflake.connector
>>> conn = snowflake.connector.connect(...)
>>> print(conn.cursor().execute("SELECT TO_TIMESTAMP('2010-06-25 12:15:30.747000') + INTERVAL '8999999999999995 MICROSECONDS'").fetchone())
(datetime.datetime(2295, 9, 6, 4, 15, 30, 746996),)
>>> print(conn.cursor().execute("SELECT TO_TIMESTAMP('2010-06-25 12:15:30.747000') + INTERVAL '8999999999999996 MICROSECONDS'").fetchone())
(datetime.datetime(2295, 9, 6, 4, 15, 30, 746996),)
>>> print(conn.cursor().execute("SELECT TO_TIMESTAMP('2010-06-25 12:15:30.747000') + INTERVAL '8999999999999997 MICROSECONDS'").fetchone())
(datetime.datetime(2295, 9, 6, 4, 15, 30, 746998),
>>> print(conn.cursor().execute("SELECT TO_TIMESTAMP('2010-06-25 12:15:30.747000') + INTERVAL '8999999999999998 MICROSECONDS'").fetchone())
(datetime.datetime(2295, 9, 6, 4, 15, 30, 746998),)
>>> print(conn.cursor().execute("SELECT TO_TIMESTAMP('2010-06-25 12:15:30.747000') + INTERVAL '8999999999999999 MICROSECONDS'").fetchone())
(datetime.datetime(2295, 9, 6, 4, 15, 30, 747000),)
```
I thought this may be an issue in Snowflake itself, but app.snowflake.com gives correct results.

I stepped through the code to see that [`ArrowConverterContext.TIMESTAMP_LTZ_to_python()`](https://github.com/snowflakedb/snowflake-connector-python/blob/c9aa4f1f82d71db145ec4a435f5ffc6113f35c34/src/snowflake/connector/arrow_context.py#L85-L86) gets the respective values for the above queries:
```
10277468130.746996
10277468130.746996
10277468130.746998
10277468130.746998
10277468130.747
```
so it seems the problem lies before there, possibly in [TimeStampConverter.cpp](https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/cpp/ArrowIterator/TimeStampConverter.cpp)? I don't have much experience with C.

If you change the first number of microseconds (8) to six or less, it works correctly, e.g.
```python
>>> print(conn.cursor().execute("SELECT TO_TIMESTAMP('2010-06-25 12:15:30.747000') + INTERVAL '6999999999999995 MICROSECONDS'").fetchone())
(datetime.datetime(2232, 4, 21, 0, 42, 10, 746995),)
>>> print(conn.cursor().execute("SELECT TO_TIMESTAMP('2010-06-25 12:15:30.747000') + INTERVAL '6999999999999996 MICROSECONDS'").fetchone())
(datetime.datetime(2232, 4, 21, 0, 42, 10, 746996),)
```
(This is from a [Django test](https://github.com/django/django/blob/f38458fe56bf8850da72a924bd2e8ff59c6adf06/tests/expressions/tests.py#L1699-L1706).)

**Comment by sfc-gh-mkeller** [comment]
recreate jira

**Comment by sfc-gh-jbahk** [comment]
Hi @timgraham, I have PR out for this: https://github.com/snowflakedb/snowflake-connector-python/pull/1030. It fails because of a new test I wrote (test_time_interval_microsecond) on GitHub, but it works fine locally for myself. Would you mind pulling the branch and letting me know if this fixes your issue? The root cause is because the level of precision you requested (up to an atomic microsecond) is beyond what Python as a native language can handle and so it rounds it up -- please let me know.

**Comment by timgraham** [comment]
When I try to `pip install -e` my checkout of snowflake-connector-python so I can test your branch, I get the error `[Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.9/snowflake/connector'"` following "running build_ext" during the "Running setup.py develop" step. Have you seen this before?

**Comment by timgraham** [comment]
I found that `pip install` (without `-e`) works. The patch seems to solve the problem. Thanks.
