### ISSUE TITLE
SNOW-499494: network timeout not respected during snowflake outage

### ISSUE THREAD

**Issue by davidemerritt** [snowflakedb/snowflake-connector-python#933]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

`python 3.7.12`

2. What operating system and processor architecture are you using?

`Linux-5.10.47-linuxkit-x86_64-with-Ubuntu-18.04-bionic`

3. What are the component versions in the environment (`pip freeze`)?

`snowflake-connector-python==2.7.0`

4. What did you do?

We have a default snowflake connector for all application logic setup as following. During yesterday's outage on snowflake, our request setting (was set to 20 seconds) was not respected and all queries timed out after 50 seconds. This caused a significant increase in load unexpectedly.

```
return snowflake.connector.connect(
        user=settings.SNOWFLAKE_USER,
        password=settings.SNOWFLAKE_PASSWORD,
        account=settings.SNOWFLAKE_ACCOUNT,
        warehouse=settings.SNOWFLAKE_WAREHOUSE,
        database=settings.SNOWFLAKE_DATABASE,
        schema=settings.SNOWFLAKE_SCHEMA,
        timezone="UTC",
        network_timeout=settings.SNOWFLAKE_NETWORK_TIMEOUT,
    )
```

5. What did you expect to see?

I expected network timeout to be implemented in the local client during the request, not on snowflake's side. 

6. Can you set logging to DEBUG and collect the logs?

N/A.

**Comment by sfc-gh-mkeller** [comment]
recreate jira
