### ISSUE TITLE
SNOW-499495: Add an attribute with the cursor's last executed query

### ISSUE THREAD

**Issue by timgraham** [snowflakedb/snowflake-connector-python#936]
Django's `DatabaseOperations.last_executed_query()` returns the last executed query for a given cursor. While sqlite3 don't provide a way to get the SQL of the last query and thus [parameter escaping has to be done in Django](https://github.com/django/django/blob/25157033e979c134d455d46995a6db0838457d98/django/db/backends/sqlite3/operations.py#L135-L178), MySQL's drivers provides [Cursor._executed](https://github.com/PyMySQL/mysqlclient/blob/8b920774f27d9d17bc85d1593e5d4a36a7ce3f65/MySQLdb/cursors.py#L322), psycopg2 provides [Cursor.query](https://www.psycopg.org/docs/cursor.html#cursor.query), and cx_Oracle provides [Cursor.statement](https://cx-oracle.readthedocs.io/en/latest/api_manual/cursor.html#Cursor.statement). It would be ideal if snowflake-connector-python could offer the same. The following proposal works for the Django tests I've tried so far (the name `_query` could be changed to whatever you like):
```diff
diff --git a/src/snowflake/connector/cursor.py b/src/snowflake/connector/cursor.py
index d238204..5a51137 100644
--- a/src/snowflake/connector/cursor.py
+++ b/src/snowflake/connector/cursor.py
@@ -248,6 +248,7 @@ class SnowflakeCursor:
         self._result_set: Optional["ResultSet"] = None
         self._result_state: ResultState = ResultState.DEFAULT
         self._use_dict_result = use_dict_result
+        self._query = None
         # TODO: self._query_result_format could be defined as an enum
         self._query_result_format: Optional[str] = None
 
@@ -552,6 +553,7 @@ class SnowflakeCursor:
                 {p["name"]: p["value"] for p in parameters}
             )
 
+        self._query = query
         self._sequence_counter = -1
         return ret
 ```

**Comment by sfc-gh-mkeller** [comment]
@timgraham this is a good idea, would you be able to provide us with a PR since this issue is almost code complete.

I'd ask you to add type-hint to the initial definition and if you could add to one of our existing tests to verify correctness that'd be great!

**Comment by sfc-gh-mkeller** [comment]
recreate jira
