### ISSUE TITLE
SNOW-499496: Cursor.executemany() crashes if args is an iterator

### ISSUE THREAD

**Issue by timgraham** [snowflakedb/snowflake-connector-python#939]
To reproduce:
```python
>>> import snowflake.connector
>>> conn = snowflake.connector.connect(...)
>>> conn.cursor().execute('CREATE TABLE "tbl" ("col" int)')
>>> query = 'INSERT INTO "tbl" ("col") VALUES (%s)'
>>> args = ((i,) for i in range(-3, 2))
>>> conn.cursor().executemany(query, args)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../snowflake/connector/cursor.py", line 987, in executemany
    if len(seqparams) == 0:
TypeError: object of type 'generator' has no len()
```
The exception happens on a check (added in 27597cb7) which prevents using `executemany()` with empty args:
https://github.com/snowflakedb/snowflake-connector-python/blob/c37c0713ddf2eb66c7cf15eb38099040c73c0a0a/src/snowflake/connector/cursor.py#L988-L998

```python
>>> conn.cursor().executemany(query, [])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../snowflake/connector/cursor.py", line 988, in executemany
    Error.errorhandler_wrapper(
  File ".../snowflake/connector/errors.py", line 255, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File ".../snowflake/connector/errors.py", line 310, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File ".../snowflake/connector/errors.py", line 189, in default_errorhandler
    raise error_class(
snowflake.connector.errors.InterfaceError: No parameters are specified for the command: INSERT INTO "tbl" ("col") VALUES (%s)
```
To match the behavior of the other database drivers that Django is tested with, `Cursor.executemany()` should instead simply do nothing if args is empty.

Removing the code block quoted above fixes both issues.

Relevant Django tests:
[test_cursor_executemany_with_iterator](https://github.com/django/django/blob/ba9ced3e9a643a05bc521f0a2e6d02e3569de374/tests/backends/tests.py#L279-L289)
[test_cursor_executemany_with_empty_params_list](https://github.com/django/django/blob/ba9ced3e9a643a05bc521f0a2e6d02e3569de374/tests/backends/tests.py#L273-L277)

**Comment by sfc-gh-mkeller** [comment]
recreate jira

**Comment by sfc-gh-mkeller** [comment]
I see what you mean @timgraham
Again, this would be a breaking change, so it'll need to be pre-announced. Let me also point out that I think your example will never work.
```pycon
>>> import snowflake.connector
>>> conn = snowflake.connector.connect(...)
>>> conn.cursor().execute('CREATE TABLE "tbl" ("col" int)')
>>> query = 'INSERT INTO "tbl" ("col") VALUES (%s)'
>>> args = ((i,) for i in range(-3, 2))
>>> conn.cursor().executemany(query, args)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../snowflake/connector/cursor.py", line 987, in executemany
    if len(seqparams) == 0:
TypeError: object of type 'generator' has no len()
```
`executemany` doesn't have to support generators

**Comment by timgraham** [comment]
I tested the fix in my pull request and it solves the issue. The example is included as a regression test.
