### ISSUE TITLE
SNOW-499497: Pandas version lower bound is set >= 1.0 but could be >=0.25.2

### ISSUE THREAD

**Issue by caseyclements** [snowflakedb/snowflake-connector-python#940]
## What is the current behavior?
In `setup.py` the constraint is defined `pandas>=1.0.0,<1.4.0`
## What is the desired behavior?
In communication with Irina Rubenchik and John Gallaro, I was informed that this package will work with `0.25.2` and higher.
## How would this improve `snowflake-connector-python`?
Allow users with pandas constraints.
## References, Other Background
This a one-line change. I will submit a PR.

**Comment by sfc-gh-mkeller** [comment]
recreate jira

**Comment by sfc-gh-jbahk** [comment]
Hello, given our current and future dependencies and builds, we've decided not to move forward with this.
