### ISSUE TITLE
SNOW-499498: Raise InterfaceError instead of DatabaseError when trying to execute against a closed cursor

### ISSUE THREAD

**Issue by timgraham** [snowflakedb/snowflake-connector-python#943]
`Cursor.execute()` currently [raises `DatabaseError`](https://github.com/snowflakedb/snowflake-connector-python/blob/c37c0713ddf2eb66c7cf15eb38099040c73c0a0a/src/snowflake/connector/cursor.py#L617-L623) when the cursor is closed. Among the database drivers Django supports, sqlite3 and mysqlclient raise `ProgrammingError`, while psycopg2 and cx_Oracle raise `InterfaceError`. Based on the below definitions from [PEP 249](https://www.python.org/dev/peps/pep-0249/), `InterfaceError` seems most appropriate.

- InterfaceError - Exception raised for errors that are related to the database interface rather than the database itself.
- DatabaseError - Exception raised for errors that are related to the database. 
- ProgrammingError - Exception raised for programming errors, e.g. table not found or already exists, syntax error in the SQL statement, wrong number of parameters specified, etc.

**Comment by sfc-gh-mkeller** [comment]
recreate jira
