### ISSUE TITLE
SNOW-500219: Unique index for dataframes created from fetch_pandas_all()

### ISSUE THREAD

**Issue by scottabarnes** [snowflakedb/snowflake-connector-python#956]
## What is the current behavior?
Loaded data from a `cur.execute()` statement into a pandas dataframe using `fetch_pandas_all()` 
```
df = cur.execute("SELECT * FROM TABLE").fetch_pandas_all()
```

The indexes in the dataframe were not unique, so the below fails
```
assert len(df) == df.index.nunique()
```
There is not an equal distribution of indexes, i.e. some appear more frequently than others. 

## What is the desired behavior?
Expected the index to be a unique integer starting at 0, as is in `pandas.read_csv()` when `index_col` is left with default value of `None`. 

## How would this improve `snowflake-connector-python`?
The current behaviour may be confusing as users might expect a unique index as is the case with `pandas.read_csv`. This was replicated against two different datasets but could be an environment or data specific issue! Can provide further information if helpful.

**Comment by sfc-gh-mkeller** [comment]
This should have been fixed by https://github.com/snowflakedb/snowflake-connector-python/pull/1068

**Comment by scottabarnes** [comment]
> This should have been fixed by #1068

Great thank you! I will test on the next release

**Comment by alonme** [comment]
seems like #1068 is part of the new 2.7.5 release

**Comment by sfc-gh-aling** [comment]
To clean up and re-prioritize bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please re-create them. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response
