### ISSUE TITLE
SNOW-501058: Cursor.execute() fails to interpolate SQL when params=()

### ISSUE THREAD

**Issue by timgraham** [snowflakedb/snowflake-connector-python#961]
With psycopg2 and PostgreSQL:
```python
>>> import psycopg2
>>> cursor = psycopg2.connect(...).cursor()
>>> cursor.execute('SELECT (\'%%s\') AS "foo"', None)
>>> cursor.fetchone()
('%%s',)
>>> cursor.execute('SELECT (\'%%s\') AS "foo"', ())
>>> cursor.fetchone()
('%s',)
```
With snowflake-connector-python and Snowflake:
```python
>>> import snowflake.connector
>>> conn = snowflake.connector.connect(...)
>>> conn.cursor().execute('SELECT (\'%%s\') AS "foo"', None).fetchone()
('%%s',)
>>> conn.cursor().execute('SELECT (\'%%s\') AS "foo"', ()).fetchone()
('%%s',)
```
The expected result of the second query is `'%s'` as with PostgreSQL.

This comes from [a Django test](https://github.com/django/django/blob/05cde4764da022ae80e9d7d97ef67c30e896c607/tests/queries/tests.py#L1651-L1664).

**Comment by sfc-gh-mkeller** [comment]
@timgraham could you link the part of https://www.python.org/dev/peps/pep-0249/ that explains this behavior?

**Comment by timgraham** [comment]
I don't know that it's discussed in the PEP, but the proposed behavior seems more logical than the current behavior and is consistent with all the database drivers that Django is tested with (sqlite3, psycopg2, mysqlclient, cx_Oracle).

**Comment by sfc-gh-mkeller** [comment]
So #962 was a behavior change that after giving more thought to we cannot release this change without an announcement. In #997 I'm introducing a connection parameter to switch between behaviors.
I'm going to re-open this issue until we complete the behavior change!
