### ISSUE TITLE
SNOW-507469: Can a release be cut to include #965 ?

### ISSUE THREAD

**Issue by p5k6** [snowflakedb/snowflake-connector-python#985]
## What is the current behavior?
On MacOS, fresh install - I attempted to run `brew install apache-arrow` and `pip install snowflake-connector-python`. The former worked, installing version Arrow version 6.0; The latter failed, as `snowflake-connector-python` is still pinned to 5.0 => 5.1 in version 2.7.1, and happens to make a call to a (formerly deprecated, now removed) api. Installing from the `master` branch via `pip install -e git+...` worked.

## What is the desired behavior?
Cut a release version 2.7.2, which includes #965. This would ensure that  `brew install apache-arrow` followed by `pip install snowflake-connector-python` would complete successfully. Note that #965 has already been merged to `master`

## How would this improve `snowflake-connector-python`?
I'd imagine new MacOS users who are installing `snowflake-connector-python` would be happier that things worked without error.

**Comment by sfc-gh-hchaturvedi** [comment]
Hey @p5k6, if I understand correctly you're asking that we release a new version with this fix? If I got that right, we have a release coming up mid December which should have this change. Please stay tuned, thanks for your patience!

**Comment by sodul** [comment]
Adding our 2 cents here. We want to upgrade to Python 3.10 but cannot until the next release of the connector.
We use macOS 11 and 12, and install python through pyenv. Things are ok with Python 3.9.

**Comment by sfc-gh-jbahk** [comment]
@sodul we are aiming to add 3.10 support with our next release

**Comment by sfc-gh-jbahk** [comment]
Hello, the newest release is available. Thank you.
