### ISSUE TITLE
SNOW-507674: v2.7.1 - Blocked queries are now be considered to be still running- Not working as expected

### ISSUE THREAD

**Issue by shaik-abdulhaffeez** [snowflakedb/snowflake-connector-python#987]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Replace with the output of `3.6.13`

2. What operating system and processor architecture are you using?

   Replace with the output of `Linux-4.14.238-125.422.amzn1.x86_64-x86_64-with-debian-10.10`

3. What are the component versions in the environment (`pip freeze`)?

   Replace with the output of `python -m pip freeze`

4. What did you do?
           self.snow_flake_cur.execute_async(qry)
            query_id = self.snow_flake_cur.sfqid
            for _ in range(max_attempts):
                log.debug(f"query_id usage -- {query_id}")
                retrieve_status = self.snow_flake_conn.get_query_status_throw_if_error(
                    query_id
                )
                is_error = self.snow_flake_conn.is_an_error(retrieve_status)

   I'm trying to call get_query_status_throw_if_error() python function, As part of this, is_an_error() function has getting called 
  and failed with following error "TypeError: must be str, not NoneType". when i had start debug the application and identified 
  that query status has been changing to QueryStatus.BLOCKED and it is causing to above mentioned failure.
  As per latest release v2.7.1(Blocked queries are now be considered to be still running.). which means QueryStatus.BLOCKED 
  check has been removed from is_an_error(). But still, the function has referring  QueryStatus.BLOCKED.

  please find the below code sample taken from v2.7.1

   def is_an_error(status: QueryStatus) -> bool:
        """Checks whether given status means that there has been an error."""
        return status in (
            QueryStatus.ABORTING,
            QueryStatus.FAILED_WITH_ERROR,
            QueryStatus.ABORTED,
            QueryStatus.FAILED_WITH_INCIDENT,
            QueryStatus.DISCONNECTED,
            QueryStatus.BLOCKED,
        )

5. What did you expect to see?

   is_an_error() python function has to be handled properly. we can't have same condition applied on two functions (is_an_error(), 
  is_still_running())

  def is_still_running(status: QueryStatus) -> bool:
        """Checks whether given status is currently running."""
        return status in (
            QueryStatus.RUNNING,
            QueryStatus.QUEUED,
            QueryStatus.RESUMING_WAREHOUSE,
            QueryStatus.QUEUED_REPARING_WAREHOUSE,
            QueryStatus.BLOCKED,
            QueryStatus.NO_DATA,
        )

6. Can you set logging to DEBUG and collect the logs?

 Cannot attach full log since it included confidential info

Traceback (most recent call last):
  File "/glue/lib/installation/data_tool/process/glue_shell_post_process.py", line 169, in _execute_snowflake_merge
    query_id
  File "/glue/lib/installation/snowflake/connector/connection.py", line 1434, in get_query_status_throw_if_error
    queries[0].get("errorMessage", "") if len(queries) > 0 else ""
TypeError: must be str, not NoneType

**Comment by sfc-gh-mkeller** [comment]
Hi @shaik-abdulhaffeez 
Thank you for your bug report, you're right If we consider `BLOCKED` to be still running then it shouldn't count as an error
CC @sfc-gh-jbahk

**Comment by shaik-abdulhaffeez** [comment]
What should the next step be?, shall we expect any hot fix and release.
