### ISSUE TITLE
SNOW-510552: PEP 561 support, missing py.typed

### ISSUE THREAD

**Issue by jerry-git** [snowflakedb/snowflake-connector-python#991]
Is there some reason why the package doesn't contain _py.typed_ file (see [PEP 561](https://www.python.org/dev/peps/pep-0561/)) although there seems to be type hints in use in the source code?

For example, if I run `mypy` over this
```python
from snowflake.connector import SnowflakeConnection

reveal_type(SnowflakeConnection)
```

It results in 
```
file.py:1: error: Skipping analyzing "snowflake.connector": found module but no type hints or library stubs
file.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
file.py:3: note: Revealed type is "Any"
```

If I add a _py.typed_ file into the root of the `connector` package, `mypy` can infer the proper type.

**Comment by sfc-gh-mkeller** [comment]
Thanks for bringing this to our attention, let's make this happen!

**Comment by sfc-gh-mkeller** [comment]
It looks like the PR I submitted only included `py.typed` in our source distribution and not in wheels.
See https://github.com/snowflakedb/snowflake-connector-python/pull/996#issuecomment-998178675
Re-opening this ticket

**Comment by allenhumphreys** [comment]
@sfc-gh-mkeller I think that `package_data` is relative the package root.

https://docs.python.org/3/distutils/setupscript.html#installing-package-data

> The value must be a mapping from package name to a list of relative path names that should be copied into the package. The paths are interpreted as relative to the directory containing the package (information from the package_dir mapping is used if appropriate); that is, the files are expected to be part of the package in the source directories.

So change `"src/snowflake/connector/py.typed", to `"py.typed",` and it should pick it up.

**Comment by sfc-gh-mkeller** [comment]
> @sfc-gh-mkeller I think that `package_data` is relative the package root.
> 
> [docs.python.org/3/distutils/setupscript.html#installing-package-data](https://docs.python.org/3/distutils/setupscript.html#installing-package-data)
> 
> > The value must be a mapping from package name to a list of relative path names that should be copied into the package. The paths are interpreted as relative to the directory containing the package (information from the package_dir mapping is used if appropriate); that is, the files are expected to be part of the package in the source directories.
> 
> So change `"src/snowflake/connector/py.typed",` to `"py.typed",` and it should pick it up.

Thank you for your input, what you said is right. Switching to `py.typed` included it in the wheel locally for me, but that means that the rest (`"*.md", "LICENSE.txt", "NOTICE"`) were incorrect, since these are not situated in the package root, but in the git repository's root.

I was previously planning to switch to use `include_package_data` and `MANIFEST.in` so that we wouldn't need to maintain this list in 2 separate places.
Please do let me know if you think that this would lead to another error!

**Comment by allenhumphreys** [comment]
@sfc-gh-mkeller I think you're good to go based on a very similar set of changes in the Azure Python SDK https://github.com/Azure/azure-sdk-for-python/pull/18327/files
